`ifndef INC_GUARD_usb_tm_packetizer
`define INC_GUARD_usb_tm_packetizer

`define IFC_PHY_RX_P_VALID_UPPER_INDEX  0
`define IFC_PHY_RX_P_VALID_LOWER_INDEX  0
`define IFC_PHY_RX_P_VALID_WIDTH  0-0+1
`define IFC_PHY_RX_P_VALID_RANGE `IFC_PHY_RX_P_VALID_UPPER_INDEX:`IFC_PHY_RX_P_VALID_LOWER_INDEX
`define IFC_PHY_RX_P_CMD_UPPER_INDEX  0
`define IFC_PHY_RX_P_CMD_LOWER_INDEX  0
`define IFC_PHY_RX_P_CMD_WIDTH  0-0+1
`define IFC_PHY_RX_P_CMD_RANGE `IFC_PHY_RX_P_CMD_UPPER_INDEX:`IFC_PHY_RX_P_CMD_LOWER_INDEX
`define IFC_PHY_RX_P_DATA_UPPER_INDEX  8-1
`define IFC_PHY_RX_P_DATA_LOWER_INDEX  0
`define IFC_PHY_RX_P_DATA_WIDTH  8
`define IFC_PHY_RX_P_DATA_RANGE `IFC_PHY_RX_P_DATA_UPPER_INDEX:`IFC_PHY_RX_P_DATA_LOWER_INDEX
`define IFC_PHY_RX_P_READY_UPPER_INDEX  0
`define IFC_PHY_RX_P_READY_LOWER_INDEX  0
`define IFC_PHY_RX_P_READY_WIDTH  0-0+1
`define IFC_PHY_RX_P_READY_RANGE `IFC_PHY_RX_P_READY_UPPER_INDEX:`IFC_PHY_RX_P_READY_LOWER_INDEX

`endif
