`ifndef INC_GUARD_eth_bridge
`define INC_GUARD_eth_bridge

`define IFC_EB_EM_P_DUMMY4_UPPER_INDEX  0
`define IFC_EB_EM_P_DUMMY4_LOWER_INDEX  0
`define IFC_EB_EM_P_DUMMY4_WIDTH  1
`define IFC_EB_EM_P_DUMMY4_RANGE `IFC_EB_EM_P_DUMMY4_UPPER_INDEX:`IFC_EB_EM_P_DUMMY4_LOWER_INDEX
`define IFC_LB_P_DUMMY2_UPPER_INDEX  0
`define IFC_LB_P_DUMMY2_LOWER_INDEX  0
`define IFC_LB_P_DUMMY2_WIDTH  1
`define IFC_LB_P_DUMMY2_RANGE `IFC_LB_P_DUMMY2_UPPER_INDEX:`IFC_LB_P_DUMMY2_LOWER_INDEX

`endif
