`ifndef INC_GUARD_mfd_trans
`define INC_GUARD_mfd_trans

`define IFC_LBA_P_DUMMY3_UPPER_INDEX  0
`define IFC_LBA_P_DUMMY3_LOWER_INDEX  0
`define IFC_LBA_P_DUMMY3_WIDTH  1
`define IFC_LBA_P_DUMMY3_RANGE `IFC_LBA_P_DUMMY3_UPPER_INDEX:`IFC_LBA_P_DUMMY3_LOWER_INDEX

`endif
