package com.fastpath.cslc.cslgen.cgentb;

import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;

/**
 * Legacy {@code ECSLCmdType} ({@code trunk/cslc/trunk/csl_gen/cGen_Declarations.h}). Declaration order matches the
 * C++ enum (ordinal = legacy discriminant). {@link #legacyCslCmdName()} mirrors {@code buildCmdNames()} in
 * {@code cGenBase_tb.cpp} ({@code ECSLCmdStringMap} / {@code cslCmdName}).
 */
public enum CGenTbCmdType {
    CMD_ADD("add"),
    CMD_ADD_ADDRESS_RANGE("add_address_range"),
    CMD_ADD_ALLOWED_RANGE("add_allowed_range"),
    CMD_ADD_EQUATION("add_equation"),
    CMD_ADD_LOGIC("add_logic"),
    CMD_ADD_RESERVED_ADDRESS_RANGE("add_reserved_address_range"),
    CMD_ADD_TO_MEMORY_MAP("add_to_memory_map"),
    CMD_AUTO_GEN_MEMORY_MAP("auto_gen_memory_map"),
    CMD_CONCAT("concat"),
    CMD_CONNECT("connect"),
    CMD_CREATE_RTL_MODULE("create_rtl_module"),
    CMD_DIRECTIVE("directive"),
    CMD_EXCLUSION_LIST("exclusion_list"),
    CMD_GEN_DECODER("gen_decoder"),
    CMD_GENERATE_INDIVIDUAL_RTL_SIGNALS("generate_individual_rtl_signals"),
    CMD_GET_ADDRESS_INCREMENT("get_address_increment"),
    CMD_GET_ALIGNMENT("get_alignment"),
    CMD_GET_ATTR("get_attr"),
    CMD_GET_ATTRIBUTES("get_attributes"),
    CMD_GET_BITRANGE("get_bitrange"),
    CMD_GET_CLOCK_NAME("get_clock_name"),
    CMD_GET_CNT_DIR_SIGNAL("get_cnt_dir_signal"),
    CMD_GET_DATA_WORD_WIDTH("get_data_word_width"),
    CMD_GET_DEPTH("get_depth"),
    CMD_GET_DIM_BITRANGE("get_dim_bitrange"),
    CMD_GET_DIM_LOWER("get_dim_lower"),
    CMD_GET_DIM_OFFSET("get_dim_offset"),
    CMD_GET_DIM_UPPER("get_dim_upper"),
    CMD_GET_DIM_WIDTH("get_dim_width"),
    CMD_GET_EMPTY_NAME("get_empty_name"),
    CMD_GET_ENDIANESS("get_endianess"),
    CMD_GET_ENUM("get_enum"),
    CMD_GET_ENUM_ITEM("get_enum_item"),
    CMD_GET_FULL_NAME("get_full_name"),
    CMD_GET_LOWER("get_lower"),
    CMD_GET_LOWER_BOUND("get_lower_bound"),
    CMD_GET_LOWER_INDEX("get_lower_index"),
    CMD_GET_MNEMONIC("get_mnemonic"),
    CMD_GET_NEXT_ADDRESS("get_next_address"),
    CMD_GET_OFFSET("get_offset"),
    CMD_GET_OUTPUT_FILENAME("get_output_filename"),
    CMD_GET_POP_NAME("get_pop_name"),
    CMD_GET_PREFIX("get_prefix"),
    CMD_GET_PUSH_NAME("get_push_name"),
    CMD_GET_RD_ADDR_NAME("get_rd_addr_name"),
    CMD_GET_RD_CLOCK_NAME("get_rd_clock_name"),
    CMD_GET_RD_DATA_NAME("get_rd_data_name"),
    CMD_GET_RD_EN_NAME("get_rd_en_name"),
    CMD_GET_RESET_NAME("get_reset_name"),
    CMD_GET_RADIX("get_radix"),
    CMD_GET_SIGNAL_PREFIX("get_signal_prefix"),
    CMD_GET_SIGNAL_PREFIX_LOCAL("get_signal_prefix_local"),
    CMD_GET_SIMULATION_TIMEOUT_COUNT("get_simulation_timeout_count"),
    CMD_GET_SUFFIX("get_suffix"),
    CMD_GET_SYMBOL_LENGTH("get_symbol_length"),
    CMD_GET_TYPE("get_type"),
    CMD_GET_UNIT_PREFIX("get_unit_prefix"),
    CMD_GET_UPPER("get_upper"),
    CMD_GET_UPPER_BOUND("get_upper_bound"),
    CMD_GET_UPPER_INDEX("get_upper_index"),
    CMD_GET_VALID_NAME("get_valid_name"),
    CMD_GET_VALUE("get_value"),
    CMD_GET_VC_CAPTURE_EDGE_TYPE("get_vc_capture_edge_type"),
    CMD_GET_VC_CLOCK("get_vc_clock"),
    CMD_GET_VC_COMPARE_TRIGGER("get_vc_compare_trigger"),
    CMD_GET_VC_CPP_RD_NAME("get_vc_cpp_rd_name"),
    CMD_GET_VC_CPP_WR_NAME("get_vc_cpp_wr_name"),
    CMD_GET_VC_END_GENERATION_TRIGGER("get_vc_end_generation_trigger"),
    CMD_GET_VC_HEADER_COMMENT("get_vc_header_comment"),
    CMD_GET_VC_ID("get_vc_id"),
    CMD_GET_VC_MAX_NUMBER_OF_CAPTURE_EVENTS("get_vc_max_number_of_capture_events"),
    CMD_GET_VC_MAX_NUMBER_OF_MISMATCHES("get_vc_max_number_of_mismatches"),
    CMD_GET_VC_MAX_NUM_STATES("get_vc_max_num_states"),
    CMD_GET_VC_MODULE("get_vc_module"),
    CMD_GET_VC_NAME("get_vc_name"),
    CMD_GET_VC_RESET("get_vc_reset"),
    CMD_GET_VC_STALL("get_vc_stall "),
    CMD_GET_VC_START_GENERATION_TRIGGER("get_vc_start_generation_trigger"),
    CMD_GET_VC_TIMEOUT("get_vc_timeout"),
    CMD_GET_WIDTH("get_width"),
    CMD_GET_WR_ADDR_NAME("get_wr_addr_name"),
    CMD_GET_WR_CLOCK_NAME("get_wr_clock_name"),
    CMD_GET_WR_DATA_NAME("get_wr_data_name"),
    CMD_GET_WR_EN_NAME("get_wr_en_name"),
    CMD_INCLUDE_ONLY("include_only"),
    CMD_MERGE("merge"),
    CMD_PRINT("print"),
    CMD_REVERSE("reverse"),
    CMD_SET_ACCESS_RIGHTS("set_access_rights"),
    CMD_SET_ACCESS_RIGHTS_ENUM("set_access_rights_enum"),
    CMD_SET_ADDRESS_INCREMENT("set_address_increment"),
    CMD_SET_ALIGNMENT("set_alignment"),
    CMD_SET_ATTR("set_attr"),
    CMD_SET_ATTRIBUTES("set_attributes"),
    CMD_SET_BITRANGE("set_bitrange"),
    CMD_SET_CLK_DIVIDER("set_clk_divider"),
    CMD_SET_CLK_MULTIPLIER("set_clk_multiplier"),
    CMD_SET_CLOCK_NAME("set_clock_name"),
    CMD_SET_CONST_VALUE("set_const_value"),
    CMD_SET_DATA_WORD_WIDTH("set_data_word_width"),
    CMD_SET_DECODER_NAME("set_decoder_name"),
    CMD_SET_DECODER_OUT_NAME_PREFIX("set_decoder_out_name_prefix"),
    CMD_SET_DECODER_OUT_NAME_SUFFIX("set_decoder_out_name_suffix"),
    CMD_SET_DEFAULT_VALUE("set_default_value"),
    CMD_SET_DEPTH("set_depth"),
    CMD_SET_DIM_BITRANGE("set_dim_bitrange"),
    CMD_SET_DIM_OFFSET("set_dim_offset"),
    CMD_SET_DIM_RANGE("set_dim_range"),
    CMD_SET_DIM_WIDTH("set_dim_width"),
    CMD_SET_DIRECTION("set_direction"),
    CMD_SET_DURATION("set_duration"),
    CMD_SET_ENDIANESS("set_endianess"),
    CMD_SET_ENUM("set_enum"),
    CMD_SET_ENUM_ITEM("set_enum_item"),
    CMD_SET_EMPTY_NAME("set_empty_name"),
    CMD_SET_FIELD("set_field"),
    CMD_SET_FIELD_POSITION("set_field_position"),
    CMD_SET_FULL_NAME("set_full_name"),
    CMD_SET_GENERATOR_TYPE("set_generator_type"),
    CMD_SET_INSTANCE_ALTERATION_BIT("set_instance_alteration_bit"),
    CMD_SET_MEM_INSTANCE_NAME("set_mem_instance_name"),
    CMD_SET_MNEMONIC("set_mnemonic"),
    CMD_SET_MODULE_NAME("set_module_name"),
    CMD_SET_NAME("set_name"),
    CMD_SET_NEXT("set_next"),
    CMD_SET_NEXT_ADDRESS("set_next_address"),
    CMD_SET_NUMBER_OF_DIMENSIONS("set_number_of_dimensions"),
    CMD_SET_OFFSET("set_offset"),
    CMD_SET_PATTERN("set_pattern"),
    CMD_SET_PERIOD("set_period"),
    CMD_SET_PHASE_DIFFERENCE("set_phase_difference"),
    CMD_SET_PHYSICAL_IMPLEMENTATION("set_physical_implementation"),
    CMD_SET_POP_NAME("set_pop_name"),
    CMD_SET_PREFIX("set_prefix"),
    CMD_SET_PREVIOUS("set_previous"),
    CMD_SET_PUSH_NAME("set_push_name"),
    CMD_SET_RADIX("set_radix"),
    CMD_SET_RANGE("set_range"),
    CMD_SET_RD_ADDR_NAME("set_rd_addr_name"),
    CMD_SET_RD_CLOCK_NAME("set_rd_clock_name"),
    CMD_SET_RD_DATA_NAME("set_rd_data_name"),
    CMD_SET_RD_EN_NAME("set_rd_en_name"),
    CMD_SET_RESET("set_reset"),
    CMD_SET_RESET_NAME("set_reset_name"),
    CMD_SET_SIGNAL_NAME("set_signal_name"),
    CMD_SET_SIGNAL_PREFIX_LOCAL("set_signal_prefix_local"),
    CMD_SET_START_SIGNAL("set_start_signal"),
    CMD_SET_SUFFIX("set_suffix"),
    CMD_SET_SYMBOL_MAX_LENGTH("set_symbol_max_length"),
    CMD_SET_TESTBENCH_VERILOG_FILENAME("set_testbench_verilog_filename"),
    CMD_SET_TIMEBASE("set_timebase"),
    CMD_SET_TOP_UNIT("set_top_unit"),
    CMD_SET_TYPE("set_type"),
    CMD_SET_UNIT_PREFIX("set_unit_prefix"),
    CMD_SET_VALID_NAME("set_valid_name"),
    CMD_SET_VALUE("set_value"),
    CMD_SET_VC_CAPTURE_EDGE_TYPE("set_vc_capture_edge_type"),
    CMD_SET_VC_CLOCK("set_vc_clock"),
    CMD_SET_VC_COMPARE_TRIGGER("set_vc_compare_trigger"),
    CMD_SET_VC_CPP_RD_NAME("set_vc_cpp_rd_name"),
    CMD_SET_VC_CPP_WR_NAME("set_vc_cpp_wr_name"),
    CMD_SET_VC_END_GENERATION_TRIGGER("set_vc_end_generation_trigger"),
    CMD_SET_VC_HEADER_COMMENT("set_vc_header_comment"),
    CMD_SET_VC_ID("set_vc_id"),
    CMD_SET_VC_MAX_NUMBER_OF_CAPTURE_EVENTS("set_vc_max_number_of_capture_events"),
    CMD_SET_VC_MAX_NUMBER_OF_MISMATCHES("set_vc_max_number_of_mismatches"),
    CMD_SET_VC_MAX_NUM_OF_TRANSACTION_EVENTS("set_vc_max_num_of_transaction_events"),
    CMD_SET_VC_MAX_NUM_STATES("set_vc_max_num_states"),
    CMD_SET_VC_NAME("set_vc_name"),
    CMD_SET_VC_OUTPUT_FILENAME("set_vc_output_filename"),
    CMD_SET_VC_RESET("set_vc_reset"),
    CMD_SET_VC_STALL("set_vc_stall"),
    CMD_SET_VC_START_GENERATION_TRIGGER("set_vc_start_generation_trigger"),
    CMD_SET_VC_TIMEOUT("set_vc_timeout"),
    CMD_SET_VERSION("set_version"),
    CMD_SET_WIDTH("set_width"),
    CMD_SET_WR_ADDR_NAME("set_wr_addr_name"),
    CMD_SET_WR_CLOCK_NAME("set_wr_clock_name"),
    CMD_SET_WR_DATA_NAME("set_wr_data_name"),
    CMD_SET_WR_EN_NAME("set_wr_en_name")
    ;

    private static final Map<CGenTbCmdType, String> LEGACY_NAMES;

    static {
        EnumMap<CGenTbCmdType, String> m = new EnumMap<>(CGenTbCmdType.class);
        for (CGenTbCmdType t : values()) {
            m.put(t, t.legacyCslCmdName);
        }
        LEGACY_NAMES = Collections.unmodifiableMap(m);
    }

    private final String legacyCslCmdName;

    CGenTbCmdType(String legacyCslCmdName) {
        this.legacyCslCmdName = legacyCslCmdName;
    }

    /** String used in legacy {@code cslCmdName} / {@code GET_CMD} tables ({@code cGenBase_tb.cpp}). */
    public String legacyCslCmdName() {
        return legacyCslCmdName;
    }

    /** Unmodifiable view of all legacy command strings (same as per-constant {@link #legacyCslCmdName()}). */
    public static Map<CGenTbCmdType, String> legacyNameTable() {
        return LEGACY_NAMES;
    }
}
