`ifndef INC_GUARD_u1
`define INC_GUARD_u1

`define IFC_IFC10_P_P1_UPPER_INDEX  (param1-1)
`define IFC_IFC10_P_P1_LOWER_INDEX  (0)
`define IFC_IFC10_P_P1_WIDTH  (param1)
`define IFC_IFC10_P_P1_RANGE `IFC_IFC10_P_P1_UPPER_INDEX:`IFC_IFC10_P_P1_LOWER_INDEX
`define IFC_IFC10_P_P2_UPPER_INDEX  (param2-1)
`define IFC_IFC10_P_P2_LOWER_INDEX  (0)
`define IFC_IFC10_P_P2_WIDTH  (param2)
`define IFC_IFC10_P_P2_RANGE `IFC_IFC10_P_P2_UPPER_INDEX:`IFC_IFC10_P_P2_LOWER_INDEX

`endif
