<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
		<!-- Column 1 start -->
		<h2 class="caps">About Fastpath Logic&reg;</h2>

		<p>
		Fastpath Logic supplies system level design, verification, and
		simulation automation and infrastructure generation tools to
		ASIC, FPGA, and custom chip design teams. Fastpath Logic was
		founded by engineers with work experience on Intel microprocessor
		projects, Sun Microsystems parallel systems, and Graphics and
		encoder/decoder chip designs. The team has a back ground in system
		on chip and network on chip designs, application specific
		processor instruction set architecture design, micro coding, CAD
		tool and compiler design. The Fastpath Logic solution set
		leverages the experience of the team and provides a world class
		chip management solution.  
		</p>
		<!-- Column 1 end -->
      </div>
      <div class="col2">
		<!-- Column 2 start -->
		$aboutMenu$
		<!-- Column 2 end -->
      </div>
      <div class="col3">
		<!-- Column 3 start -->
		<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

