<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
		<!-- Column 1 start -->
		<h2 class="caps">Advisory Board</h2>
		<h3 class="caps">Peter Baran</h3>
		<p>
		</p>
		<h3 class="caps">Ed Hutchings</h3>
		<p>
		</p>
		<h3 class="caps">Jim Hogan</h3>
		<p>
		</p>
	</h2>
	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->	

	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

