<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
		<!-- Column 1 start -->
	    <h2><span>Automating the chip design and verification process</span></h2>
	    <p></p>
	    <h2>SoC example</h2>
	    <p>SoC's designs are typically
	      proliferated which requires
	      modifications to the interconnect in
	      order to add new modules or delete
	      existing modules.</p>
	    <img class="g1515" src="../imagesfpl/soc_interconnect.png"  alt="soc"/>
	    <p> Interconnect is built during chip design projects in verification and
	      design teams. The interconnect uses
	      interfaces to connect modules to one
	      another in the verification
	      simulator, the testbenches, and the
	      the RTL design. A change in the RTL
	      design must be reflected in the
	      verification components and the
	      functional simulator. Changes between modules in the RTL
	      or functional simulator must be maintained by two or
	      more RTL design engineers or functional simulator
	      writers.</p>  
	    <h2>SoC Design Hierarchy and Interconnect</h2>
	    <p>SoC's designs are constructed using a design heirarchy
	      and interconnect. The design is verified at specific
	      points (interfaces) using simulation models, bus functional models,
	      and assertions. These interfaces change during the
	      development of the project in the verification test
	      benches, tranaction level interfaces, and the RTL module
	      interfaces. Maintenance of the consistency between these interfaces is a
	      consistency problem. </p>
	    <img  class="g1515" src="../imagesfpl/soc_tlm.png"  alt="soc" />
	    <h2>Transaction Level Modeling</h2>
	    <p>SoC's designs are constructed using a design heirarchy
	      and interconnect. The design is verified at specific
	      points (interfaces) using simulation models, bus functional models,
	      and assertions. These interfaces change during the
	      development of the project in the verification test
	      benches, tranaction level interfaces, and the RTL module
	      interfaces. Maintenance of the consistency between these interfaces is a
	      consistency problem. </p>
	    <img  class="g1515" src="../imagesfpl/soc_tlm.png"  alt="soc" />
	    <h2>Design, simulation, and verification management system</h2>
	    <p>SoC's </p>
	    <img  class="g3535" src="../imagesfpl/design_management_hub.png"  alt="soc" />
	    <h2>SoC Address maps</h2>
	    <p>SoC's designs contain an address map which is used to
	      write and read the addressable objects in the SoC
	      design. The memory map must be implmented in both the
	      functional simulator and the RTL design. The address map changes during the
	      development of the project. Maintenance of the consistency
	      between these interfaces is  address map between the
	      simulaiton and RTL designs is a consistency problem. </p>
	    <img  class="g1515" src="../imagesfpl/soc_tlm.png"  alt="soc" />

		<!-- Column 1 end -->
	  </div>
	  <div class="col2">
		<!-- Column 2 start -->	
		<h2>Innovative Technology</h2>
		<p>The Fastpath Logic synthesis engine is at the core of
		  the Fastpath Logic solution. The engine includes
		  an auto router to automatically
		  connect modules across design hierarchies.</p>

		<h2>Preemptive benefits</h2>
		<p>Customers have reported a 15-30x
		  reduction in the amount of time spent
		  architecting and building the
		  RTL design and functional simulator 
		  interconnect for SoC and NoC chips.</p>

		<h2>Tape outs</h2>
		<p>A large semi company recently taped
		  out a design that utilized the Fastpath Logic
		  tool to construct the SoC interconnect.</p>

		<!-- Column 2 end -->
	  </div>
	  <div class="col3">
		<!-- Column 3 start -->
		<!-- Column 3 end -->
	  </div>
	</div>
  </div>
</div>

