<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
	<!-- Column 1 start -->
Fastpath Logic is looking for application engineers who are looking
	for a significant equity position in an early ESL startup. Experience in
	supporting EDA/ESL tools in ASIC and FPGA design flows is
	required. Knowledge of Verilog and SystemC, as well as chip/FPGA
	design flows involving functional simulator development,
	testbench/transaction level modeling, and RTL design is a must.
	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->
	$careersMenu$
	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

