<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
	<!-- Column 1 start -->
	Fastpath Logic, Inc.            <br>
	PO Box 188                      <br>
	Palo Alto, California 94302-0188<br>

	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->
	$contactMenu$

	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

