<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
		<!-- Column 1 start -->
		Fastpath Logic's synthesis engine reads the design specifications, checks
		the specifications for correctness, synthesizes the specification
		into a language agnostic representation and then generates
		industry standard languages and documention. The specification is
		entered in two different ways: <br>
		1. Use the Fastpath Logic GUI to create the specification.<br> 
		2. Use an editor to create the design specification using
		extended C++. 

		<h2>Design, simulation, and verification management system</h2>
		<p>SoC's </p>
		<img  class="g3535" src="../imagesfpl/design_management_hub.png"  alt="soc" />
		
		<!-- Column 1 end -->
      </div>
      <div class="col2">
		<!-- Column 2 start -->
		$cslcMenu$
		<!-- Column 2 end -->
      </div>
      <div class="col3">
		<!-- Column 3 start -->
		<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

