
<div id="footer">
  <div class="footLinks">
    <p>
      <a href="index.htm">Home</a> <span>|</span>
      <a href="PageContact.htm">Contact Us</a> <span>|</span>
      <a href="PageSitemap.htm">Sitemap</a> <span>|</span>
      <a href="#">Privacy Policy</a>
      <span>|</span>
      <a href="#">User Agreement</a>
      <span>|</span>
      <a href="#">Conditions of Use</a>
      <span>|</span>
      <a href="#">Investor Relations</a>
      <span>|</span>
	<a href="http://validator.w3.org/check/referer" title="Check the validity of this site&#8217;s XHTML">xhtml validation</a>
      <span>|</span>
	<a href="http://jigsaw.w3.org/css-validator/check/referer" title="Check the validity of this site&#8217;s CSS">css validation</a>

    </p>
    <!--<p>
	<a href="#">Privacy Policy</a>
	<span>|</span>
	<a href="#">User Agreement</a>
	<span>|</span>
	<a href="#">Conditions of Use</a>
	<span>|</span>
	<a href="#">Investor Relations</a>
      </p>-->
  </div>
  <p class="copyRt">
    Copyright &#169; 2009, Fastpath Logic&reg; Inc.
  </p>  
</div>

<!--<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1848067-8";
urchinTracker();
</script>
-->

</body>
</html>
