<table border = "1" width ="100%" align = "right">
  <tr>
    <td align = "top">
      
      
      <div id="mainbody" style="margin:auto;z-index:1">
	<script language="javascript">
	  if (AC_FL_RunContent == 0) {
	  alert("This page requires AC_RunActiveContent.js.");
	  } else {
	  AC_FL_RunContent(
	  'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0',
	  'width', '600',
	  'height', '208',
	  'src', 'vast_web_graphic_v6',
	  'quality', 'high',
	  'pluginspage', 'http://www.macromedia.com/go/getflashplayer',
	  'align', 'center',
	  'play', 'true',
	  'loop', 'true',
	  'scale', 'showall',
	  'wmode', 'transparent',
	  'devicefont', 'false',
	  'id', 'mainbody',
	  'bgcolor', '#ffffff',
	  'name', 'mainbody',
	  'menu', 'true',
	  'allowFullScreen', 'false',
	  'allowScriptAccess','sameDomain',
	  'movie', 'vast_web_graphic_v6',
	  'salign', ''
	  ); //end AC code
	  }
	</script>
	<noscript>
	  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="600" height="208" id="mainbody" align="center">
	    <param name="allowScriptAccess" value="sameDomain" />
	    <param name="allowFullScreen" value="false" />
	    <param name="movie" value="../flash/SoC.swf" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" />	<embed src="../flash/SoC.swf" quality="high" bgcolor="#ffffff" width="600" height="208" name="flash" align="center" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
	  </object>
	</noscript>
      </div>
    </td>
    
  </tr>
  
</table>

