`ifndef INC_GUARD_u1
`define INC_GUARD_u1

`define P_SU1_UPPER_INDEX  (0)
`define P_SU1_LOWER_INDEX  (0)
`define P_SU1_WIDTH  (0-0+1)
`define P_SU1_RANGE `P_SU1_UPPER_INDEX:`P_SU1_LOWER_INDEX
`define P_AR_SA0_S10_UPPER_INDEX  (1-1)
`define P_AR_SA0_S10_LOWER_INDEX  (0)
`define P_AR_SA0_S10_WIDTH  (1)
`define P_AR_SA0_S10_RANGE `P_AR_SA0_S10_UPPER_INDEX:`P_AR_SA0_S10_LOWER_INDEX

`endif
