`ifndef INC_GUARD_alutop
`define INC_GUARD_alutop

`define P_CIN_UPPER_INDEX  (0)
`define P_CIN_LOWER_INDEX  (0)
`define P_CIN_WIDTH  (0-0+1)
`define P_CIN_RANGE `P_CIN_UPPER_INDEX:`P_CIN_LOWER_INDEX
`define P_ALUOUT_UPPER_INDEX  (DATA_WIDTH-1)
`define P_ALUOUT_LOWER_INDEX  (0)
`define P_ALUOUT_WIDTH  (DATA_WIDTH-1-0+1)
`define P_ALUOUT_RANGE `P_ALUOUT_UPPER_INDEX:`P_ALUOUT_LOWER_INDEX
`define P_COUT_UPPER_INDEX  (0)
`define P_COUT_LOWER_INDEX  (0)
`define P_COUT_WIDTH  (0-0+1)
`define P_COUT_RANGE `P_COUT_UPPER_INDEX:`P_COUT_LOWER_INDEX
`define P_SELAL_UPPER_INDEX  (0)
`define P_SELAL_LOWER_INDEX  (0)
`define P_SELAL_WIDTH  (0-0+1)
`define P_SELAL_RANGE `P_SELAL_UPPER_INDEX:`P_SELAL_LOWER_INDEX
`define IFC_OPS_P_A_UPPER_INDEX  (DATA_WIDTH-1)
`define IFC_OPS_P_A_LOWER_INDEX  (0)
`define IFC_OPS_P_A_WIDTH  (DATA_WIDTH-1-0+1)
`define IFC_OPS_P_A_RANGE `IFC_OPS_P_A_UPPER_INDEX:`IFC_OPS_P_A_LOWER_INDEX
`define IFC_OPS_P_B_UPPER_INDEX  (DATA_WIDTH-1)
`define IFC_OPS_P_B_LOWER_INDEX  (0)
`define IFC_OPS_P_B_WIDTH  (DATA_WIDTH-1-0+1)
`define IFC_OPS_P_B_RANGE `IFC_OPS_P_B_UPPER_INDEX:`IFC_OPS_P_B_LOWER_INDEX
`define IFC_SELOPS_P_S_UPPER_INDEX  (0)
`define IFC_SELOPS_P_S_LOWER_INDEX  (0)
`define IFC_SELOPS_P_S_WIDTH  (0-0+1)
`define IFC_SELOPS_P_S_RANGE `IFC_SELOPS_P_S_UPPER_INDEX:`IFC_SELOPS_P_S_LOWER_INDEX
`define SG_OUTIFC0_S_O_UPPER_INDEX  (8-1)
`define SG_OUTIFC0_S_O_LOWER_INDEX  (0)
`define SG_OUTIFC0_S_O_WIDTH  (8)
`define SG_OUTIFC0_S_O_RANGE `SG_OUTIFC0_S_O_UPPER_INDEX:`SG_OUTIFC0_S_O_LOWER_INDEX

`endif
