`ifndef INC_GUARD_mux21
`define INC_GUARD_mux21

`define IFC_INIFC0_P_O_UPPER_INDEX  (DATA_WIDTH-1)
`define IFC_INIFC0_P_O_LOWER_INDEX  (0)
`define IFC_INIFC0_P_O_WIDTH  (DATA_WIDTH-1-0+1)
`define IFC_INIFC0_P_O_RANGE `IFC_INIFC0_P_O_UPPER_INDEX:`IFC_INIFC0_P_O_LOWER_INDEX
`define IFC_INIFC1_P_O_UPPER_INDEX  (DATA_WIDTH-1)
`define IFC_INIFC1_P_O_LOWER_INDEX  (0)
`define IFC_INIFC1_P_O_WIDTH  (DATA_WIDTH-1-0+1)
`define IFC_INIFC1_P_O_RANGE `IFC_INIFC1_P_O_UPPER_INDEX:`IFC_INIFC1_P_O_LOWER_INDEX
`define P_MUXOUT_UPPER_INDEX  (DATA_WIDTH-1)
`define P_MUXOUT_LOWER_INDEX  (0)
`define P_MUXOUT_WIDTH  (DATA_WIDTH-1-0+1)
`define P_MUXOUT_RANGE `P_MUXOUT_UPPER_INDEX:`P_MUXOUT_LOWER_INDEX
`define P_S_UPPER_INDEX  (0)
`define P_S_LOWER_INDEX  (0)
`define P_S_WIDTH  (0-0+1)
`define P_S_RANGE `P_S_UPPER_INDEX:`P_S_LOWER_INDEX

`endif
