`ifndef INC_GUARD_rf
`define INC_GUARD_rf

`define P_CLOCK_UPPER_INDEX  (0)
`define P_CLOCK_LOWER_INDEX  (0)
`define P_CLOCK_WIDTH  (0-0+1)
`define P_CLOCK_RANGE `P_CLOCK_UPPER_INDEX:`P_CLOCK_LOWER_INDEX
`define P_RESET_UPPER_INDEX  (0)
`define P_RESET_LOWER_INDEX  (0)
`define P_RESET_WIDTH  (0-0+1)
`define P_RESET_RANGE `P_RESET_UPPER_INDEX:`P_RESET_LOWER_INDEX
`define P_DATA_IN_UPPER_INDEX  (15)
`define P_DATA_IN_LOWER_INDEX  (0)
`define P_DATA_IN_WIDTH  (15-0+1)
`define P_DATA_IN_RANGE `P_DATA_IN_UPPER_INDEX:`P_DATA_IN_LOWER_INDEX
`define P_DATA_OUT1_UPPER_INDEX  (15)
`define P_DATA_OUT1_LOWER_INDEX  (0)
`define P_DATA_OUT1_WIDTH  (15-0+1)
`define P_DATA_OUT1_RANGE `P_DATA_OUT1_UPPER_INDEX:`P_DATA_OUT1_LOWER_INDEX
`define P_DATA_OUT2_UPPER_INDEX  (15)
`define P_DATA_OUT2_LOWER_INDEX  (0)
`define P_DATA_OUT2_WIDTH  (15-0+1)
`define P_DATA_OUT2_RANGE `P_DATA_OUT2_UPPER_INDEX:`P_DATA_OUT2_LOWER_INDEX
`define P_WR_ADDR_UPPER_INDEX  (3)
`define P_WR_ADDR_LOWER_INDEX  (0)
`define P_WR_ADDR_WIDTH  (3-0+1)
`define P_WR_ADDR_RANGE `P_WR_ADDR_UPPER_INDEX:`P_WR_ADDR_LOWER_INDEX
`define P_RD_ADDR1_UPPER_INDEX  (3)
`define P_RD_ADDR1_LOWER_INDEX  (0)
`define P_RD_ADDR1_WIDTH  (3-0+1)
`define P_RD_ADDR1_RANGE `P_RD_ADDR1_UPPER_INDEX:`P_RD_ADDR1_LOWER_INDEX
`define P_RD_ADDR2_UPPER_INDEX  (3)
`define P_RD_ADDR2_LOWER_INDEX  (0)
`define P_RD_ADDR2_WIDTH  (3-0+1)
`define P_RD_ADDR2_RANGE `P_RD_ADDR2_UPPER_INDEX:`P_RD_ADDR2_LOWER_INDEX
`define P_WR_EN_UPPER_INDEX  (0)
`define P_WR_EN_LOWER_INDEX  (0)
`define P_WR_EN_WIDTH  (0-0+1)
`define P_WR_EN_RANGE `P_WR_EN_UPPER_INDEX:`P_WR_EN_LOWER_INDEX
`define P_RD_EN1_UPPER_INDEX  (0)
`define P_RD_EN1_LOWER_INDEX  (0)
`define P_RD_EN1_WIDTH  (0-0+1)
`define P_RD_EN1_RANGE `P_RD_EN1_UPPER_INDEX:`P_RD_EN1_LOWER_INDEX
`define P_RD_EN2_UPPER_INDEX  (0)
`define P_RD_EN2_LOWER_INDEX  (0)
`define P_RD_EN2_WIDTH  (0-0+1)
`define P_RD_EN2_RANGE `P_RD_EN2_UPPER_INDEX:`P_RD_EN2_LOWER_INDEX

`endif
