`ifndef INC_GUARD_u_alu
`define INC_GUARD_u_alu

`define P_P_OP1_UPPER_INDEX  (15)
`define P_P_OP1_LOWER_INDEX  (0)
`define P_P_OP1_WIDTH  (15-0+1)
`define P_P_OP1_RANGE `P_P_OP1_UPPER_INDEX:`P_P_OP1_LOWER_INDEX
`define P_P_OP2_UPPER_INDEX  (15)
`define P_P_OP2_LOWER_INDEX  (0)
`define P_P_OP2_WIDTH  (15-0+1)
`define P_P_OP2_RANGE `P_P_OP2_UPPER_INDEX:`P_P_OP2_LOWER_INDEX
`define P_P_OPSEL_UPPER_INDEX  (2)
`define P_P_OPSEL_LOWER_INDEX  (0)
`define P_P_OPSEL_WIDTH  (2-0+1)
`define P_P_OPSEL_RANGE `P_P_OPSEL_UPPER_INDEX:`P_P_OPSEL_LOWER_INDEX
`define P_P_CIN_UPPER_INDEX  (0)
`define P_P_CIN_LOWER_INDEX  (0)
`define P_P_CIN_WIDTH  (0-0+1)
`define P_P_CIN_RANGE `P_P_CIN_UPPER_INDEX:`P_P_CIN_LOWER_INDEX
`define P_P_RES_UPPER_INDEX  (15)
`define P_P_RES_LOWER_INDEX  (0)
`define P_P_RES_WIDTH  (15-0+1)
`define P_P_RES_RANGE `P_P_RES_UPPER_INDEX:`P_P_RES_LOWER_INDEX
`define P_P_COUT_UPPER_INDEX  (0)
`define P_P_COUT_LOWER_INDEX  (0)
`define P_P_COUT_WIDTH  (0-0+1)
`define P_P_COUT_RANGE `P_P_COUT_UPPER_INDEX:`P_P_COUT_LOWER_INDEX

`endif
