`ifndef INC_GUARD_u_ir
`define INC_GUARD_u_ir

`define P_P_CLOCK_UPPER_INDEX  (0)
`define P_P_CLOCK_LOWER_INDEX  (0)
`define P_P_CLOCK_WIDTH  (0-0+1)
`define P_P_CLOCK_RANGE `P_P_CLOCK_UPPER_INDEX:`P_P_CLOCK_LOWER_INDEX
`define P_P_I_UPPER_INDEX  (15)
`define P_P_I_LOWER_INDEX  (0)
`define P_P_I_WIDTH  (15-0+1)
`define P_P_I_RANGE `P_P_I_UPPER_INDEX:`P_P_I_LOWER_INDEX
`define P_P_OPCODE_UPPER_INDEX  (4)
`define P_P_OPCODE_LOWER_INDEX  (0)
`define P_P_OPCODE_WIDTH  (4-0+1)
`define P_P_OPCODE_RANGE `P_P_OPCODE_UPPER_INDEX:`P_P_OPCODE_LOWER_INDEX
`define P_P_RDST_UPPER_INDEX  (3)
`define P_P_RDST_LOWER_INDEX  (0)
`define P_P_RDST_WIDTH  (3-0+1)
`define P_P_RDST_RANGE `P_P_RDST_UPPER_INDEX:`P_P_RDST_LOWER_INDEX
`define P_P_OP1_UPPER_INDEX  (3)
`define P_P_OP1_LOWER_INDEX  (0)
`define P_P_OP1_WIDTH  (3-0+1)
`define P_P_OP1_RANGE `P_P_OP1_UPPER_INDEX:`P_P_OP1_LOWER_INDEX
`define P_P_OP2_UPPER_INDEX  (3)
`define P_P_OP2_LOWER_INDEX  (0)
`define P_P_OP2_WIDTH  (3-0+1)
`define P_P_OP2_RANGE `P_P_OP2_UPPER_INDEX:`P_P_OP2_LOWER_INDEX
`define P_P_C_UPPER_INDEX  (0)
`define P_P_C_LOWER_INDEX  (0)
`define P_P_C_WIDTH  (0-0+1)
`define P_P_C_RANGE `P_P_C_UPPER_INDEX:`P_P_C_LOWER_INDEX
`define P_P_BRADDR_UPPER_INDEX  (11-1)
`define P_P_BRADDR_LOWER_INDEX  (0)
`define P_P_BRADDR_WIDTH  (11)
`define P_P_BRADDR_RANGE `P_P_BRADDR_UPPER_INDEX:`P_P_BRADDR_LOWER_INDEX
`define P_P_SHA_UPPER_INDEX  (4-1)
`define P_P_SHA_LOWER_INDEX  (0)
`define P_P_SHA_WIDTH  (4)
`define P_P_SHA_RANGE `P_P_SHA_UPPER_INDEX:`P_P_SHA_LOWER_INDEX
`define P_P_CONST8_UPPER_INDEX  (7)
`define P_P_CONST8_LOWER_INDEX  (0)
`define P_P_CONST8_WIDTH  (7-0+1)
`define P_P_CONST8_RANGE `P_P_CONST8_UPPER_INDEX:`P_P_CONST8_LOWER_INDEX
`define P_P_ROMADDR_UPPER_INDEX  (7)
`define P_P_ROMADDR_LOWER_INDEX  (0)
`define P_P_ROMADDR_WIDTH  (7-0+1)
`define P_P_ROMADDR_RANGE `P_P_ROMADDR_UPPER_INDEX:`P_P_ROMADDR_LOWER_INDEX
`define P_P_D_UPPER_INDEX  (0)
`define P_P_D_LOWER_INDEX  (0)
`define P_P_D_WIDTH  (0-0+1)
`define P_P_D_RANGE `P_P_D_UPPER_INDEX:`P_P_D_LOWER_INDEX

`endif
