`ifndef INC_GUARD_r_pc
`define INC_GUARD_r_pc

`define P_P_CLOCK_UPPER_INDEX  (0)
`define P_P_CLOCK_LOWER_INDEX  (0)
`define P_P_CLOCK_WIDTH  (0-0+1)
`define P_P_CLOCK_RANGE `P_P_CLOCK_UPPER_INDEX:`P_P_CLOCK_LOWER_INDEX
`define P_P_RESET_UPPER_INDEX  (0)
`define P_P_RESET_LOWER_INDEX  (0)
`define P_P_RESET_WIDTH  (0-0+1)
`define P_P_RESET_RANGE `P_P_RESET_UPPER_INDEX:`P_P_RESET_LOWER_INDEX
`define P_P_ENABLE_UPPER_INDEX  (0)
`define P_P_ENABLE_LOWER_INDEX  (0)
`define P_P_ENABLE_WIDTH  (0-0+1)
`define P_P_ENABLE_RANGE `P_P_ENABLE_UPPER_INDEX:`P_P_ENABLE_LOWER_INDEX
`define P_P_BR_ADDR_UPPER_INDEX  (15)
`define P_P_BR_ADDR_LOWER_INDEX  (0)
`define P_P_BR_ADDR_WIDTH  (15-0+1)
`define P_P_BR_ADDR_RANGE `P_P_BR_ADDR_UPPER_INDEX:`P_P_BR_ADDR_LOWER_INDEX
`define P_P_SEL_UPPER_INDEX  (0)
`define P_P_SEL_LOWER_INDEX  (0)
`define P_P_SEL_WIDTH  (0-0+1)
`define P_P_SEL_RANGE `P_P_SEL_UPPER_INDEX:`P_P_SEL_LOWER_INDEX
`define P_P_ADDR_OUT_UPPER_INDEX  (15)
`define P_P_ADDR_OUT_LOWER_INDEX  (0)
`define P_P_ADDR_OUT_WIDTH  (15-0+1)
`define P_P_ADDR_OUT_RANGE `P_P_ADDR_OUT_UPPER_INDEX:`P_P_ADDR_OUT_LOWER_INDEX

`endif
