`ifndef INC_GUARD_u1
`define INC_GUARD_u1

`define S_RST_UPPER_INDEX  (0)
`define S_RST_LOWER_INDEX  (0)
`define S_RST_WIDTH  (0-0+1)
`define S_RST_RANGE `S_RST_UPPER_INDEX:`S_RST_LOWER_INDEX
`define S_CLK_UPPER_INDEX  (0)
`define S_CLK_LOWER_INDEX  (0)
`define S_CLK_WIDTH  (0-0+1)
`define S_CLK_RANGE `S_CLK_UPPER_INDEX:`S_CLK_LOWER_INDEX
`define S_EN_UPPER_INDEX  (0)
`define S_EN_LOWER_INDEX  (0)
`define S_EN_WIDTH  (0-0+1)
`define S_EN_RANGE `S_EN_UPPER_INDEX:`S_EN_LOWER_INDEX
`define S_DATA_UPPER_INDEX  (16-1)
`define S_DATA_LOWER_INDEX  (0)
`define S_DATA_WIDTH  (16)
`define S_DATA_RANGE `S_DATA_UPPER_INDEX:`S_DATA_LOWER_INDEX

`endif
