`ifndef INC_GUARD_chip
`define INC_GUARD_chip

`define S_RESET_UPPER_INDEX  (0)
`define S_RESET_LOWER_INDEX  (0)
`define S_RESET_WIDTH  (0-0+1)
`define S_RESET_RANGE `S_RESET_UPPER_INDEX:`S_RESET_LOWER_INDEX
`define S_CLEAR_UPPER_INDEX  (0)
`define S_CLEAR_LOWER_INDEX  (0)
`define S_CLEAR_WIDTH  (0-0+1)
`define S_CLEAR_RANGE `S_CLEAR_UPPER_INDEX:`S_CLEAR_LOWER_INDEX
`define S_CLK_UPPER_INDEX  (0)
`define S_CLK_LOWER_INDEX  (0)
`define S_CLK_WIDTH  (0-0+1)
`define S_CLK_RANGE `S_CLK_UPPER_INDEX:`S_CLK_LOWER_INDEX
`define S_WR_ADDR_UPPER_INDEX  (7-1)
`define S_WR_ADDR_LOWER_INDEX  (0)
`define S_WR_ADDR_WIDTH  (7)
`define S_WR_ADDR_RANGE `S_WR_ADDR_UPPER_INDEX:`S_WR_ADDR_LOWER_INDEX
`define S_RD_ADDR0_UPPER_INDEX  (7-1)
`define S_RD_ADDR0_LOWER_INDEX  (0)
`define S_RD_ADDR0_WIDTH  (7)
`define S_RD_ADDR0_RANGE `S_RD_ADDR0_UPPER_INDEX:`S_RD_ADDR0_LOWER_INDEX
`define S_RD_ADDR1_UPPER_INDEX  (7-1)
`define S_RD_ADDR1_LOWER_INDEX  (0)
`define S_RD_ADDR1_WIDTH  (7)
`define S_RD_ADDR1_RANGE `S_RD_ADDR1_UPPER_INDEX:`S_RD_ADDR1_LOWER_INDEX
`define S_DATA_IN_UPPER_INDEX  (32-1)
`define S_DATA_IN_LOWER_INDEX  (0)
`define S_DATA_IN_WIDTH  (32)
`define S_DATA_IN_RANGE `S_DATA_IN_UPPER_INDEX:`S_DATA_IN_LOWER_INDEX
`define S_DATA_OUT0_UPPER_INDEX  (32-1)
`define S_DATA_OUT0_LOWER_INDEX  (0)
`define S_DATA_OUT0_WIDTH  (32)
`define S_DATA_OUT0_RANGE `S_DATA_OUT0_UPPER_INDEX:`S_DATA_OUT0_LOWER_INDEX
`define S_DATA_OUT1_UPPER_INDEX  (32-1)
`define S_DATA_OUT1_LOWER_INDEX  (0)
`define S_DATA_OUT1_WIDTH  (32)
`define S_DATA_OUT1_RANGE `S_DATA_OUT1_UPPER_INDEX:`S_DATA_OUT1_LOWER_INDEX
`define S_WR_EN_UPPER_INDEX  (0)
`define S_WR_EN_LOWER_INDEX  (0)
`define S_WR_EN_WIDTH  (0-0+1)
`define S_WR_EN_RANGE `S_WR_EN_UPPER_INDEX:`S_WR_EN_LOWER_INDEX
`define S_RD_EN0_UPPER_INDEX  (0)
`define S_RD_EN0_LOWER_INDEX  (0)
`define S_RD_EN0_WIDTH  (0-0+1)
`define S_RD_EN0_RANGE `S_RD_EN0_UPPER_INDEX:`S_RD_EN0_LOWER_INDEX
`define S_RD_EN1_UPPER_INDEX  (0)
`define S_RD_EN1_LOWER_INDEX  (0)
`define S_RD_EN1_WIDTH  (0-0+1)
`define S_RD_EN1_RANGE `S_RD_EN1_UPPER_INDEX:`S_RD_EN1_LOWER_INDEX
`define S_VALID_UPPER_INDEX  (0)
`define S_VALID_LOWER_INDEX  (0)
`define S_VALID_WIDTH  (0-0+1)
`define S_VALID_RANGE `S_VALID_UPPER_INDEX:`S_VALID_LOWER_INDEX

`endif
