#!/usr/bin/perl

#oanab
#Test_Matrix: /test_matrices/ar_conn_by_name_matr.ods, 11 test cases

use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

print "Generated tests path : test/csl_test_gen/ar_conn_name_sss_valid/\n";

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_sss".$i."_legal.csl";
    if($j != $m) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+3;
    my $val2 = int(rand(100))+4;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_sss_valid");
        open(FH,">$path/ar_conn_name_sss_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_sss_invalid"); 
        open(FH,">$path/ar_conn_name_sss_invalid/$test_name");
    }
    print FH "//Generated by oanab\n\n";
    print FH "//Test_Matrix: /test_matrices/ar_conn_by_name_matr.ods\n\n";

    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";


#ifcj
    if($i > 50 && $i <= 150 || $i > 200) {
	print FH "csl_interface ifc$j {\n";
	print FH "  csl_port p_m$i(input,br1);\n";
	print FH "  csl_port p_n$i(output,br3);\n";
	print FH "  ifc$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#ifcm
    if($i > 100 && $i <= 150 || $i > 200) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_x$i(input,br2);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  ifc$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgj
    if($i > 150 && $i <= 200) {
	print FH "csl_signal_group sg$j {\n";
	if($i > 150 && $i <= 200) {
	    print FH "  csl_signal s_a$i(2);\n";
	}
	else {
	    print FH "  csl_signal s_a$i($val2);\n";
	}
	print FH "  csl_signal s_b$i(br1);\n";
	print FH "  csl_signal s_c$i(br3);\n";
	print FH "  sg$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }


#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  csl_port p_a$i(input,br3);\n";
	print FH "  csl_signal s_b$i($val1);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_port p_x$i($dir{$l},".($val2+$val3).");\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal s_m$i(".($val2+$val3).");\n";
	print FH "  csl_port p_x$i(input,".($val3+2).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_x$i($dir{$l},".($val2+$val1).");\n";
	print FH "  csl_signal s_n$i(".($val3+$val2).");\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    if($i <= 50) {
	print FH "  a$k a$k\_$zero;\n";
    }
    if($i > 50 && $i <= 100) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_signal s_x$i(br2);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  a$k a$k\_$zero(.ifc$m\_$zero.ifc$j\_$one(ifc$j\_$zero),.ifc$m\_$zero.ifc$j\_$zero.p_n$i(ifc$j\_$zero.p_n$i),.ifc$m\_$zero.p_x$i(s_x$i));\n";
	print FH "  csl_signal s_n$i($val3);\n";
	print FH "  csl_signal s_x$i(br2);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  a$k a$k\_$zero(.p_x$i({sg$j\_$zero.s_a$i,sg$j\_$zero.s_c$i}));\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_signal s_x$i(".($val1+$val2).");\n";
    }
    print FH "  b$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    if($i <= 50) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  csl_signal s_a$i(br3);\n";
	print FH "  csl_port p_b$i($dir{$l},br1);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero.p_n$i(s_a$i));\n";
	print FH "  a$k a$k\_$one;\n";
	print FH "  csl_signal s_a$i(br3);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero(ifc$j\_$tre));\n";
	print FH "  ifc$j ifc$j\_$tre;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  csl_port p_b$i(input,3);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  ifc$m ifc$m\_$one;\n";
    }
    print FH "  c$k () {\n";
    if($i <= 50) {
	print FH "    s_a$i\[".($val3-1)."\] = p_b$i\[".($val1-1)."\];  // assign : s.ps--p.ps\n";
	print FH "    s_a$i.connect_by_name(b$k\_$zero.a$k\_$zero.p_a$i,pa_$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.s_x$i.connect_by_name(a$k\_$one.p_x$i\[".($val2+$val3-1)."\:".$val3."\]);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    b$k\_$zero.s_n$i.connect_by_name(ifc$j\_$tre.p_n$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.sg$j\_$zero.s_b$i\[".($val1-1)."\:".($val1-3)."\].connect_by_name(p_b$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "    b$k\_$zero.s_x$i\[".($val1+$val2-1)."\:".$val2."\].connect_by_name(b$k\_$zero.a$k\_$zero.p_x$i\[".($val2+$val1-1)."\:".$val2."\]);\n";
	print FH "    b$k\_$zero.a$k\_$zero.s_n$i\[".($val3+$val2-1)."\:".$val2."\].connect_by_name(ifc$m\_$one.ifc$j\_$one.p_n$i,pa_n$i);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    if($i <= 50) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  a$k a$k\_$one(.p_a$i(s_a$i));\n";
	print FH "  csl_signal s_a$i($val3);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  csl_signal s_c$i(2);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  c$k c$k\_$zero(.ifc$j\_$tre(ifc$j\_$one));\n";
	print FH "  csl_signal s_m$i($val1);\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  c$k c$k\_$zero(.p_b$i(p_m$i\[".($val2-1)."\-\:".(3)."\]));\n";
	print FH "  csl_port p_m$i(input,br2);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  c$k c$k\_$zero(.ifc$m\_$one(ifc$m\_$zero));\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    print FH "  d$k () {\n";
    if($i <= 50) {
	print FH "    a$k\_$one.s_b$i.connect_by_name(c$k\_$zero.p_b$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    s_c$i.connect_by_name(c$k\_$zero.b$k\_$zero.ifc$j\_$zero.p_m$i\[".($val1-1)."\:".($val1-2)."\],pc$i);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    s_m$i.connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.ifc$m\_$zero.ifc$j\_$zero.p_m$i,pa_m$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.s_m$i\[".($val2+$val3-1)."\:".($val3)."\].connect_by_name(p_m$i,pa_m$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "    ifc$j\_$zero.p_n$i = ifc$m\_$zero.ifc$j\_$one.p_n$i;  // assign : ifc.p---ifc.ifc.p\n";
	print FH "    c$k\_$zero.b$k\_$zero.s_x$i\[".($val1+$val2-1)."\:".$val2."\].connect_by_name(ifc$j\_$zero.p_m$i);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";



}
