#!/usr/bin/perl

#oanab
#connect_by_name() with param : par obj and par obj with const ps, const obj with par ps, par obj with par ps

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_param_valid4/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_param".$i."_legal.csl";
    if($j != $m) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+2;
    my $val2 = int(rand(100))+1;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_param_valid4");
        open(FH,">$path/ar_conn_name_param_valid4/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_param_invalid1"); 
        open(FH,">$path/ar_conn_name_param_invalid1/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#ifcj
    if($i <= 250) {
	print FH "csl_interface ifc$j {\n";
	if($i <= 50 || $i > 150 && $i <= 200) {
	    print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	    print FH "  csl_parameter par2(".($val2).");\n";
	    print FH "  csl_port p_n$i(input,br2);\n";
	    print FH "  csl_port p_o$i(input,".($val1+$val2+$val3).");\n";
	}
	elsif($i > 50 && $i <= 100 || $i > 200 && $i <= 250) {
	    print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	    print FH "  csl_parameter par2(".($val1).");\n";
	    print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	    print FH "  csl_port p_m$i(output,par_m$i);\n";
	    print FH "  csl_parameter par_n$i(".($val3+$val2).");\n";
	    print FH "  csl_port p_n$i(input,par_n$i);\n";
	}
	elsif($i > 100 && $i <= 150) {
	    print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	    print FH "  csl_port p_m$i(output,par_m$i);\n";
	    print FH "  csl_parameter par_n$i(".($val3+$val2+$val1).");\n";
	    print FH "  csl_port p_n$i(input,par_n$i);\n";
	}
	print FH "  ifc$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgj
    if($i <= 250) {
	print FH "csl_signal_group sg$j {\n";
	if($i <= 50 || $i > 150 && $i <= 200) {
	    print FH "  csl_parameter par1(".($val2+$val3-1).");\n";
	    print FH "  csl_parameter par2(".($val2).");\n";
	    print FH "  csl_signal p_n$i(".($val1+$val2).");\n";
	    print FH "  csl_signal p_o$i(".($val2+$val3).");\n";
	}
	elsif($i > 50 && $i <= 100 || $i > 200 && $i <= 250) {
	    print FH "  csl_parameter par3(".($val3+$val2-1).");\n";
	    print FH "  csl_parameter par4(".($val2).");\n";
	    print FH "  csl_parameter par_m$i(".($val2+$val3).");\n";
	    print FH "  csl_signal p_m$i(par_m$i);\n";
	    print FH "  csl_parameter par_n$i($val3);\n";
	    print FH "  csl_signal p_n$i(par_n$i);\n";
	}
	elsif($i > 100 && $i <= 150) {
	    print FH "  csl_parameter par_m$i(".($val1+$val2+$val3).");\n";
	    print FH "  csl_signal p_m$i(par_m$i);\n";
	    print FH "  csl_parameter par_n$i(".($val1+$val2).");\n";
	    print FH "  csl_signal p_n$i(par_n$i);\n";
	}
	print FH "  sg$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }


#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  csl_signal s_a$i(br2);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_port p_a$i(input,".($val1+$val3).");\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_port p_m$i($dir{$l},br1);\n";
	print FH "  csl_signal s_c$i(".($val1).");\n";
	print FH "  csl_signal s_d$i(br2);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	print FH "  csl_port p_m$i(input,par_m$i);\n";
	print FH "  csl_parameter par_s$i(".$val2.");\n";
	print FH "  csl_signal s_s$i(par_s$i);\n";
	print FH "  csl_parameter par_a$i(".($val1).");\n";
	print FH "  csl_port p_a$i(output,par_a$i);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_x$i(".($val1+$val2).");\n";
	print FH "  csl_parameter par_c$i(".($val3).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  csl_parameter par_m$i(".($val1+$val3).");\n";
	print FH "  csl_port p_m$i(input,par_m$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	print FH "  csl_signal s_m$i(par_m$i);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par_n$i(".($val3).");\n";
	print FH "  csl_port p_n$i(output,par_n$i);\n";
    }
    print FH "  a$k () {\n";
    if($i > 100 && $i <= 150) {
	print FH "    sg$j\_$one.p_n$i = p_m$i;  // assig : sg.sig---ppar\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    s_x$i = sg$j\_$zero.p_n$i;  // assig : sig---sg.sig\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    if($i <= 50) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$zero.p_n$i(sg$j\_$one.p_n$i\[".($val1+$val2-1)."\:".($val1)."\]));\n";
	print FH "  csl_port p_b$i(input,br2);\n";
	print FH "  csl_port p_c$i(input,br2);\n";
	print FH "  csl_signal s_o$i(".($val1+$val3).");\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	print FH "  csl_signal s_m$i(par_m$i);\n";
	print FH "  csl_port p_a$i(output,br2);\n";
	print FH "  csl_port p_b$i(input,br3);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  a$k a$k\_$zero(.p_a$i(ifc$j\_$zero.p_m$i\[".($val1+$val2-1)."\:".($val2)."\]));\n";
	print FH "  a$k a$k\_$one(.p_m$i(ifc$j\_$zero.p_n$i\[".($val1+$val2+$val3-1)."\:".($val3)."\]));\n";
	print FH "  csl_parameter par_a$i(".($val2+$val3).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  csl_parameter par_b$i(1);\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_parameter par_b$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par_c$i(".($val3).");\n";
	print FH "  csl_port p_b$i(input,par_c$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_parameter par_d$i(".($val2).");\n";
	print FH "  csl_port p_e$i(output,par_d$i);\n";
	print FH "  csl_parameter par_c$i(".($val3).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  csl_signal s_d$i(par_d$i);\n";
    }
    print FH "  b$k () {\n";
#connect_by_name : sig---ifc.p.pspar (PC)
    if($i <= 50) {
	print FH "    s_o$i.connect_by_name(a$k\_$zero.ifc$j\_$zero.p_o$i\[".($val1+$val2+$val3-1)."\:par2\]);  // sig---ifc.p.pspar (PC)\n";
    }
#connect_by_name : port---spar.pspar (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "    a$k\_$zero.p_m$i.connect_by_name(s_m$i\[par1\-\:par2\]);  // port---spar.pspar (CP)\n";
    }
#connect_by_name : spar---ifc.ppar.ps (CP) and ppar---ifc.ppar.ps (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    a$k\_$zero.s_s$i.connect_by_name(ifc$j\_$zero.p_n$i\[".($val2+$val3-1)."\-\:".($val2)."\]);  // spar---ifc.ppar.ps (CP)\n";
	print FH "    a$k\_$one.p_a$i.connect_by_name(ifc$j\_$zero.p_m$i\[".($val1+$val2-1)."\:".($val2)."\]);  // ppar---ifc.ppar.ps (CP)\n";
    }
#connect_by_name : ppar---sg.s.pspar (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    p_b$i.connect_by_name(a$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par2\]);  // ppar---sg.s.pspar (PC)\n";
	print FH "    s_b$i\[".($val1+$val3-1)."\:".($val1)."\] = p_b$i;  // assign : spar---ppar.ps\n";
    }
#connect_by_name : ppar---ifc.ppar.pspar (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    p_e$i.connect_by_name(a$k\_$zero.ifc$j\_$zero.p_m$i\[".($val1+$val2-1)."\:par2\]);  // ppar---ifc.ppar.pspar (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    if($i <= 50) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  csl_parameter par1(".($val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_signal s_b$i(".($val2+2*$val3).");\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  csl_port p_o$i(input,br3);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  b$k b$k\_$zero(.p_b$i(sg$j\_$one.p_n$i));\n";
	print FH "  csl_parameter par1(".($val2+$val3+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val3+$val2).");\n";
	print FH "  csl_parameter par_s$i(".($val2+$val3+$val1).");\n";
	print FH "  csl_port p_s$i(input,par_s$i);\n";
	print FH "  csl_port p_z$i(input,par_s$i);\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero.p_m$i(s_m$i));\n";
	print FH "  csl_parameter par_x$i(".$val3.");\n";
	print FH "  csl_port p_x$i(input,par_x$i);\n";
	print FH "  csl_parameter par_y$i(".($val3+$val1).");\n";
	print FH "  csl_port p_y$i(input,par_y$i);\n";
	print FH "  csl_signal s_m$i(".($val2+$val1).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  b$k b$k\_$zero(.p_b$i(p_n$i\[".($val2+$val3-1)."\:".($val2)."\]),.ifc$j\_$zero.p_n$i(p_n$i\[".($val2+$val3-1)."\-\:".($val2)."\]));\n";
	print FH "  csl_parameter par1(".($val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_port p_n$i(input,".($val2+$val3).");\n";
#	print FH "  b$k b$k\_$one(.p_b$i(s_b$i),.ifc$j\_$zero.p_n$i(p_n$i\[".($val2+$val3-1)."\:".($val3)."\]));\n";
#	print FH "  csl_signal s_b$i(".($val3).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  b$k b$k\_$zero(.p_e$i(s_e$i));\n";
	print FH "  csl_signal s_e$i(".($val2).");\n";
	print FH "  csl_parameter par_d$i(".($val2).");\n";
	print FH "  csl_port p_d$i(input,par_d$i);\n";
	print FH "  csl_parameter par1(".($val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par_z$i(".($val2+$val3).");\n";
	print FH "  csl_port p_z$i(input,par_z$i);\n";
	print FH "  csl_port p_x$i(input,par_z$i);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    print FH "  c$k () {\n";
#connect_by_name : port---s.pspar (CP) and port---ifc.p.pspar (CP) and port---sg.s.pspar (PC)
    if($i <= 50) {
	print FH "    b$k\_$zero.p_b$i.connect_by_name(s_b$i\[par1\:par2\]);  // port---s.pspar (CP)\n";
	print FH "    b$k\_$zero.a$k\_$zero.p_a$i.connect_by_name(ifc$j\_$one.p_o$i\[par1\:par2\]);  // port---ifc.p.pspar (CP)\n";
	print FH "    p_o$i.connect_by_name(b$k\_$zero.sg$j\_$one.p_o$i\[".($val2+$val3-1)."\:par2\]);  // port---sg.s.pspar (PC)\n";
    }
#connect_by_name : sig---ppar.pspar (CP) and sig---ifc.ppar.pspar (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "   b$k\_$zero.a$k\_$zero.s_c$i.connect_by_name(p_s$i\[par1\:par2\]);  // sig---ppar.pspar (CP)\n";
	print FH "    b$k\_$zero.a$k\_$zero.s_d$i.connect_by_name(ifc$j\_$one.p_m$i\[par1\:par2\]);  // sig---ifc.ppar.pspar (CP)\n";
    }
#connect_by_name : ppar---spar.ps (PC) and ppar---sg.spar.ps (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    p_x$i.connect_by_name(b$k\_$zero.s_a$i\[".($val2+$val3-1)."\:".($val2)."\]);  // ppar---spar.ps (PC)\n";
	print FH "    p_y$i.connect_by_name(b$k\_$zero.a$k\_$zero.sg$j\_$one.p_m$i\[".($val1+$val2+$val3-1)."\:".($val2)."\]);  // ppar---sg.spar.ps (PC)\n";
    }
#connect_by_name : spar---p.pspar (CP) and ppar---ifc.p.pspar (SS)
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.a$k\_$zero.s_c$i.connect_by_name(p_n$i\[par1\:par2\]);  // spar---p.pspar (CP)\n";
	print FH "    b$k\_$zero.a$k\_$zero.p_m$i.connect_by_name(b$k\_$zero.ifc$j\_$zero.p_o$i\[".($val1+$val2+$val3-1)."\:par2\]);  // ppar---ifc.p.pspar (SS)\n";
    }
#connect_by_name : ppar---spar.pspar (PC) and spar---ppar.pspar (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    p_d$i.connect_by_name(b$k\_$zero.a$k\_$zero.s_m$i\[par1\:par2\]);  // ppar---spar.pspar (PC)\n";
	print FH "    b$k\_$zero.s_c$i.connect_by_name(p_z$i\[par1\:par2\]);  // spar---ppar.pspar (CP)\n";
	print FH "    b$k\_$zero.a$k\_$zero.ifc$j\_$zero.p_n$i\[".($val2+$val3-1)."\:".($val2)."\].connect_by_name(p_x$i\[par1\:par2\]);  // ifc.ppar.ps---ppar.pspar (CP)\n";
	print FH "    {s_e$i\[".($val2-1)."\:".(1)."\],sg$j\_$one.p_n$i\[".($val3-1)."\]} = p_d$i;  // assign : concat---ppar\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    if($i <= 50) {
	print FH "  c$k c$k\_$zero(.ifc$j\_$one.p_n$i(p_a$i\[par1\-\:par2\]),.ifc$j\_$one.p_o$i(p_c$i),.p_o$i(p_a$i\[".($val2+$val3-1)."\:par2\]));\n";
	print FH "  csl_parameter par1(".($val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par3(".($val3).");\n";
	print FH "  csl_port p_c$i(input,".($val3+$val2+$val1).");\n";
	print FH "  csl_port p_a$i(input,".($val3+$val2).");\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  c$k c$k\_$zero(.ifc$j\_$one(ifc$j\_$zero));\n";
	print FH "  csl_port p_a$i(input,$val1);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_signal s_b$i(".($val2).");\n";
	print FH "  b$k b$k\_$one(.p_a$i(s_b$i));\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  c$k c$k\_$zero(.p_y$i(ifc$j\_$one.p_n$i\[".($val3+$val2+$val1-1)."\:".($val2)."\]));\n";
	print FH "  csl_parameter par_c$i(".($val2+2*$val1).");\n";
	print FH "  csl_port p_c$i(input,par_c$i);\n";
	print FH "  csl_signal s_m$i(".($val1).");\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  c$k c$k\_$zero(.p_n$i(p_d$i));\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  csl_parameter par_c$i(".($val2+$val3).");\n";
	print FH "  csl_port p_c$i(output,par_c$i);\n";
        print FH "  csl_port p_d$i(input,par_c$i);\n"; 
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  c$k c$k\_$zero(.p_d$i(ifc$j\_$one.p_n$i\[".($val2+$val3-1)."\:".($val3)."\]));\n";
	print FH "  csl_parameter par_a$i(".($val3).");\n";
	print FH "  csl_port p_a$i(input,par_a$i);\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    print FH "  d$k () {\n";
#connect_by_name : sig---p.pspar (CP) and port---p.pspar (CP)
    if($i <= 50) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.s_a$i.connect_by_name(p_a$i\[par1\:par3\]);  // sig---p.pspar (PC)\n";
	print FH "    c$k\_$zero.b$k\_$zero.p_c$i.connect_by_name(p_c$i\[par1\-\:par2\]);  // port---p.pspar (CP)\n";
    }
#connect_by_name : port---ppar.pspar (PC) and port---ifc.ppar.pspar (CP) and port---sg.spar.pspar (SS)
    elsif($i > 50 && $i <= 100) {
	print FH "    p_a$i.connect_by_name(c$k\_$zero.p_z$i\[par1\:par2\]);  // port---ppar.pspar (PC)\n";
	print FH "    c$k\_$zero.b$k\_$zero.p_a$i.connect_by_name(ifc$j\_$zero.p_m$i\[par1\:par2\]);  // port---ifc.ppar.pspar (CP)\n";
	print FH "    b$k\_$one.p_b$i.connect_by_name(c$k\_$zero.sg$j\_$one.p_m$i\[".($val3+$val2-1)."\:par4\]);  // port---sg.spar.pspar (SS)\n";
    }
#connect_by_name : spar---ppar.ps (CP) and  ppar---ppar.ps (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.b$k\_$zero.s_b$i.connect_by_name(c$k\_$zero.p_x$i\[".($val3-1)."\]);  // spar---ppar.ps (CP)\n";
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.p_m$i.connect_by_name(p_c$i\[".($val2+2*$val1-1)."\:".($val1)."\]);  // ppar---ppar.ps (CP)\n";
	print FH "    ifc$j\_$one.p_m$i\[".($val1+$val2-1)."\-\:".($val1)."\] = s_m$i;  // assign : ifc.ppar.ps---sig\n";
    }
#connect_by_name : ppar---s.pspar (PC) and spar---ifc.p.pspar (CP)
    elsif($i > 150 && $i <= 200) {
	print FH "    p_c$i\[".($val2+$val3-1)."\:".($val3)."\].connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.s_x$i\[par1\:par2\]);  // ppar---s.pspar (PC)\n";
	print FH "    c$k\_$zero.b$k\_$zero.s_b$i.connect_by_name(ifc$j\_$one.p_o$i\[par1\:par2\]);  // spar---ifc.p.pspar (CP)\n";
    }
#connect_by_name : ppar---ppar.pspar (PC) and spar---ifc.ppar.pspar (CP) and ppar---sg.spar.pspar (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    p_a$i.connect_by_name(c$k\_$zero.p_x$i\[par1\:par2\]);  // ppar---ppar.pspar (PC)\n";
	print FH "    c$k\_$zero.b$k\_$zero.s_d$i.connect_by_name(ifc$j\_$one.p_m$i\[".($val1+$val2-1)."\:par2\]);  // spar---ifc.ppar.pspar (CP)\n";
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.p_n$i.connect_by_name(c$k\_$zero.sg$j\_$one.p_m$i\[".($val3+$val2-1)."\:par4\]);  // ppar---sg.spar.pspar (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
