#!/usr/bin/perl

#Author Monica
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 40; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $test_name = "connect_port_unit_test".$i."_illegal.csl";
    &createCslFile($test_name, $i);
}
sub createCslFile {
    my($test_name, $i) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
 if($i==1){
        print ("Generated path: $path/ar_connect_port_unit_invalid/ \n");}
    my $val = int(rand(500));
    if($val == 0) { $val = 1; }
    my $val1 =int(rand(25))+1;

    if($test_name=~/(_illegal)/){
        &mkDir("$path/ar_connect_port_unit_invalid");
        open(FH,">$path/ar_connect_port_unit_invalid/$test_name");
    }
#*************************************************
#port.connect(unit)
 print FH "csl_bitrange br($val);\n\n";
    if( $i<=10){
    print FH "//Generated by Monica\n";
    print FH "//Connect port--unit\n\n";
    print FH "// INVALID TEST $i;\n";
   
    print FH " csl_unit u_$i {\n";
    foreach( my $j=1; $j<=$i+1; $j++){
    print FH "   csl_port  p1_$j(input,$j);\n";
    print FH "   csl_port  p2_$j(output,$j);\n";
}
    print FH " u_$i(){\n";
    print FH " }\n";
    print FH "};\n";

    print FH " csl_unit top_$i {\n";
    foreach( my $j=1; $j<=$i+1; $j++){
    print FH "   csl_port  pt1_$j(input,$j);\n";
    print FH "   csl_port  pt2_$j(output,$j);\n";
}
foreach( my $j=1; $j<=$i+1; $j++){
    print FH " u_$i u_i$j;\n";
}
    print FH " top_$i(){\n";
foreach( my $j=1; $j<=$i+1; $j++){
    my $k=$j+1;
    if($k<=$i+1){
    print FH " u_i$j.p1_$j.connect(u_i$k);    //invalid connection: unit.port--unit\n";
    print FH " u_i$j.p2_$j.connect(u_i$k);    //invalid connection: unit.port--unit\n";
    print FH " pt1_$j.connect(u_i$j);         //invalid connection:  port--unit\n";
}
}
    print FH " }\n";
    print FH "};\n";
}
#*************************************************
#signal.connect(unit)

    if( $i>10 && $i<=20){
    print FH "//Generated by Monica\n";
    print FH "//Connect signal--unit\n\n";
    print FH "// INVALID TEST $i;\n";
   
    print FH " csl_unit u_$i {\n";
  foreach( my $j=11; $j<=$i+1; $j++){
    print FH "   csl_signal  s1_$j($j);\n";
    print FH "   csl_signal  s2_$j($j);\n";
}
    print FH "   csl_port    p1(output,br);\n";

    print FH " u_$i(){\n";
    print FH " }\n";
    print FH "};\n";
   print FH " csl_unit top_$i {\n";
    foreach( my $j=11; $j<=$i+1; $j++){
    print FH "   csl_signal  st1_$j($j);\n";
    print FH "   csl_signal  st2_$j($j);\n";
}
foreach( my $j=11; $j<=$i+1; $j++){
    print FH " u_$i u_i$j;\n";
}
    print FH " top_$i(){\n";
foreach( my $j=11; $j<=$i+1; $j++){
    my $k=$j+1;
    if($k<=$i+1){
    print FH " u_i$j.s1_$j.connect(u_i$k);    //invalid connection: unit.signal--unit\n";
    print FH " u_i$j.s2_$j.connect(u_i$k);    //invalid connection: unit.signal--unit\n";
    print FH " st2_$j.connect(u_i$j);         //invalid connection: signal--unit\n";
}
}

    print FH " }\n";
    print FH "};\n";
}
#*************************************************
#unit.connect(unit)

#    if( $i>20 && $i<=30){
#    print FH "//Generated by Monica\n";
#    print FH "//Connect unit--unit\n\n";
#    print FH "// INVALID TEST $i;\n";
   
#    print FH " csl_unit u1_$i {\n";
#  foreach( my $j=21; $j<=$i+1; $j++){
#    print FH "   csl_signal  s1_$j($j);\n";
#    print FH "   csl_signal  s2_$j($j);\n";
#}
#    print FH "   csl_port    p1(output,br);\n";

#    print FH " u1_$i(){\n";
#    print FH " }\n";
#    print FH "};\n";

#   print FH " csl_unit u2_$i {\n";
#   print FH "   csl_port    p1(output,br);\n";
#  foreach( my $j=21; $j<=$i+1; $j++){
#      print FH " u1_$i u1_i$j;\n";
#}
   
#    print FH " u2_$i(){\n";
#    print FH " }\n";
#    print FH "};\n";

#   print FH " csl_unit top_$i {\n";
#    foreach( my $j=21; $j<=$i+1; $j++){
#    print FH "   csl_signal  st1_$j($j);\n";
#    print FH "   csl_signal  st2_$j($j);\n";
#}
# foreach( my $j=21; $j<=$i+1; $j++){
#    print FH " u2_$i u2_i$j;\n";
#}
#    print FH " top_$i(){\n";
# foreach( my $j=21; $j<=$i+1; $j++){
#    my $k=$j+1;
# if($k<=$i+1){
#    print FH " u2_i$j.u1_i$j.connect(u2_i$k);              //invalid connection: unit.unit1--unit\n";
#    print FH " u2_i$j.u1_i$j.connect(u2_i$j.u1_i$k);       //invalid connection: unit.unit1--unit.unit1\n";
#    print FH " u2_i$j.connect(u2_i$k.u1_i$j);              //invalid connection: unit--unit.unit1\n";
#    print FH " u2_i$j.connect(u2_i$k);                     //invalid connection: unit--unit\n";
#}
#}
#    print FH " }\n";
#    print FH "};\n";
#}
#*************************************************
# rf.connect(unit)

 if( $i>20 && $i<=30){
    print FH "//Generated by Monica\n";
    print FH "//Connect rf--unit\n\n";
    print FH "// INVALID TEST $i;\n";

    print FH " csl_register_file rf {\n";
    print FH " rf(){\n";
    print FH " set_width(32);\n";
    print FH " set_depth(1<<16);\n";
    print FH " }\n";
    print FH "};\n";

    print FH " csl_unit u1_$i {\n";
  foreach( my $j=21; $j<=$i+1; $j++){
    print FH "   csl_signal  s1_$j($j);\n";
    print FH "   csl_signal  s2_$j($j);\n";
}
    print FH "   csl_port    p1(output,br);\n";
 foreach( my $j=21; $j<=$i+1; $j++){
     print FH " rf rf1_$j;\n";
 }
    print FH " u1_$i(){\n";
    print FH " }\n";
    print FH "};\n";

  print FH " csl_unit u2_$i {\n";
   print FH "   csl_port    p1(output,br);\n";
  foreach( my $j=21; $j<=$i+1; $j++){
      print FH " u1_$i u1_i$j;\n";
}
   foreach( my $j=21; $j<=$i+1; $j++){
   print FH " rf rf2_$j;\n";
}
    print FH " u2_$i(){\n";
    print FH " }\n";
    print FH "};\n";

   print FH " csl_unit top_$i {\n";
    foreach( my $j=21; $j<=$i+1; $j++){
    print FH "   csl_signal  st1_$j($j);\n";
    print FH "   csl_signal  st2_$j($j);\n";
}
foreach( my $j=21; $j<=$i+1; $j++){
    print FH " u2_$i u2_i$j;\n";
}
    print FH " top_$i(){\n";
foreach( my $j=21; $j<=$i+1; $j++){
    my $k=$j+1;
 if($k<=$i+1){
    print FH " u2_i$j.u1_i$j.rf1_$j.connect(u2_i$k);        //invalid connection: unit.unit1.rf--unit \n";
    print FH " u2_i$j.u1_i$j.rf1_$j.connect(u2_i$j.u1_i$k); //invalid connection: unit.unit1.rf--unit.unit1\n";
    print FH " u2_i$j.rf2_$j.connect(u2_i$k.u1_i$j);       //invalid connection: unit.rf--unit.unit1\n";
    print FH " u2_i$j.rf2_$j.connect(u2_i$k);              //invalid connection: unit.rf--unit\n";
}
}
    print FH " }\n";
    print FH "};\n";
}
#*************************************************
# fifo.connect(unit)
if( $i>30 && $i<=40){
    print FH "//Generated by Monica\n";
    print FH "//Connect fifo--unit\n\n";
    print FH "// INVALID TEST $i;\n";

    print FH " csl_fifo fifo1 {\n";
    print FH " fifo1(){\n";
    print FH " set_width(32);\n";
    print FH " set_depth(1<<16);\n";
    print FH " }\n";
    print FH "};\n";
 print FH " csl_unit u1_$i {\n";
  foreach( my $j=31; $j<=$i+1; $j++){
    print FH "   csl_signal  s1_$j($j);\n";
    print FH "   csl_signal  s2_$j($j);\n";
}
    print FH "   csl_port    p1(output,br);\n";
 foreach( my $j=31; $j<=$i+1; $j++){
     print FH " fifo1 f1_$j;\n";
 }
    print FH " u1_$i(){\n";
    print FH " }\n";
    print FH "};\n";

  print FH " csl_unit u2_$i {\n";
   print FH "   csl_port    p1(output,br);\n";
  foreach( my $j=31; $j<=$i+1; $j++){
      print FH " u1_$i u1_i$j;\n";
}
   foreach( my $j=31; $j<=$i+1; $j++){
   print FH " fifo1 f2_$j;\n";
}
    print FH " u2_$i(){\n";
    print FH " }\n";
    print FH "};\n";

   print FH " csl_unit top_$i {\n";
    foreach( my $j=31; $j<=$i+1; $j++){
    print FH "   csl_signal  st1_$j($j);\n";
    print FH "   csl_signal  st2_$j($j);\n";
}
foreach( my $j=31; $j<=$i+1; $j++){
    print FH " u2_$i u2_i$j;\n";
}
    print FH " top_$i(){\n";
foreach( my $j=31; $j<=$i+1; $j++){
    my $k=$j+1;
 if($k<=$i+1){
    print FH " u2_i$j.u1_i$j.f1_$j.connect(u2_i$k);        //invalid connection: unit.unit1.fifo--unit \n";
    print FH " u2_i$j.u1_i$j.f1_$j.connect(u2_i$j.u1_i$k); //invalid connection: unit.unit1.fifo--unit.unit1\n";
    print FH " u2_i$j.f2_$j.connect(u2_i$k.u1_i$j);       //invalid connection: unit.fifo--unit.unit1\n";
    print FH " u2_i$j.f2_$j.connect(u2_i$k);              //invalid connection: unit.fifo--unit\n";
}
}
    print FH " }\n";
    print FH "};\n";
}

    close(FH);
}
