`ifndef INC_GUARD_a
`define INC_GUARD_a

`define IFC_IFC10_P_X_UPPER_INDEX  (0)
`define IFC_IFC10_P_X_LOWER_INDEX  (0)
`define IFC_IFC10_P_X_WIDTH  (0-0+1)
`define IFC_IFC10_P_X_RANGE `IFC_IFC10_P_X_UPPER_INDEX:`IFC_IFC10_P_X_LOWER_INDEX
`define IFC_IFC10_P_Y_UPPER_INDEX  (0)
`define IFC_IFC10_P_Y_LOWER_INDEX  (0)
`define IFC_IFC10_P_Y_WIDTH  (0-0+1)
`define IFC_IFC10_P_Y_RANGE `IFC_IFC10_P_Y_UPPER_INDEX:`IFC_IFC10_P_Y_LOWER_INDEX

`endif
