`ifndef INC_GUARD_Clk_ctrl
`define INC_GUARD_Clk_ctrl

`define P_RESET_UPPER_INDEX  (0)
`define P_RESET_LOWER_INDEX  (0)
`define P_RESET_WIDTH  (0-0+1)
`define P_RESET_RANGE `P_RESET_UPPER_INDEX:`P_RESET_LOWER_INDEX
`define P_CLK_125M_UPPER_INDEX  (0)
`define P_CLK_125M_LOWER_INDEX  (0)
`define P_CLK_125M_WIDTH  (0-0+1)
`define P_CLK_125M_RANGE `P_CLK_125M_UPPER_INDEX:`P_CLK_125M_LOWER_INDEX
`define P_SPEED_UPPER_INDEX  (3-1)
`define P_SPEED_LOWER_INDEX  (0)
`define P_SPEED_WIDTH  (3)
`define P_SPEED_RANGE `P_SPEED_UPPER_INDEX:`P_SPEED_LOWER_INDEX
`define P_GTX_CLK_UPPER_INDEX  (0)
`define P_GTX_CLK_LOWER_INDEX  (0)
`define P_GTX_CLK_WIDTH  (0-0+1)
`define P_GTX_CLK_RANGE `P_GTX_CLK_UPPER_INDEX:`P_GTX_CLK_LOWER_INDEX
`define P_RX_CLK_UPPER_INDEX  (0)
`define P_RX_CLK_LOWER_INDEX  (0)
`define P_RX_CLK_WIDTH  (0-0+1)
`define P_RX_CLK_RANGE `P_RX_CLK_UPPER_INDEX:`P_RX_CLK_LOWER_INDEX
`define P_TX_CLK_UPPER_INDEX  (0)
`define P_TX_CLK_LOWER_INDEX  (0)
`define P_TX_CLK_WIDTH  (0-0+1)
`define P_TX_CLK_RANGE `P_TX_CLK_UPPER_INDEX:`P_TX_CLK_LOWER_INDEX
`define P_MAC_TX_CLK_UPPER_INDEX  (0)
`define P_MAC_TX_CLK_LOWER_INDEX  (0)
`define P_MAC_TX_CLK_WIDTH  (0-0+1)
`define P_MAC_TX_CLK_RANGE `P_MAC_TX_CLK_UPPER_INDEX:`P_MAC_TX_CLK_LOWER_INDEX
`define P_MAC_RX_CLK_UPPER_INDEX  (0)
`define P_MAC_RX_CLK_LOWER_INDEX  (0)
`define P_MAC_RX_CLK_WIDTH  (0-0+1)
`define P_MAC_RX_CLK_RANGE `P_MAC_RX_CLK_UPPER_INDEX:`P_MAC_RX_CLK_LOWER_INDEX
`define P_MAC_TX_CLK_DIV_UPPER_INDEX  (0)
`define P_MAC_TX_CLK_DIV_LOWER_INDEX  (0)
`define P_MAC_TX_CLK_DIV_WIDTH  (0-0+1)
`define P_MAC_TX_CLK_DIV_RANGE `P_MAC_TX_CLK_DIV_UPPER_INDEX:`P_MAC_TX_CLK_DIV_LOWER_INDEX
`define P_MAC_RX_CLK_DIV_UPPER_INDEX  (0)
`define P_MAC_RX_CLK_DIV_LOWER_INDEX  (0)
`define P_MAC_RX_CLK_DIV_WIDTH  (0-0+1)
`define P_MAC_RX_CLK_DIV_RANGE `P_MAC_RX_CLK_DIV_UPPER_INDEX:`P_MAC_RX_CLK_DIV_LOWER_INDEX

`endif
