`ifndef INC_GUARD_mfd_sec_lba
`define INC_GUARD_mfd_sec_lba

`define IFC_LB_P_DUMMY3_UPPER_INDEX  0
`define IFC_LB_P_DUMMY3_LOWER_INDEX  0
`define IFC_LB_P_DUMMY3_WIDTH  1
`define IFC_LB_P_DUMMY3_RANGE `IFC_LB_P_DUMMY3_UPPER_INDEX:`IFC_LB_P_DUMMY3_LOWER_INDEX
`define IFC_LBA_P_DUMMY2_UPPER_INDEX  0
`define IFC_LBA_P_DUMMY2_LOWER_INDEX  0
`define IFC_LBA_P_DUMMY2_WIDTH  1
`define IFC_LBA_P_DUMMY2_RANGE `IFC_LBA_P_DUMMY2_UPPER_INDEX:`IFC_LBA_P_DUMMY2_LOWER_INDEX

`endif
