`ifndef INC_GUARD_b
`define INC_GUARD_b

`define P_P_M_UPPER_INDEX  (78-1)
`define P_P_M_LOWER_INDEX  (0)
`define P_P_M_WIDTH  (78)
`define P_P_M_RANGE `P_P_M_UPPER_INDEX:`P_P_M_LOWER_INDEX
`define P_P_C_UPPER_INDEX  (64-1)
`define P_P_C_LOWER_INDEX  (0)
`define P_P_C_WIDTH  (64)
`define P_P_C_RANGE `P_P_C_UPPER_INDEX:`P_P_C_LOWER_INDEX
`define IFC_IFC11_P_P_X_UPPER_INDEX  (88-1)
`define IFC_IFC11_P_P_X_LOWER_INDEX  (0)
`define IFC_IFC11_P_P_X_WIDTH  (88)
`define IFC_IFC11_P_P_X_RANGE `IFC_IFC11_P_P_X_UPPER_INDEX:`IFC_IFC11_P_P_X_LOWER_INDEX
`define IFC_IFC11_IFC_IFC00_P_P_M_UPPER_INDEX  (78-1)
`define IFC_IFC11_IFC_IFC00_P_P_M_LOWER_INDEX  (0)
`define IFC_IFC11_IFC_IFC00_P_P_M_WIDTH  (78)
`define IFC_IFC11_IFC_IFC00_P_P_M_RANGE `IFC_IFC11_IFC_IFC00_P_P_M_UPPER_INDEX:`IFC_IFC11_IFC_IFC00_P_P_M_LOWER_INDEX
`define IFC_IFC11_IFC_IFC00_P_P_N_UPPER_INDEX  (64-1)
`define IFC_IFC11_IFC_IFC00_P_P_N_LOWER_INDEX  (0)
`define IFC_IFC11_IFC_IFC00_P_P_N_WIDTH  (64)
`define IFC_IFC11_IFC_IFC00_P_P_N_RANGE `IFC_IFC11_IFC_IFC00_P_P_N_UPPER_INDEX:`IFC_IFC11_IFC_IFC00_P_P_N_LOWER_INDEX
`define IFC_IFC11_IFC_IFC00_P_P_O_UPPER_INDEX  (78-1)
`define IFC_IFC11_IFC_IFC00_P_P_O_LOWER_INDEX  (0)
`define IFC_IFC11_IFC_IFC00_P_P_O_WIDTH  (78)
`define IFC_IFC11_IFC_IFC00_P_P_O_RANGE `IFC_IFC11_IFC_IFC00_P_P_O_UPPER_INDEX:`IFC_IFC11_IFC_IFC00_P_P_O_LOWER_INDEX
`define IFC_IFC11_IFC_IFC01_P_P_M_UPPER_INDEX  (78-1)
`define IFC_IFC11_IFC_IFC01_P_P_M_LOWER_INDEX  (0)
`define IFC_IFC11_IFC_IFC01_P_P_M_WIDTH  (78)
`define IFC_IFC11_IFC_IFC01_P_P_M_RANGE `IFC_IFC11_IFC_IFC01_P_P_M_UPPER_INDEX:`IFC_IFC11_IFC_IFC01_P_P_M_LOWER_INDEX
`define IFC_IFC11_IFC_IFC01_P_P_N_UPPER_INDEX  (64-1)
`define IFC_IFC11_IFC_IFC01_P_P_N_LOWER_INDEX  (0)
`define IFC_IFC11_IFC_IFC01_P_P_N_WIDTH  (64)
`define IFC_IFC11_IFC_IFC01_P_P_N_RANGE `IFC_IFC11_IFC_IFC01_P_P_N_UPPER_INDEX:`IFC_IFC11_IFC_IFC01_P_P_N_LOWER_INDEX
`define IFC_IFC11_IFC_IFC01_P_P_O_UPPER_INDEX  (78-1)
`define IFC_IFC11_IFC_IFC01_P_P_O_LOWER_INDEX  (0)
`define IFC_IFC11_IFC_IFC01_P_P_O_WIDTH  (78)
`define IFC_IFC11_IFC_IFC01_P_P_O_RANGE `IFC_IFC11_IFC_IFC01_P_P_O_UPPER_INDEX:`IFC_IFC11_IFC_IFC01_P_P_O_LOWER_INDEX
`define IFC_IFC10_IFC_IFC00_P_P_N_UPPER_INDEX  (64-1)
`define IFC_IFC10_IFC_IFC00_P_P_N_LOWER_INDEX  (0)
`define IFC_IFC10_IFC_IFC00_P_P_N_WIDTH  (64)
`define IFC_IFC10_IFC_IFC00_P_P_N_RANGE `IFC_IFC10_IFC_IFC00_P_P_N_UPPER_INDEX:`IFC_IFC10_IFC_IFC00_P_P_N_LOWER_INDEX

`endif
