`ifndef INC_GUARD_u_cmp
`define INC_GUARD_u_cmp

`define IFC_IFC_OP_CMP_P_OP1_UPPER_INDEX  (15)
`define IFC_IFC_OP_CMP_P_OP1_LOWER_INDEX  (0)
`define IFC_IFC_OP_CMP_P_OP1_WIDTH  (15-0+1)
`define IFC_IFC_OP_CMP_P_OP1_RANGE `IFC_IFC_OP_CMP_P_OP1_UPPER_INDEX:`IFC_IFC_OP_CMP_P_OP1_LOWER_INDEX
`define IFC_IFC_OP_CMP_P_OP2_UPPER_INDEX  (15)
`define IFC_IFC_OP_CMP_P_OP2_LOWER_INDEX  (0)
`define IFC_IFC_OP_CMP_P_OP2_WIDTH  (15-0+1)
`define IFC_IFC_OP_CMP_P_OP2_RANGE `IFC_IFC_OP_CMP_P_OP2_UPPER_INDEX:`IFC_IFC_OP_CMP_P_OP2_LOWER_INDEX
`define P_RES_UPPER_INDEX  (0)
`define P_RES_LOWER_INDEX  (0)
`define P_RES_WIDTH  (0-0+1)
`define P_RES_RANGE `P_RES_UPPER_INDEX:`P_RES_LOWER_INDEX

`endif
