`ifndef INC_GUARD_u_control
`define INC_GUARD_u_control

`define P_S_STATUS_UPPER_INDEX  (8-1)
`define P_S_STATUS_LOWER_INDEX  (0)
`define P_S_STATUS_WIDTH  (8)
`define P_S_STATUS_RANGE `P_S_STATUS_UPPER_INDEX:`P_S_STATUS_LOWER_INDEX
`define P_OP_INSTR_UPPER_INDEX  (0)
`define P_OP_INSTR_LOWER_INDEX  (0)
`define P_OP_INSTR_WIDTH  (0-0+1)
`define P_OP_INSTR_RANGE `P_OP_INSTR_UPPER_INDEX:`P_OP_INSTR_LOWER_INDEX
`define P_R_INSTR_UPPER_INDEX  (0)
`define P_R_INSTR_LOWER_INDEX  (0)
`define P_R_INSTR_WIDTH  (0-0+1)
`define P_R_INSTR_RANGE `P_R_INSTR_UPPER_INDEX:`P_R_INSTR_LOWER_INDEX
`define P_WR_HADDR_UPPER_INDEX  (0)
`define P_WR_HADDR_LOWER_INDEX  (0)
`define P_WR_HADDR_WIDTH  (0-0+1)
`define P_WR_HADDR_RANGE `P_WR_HADDR_UPPER_INDEX:`P_WR_HADDR_LOWER_INDEX
`define P_WR_CRTADDR_UPPER_INDEX  (0)
`define P_WR_CRTADDR_LOWER_INDEX  (0)
`define P_WR_CRTADDR_WIDTH  (0-0+1)
`define P_WR_CRTADDR_RANGE `P_WR_CRTADDR_UPPER_INDEX:`P_WR_CRTADDR_LOWER_INDEX
`define P_WR_RAM_UPPER_INDEX  (0)
`define P_WR_RAM_LOWER_INDEX  (0)
`define P_WR_RAM_WIDTH  (0-0+1)
`define P_WR_RAM_RANGE `P_WR_RAM_UPPER_INDEX:`P_WR_RAM_LOWER_INDEX
`define P_RD_RAM_UPPER_INDEX  (0)
`define P_RD_RAM_LOWER_INDEX  (0)
`define P_RD_RAM_WIDTH  (0-0+1)
`define P_RD_RAM_RANGE `P_RD_RAM_UPPER_INDEX:`P_RD_RAM_LOWER_INDEX
`define P_RD_IM_UPPER_INDEX  (0)
`define P_RD_IM_LOWER_INDEX  (0)
`define P_RD_IM_WIDTH  (0-0+1)
`define P_RD_IM_RANGE `P_RD_IM_UPPER_INDEX:`P_RD_IM_LOWER_INDEX
`define P_RD_ROM_UPPER_INDEX  (0)
`define P_RD_ROM_LOWER_INDEX  (0)
`define P_RD_ROM_WIDTH  (0-0+1)
`define P_RD_ROM_RANGE `P_RD_ROM_UPPER_INDEX:`P_RD_ROM_LOWER_INDEX
`define P_INCR_UPPER_INDEX  (0)
`define P_INCR_LOWER_INDEX  (0)
`define P_INCR_WIDTH  (0-0+1)
`define P_INCR_RANGE `P_INCR_UPPER_INDEX:`P_INCR_LOWER_INDEX
`define P_DECR_UPPER_INDEX  (0)
`define P_DECR_LOWER_INDEX  (0)
`define P_DECR_WIDTH  (0-0+1)
`define P_DECR_RANGE `P_DECR_UPPER_INDEX:`P_DECR_LOWER_INDEX
`define P_WR_DM_UPPER_INDEX  (0)
`define P_WR_DM_LOWER_INDEX  (0)
`define P_WR_DM_WIDTH  (0-0+1)
`define P_WR_DM_RANGE `P_WR_DM_UPPER_INDEX:`P_WR_DM_LOWER_INDEX
`define P_RD_DM_UPPER_INDEX  (0)
`define P_RD_DM_LOWER_INDEX  (0)
`define P_RD_DM_WIDTH  (0-0+1)
`define P_RD_DM_RANGE `P_RD_DM_UPPER_INDEX:`P_RD_DM_LOWER_INDEX

`endif
