
CC = g++ 
OPT    = -O3  
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) -fexceptions 

MODULE = main 
SRCS = $(WORK)/trunk/src/cdom/SystemCVectorWriterTrace.cpp main.cpp 

OBJS = $(SRCS:.cpp = SystemCVectorWriterTrace.o main.o) 

include ./Makefile.defs
