#!/usr/bin/perl

#Author Petronela
use strict;

my $path = "$ENV{WORK}/test/csl_test_gen";
print "the path for generated tests is: $path/conn_units_pps_sps_u_mem_fifo_reg_rf_invalid\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

my @lower = (0,5,9,17,29);
my @upper = (33,44,53,68,82);
my @units = ("unit","fifo","register","register_file","memory");
foreach my $unit(@units){
    for (my $i = 1; $i <= 5; ++$i ) {       
        foreach my $l(@lower) {
            foreach my $u(@upper) { 
                &main($i,$l,$u,$unit);
            }
        }       
    }
}

sub main {
    my ($i,$l, $u,$unit) = @_;
    my $test_name = "conn_units_pps_sps_$unit"."_".$i."_".$l."_".$u."_illegal.csl";
    &createCslFile($test_name,$i, $l, $u,$unit);
}

sub createCslFile {
    my($test_name, $i,$l, $u,$unit) = @_;
    my $val1 = $u + int(rand(100)) + 1;
    my $w = $u - $l + 1;
    my $val2 = $val1 + int(rand(100)) + 1;
    my $val3 = $val1 + int(rand(100)) + 1;
    &mkDir("$path/conn_units_pps_sps_u_mem_fifo_reg_rf_invalid");
    open(FH,">$path/conn_units_pps_sps_u_mem_fifo_reg_rf_invalid/$test_name");

    print FH "//Generated by Petronela\n";
    print FH "//testing the method connect_units for connections port[part select] to  unit, port[part select] to fifo, port[part select] to register, port[part select] to register_file, port[part select] to memory \n";
    print FH "//unit to port[part select], fifo to port[part select], register to port[part select], refister_file to port[part select], memory to port[part select] and \n";
    print FH "//signal[part select] to unit, signal[part select] to fifo, signal[part select] to register, signal[part select] to register_file, signal[part select] to memory \n";
    print FH "//unit to signal, fifo to signal[part select], register to signal[part select], refister_file to signal[part select], memory to signal[part select] \n\n";
    print FH "csl_$unit ua {\n";
    if($unit eq "unit"){
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port pa(output,$val2);\n";
        print FH "  csl_port pb(output,$val3);\n";
    }
    print FH "  ua(){\n";
    if($unit ne "unit"){
        print FH "    set_width($val2);\n";
        if($unit ne "register"){
            print FH "    set_depth($val1);\n";
        }
        else{
            print FH "    set_type(register);\n";
        }
    }   
    print FH "  }\n";
    print FH "};\n\n";
    
    print FH "csl_$unit ub {\n";
    if($unit eq "unit"){
        print FH "  ua ua0;\n";
        print FH "  ua ua1;\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port pa(output,$val2);\n";
        print FH "  csl_port pb(output,$val3);\n";
    }
    
    print FH "  ub(){\n";
    if($unit ne "unit"){
        print FH "    set_width($val2);\n";
        if($unit ne "register"){
            print FH "    set_depth($val1);\n";
        }
        else{
            print FH "    set_type(register);\n";
        }
    }  
    print FH "  }\n";
    print FH "};\n\n";
    
    print FH "csl_$unit uc {\n";
    if($unit eq "unit"){
        print FH "  ub ub0;\n";
        print FH "  ub ub1;\n";
        print FH "  ua ua0;\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port pa(output,$val2);\n";
        print FH "  csl_port pb(output,$val3);\n";
    }
    
    print FH "  uc(){\n";
    if($unit ne "unit"){
        print FH "    set_width($val2);\n";
        if($unit ne "register"){
            print FH "    set_depth($val1);\n";
        }
        else{
            print FH "    set_type(register);\n";
        }
    }  
    print FH "  }\n";
    print FH "};\n\n";

    print FH "csl_$unit ud {\n";
    if($unit eq "unit"){
        print FH "  uc uc0;\n";
        print FH "  uc uc1;\n";
        print FH "  uc uc2;\n";
        print FH "  ub ub0;\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port pa(output,$val2);\n";
        print FH "  csl_port pb(output,$val3);\n";
    }
    
    print FH "  ud(){\n";
    if($unit ne "unit"){
        print FH "    set_width($val2);\n";
        if($unit ne "register"){
            print FH "    set_depth($val1);\n";
        }
        else{
            print FH "    set_type(register);\n";
        }
    }  
    print FH "  }\n";
    print FH "};\n\n";
    
    print FH "csl_unit top {\n";
    if($i <= 5) {
        print FH "  ud ud0;\n";
        print FH "  ud ud1;\n";
        print FH "  uc uc0;\n";
        print FH "  uc uc1;\n"; 
        print FH "  ub ub0;\n";
        print FH "  ua ua0;\n";
        print FH "  csl_port ptop(input,$val2);\n";
        print FH "  csl_port p(input,$val3);\n";
        print FH "  csl_signal s_top$i($val3);\n";
        print FH "  csl_signal stop($val2);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  ud ud0;\n";
        print FH "  ud ud1;\n";
        print FH "  ud ud2;\n";
        print FH "  uc uc0;\n";
        print FH "  uc uc1;\n";
        print FH "  ub ub0;\n";
        print FH "  ua ua0;\n";
        print FH "  csl_port p_top$i(output,$val2);\n";      
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port ptop(output,$val2);\n";        
        print FH "  csl_signal st($val2);\n";
        print FH "  csl_signal s_top_br$i($val3);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "  ud ud0;\n";
        print FH "  ud ud1;\n";
        print FH "  uc uc0;\n";
        print FH "  uc uc1;\n";
        print FH "  uc uc2;\n";
        print FH "  ub ub0;\n";
        print FH "  ua ua0;\n";
        print FH "  csl_port p_top$i(input,$val3);\n";      
        print FH "  csl_port p(input,$val3);\n";
        print FH "  csl_port p_top_br$i(input,$val2);\n";
        print FH "  csl_signal s_top$i($val2);\n";
        print FH "  csl_signal stop($val3);\n";
    }
    print FH "  top(){\n";
    if($i <= 5) {
        if($unit eq "unit"){
            print FH "    ptop[$u:$l].connect_units(ud0.uc2.ub1);\n";
            print FH "    uc1.ub0.connect_units(stop[$u:$l]);\n";
            print FH "    uc0.ua0.connect_units(p[$u-:$l]);\n";
            print FH "    s_top$i"."[$u:$l].connect_units(ud0.ub0);\n";
        }
        else {
            print FH "    ptop[$u:$l].connect_units(ud0);\n";
            print FH "    uc1.connect_units(stop[$u-:$l]);\n";
            print FH "    uc0.connect_units(p[$u:$l]);\n";
            print FH "    s_top$i"."[$u:$l].connect_units(ud1);\n";
        }
    }
    elsif($i > 5 && $i <= 10) {
        if($unit eq "unit"){
            print FH "    p_top$i"."[$u:$l].connect_units(ud0.uc2.ub1.ua0);\n";
            print FH "    uc1.ub0.ua1.connect_units(st[$u:$l]);\n";
            print FH "    uc0.connect_units(ptop[$u:$l]);\n";
            print FH "    s_top_br$i"."[$u-:$l].connect_units(ud2.ub1);\n";
        }
        else{
            print FH "    p_top$i"."[$u:$l].connect_units(ub0);\n";
            print FH "    ua0.connect_units(st[$u:$l]);\n";
            print FH "    uc0.connect_units(ptop[$u:$l]);\n";
            print FH "    s_top_br$i"."[$u-:$l].connect_units(ud2);\n";
        }
    }
    elsif($i > 10 && $i <= 15) {
        if($unit eq "unit"){
            print FH "    p_top_br$i"."[$u:$l].connect_units(uc2.ub1);\n";
            print FH "    ud0.uc1.ub0.connect_units(stop[$u:$l]);\n";
            print FH "    ud1.uc2.ua0.connect_units(p[$u-:$l]);\n";
            print FH "    s_top$i"."[$u:$l].connect_units(ud0.ub0.ua1);\n";
        }
        else {
            print FH "    p_top_br$i"."[$u:$l].connect_units(uc2);\n";
            print FH "    ub0.connect_units(stop[$u-:$l]);\n";
            print FH "    ud1.connect_units(p[$u:$l]);\n";
            print FH "    s_top$i"."[$u:$l].connect_units(ua0);\n";
        }
        
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);
}

