`ifndef INC_GUARD_d
`define INC_GUARD_d

`define P_AR_CLK_CK_UPPER_INDEX  (1-1)
`define P_AR_CLK_CK_LOWER_INDEX  (0)
`define P_AR_CLK_CK_WIDTH  (1)
`define P_AR_CLK_CK_RANGE `P_AR_CLK_CK_UPPER_INDEX:`P_AR_CLK_CK_LOWER_INDEX
`define P_AR_RST_RESET_UPPER_INDEX  (1-1)
`define P_AR_RST_RESET_LOWER_INDEX  (0)
`define P_AR_RST_RESET_WIDTH  (1)
`define P_AR_RST_RESET_RANGE `P_AR_RST_RESET_UPPER_INDEX:`P_AR_RST_RESET_LOWER_INDEX
`define P_AR_P_OUT1_P_OUT_UPPER_INDEX  (8-1)
`define P_AR_P_OUT1_P_OUT_LOWER_INDEX  (0)
`define P_AR_P_OUT1_P_OUT_WIDTH  (8)
`define P_AR_P_OUT1_P_OUT_RANGE `P_AR_P_OUT1_P_OUT_UPPER_INDEX:`P_AR_P_OUT1_P_OUT_LOWER_INDEX
`define P_AR_P_IN1_P_IN_UPPER_INDEX  (8-1)
`define P_AR_P_IN1_P_IN_LOWER_INDEX  (0)
`define P_AR_P_IN1_P_IN_WIDTH  (8)
`define P_AR_P_IN1_P_IN_RANGE `P_AR_P_IN1_P_IN_UPPER_INDEX:`P_AR_P_IN1_P_IN_LOWER_INDEX
`define IFC_IFC_TOP_P_IFC_P1_IN_UPPER_INDEX  (8-1)
`define IFC_IFC_TOP_P_IFC_P1_IN_LOWER_INDEX  (0)
`define IFC_IFC_TOP_P_IFC_P1_IN_WIDTH  (8)
`define IFC_IFC_TOP_P_IFC_P1_IN_RANGE `IFC_IFC_TOP_P_IFC_P1_IN_UPPER_INDEX:`IFC_IFC_TOP_P_IFC_P1_IN_LOWER_INDEX
`define IFC_IFC_TOP_P_IFC_P2_OUT_UPPER_INDEX  (8-1)
`define IFC_IFC_TOP_P_IFC_P2_OUT_LOWER_INDEX  (0)
`define IFC_IFC_TOP_P_IFC_P2_OUT_WIDTH  (8)
`define IFC_IFC_TOP_P_IFC_P2_OUT_RANGE `IFC_IFC_TOP_P_IFC_P2_OUT_UPPER_INDEX:`IFC_IFC_TOP_P_IFC_P2_OUT_LOWER_INDEX
`define IFC_IFC_TOP_P_P_SG_UPPER_INDEX  (8-1)
`define IFC_IFC_TOP_P_P_SG_LOWER_INDEX  (0)
`define IFC_IFC_TOP_P_P_SG_WIDTH  (8)
`define IFC_IFC_TOP_P_P_SG_RANGE `IFC_IFC_TOP_P_P_SG_UPPER_INDEX:`IFC_IFC_TOP_P_P_SG_LOWER_INDEX

`endif
