`ifndef INC_GUARD_u21
`define INC_GUARD_u21

`define IFC_IFC_IN1_P_PI1_UPPER_INDEX  (2-1)
`define IFC_IFC_IN1_P_PI1_LOWER_INDEX  (0)
`define IFC_IFC_IN1_P_PI1_WIDTH  (2)
`define IFC_IFC_IN1_P_PI1_RANGE `IFC_IFC_IN1_P_PI1_UPPER_INDEX:`IFC_IFC_IN1_P_PI1_LOWER_INDEX
`define IFC_IFC_IN1_P_PI2_UPPER_INDEX  (4-1)
`define IFC_IFC_IN1_P_PI2_LOWER_INDEX  (0)
`define IFC_IFC_IN1_P_PI2_WIDTH  (4)
`define IFC_IFC_IN1_P_PI2_RANGE `IFC_IFC_IN1_P_PI2_UPPER_INDEX:`IFC_IFC_IN1_P_PI2_LOWER_INDEX
`define IFC_IFC_IN1_P_PI3_UPPER_INDEX  (0)
`define IFC_IFC_IN1_P_PI3_LOWER_INDEX  (0)
`define IFC_IFC_IN1_P_PI3_WIDTH  (0-0+1)
`define IFC_IFC_IN1_P_PI3_RANGE `IFC_IFC_IN1_P_PI3_UPPER_INDEX:`IFC_IFC_IN1_P_PI3_LOWER_INDEX

`endif
