`ifndef INC_GUARD_uk882
`define INC_GUARD_uk882

`define P_PIN0_UPPER_INDEX  (3-1)
`define P_PIN0_LOWER_INDEX  (0)
`define P_PIN0_WIDTH  (3)
`define P_PIN0_RANGE `P_PIN0_UPPER_INDEX:`P_PIN0_LOWER_INDEX
`define P_PIN1_UPPER_INDEX  (12-1)
`define P_PIN1_LOWER_INDEX  (0)
`define P_PIN1_WIDTH  (12)
`define P_PIN1_RANGE `P_PIN1_UPPER_INDEX:`P_PIN1_LOWER_INDEX
`define P_PIN2_UPPER_INDEX  (8-1)
`define P_PIN2_LOWER_INDEX  (0)
`define P_PIN2_WIDTH  (8)
`define P_PIN2_RANGE `P_PIN2_UPPER_INDEX:`P_PIN2_LOWER_INDEX
`define P_PIN3_UPPER_INDEX  (3-1)
`define P_PIN3_LOWER_INDEX  (0)
`define P_PIN3_WIDTH  (3)
`define P_PIN3_RANGE `P_PIN3_UPPER_INDEX:`P_PIN3_LOWER_INDEX
`define P_CLK_UPPER_INDEX  (0)
`define P_CLK_LOWER_INDEX  (0)
`define P_CLK_WIDTH  (0-0+1)
`define P_CLK_RANGE `P_CLK_UPPER_INDEX:`P_CLK_LOWER_INDEX
`define P_RESET_UPPER_INDEX  (0)
`define P_RESET_LOWER_INDEX  (0)
`define P_RESET_WIDTH  (0-0+1)
`define P_RESET_RANGE `P_RESET_UPPER_INDEX:`P_RESET_LOWER_INDEX

`endif
