`ifndef INC_GUARD_uv
`define INC_GUARD_uv

`define IFC_IRC_P_RESET_UPPER_INDEX  (0)
`define IFC_IRC_P_RESET_LOWER_INDEX  (0)
`define IFC_IRC_P_RESET_WIDTH  (0-0+1)
`define IFC_IRC_P_RESET_RANGE `IFC_IRC_P_RESET_UPPER_INDEX:`IFC_IRC_P_RESET_LOWER_INDEX
`define IFC_IRC_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IRC_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IRC_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IRC_P_CLOCK_RANGE `IFC_IRC_P_CLOCK_UPPER_INDEX:`IFC_IRC_P_CLOCK_LOWER_INDEX
`define IFC_IIN1_P_PINX_UPPER_INDEX  (8-1)
`define IFC_IIN1_P_PINX_LOWER_INDEX  (0)
`define IFC_IIN1_P_PINX_WIDTH  (8)
`define IFC_IIN1_P_PINX_RANGE `IFC_IIN1_P_PINX_UPPER_INDEX:`IFC_IIN1_P_PINX_LOWER_INDEX
`define IFC_IIN1_P_PINY_UPPER_INDEX  (8-1)
`define IFC_IIN1_P_PINY_LOWER_INDEX  (0)
`define IFC_IIN1_P_PINY_WIDTH  (8)
`define IFC_IIN1_P_PINY_RANGE `IFC_IIN1_P_PINY_UPPER_INDEX:`IFC_IIN1_P_PINY_LOWER_INDEX
`define IFC_IIN2_P_PINX_UPPER_INDEX  (8-1)
`define IFC_IIN2_P_PINX_LOWER_INDEX  (0)
`define IFC_IIN2_P_PINX_WIDTH  (8)
`define IFC_IIN2_P_PINX_RANGE `IFC_IIN2_P_PINX_UPPER_INDEX:`IFC_IIN2_P_PINX_LOWER_INDEX
`define IFC_IIN2_P_PINY_UPPER_INDEX  (8-1)
`define IFC_IIN2_P_PINY_LOWER_INDEX  (0)
`define IFC_IIN2_P_PINY_WIDTH  (8)
`define IFC_IIN2_P_PINY_RANGE `IFC_IIN2_P_PINY_UPPER_INDEX:`IFC_IIN2_P_PINY_LOWER_INDEX
`define IFC_IOUT1_P_PINX_UPPER_INDEX  (8-1)
`define IFC_IOUT1_P_PINX_LOWER_INDEX  (0)
`define IFC_IOUT1_P_PINX_WIDTH  (8)
`define IFC_IOUT1_P_PINX_RANGE `IFC_IOUT1_P_PINX_UPPER_INDEX:`IFC_IOUT1_P_PINX_LOWER_INDEX
`define IFC_IOUT1_P_PINY_UPPER_INDEX  (8-1)
`define IFC_IOUT1_P_PINY_LOWER_INDEX  (0)
`define IFC_IOUT1_P_PINY_WIDTH  (8)
`define IFC_IOUT1_P_PINY_RANGE `IFC_IOUT1_P_PINY_UPPER_INDEX:`IFC_IOUT1_P_PINY_LOWER_INDEX
`define IFC_IOUT2_P_PINX_UPPER_INDEX  (8-1)
`define IFC_IOUT2_P_PINX_LOWER_INDEX  (0)
`define IFC_IOUT2_P_PINX_WIDTH  (8)
`define IFC_IOUT2_P_PINX_RANGE `IFC_IOUT2_P_PINX_UPPER_INDEX:`IFC_IOUT2_P_PINX_LOWER_INDEX
`define IFC_IOUT2_P_PINY_UPPER_INDEX  (8-1)
`define IFC_IOUT2_P_PINY_LOWER_INDEX  (0)
`define IFC_IOUT2_P_PINY_WIDTH  (8)
`define IFC_IOUT2_P_PINY_RANGE `IFC_IOUT2_P_PINY_UPPER_INDEX:`IFC_IOUT2_P_PINY_LOWER_INDEX

`endif
