`ifndef INC_GUARD_ISA
`define INC_GUARD_ISA

`define IF_F_OPCODE_UPPER_INDEX  (6-1)
`define IF_F_OPCODE_LOWER_INDEX (0)
`define IF_F_OPCODE_WIDTH (6)
`define IF_F_OPCODE_RANGE `IF_F_OPCODE_UPPER_INDEX:`IF_F_OPCODE_LOWER_INDEX

`define IF_F_FIELD_UPPER_INDEX  (6-1)
`define IF_F_FIELD_LOWER_INDEX (0)
`define IF_F_FIELD_WIDTH (6)
`define IF_F_FIELD_RANGE `IF_F_FIELD_UPPER_INDEX:`IF_F_FIELD_LOWER_INDEX

`define IF_F_IMM_UPPER_INDEX  (1-1)
`define IF_F_IMM_LOWER_INDEX (0)
`define IF_F_IMM_WIDTH (1)
`define IF_F_IMM_RANGE `IF_F_IMM_UPPER_INDEX:`IF_F_IMM_LOWER_INDEX

`define IF_F_N_UPPER_INDEX  (19-1)
`define IF_F_N_LOWER_INDEX (0)
`define IF_F_N_WIDTH (19)
`define IF_F_N_RANGE `IF_F_N_UPPER_INDEX:`IF_F_N_LOWER_INDEX

`define IF_F_UNUSED_UPPER_INDEX  (7-1)
`define IF_F_UNUSED_LOWER_INDEX (0)
`define IF_F_UNUSED_WIDTH (7)
`define IF_F_UNUSED_RANGE `IF_F_UNUSED_UPPER_INDEX:`IF_F_UNUSED_LOWER_INDEX

`define IE_ISA_ROOT_UPPER_INDEX (32-1)
`define IE_ISA_ROOT_LOWER_INDEX (0)
`define IE_ISA_ROOT_WIDTH (32)
`define IE_ISA_ROOT_RANGE `IE_ISA_ROOT_UPPER_INDEX:`IE_ISA_ROOT_LOWER_INDEX
`define IE_BASE_FORMAT_UPPER_INDEX (32-1)
`define IE_BASE_FORMAT_LOWER_INDEX (0)
`define IE_BASE_FORMAT_WIDTH (32)
`define IE_BASE_FORMAT_RANGE `IE_BASE_FORMAT_UPPER_INDEX:`IE_BASE_FORMAT_LOWER_INDEX
`define IE_BASE_FORMAT_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_BASE_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_BASE_FORMAT_IF_F_OPCODE_RANGE `IE_BASE_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_BASE_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_BASE_FORMAT_IF_F_RZ_UPPER_INDEX  (5)
`define IE_BASE_FORMAT_IF_F_RZ_LOWER_INDEX (0)
`define IE_BASE_FORMAT_IF_F_RZ_RANGE `IE_BASE_FORMAT_IF_F_RZ_UPPER_INDEX:`IE_BASE_FORMAT_IF_F_RZ_LOWER_INDEX

`define IF_OPERAND_UPPER_INDEX  (13-1)
`define IF_OPERAND_LOWER_INDEX (0)
`define IF_OPERAND_WIDTH (13)
`define IF_OPERAND_RANGE `IF_OPERAND_UPPER_INDEX:`IF_OPERAND_LOWER_INDEX

`define IE_FORMAT1_UPPER_INDEX (32-1)
`define IE_FORMAT1_LOWER_INDEX (0)
`define IE_FORMAT1_WIDTH (32)
`define IE_FORMAT1_RANGE `IE_FORMAT1_UPPER_INDEX:`IE_FORMAT1_LOWER_INDEX
`define IE_FORMAT1_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_FORMAT1_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_FORMAT1_IF_F_OPCODE_RANGE `IE_FORMAT1_IF_F_OPCODE_UPPER_INDEX:`IE_FORMAT1_IF_F_OPCODE_LOWER_INDEX

`define IE_FORMAT1_IF_F_RZ_UPPER_INDEX  (5)
`define IE_FORMAT1_IF_F_RZ_LOWER_INDEX (0)
`define IE_FORMAT1_IF_F_RZ_RANGE `IE_FORMAT1_IF_F_RZ_UPPER_INDEX:`IE_FORMAT1_IF_F_RZ_LOWER_INDEX

`define IE_FORMAT1_IF_F_ONE_UPPER_INDEX  (0)
`define IE_FORMAT1_IF_F_ONE_LOWER_INDEX (0)
`define IE_FORMAT1_IF_F_ONE_RANGE `IE_FORMAT1_IF_F_ONE_UPPER_INDEX:`IE_FORMAT1_IF_F_ONE_LOWER_INDEX

`define IE_FORMAT1_IF_F_M_UPPER_INDEX  (18)
`define IE_FORMAT1_IF_F_M_LOWER_INDEX (0)
`define IE_FORMAT1_IF_F_M_RANGE `IE_FORMAT1_IF_F_M_UPPER_INDEX:`IE_FORMAT1_IF_F_M_LOWER_INDEX

`define IE_FORMAT2_UPPER_INDEX (32-1)
`define IE_FORMAT2_LOWER_INDEX (0)
`define IE_FORMAT2_WIDTH (32)
`define IE_FORMAT2_RANGE `IE_FORMAT2_UPPER_INDEX:`IE_FORMAT2_LOWER_INDEX
`define IE_FORMAT2_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_FORMAT2_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_FORMAT2_IF_F_OPCODE_RANGE `IE_FORMAT2_IF_F_OPCODE_UPPER_INDEX:`IE_FORMAT2_IF_F_OPCODE_LOWER_INDEX

`define IE_FORMAT2_IF_F_RZ_UPPER_INDEX  (5)
`define IE_FORMAT2_IF_F_RZ_LOWER_INDEX (0)
`define IE_FORMAT2_IF_F_RZ_RANGE `IE_FORMAT2_IF_F_RZ_UPPER_INDEX:`IE_FORMAT2_IF_F_RZ_LOWER_INDEX

`define IE_FORMAT2_IF_F_RY_UPPER_INDEX  (5)
`define IE_FORMAT2_IF_F_RY_LOWER_INDEX (0)
`define IE_FORMAT2_IF_F_RY_RANGE `IE_FORMAT2_IF_F_RY_UPPER_INDEX:`IE_FORMAT2_IF_F_RY_LOWER_INDEX

`define IE_FORMAT2_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_FORMAT2_IF_F1_IMM_LOWER_INDEX (0)
`define IE_FORMAT2_IF_F1_IMM_RANGE `IE_FORMAT2_IF_F1_IMM_UPPER_INDEX:`IE_FORMAT2_IF_F1_IMM_LOWER_INDEX

`define IE_FORMAT2_IF_OPERAND_UPPER_INDEX  (12)
`define IE_FORMAT2_IF_OPERAND_LOWER_INDEX (0)
`define IE_FORMAT2_IF_OPERAND_RANGE `IE_FORMAT2_IF_OPERAND_UPPER_INDEX:`IE_FORMAT2_IF_OPERAND_LOWER_INDEX

`define IE_FORMAT3_UPPER_INDEX (32-1)
`define IE_FORMAT3_LOWER_INDEX (0)
`define IE_FORMAT3_WIDTH (32)
`define IE_FORMAT3_RANGE `IE_FORMAT3_UPPER_INDEX:`IE_FORMAT3_LOWER_INDEX
`define IE_FORMAT3_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_FORMAT3_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_FORMAT3_IF_F_OPCODE_RANGE `IE_FORMAT3_IF_F_OPCODE_UPPER_INDEX:`IE_FORMAT3_IF_F_OPCODE_LOWER_INDEX

`define IE_FORMAT3_IF_F_RZ_UPPER_INDEX  (5)
`define IE_FORMAT3_IF_F_RZ_LOWER_INDEX (0)
`define IE_FORMAT3_IF_F_RZ_RANGE `IE_FORMAT3_IF_F_RZ_UPPER_INDEX:`IE_FORMAT3_IF_F_RZ_LOWER_INDEX

`define IE_FORMAT3_IF_F_RX_UPPER_INDEX  (5)
`define IE_FORMAT3_IF_F_RX_LOWER_INDEX (0)
`define IE_FORMAT3_IF_F_RX_RANGE `IE_FORMAT3_IF_F_RX_UPPER_INDEX:`IE_FORMAT3_IF_F_RX_LOWER_INDEX

`define IE_FORMAT3_IF_F_RY_UPPER_INDEX  (5)
`define IE_FORMAT3_IF_F_RY_LOWER_INDEX (0)
`define IE_FORMAT3_IF_F_RY_RANGE `IE_FORMAT3_IF_F_RY_UPPER_INDEX:`IE_FORMAT3_IF_F_RY_LOWER_INDEX

`define IE_FORMAT3_IF_F0_IMM_UPPER_INDEX  (0)
`define IE_FORMAT3_IF_F0_IMM_LOWER_INDEX (0)
`define IE_FORMAT3_IF_F0_IMM_RANGE `IE_FORMAT3_IF_F0_IMM_UPPER_INDEX:`IE_FORMAT3_IF_F0_IMM_LOWER_INDEX

`define IE_FORMAT3_IF_F_UNUSED_UPPER_INDEX  (6)
`define IE_FORMAT3_IF_F_UNUSED_LOWER_INDEX (0)
`define IE_FORMAT3_IF_F_UNUSED_RANGE `IE_FORMAT3_IF_F_UNUSED_UPPER_INDEX:`IE_FORMAT3_IF_F_UNUSED_LOWER_INDEX

`define IE_I_ADDN_UPPER_INDEX (32-1)
`define IE_I_ADDN_LOWER_INDEX (0)
`define IE_I_ADDN_WIDTH (32)
`define IE_I_ADDN_RANGE `IE_I_ADDN_UPPER_INDEX:`IE_I_ADDN_LOWER_INDEX
`define IE_I_ADDN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_ADDN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_ADDN_IF_F_OPCODE_RANGE `IE_I_ADDN_IF_F_OPCODE_UPPER_INDEX:`IE_I_ADDN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_ADDN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_ADDN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_ADDN_IF_F_RZ_RANGE `IE_I_ADDN_IF_F_RZ_UPPER_INDEX:`IE_I_ADDN_IF_F_RZ_LOWER_INDEX

`define IE_I_ADDN_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_ADDN_IF_F_RY_LOWER_INDEX (0)
`define IE_I_ADDN_IF_F_RY_RANGE `IE_I_ADDN_IF_F_RY_UPPER_INDEX:`IE_I_ADDN_IF_F_RY_LOWER_INDEX

`define IE_I_ADDN_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_ADDN_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_ADDN_IF_F1_IMM_RANGE `IE_I_ADDN_IF_F1_IMM_UPPER_INDEX:`IE_I_ADDN_IF_F1_IMM_LOWER_INDEX

`define IE_I_ADDN_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_ADDN_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_ADDN_IF_OPERAND_RANGE `IE_I_ADDN_IF_OPERAND_UPPER_INDEX:`IE_I_ADDN_IF_OPERAND_LOWER_INDEX

`define IE_I_ADDCR_UPPER_INDEX (32-1)
`define IE_I_ADDCR_LOWER_INDEX (0)
`define IE_I_ADDCR_WIDTH (32)
`define IE_I_ADDCR_RANGE `IE_I_ADDCR_UPPER_INDEX:`IE_I_ADDCR_LOWER_INDEX
`define IE_I_ADDCR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_ADDCR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_ADDCR_IF_F_OPCODE_RANGE `IE_I_ADDCR_IF_F_OPCODE_UPPER_INDEX:`IE_I_ADDCR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_ADDCR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_ADDCR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_ADDCR_IF_F_RZ_RANGE `IE_I_ADDCR_IF_F_RZ_UPPER_INDEX:`IE_I_ADDCR_IF_F_RZ_LOWER_INDEX

`define IE_I_ADDCR_IF_F_RX_UPPER_INDEX  (5)
`define IE_I_ADDCR_IF_F_RX_LOWER_INDEX (0)
`define IE_I_ADDCR_IF_F_RX_RANGE `IE_I_ADDCR_IF_F_RX_UPPER_INDEX:`IE_I_ADDCR_IF_F_RX_LOWER_INDEX

`define IE_I_ADDCR_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_ADDCR_IF_F_RY_LOWER_INDEX (0)
`define IE_I_ADDCR_IF_F_RY_RANGE `IE_I_ADDCR_IF_F_RY_UPPER_INDEX:`IE_I_ADDCR_IF_F_RY_LOWER_INDEX

`define IE_I_ADDCR_IF_F0_IMM_UPPER_INDEX  (0)
`define IE_I_ADDCR_IF_F0_IMM_LOWER_INDEX (0)
`define IE_I_ADDCR_IF_F0_IMM_RANGE `IE_I_ADDCR_IF_F0_IMM_UPPER_INDEX:`IE_I_ADDCR_IF_F0_IMM_LOWER_INDEX

`define IE_I_ADDCR_IF_F_UNUSED_UPPER_INDEX  (6)
`define IE_I_ADDCR_IF_F_UNUSED_LOWER_INDEX (0)
`define IE_I_ADDCR_IF_F_UNUSED_RANGE `IE_I_ADDCR_IF_F_UNUSED_UPPER_INDEX:`IE_I_ADDCR_IF_F_UNUSED_LOWER_INDEX

`define IE_I_ANDN_UPPER_INDEX (32-1)
`define IE_I_ANDN_LOWER_INDEX (0)
`define IE_I_ANDN_WIDTH (32)
`define IE_I_ANDN_RANGE `IE_I_ANDN_UPPER_INDEX:`IE_I_ANDN_LOWER_INDEX
`define IE_I_ANDN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_ANDN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_ANDN_IF_F_OPCODE_RANGE `IE_I_ANDN_IF_F_OPCODE_UPPER_INDEX:`IE_I_ANDN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_ANDN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_ANDN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_ANDN_IF_F_RZ_RANGE `IE_I_ANDN_IF_F_RZ_UPPER_INDEX:`IE_I_ANDN_IF_F_RZ_LOWER_INDEX

`define IE_I_ANDN_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_ANDN_IF_F_RY_LOWER_INDEX (0)
`define IE_I_ANDN_IF_F_RY_RANGE `IE_I_ANDN_IF_F_RY_UPPER_INDEX:`IE_I_ANDN_IF_F_RY_LOWER_INDEX

`define IE_I_ANDN_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_ANDN_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_ANDN_IF_F1_IMM_RANGE `IE_I_ANDN_IF_F1_IMM_UPPER_INDEX:`IE_I_ANDN_IF_F1_IMM_LOWER_INDEX

`define IE_I_ANDN_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_ANDN_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_ANDN_IF_OPERAND_RANGE `IE_I_ANDN_IF_OPERAND_UPPER_INDEX:`IE_I_ANDN_IF_OPERAND_LOWER_INDEX

`define IE_I_CONST_PLUS_UPPER_INDEX (32-1)
`define IE_I_CONST_PLUS_LOWER_INDEX (0)
`define IE_I_CONST_PLUS_WIDTH (32)
`define IE_I_CONST_PLUS_RANGE `IE_I_CONST_PLUS_UPPER_INDEX:`IE_I_CONST_PLUS_LOWER_INDEX
`define IE_I_CONST_PLUS_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_CONST_PLUS_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_CONST_PLUS_IF_F_OPCODE_RANGE `IE_I_CONST_PLUS_IF_F_OPCODE_UPPER_INDEX:`IE_I_CONST_PLUS_IF_F_OPCODE_LOWER_INDEX

`define IE_I_CONST_PLUS_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_CONST_PLUS_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_CONST_PLUS_IF_F_RZ_RANGE `IE_I_CONST_PLUS_IF_F_RZ_UPPER_INDEX:`IE_I_CONST_PLUS_IF_F_RZ_LOWER_INDEX

`define IE_I_CONST_PLUS_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_CONST_PLUS_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_CONST_PLUS_IF_F_ONE_RANGE `IE_I_CONST_PLUS_IF_F_ONE_UPPER_INDEX:`IE_I_CONST_PLUS_IF_F_ONE_LOWER_INDEX

`define IE_I_CONST_PLUS_IF_F_M_UPPER_INDEX  (18)
`define IE_I_CONST_PLUS_IF_F_M_LOWER_INDEX (0)
`define IE_I_CONST_PLUS_IF_F_M_RANGE `IE_I_CONST_PLUS_IF_F_M_UPPER_INDEX:`IE_I_CONST_PLUS_IF_F_M_LOWER_INDEX

`define IE_I_CONST_MINUS_UPPER_INDEX (32-1)
`define IE_I_CONST_MINUS_LOWER_INDEX (0)
`define IE_I_CONST_MINUS_WIDTH (32)
`define IE_I_CONST_MINUS_RANGE `IE_I_CONST_MINUS_UPPER_INDEX:`IE_I_CONST_MINUS_LOWER_INDEX
`define IE_I_CONST_MINUS_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_CONST_MINUS_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_CONST_MINUS_IF_F_OPCODE_RANGE `IE_I_CONST_MINUS_IF_F_OPCODE_UPPER_INDEX:`IE_I_CONST_MINUS_IF_F_OPCODE_LOWER_INDEX

`define IE_I_CONST_MINUS_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_CONST_MINUS_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_CONST_MINUS_IF_F_RZ_RANGE `IE_I_CONST_MINUS_IF_F_RZ_UPPER_INDEX:`IE_I_CONST_MINUS_IF_F_RZ_LOWER_INDEX

`define IE_I_CONST_MINUS_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_CONST_MINUS_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_CONST_MINUS_IF_F_ONE_RANGE `IE_I_CONST_MINUS_IF_F_ONE_UPPER_INDEX:`IE_I_CONST_MINUS_IF_F_ONE_LOWER_INDEX

`define IE_I_CONST_MINUS_IF_F_M_UPPER_INDEX  (18)
`define IE_I_CONST_MINUS_IF_F_M_LOWER_INDEX (0)
`define IE_I_CONST_MINUS_IF_F_M_RANGE `IE_I_CONST_MINUS_IF_F_M_UPPER_INDEX:`IE_I_CONST_MINUS_IF_F_M_LOWER_INDEX

`define IE_I_CONSTH_UPPER_INDEX (32-1)
`define IE_I_CONSTH_LOWER_INDEX (0)
`define IE_I_CONSTH_WIDTH (32)
`define IE_I_CONSTH_RANGE `IE_I_CONSTH_UPPER_INDEX:`IE_I_CONSTH_LOWER_INDEX
`define IE_I_CONSTH_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_CONSTH_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_CONSTH_IF_F_OPCODE_RANGE `IE_I_CONSTH_IF_F_OPCODE_UPPER_INDEX:`IE_I_CONSTH_IF_F_OPCODE_LOWER_INDEX

`define IE_I_CONSTH_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_CONSTH_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_CONSTH_IF_F_RZ_RANGE `IE_I_CONSTH_IF_F_RZ_UPPER_INDEX:`IE_I_CONSTH_IF_F_RZ_LOWER_INDEX

`define IE_I_CONSTH_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_CONSTH_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_CONSTH_IF_F_ONE_RANGE `IE_I_CONSTH_IF_F_ONE_UPPER_INDEX:`IE_I_CONSTH_IF_F_ONE_LOWER_INDEX

`define IE_I_CONSTH_IF_F_M_UPPER_INDEX  (18)
`define IE_I_CONSTH_IF_F_M_LOWER_INDEX (0)
`define IE_I_CONSTH_IF_F_M_RANGE `IE_I_CONSTH_IF_F_M_UPPER_INDEX:`IE_I_CONSTH_IF_F_M_LOWER_INDEX

`define IE_I_ORR_UPPER_INDEX (32-1)
`define IE_I_ORR_LOWER_INDEX (0)
`define IE_I_ORR_WIDTH (32)
`define IE_I_ORR_RANGE `IE_I_ORR_UPPER_INDEX:`IE_I_ORR_LOWER_INDEX
`define IE_I_ORR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_ORR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_ORR_IF_F_OPCODE_RANGE `IE_I_ORR_IF_F_OPCODE_UPPER_INDEX:`IE_I_ORR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_ORR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_ORR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_ORR_IF_F_RZ_RANGE `IE_I_ORR_IF_F_RZ_UPPER_INDEX:`IE_I_ORR_IF_F_RZ_LOWER_INDEX

`define IE_I_ORR_IF_F_RX_UPPER_INDEX  (5)
`define IE_I_ORR_IF_F_RX_LOWER_INDEX (0)
`define IE_I_ORR_IF_F_RX_RANGE `IE_I_ORR_IF_F_RX_UPPER_INDEX:`IE_I_ORR_IF_F_RX_LOWER_INDEX

`define IE_I_ORR_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_ORR_IF_F_RY_LOWER_INDEX (0)
`define IE_I_ORR_IF_F_RY_RANGE `IE_I_ORR_IF_F_RY_UPPER_INDEX:`IE_I_ORR_IF_F_RY_LOWER_INDEX

`define IE_I_ORR_IF_F0_IMM_UPPER_INDEX  (0)
`define IE_I_ORR_IF_F0_IMM_LOWER_INDEX (0)
`define IE_I_ORR_IF_F0_IMM_RANGE `IE_I_ORR_IF_F0_IMM_UPPER_INDEX:`IE_I_ORR_IF_F0_IMM_LOWER_INDEX

`define IE_I_ORR_IF_F_UNUSED_UPPER_INDEX  (6)
`define IE_I_ORR_IF_F_UNUSED_LOWER_INDEX (0)
`define IE_I_ORR_IF_F_UNUSED_RANGE `IE_I_ORR_IF_F_UNUSED_UPPER_INDEX:`IE_I_ORR_IF_F_UNUSED_LOWER_INDEX

`define IE_I_ROTLN_UPPER_INDEX (32-1)
`define IE_I_ROTLN_LOWER_INDEX (0)
`define IE_I_ROTLN_WIDTH (32)
`define IE_I_ROTLN_RANGE `IE_I_ROTLN_UPPER_INDEX:`IE_I_ROTLN_LOWER_INDEX
`define IE_I_ROTLN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_ROTLN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_ROTLN_IF_F_OPCODE_RANGE `IE_I_ROTLN_IF_F_OPCODE_UPPER_INDEX:`IE_I_ROTLN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_ROTLN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_ROTLN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_ROTLN_IF_F_RZ_RANGE `IE_I_ROTLN_IF_F_RZ_UPPER_INDEX:`IE_I_ROTLN_IF_F_RZ_LOWER_INDEX

`define IE_I_ROTLN_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_ROTLN_IF_F_RY_LOWER_INDEX (0)
`define IE_I_ROTLN_IF_F_RY_RANGE `IE_I_ROTLN_IF_F_RY_UPPER_INDEX:`IE_I_ROTLN_IF_F_RY_LOWER_INDEX

`define IE_I_ROTLN_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_ROTLN_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_ROTLN_IF_F1_IMM_RANGE `IE_I_ROTLN_IF_F1_IMM_UPPER_INDEX:`IE_I_ROTLN_IF_F1_IMM_LOWER_INDEX

`define IE_I_ROTLN_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_ROTLN_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_ROTLN_IF_OPERAND_RANGE `IE_I_ROTLN_IF_OPERAND_UPPER_INDEX:`IE_I_ROTLN_IF_OPERAND_LOWER_INDEX

`define IE_I_SLLN_UPPER_INDEX (32-1)
`define IE_I_SLLN_LOWER_INDEX (0)
`define IE_I_SLLN_WIDTH (32)
`define IE_I_SLLN_RANGE `IE_I_SLLN_UPPER_INDEX:`IE_I_SLLN_LOWER_INDEX
`define IE_I_SLLN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SLLN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SLLN_IF_F_OPCODE_RANGE `IE_I_SLLN_IF_F_OPCODE_UPPER_INDEX:`IE_I_SLLN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SLLN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SLLN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SLLN_IF_F_RZ_RANGE `IE_I_SLLN_IF_F_RZ_UPPER_INDEX:`IE_I_SLLN_IF_F_RZ_LOWER_INDEX

`define IE_I_SLLN_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SLLN_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SLLN_IF_F_RY_RANGE `IE_I_SLLN_IF_F_RY_UPPER_INDEX:`IE_I_SLLN_IF_F_RY_LOWER_INDEX

`define IE_I_SLLN_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_SLLN_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_SLLN_IF_F1_IMM_RANGE `IE_I_SLLN_IF_F1_IMM_UPPER_INDEX:`IE_I_SLLN_IF_F1_IMM_LOWER_INDEX

`define IE_I_SLLN_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_SLLN_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_SLLN_IF_OPERAND_RANGE `IE_I_SLLN_IF_OPERAND_UPPER_INDEX:`IE_I_SLLN_IF_OPERAND_LOWER_INDEX

`define IE_I_SRAN_UPPER_INDEX (32-1)
`define IE_I_SRAN_LOWER_INDEX (0)
`define IE_I_SRAN_WIDTH (32)
`define IE_I_SRAN_RANGE `IE_I_SRAN_UPPER_INDEX:`IE_I_SRAN_LOWER_INDEX
`define IE_I_SRAN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SRAN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SRAN_IF_F_OPCODE_RANGE `IE_I_SRAN_IF_F_OPCODE_UPPER_INDEX:`IE_I_SRAN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SRAN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SRAN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SRAN_IF_F_RZ_RANGE `IE_I_SRAN_IF_F_RZ_UPPER_INDEX:`IE_I_SRAN_IF_F_RZ_LOWER_INDEX

`define IE_I_SRAN_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SRAN_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SRAN_IF_F_RY_RANGE `IE_I_SRAN_IF_F_RY_UPPER_INDEX:`IE_I_SRAN_IF_F_RY_LOWER_INDEX

`define IE_I_SRAN_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_SRAN_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_SRAN_IF_F1_IMM_RANGE `IE_I_SRAN_IF_F1_IMM_UPPER_INDEX:`IE_I_SRAN_IF_F1_IMM_LOWER_INDEX

`define IE_I_SRAN_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_SRAN_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_SRAN_IF_OPERAND_RANGE `IE_I_SRAN_IF_OPERAND_UPPER_INDEX:`IE_I_SRAN_IF_OPERAND_LOWER_INDEX

`define IE_I_SRLN_UPPER_INDEX (32-1)
`define IE_I_SRLN_LOWER_INDEX (0)
`define IE_I_SRLN_WIDTH (32)
`define IE_I_SRLN_RANGE `IE_I_SRLN_UPPER_INDEX:`IE_I_SRLN_LOWER_INDEX
`define IE_I_SRLN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SRLN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SRLN_IF_F_OPCODE_RANGE `IE_I_SRLN_IF_F_OPCODE_UPPER_INDEX:`IE_I_SRLN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SRLN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SRLN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SRLN_IF_F_RZ_RANGE `IE_I_SRLN_IF_F_RZ_UPPER_INDEX:`IE_I_SRLN_IF_F_RZ_LOWER_INDEX

`define IE_I_SRLN_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SRLN_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SRLN_IF_F_RY_RANGE `IE_I_SRLN_IF_F_RY_UPPER_INDEX:`IE_I_SRLN_IF_F_RY_LOWER_INDEX

`define IE_I_SRLN_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_SRLN_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_SRLN_IF_F1_IMM_RANGE `IE_I_SRLN_IF_F1_IMM_UPPER_INDEX:`IE_I_SRLN_IF_F1_IMM_LOWER_INDEX

`define IE_I_SRLN_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_SRLN_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_SRLN_IF_OPERAND_RANGE `IE_I_SRLN_IF_OPERAND_UPPER_INDEX:`IE_I_SRLN_IF_OPERAND_LOWER_INDEX

`define IE_I_SUBN_UPPER_INDEX (32-1)
`define IE_I_SUBN_LOWER_INDEX (0)
`define IE_I_SUBN_WIDTH (32)
`define IE_I_SUBN_RANGE `IE_I_SUBN_UPPER_INDEX:`IE_I_SUBN_LOWER_INDEX
`define IE_I_SUBN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SUBN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SUBN_IF_F_OPCODE_RANGE `IE_I_SUBN_IF_F_OPCODE_UPPER_INDEX:`IE_I_SUBN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SUBN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SUBN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SUBN_IF_F_RZ_RANGE `IE_I_SUBN_IF_F_RZ_UPPER_INDEX:`IE_I_SUBN_IF_F_RZ_LOWER_INDEX

`define IE_I_SUBN_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SUBN_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SUBN_IF_F_RY_RANGE `IE_I_SUBN_IF_F_RY_UPPER_INDEX:`IE_I_SUBN_IF_F_RY_LOWER_INDEX

`define IE_I_SUBN_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_SUBN_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_SUBN_IF_F1_IMM_RANGE `IE_I_SUBN_IF_F1_IMM_UPPER_INDEX:`IE_I_SUBN_IF_F1_IMM_LOWER_INDEX

`define IE_I_SUBN_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_SUBN_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_SUBN_IF_OPERAND_RANGE `IE_I_SUBN_IF_OPERAND_UPPER_INDEX:`IE_I_SUBN_IF_OPERAND_LOWER_INDEX

`define IE_I_SUBCR_UPPER_INDEX (32-1)
`define IE_I_SUBCR_LOWER_INDEX (0)
`define IE_I_SUBCR_WIDTH (32)
`define IE_I_SUBCR_RANGE `IE_I_SUBCR_UPPER_INDEX:`IE_I_SUBCR_LOWER_INDEX
`define IE_I_SUBCR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SUBCR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SUBCR_IF_F_OPCODE_RANGE `IE_I_SUBCR_IF_F_OPCODE_UPPER_INDEX:`IE_I_SUBCR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SUBCR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SUBCR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SUBCR_IF_F_RZ_RANGE `IE_I_SUBCR_IF_F_RZ_UPPER_INDEX:`IE_I_SUBCR_IF_F_RZ_LOWER_INDEX

`define IE_I_SUBCR_IF_F_RX_UPPER_INDEX  (5)
`define IE_I_SUBCR_IF_F_RX_LOWER_INDEX (0)
`define IE_I_SUBCR_IF_F_RX_RANGE `IE_I_SUBCR_IF_F_RX_UPPER_INDEX:`IE_I_SUBCR_IF_F_RX_LOWER_INDEX

`define IE_I_SUBCR_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SUBCR_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SUBCR_IF_F_RY_RANGE `IE_I_SUBCR_IF_F_RY_UPPER_INDEX:`IE_I_SUBCR_IF_F_RY_LOWER_INDEX

`define IE_I_SUBCR_IF_F0_IMM_UPPER_INDEX  (0)
`define IE_I_SUBCR_IF_F0_IMM_LOWER_INDEX (0)
`define IE_I_SUBCR_IF_F0_IMM_RANGE `IE_I_SUBCR_IF_F0_IMM_UPPER_INDEX:`IE_I_SUBCR_IF_F0_IMM_LOWER_INDEX

`define IE_I_SUBCR_IF_F_UNUSED_UPPER_INDEX  (6)
`define IE_I_SUBCR_IF_F_UNUSED_LOWER_INDEX (0)
`define IE_I_SUBCR_IF_F_UNUSED_RANGE `IE_I_SUBCR_IF_F_UNUSED_UPPER_INDEX:`IE_I_SUBCR_IF_F_UNUSED_LOWER_INDEX

`define IE_I_SUBRR_UPPER_INDEX (32-1)
`define IE_I_SUBRR_LOWER_INDEX (0)
`define IE_I_SUBRR_WIDTH (32)
`define IE_I_SUBRR_RANGE `IE_I_SUBRR_UPPER_INDEX:`IE_I_SUBRR_LOWER_INDEX
`define IE_I_SUBRR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SUBRR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SUBRR_IF_F_OPCODE_RANGE `IE_I_SUBRR_IF_F_OPCODE_UPPER_INDEX:`IE_I_SUBRR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SUBRR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SUBRR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SUBRR_IF_F_RZ_RANGE `IE_I_SUBRR_IF_F_RZ_UPPER_INDEX:`IE_I_SUBRR_IF_F_RZ_LOWER_INDEX

`define IE_I_SUBRR_IF_F_RX_UPPER_INDEX  (5)
`define IE_I_SUBRR_IF_F_RX_LOWER_INDEX (0)
`define IE_I_SUBRR_IF_F_RX_RANGE `IE_I_SUBRR_IF_F_RX_UPPER_INDEX:`IE_I_SUBRR_IF_F_RX_LOWER_INDEX

`define IE_I_SUBRR_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SUBRR_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SUBRR_IF_F_RY_RANGE `IE_I_SUBRR_IF_F_RY_UPPER_INDEX:`IE_I_SUBRR_IF_F_RY_LOWER_INDEX

`define IE_I_SUBRR_IF_F0_IMM_UPPER_INDEX  (0)
`define IE_I_SUBRR_IF_F0_IMM_LOWER_INDEX (0)
`define IE_I_SUBRR_IF_F0_IMM_RANGE `IE_I_SUBRR_IF_F0_IMM_UPPER_INDEX:`IE_I_SUBRR_IF_F0_IMM_LOWER_INDEX

`define IE_I_SUBRR_IF_F_UNUSED_UPPER_INDEX  (6)
`define IE_I_SUBRR_IF_F_UNUSED_LOWER_INDEX (0)
`define IE_I_SUBRR_IF_F_UNUSED_RANGE `IE_I_SUBRR_IF_F_UNUSED_UPPER_INDEX:`IE_I_SUBRR_IF_F_UNUSED_LOWER_INDEX

`define IE_I_SUBRCR_UPPER_INDEX (32-1)
`define IE_I_SUBRCR_LOWER_INDEX (0)
`define IE_I_SUBRCR_WIDTH (32)
`define IE_I_SUBRCR_RANGE `IE_I_SUBRCR_UPPER_INDEX:`IE_I_SUBRCR_LOWER_INDEX
`define IE_I_SUBRCR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SUBRCR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SUBRCR_IF_F_OPCODE_RANGE `IE_I_SUBRCR_IF_F_OPCODE_UPPER_INDEX:`IE_I_SUBRCR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SUBRCR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SUBRCR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SUBRCR_IF_F_RZ_RANGE `IE_I_SUBRCR_IF_F_RZ_UPPER_INDEX:`IE_I_SUBRCR_IF_F_RZ_LOWER_INDEX

`define IE_I_SUBRCR_IF_F_RX_UPPER_INDEX  (5)
`define IE_I_SUBRCR_IF_F_RX_LOWER_INDEX (0)
`define IE_I_SUBRCR_IF_F_RX_RANGE `IE_I_SUBRCR_IF_F_RX_UPPER_INDEX:`IE_I_SUBRCR_IF_F_RX_LOWER_INDEX

`define IE_I_SUBRCR_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SUBRCR_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SUBRCR_IF_F_RY_RANGE `IE_I_SUBRCR_IF_F_RY_UPPER_INDEX:`IE_I_SUBRCR_IF_F_RY_LOWER_INDEX

`define IE_I_SUBRCR_IF_F0_IMM_UPPER_INDEX  (0)
`define IE_I_SUBRCR_IF_F0_IMM_LOWER_INDEX (0)
`define IE_I_SUBRCR_IF_F0_IMM_RANGE `IE_I_SUBRCR_IF_F0_IMM_UPPER_INDEX:`IE_I_SUBRCR_IF_F0_IMM_LOWER_INDEX

`define IE_I_SUBRCR_IF_F_UNUSED_UPPER_INDEX  (6)
`define IE_I_SUBRCR_IF_F_UNUSED_LOWER_INDEX (0)
`define IE_I_SUBRCR_IF_F_UNUSED_RANGE `IE_I_SUBRCR_IF_F_UNUSED_UPPER_INDEX:`IE_I_SUBRCR_IF_F_UNUSED_LOWER_INDEX

`define IE_I_XORR_UPPER_INDEX (32-1)
`define IE_I_XORR_LOWER_INDEX (0)
`define IE_I_XORR_WIDTH (32)
`define IE_I_XORR_RANGE `IE_I_XORR_UPPER_INDEX:`IE_I_XORR_LOWER_INDEX
`define IE_I_XORR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_XORR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_XORR_IF_F_OPCODE_RANGE `IE_I_XORR_IF_F_OPCODE_UPPER_INDEX:`IE_I_XORR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_XORR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_XORR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_XORR_IF_F_RZ_RANGE `IE_I_XORR_IF_F_RZ_UPPER_INDEX:`IE_I_XORR_IF_F_RZ_LOWER_INDEX

`define IE_I_XORR_IF_F_RX_UPPER_INDEX  (5)
`define IE_I_XORR_IF_F_RX_LOWER_INDEX (0)
`define IE_I_XORR_IF_F_RX_RANGE `IE_I_XORR_IF_F_RX_UPPER_INDEX:`IE_I_XORR_IF_F_RX_LOWER_INDEX

`define IE_I_XORR_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_XORR_IF_F_RY_LOWER_INDEX (0)
`define IE_I_XORR_IF_F_RY_RANGE `IE_I_XORR_IF_F_RY_UPPER_INDEX:`IE_I_XORR_IF_F_RY_LOWER_INDEX

`define IE_I_XORR_IF_F0_IMM_UPPER_INDEX  (0)
`define IE_I_XORR_IF_F0_IMM_LOWER_INDEX (0)
`define IE_I_XORR_IF_F0_IMM_RANGE `IE_I_XORR_IF_F0_IMM_UPPER_INDEX:`IE_I_XORR_IF_F0_IMM_LOWER_INDEX

`define IE_I_XORR_IF_F_UNUSED_UPPER_INDEX  (6)
`define IE_I_XORR_IF_F_UNUSED_LOWER_INDEX (0)
`define IE_I_XORR_IF_F_UNUSED_RANGE `IE_I_XORR_IF_F_UNUSED_UPPER_INDEX:`IE_I_XORR_IF_F_UNUSED_LOWER_INDEX

`define IE_I_LW_UPPER_INDEX (32-1)
`define IE_I_LW_LOWER_INDEX (0)
`define IE_I_LW_WIDTH (32)
`define IE_I_LW_RANGE `IE_I_LW_UPPER_INDEX:`IE_I_LW_LOWER_INDEX
`define IE_I_LW_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_LW_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_LW_IF_F_OPCODE_RANGE `IE_I_LW_IF_F_OPCODE_UPPER_INDEX:`IE_I_LW_IF_F_OPCODE_LOWER_INDEX

`define IE_I_LW_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_LW_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_LW_IF_F_RZ_RANGE `IE_I_LW_IF_F_RZ_UPPER_INDEX:`IE_I_LW_IF_F_RZ_LOWER_INDEX

`define IE_I_LW_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_LW_IF_F_RY_LOWER_INDEX (0)
`define IE_I_LW_IF_F_RY_RANGE `IE_I_LW_IF_F_RY_UPPER_INDEX:`IE_I_LW_IF_F_RY_LOWER_INDEX

`define IE_I_LW_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_LW_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_LW_IF_F1_IMM_RANGE `IE_I_LW_IF_F1_IMM_UPPER_INDEX:`IE_I_LW_IF_F1_IMM_LOWER_INDEX

`define IE_I_LW_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_LW_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_LW_IF_OPERAND_RANGE `IE_I_LW_IF_OPERAND_UPPER_INDEX:`IE_I_LW_IF_OPERAND_LOWER_INDEX

`define IE_I_LHU_UPPER_INDEX (32-1)
`define IE_I_LHU_LOWER_INDEX (0)
`define IE_I_LHU_WIDTH (32)
`define IE_I_LHU_RANGE `IE_I_LHU_UPPER_INDEX:`IE_I_LHU_LOWER_INDEX
`define IE_I_LHU_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_LHU_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_LHU_IF_F_OPCODE_RANGE `IE_I_LHU_IF_F_OPCODE_UPPER_INDEX:`IE_I_LHU_IF_F_OPCODE_LOWER_INDEX

`define IE_I_LHU_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_LHU_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_LHU_IF_F_RZ_RANGE `IE_I_LHU_IF_F_RZ_UPPER_INDEX:`IE_I_LHU_IF_F_RZ_LOWER_INDEX

`define IE_I_LHU_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_LHU_IF_F_RY_LOWER_INDEX (0)
`define IE_I_LHU_IF_F_RY_RANGE `IE_I_LHU_IF_F_RY_UPPER_INDEX:`IE_I_LHU_IF_F_RY_LOWER_INDEX

`define IE_I_LHU_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_LHU_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_LHU_IF_F1_IMM_RANGE `IE_I_LHU_IF_F1_IMM_UPPER_INDEX:`IE_I_LHU_IF_F1_IMM_LOWER_INDEX

`define IE_I_LHU_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_LHU_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_LHU_IF_OPERAND_RANGE `IE_I_LHU_IF_OPERAND_UPPER_INDEX:`IE_I_LHU_IF_OPERAND_LOWER_INDEX

`define IE_I_LHS_UPPER_INDEX (32-1)
`define IE_I_LHS_LOWER_INDEX (0)
`define IE_I_LHS_WIDTH (32)
`define IE_I_LHS_RANGE `IE_I_LHS_UPPER_INDEX:`IE_I_LHS_LOWER_INDEX
`define IE_I_LHS_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_LHS_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_LHS_IF_F_OPCODE_RANGE `IE_I_LHS_IF_F_OPCODE_UPPER_INDEX:`IE_I_LHS_IF_F_OPCODE_LOWER_INDEX

`define IE_I_LHS_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_LHS_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_LHS_IF_F_RZ_RANGE `IE_I_LHS_IF_F_RZ_UPPER_INDEX:`IE_I_LHS_IF_F_RZ_LOWER_INDEX

`define IE_I_LHS_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_LHS_IF_F_RY_LOWER_INDEX (0)
`define IE_I_LHS_IF_F_RY_RANGE `IE_I_LHS_IF_F_RY_UPPER_INDEX:`IE_I_LHS_IF_F_RY_LOWER_INDEX

`define IE_I_LHS_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_LHS_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_LHS_IF_F1_IMM_RANGE `IE_I_LHS_IF_F1_IMM_UPPER_INDEX:`IE_I_LHS_IF_F1_IMM_LOWER_INDEX

`define IE_I_LHS_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_LHS_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_LHS_IF_OPERAND_RANGE `IE_I_LHS_IF_OPERAND_UPPER_INDEX:`IE_I_LHS_IF_OPERAND_LOWER_INDEX

`define IE_I_LBU_UPPER_INDEX (32-1)
`define IE_I_LBU_LOWER_INDEX (0)
`define IE_I_LBU_WIDTH (32)
`define IE_I_LBU_RANGE `IE_I_LBU_UPPER_INDEX:`IE_I_LBU_LOWER_INDEX
`define IE_I_LBU_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_LBU_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_LBU_IF_F_OPCODE_RANGE `IE_I_LBU_IF_F_OPCODE_UPPER_INDEX:`IE_I_LBU_IF_F_OPCODE_LOWER_INDEX

`define IE_I_LBU_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_LBU_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_LBU_IF_F_RZ_RANGE `IE_I_LBU_IF_F_RZ_UPPER_INDEX:`IE_I_LBU_IF_F_RZ_LOWER_INDEX

`define IE_I_LBU_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_LBU_IF_F_RY_LOWER_INDEX (0)
`define IE_I_LBU_IF_F_RY_RANGE `IE_I_LBU_IF_F_RY_UPPER_INDEX:`IE_I_LBU_IF_F_RY_LOWER_INDEX

`define IE_I_LBU_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_LBU_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_LBU_IF_F1_IMM_RANGE `IE_I_LBU_IF_F1_IMM_UPPER_INDEX:`IE_I_LBU_IF_F1_IMM_LOWER_INDEX

`define IE_I_LBU_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_LBU_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_LBU_IF_OPERAND_RANGE `IE_I_LBU_IF_OPERAND_UPPER_INDEX:`IE_I_LBU_IF_OPERAND_LOWER_INDEX

`define IE_I_LBS_UPPER_INDEX (32-1)
`define IE_I_LBS_LOWER_INDEX (0)
`define IE_I_LBS_WIDTH (32)
`define IE_I_LBS_RANGE `IE_I_LBS_UPPER_INDEX:`IE_I_LBS_LOWER_INDEX
`define IE_I_LBS_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_LBS_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_LBS_IF_F_OPCODE_RANGE `IE_I_LBS_IF_F_OPCODE_UPPER_INDEX:`IE_I_LBS_IF_F_OPCODE_LOWER_INDEX

`define IE_I_LBS_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_LBS_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_LBS_IF_F_RZ_RANGE `IE_I_LBS_IF_F_RZ_UPPER_INDEX:`IE_I_LBS_IF_F_RZ_LOWER_INDEX

`define IE_I_LBS_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_LBS_IF_F_RY_LOWER_INDEX (0)
`define IE_I_LBS_IF_F_RY_RANGE `IE_I_LBS_IF_F_RY_UPPER_INDEX:`IE_I_LBS_IF_F_RY_LOWER_INDEX

`define IE_I_LBS_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_LBS_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_LBS_IF_F1_IMM_RANGE `IE_I_LBS_IF_F1_IMM_UPPER_INDEX:`IE_I_LBS_IF_F1_IMM_LOWER_INDEX

`define IE_I_LBS_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_LBS_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_LBS_IF_OPERAND_RANGE `IE_I_LBS_IF_OPERAND_UPPER_INDEX:`IE_I_LBS_IF_OPERAND_LOWER_INDEX

`define IE_I_SW_UPPER_INDEX (32-1)
`define IE_I_SW_LOWER_INDEX (0)
`define IE_I_SW_WIDTH (32)
`define IE_I_SW_RANGE `IE_I_SW_UPPER_INDEX:`IE_I_SW_LOWER_INDEX
`define IE_I_SW_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SW_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SW_IF_F_OPCODE_RANGE `IE_I_SW_IF_F_OPCODE_UPPER_INDEX:`IE_I_SW_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SW_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SW_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SW_IF_F_RZ_RANGE `IE_I_SW_IF_F_RZ_UPPER_INDEX:`IE_I_SW_IF_F_RZ_LOWER_INDEX

`define IE_I_SW_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SW_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SW_IF_F_RY_RANGE `IE_I_SW_IF_F_RY_UPPER_INDEX:`IE_I_SW_IF_F_RY_LOWER_INDEX

`define IE_I_SW_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_SW_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_SW_IF_F1_IMM_RANGE `IE_I_SW_IF_F1_IMM_UPPER_INDEX:`IE_I_SW_IF_F1_IMM_LOWER_INDEX

`define IE_I_SW_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_SW_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_SW_IF_OPERAND_RANGE `IE_I_SW_IF_OPERAND_UPPER_INDEX:`IE_I_SW_IF_OPERAND_LOWER_INDEX

`define IE_I_SH_UPPER_INDEX (32-1)
`define IE_I_SH_LOWER_INDEX (0)
`define IE_I_SH_WIDTH (32)
`define IE_I_SH_RANGE `IE_I_SH_UPPER_INDEX:`IE_I_SH_LOWER_INDEX
`define IE_I_SH_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SH_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SH_IF_F_OPCODE_RANGE `IE_I_SH_IF_F_OPCODE_UPPER_INDEX:`IE_I_SH_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SH_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SH_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SH_IF_F_RZ_RANGE `IE_I_SH_IF_F_RZ_UPPER_INDEX:`IE_I_SH_IF_F_RZ_LOWER_INDEX

`define IE_I_SH_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SH_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SH_IF_F_RY_RANGE `IE_I_SH_IF_F_RY_UPPER_INDEX:`IE_I_SH_IF_F_RY_LOWER_INDEX

`define IE_I_SH_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_SH_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_SH_IF_F1_IMM_RANGE `IE_I_SH_IF_F1_IMM_UPPER_INDEX:`IE_I_SH_IF_F1_IMM_LOWER_INDEX

`define IE_I_SH_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_SH_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_SH_IF_OPERAND_RANGE `IE_I_SH_IF_OPERAND_UPPER_INDEX:`IE_I_SH_IF_OPERAND_LOWER_INDEX

`define IE_I_SB_UPPER_INDEX (32-1)
`define IE_I_SB_LOWER_INDEX (0)
`define IE_I_SB_WIDTH (32)
`define IE_I_SB_RANGE `IE_I_SB_UPPER_INDEX:`IE_I_SB_LOWER_INDEX
`define IE_I_SB_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_SB_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SB_IF_F_OPCODE_RANGE `IE_I_SB_IF_F_OPCODE_UPPER_INDEX:`IE_I_SB_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SB_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_SB_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_SB_IF_F_RZ_RANGE `IE_I_SB_IF_F_RZ_UPPER_INDEX:`IE_I_SB_IF_F_RZ_LOWER_INDEX

`define IE_I_SB_IF_F_RY_UPPER_INDEX  (5)
`define IE_I_SB_IF_F_RY_LOWER_INDEX (0)
`define IE_I_SB_IF_F_RY_RANGE `IE_I_SB_IF_F_RY_UPPER_INDEX:`IE_I_SB_IF_F_RY_LOWER_INDEX

`define IE_I_SB_IF_F1_IMM_UPPER_INDEX  (0)
`define IE_I_SB_IF_F1_IMM_LOWER_INDEX (0)
`define IE_I_SB_IF_F1_IMM_RANGE `IE_I_SB_IF_F1_IMM_UPPER_INDEX:`IE_I_SB_IF_F1_IMM_LOWER_INDEX

`define IE_I_SB_IF_OPERAND_UPPER_INDEX  (12)
`define IE_I_SB_IF_OPERAND_LOWER_INDEX (0)
`define IE_I_SB_IF_OPERAND_RANGE `IE_I_SB_IF_OPERAND_UPPER_INDEX:`IE_I_SB_IF_OPERAND_LOWER_INDEX

`define IE_I_B_UPPER_INDEX (32-1)
`define IE_I_B_LOWER_INDEX (0)
`define IE_I_B_WIDTH (32)
`define IE_I_B_RANGE `IE_I_B_UPPER_INDEX:`IE_I_B_LOWER_INDEX
`define IE_I_B_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_B_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_B_IF_F_OPCODE_RANGE `IE_I_B_IF_F_OPCODE_UPPER_INDEX:`IE_I_B_IF_F_OPCODE_LOWER_INDEX

`define IE_I_B_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_B_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_B_IF_F_RZ_RANGE `IE_I_B_IF_F_RZ_UPPER_INDEX:`IE_I_B_IF_F_RZ_LOWER_INDEX

`define IE_I_B_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_B_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_B_IF_F_ONE_RANGE `IE_I_B_IF_F_ONE_UPPER_INDEX:`IE_I_B_IF_F_ONE_LOWER_INDEX

`define IE_I_B_IF_F_M_UPPER_INDEX  (18)
`define IE_I_B_IF_F_M_LOWER_INDEX (0)
`define IE_I_B_IF_F_M_RANGE `IE_I_B_IF_F_M_UPPER_INDEX:`IE_I_B_IF_F_M_LOWER_INDEX

`define IE_I_S_UPPER_INDEX (32-1)
`define IE_I_S_LOWER_INDEX (0)
`define IE_I_S_WIDTH (32)
`define IE_I_S_RANGE `IE_I_S_UPPER_INDEX:`IE_I_S_LOWER_INDEX
`define IE_I_S_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_S_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_S_IF_F_OPCODE_RANGE `IE_I_S_IF_F_OPCODE_UPPER_INDEX:`IE_I_S_IF_F_OPCODE_LOWER_INDEX

`define IE_I_S_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_S_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_S_IF_F_RZ_RANGE `IE_I_S_IF_F_RZ_UPPER_INDEX:`IE_I_S_IF_F_RZ_LOWER_INDEX

`define IE_I_S_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_S_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_S_IF_F_ONE_RANGE `IE_I_S_IF_F_ONE_UPPER_INDEX:`IE_I_S_IF_F_ONE_LOWER_INDEX

`define IE_I_S_IF_F_M_UPPER_INDEX  (18)
`define IE_I_S_IF_F_M_LOWER_INDEX (0)
`define IE_I_S_IF_F_M_RANGE `IE_I_S_IF_F_M_UPPER_INDEX:`IE_I_S_IF_F_M_LOWER_INDEX

`define IE_I_CALLN_UPPER_INDEX (32-1)
`define IE_I_CALLN_LOWER_INDEX (0)
`define IE_I_CALLN_WIDTH (32)
`define IE_I_CALLN_RANGE `IE_I_CALLN_UPPER_INDEX:`IE_I_CALLN_LOWER_INDEX
`define IE_I_CALLN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_CALLN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_CALLN_IF_F_OPCODE_RANGE `IE_I_CALLN_IF_F_OPCODE_UPPER_INDEX:`IE_I_CALLN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_CALLN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_CALLN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_CALLN_IF_F_RZ_RANGE `IE_I_CALLN_IF_F_RZ_UPPER_INDEX:`IE_I_CALLN_IF_F_RZ_LOWER_INDEX

`define IE_I_CALLN_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_CALLN_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_CALLN_IF_F_ONE_RANGE `IE_I_CALLN_IF_F_ONE_UPPER_INDEX:`IE_I_CALLN_IF_F_ONE_LOWER_INDEX

`define IE_I_CALLN_IF_F_M_UPPER_INDEX  (18)
`define IE_I_CALLN_IF_F_M_LOWER_INDEX (0)
`define IE_I_CALLN_IF_F_M_RANGE `IE_I_CALLN_IF_F_M_UPPER_INDEX:`IE_I_CALLN_IF_F_M_LOWER_INDEX

`define IE_I_CALLR_UPPER_INDEX (32-1)
`define IE_I_CALLR_LOWER_INDEX (0)
`define IE_I_CALLR_WIDTH (32)
`define IE_I_CALLR_RANGE `IE_I_CALLR_UPPER_INDEX:`IE_I_CALLR_LOWER_INDEX
`define IE_I_CALLR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_CALLR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_CALLR_IF_F_OPCODE_RANGE `IE_I_CALLR_IF_F_OPCODE_UPPER_INDEX:`IE_I_CALLR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_CALLR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_CALLR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_CALLR_IF_F_RZ_RANGE `IE_I_CALLR_IF_F_RZ_UPPER_INDEX:`IE_I_CALLR_IF_F_RZ_LOWER_INDEX

`define IE_I_CALLR_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_CALLR_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_CALLR_IF_F_ONE_RANGE `IE_I_CALLR_IF_F_ONE_UPPER_INDEX:`IE_I_CALLR_IF_F_ONE_LOWER_INDEX

`define IE_I_CALLR_IF_F_M_UPPER_INDEX  (18)
`define IE_I_CALLR_IF_F_M_LOWER_INDEX (0)
`define IE_I_CALLR_IF_F_M_RANGE `IE_I_CALLR_IF_F_M_UPPER_INDEX:`IE_I_CALLR_IF_F_M_LOWER_INDEX

`define IE_I_JMPN_UPPER_INDEX (32-1)
`define IE_I_JMPN_LOWER_INDEX (0)
`define IE_I_JMPN_WIDTH (32)
`define IE_I_JMPN_RANGE `IE_I_JMPN_UPPER_INDEX:`IE_I_JMPN_LOWER_INDEX
`define IE_I_JMPN_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_JMPN_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_JMPN_IF_F_OPCODE_RANGE `IE_I_JMPN_IF_F_OPCODE_UPPER_INDEX:`IE_I_JMPN_IF_F_OPCODE_LOWER_INDEX

`define IE_I_JMPN_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_JMPN_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_JMPN_IF_F_RZ_RANGE `IE_I_JMPN_IF_F_RZ_UPPER_INDEX:`IE_I_JMPN_IF_F_RZ_LOWER_INDEX

`define IE_I_JMPN_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_JMPN_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_JMPN_IF_F_ONE_RANGE `IE_I_JMPN_IF_F_ONE_UPPER_INDEX:`IE_I_JMPN_IF_F_ONE_LOWER_INDEX

`define IE_I_JMPN_IF_F_M_UPPER_INDEX  (18)
`define IE_I_JMPN_IF_F_M_LOWER_INDEX (0)
`define IE_I_JMPN_IF_F_M_RANGE `IE_I_JMPN_IF_F_M_UPPER_INDEX:`IE_I_JMPN_IF_F_M_LOWER_INDEX

`define IE_I_JMPR_UPPER_INDEX (32-1)
`define IE_I_JMPR_LOWER_INDEX (0)
`define IE_I_JMPR_WIDTH (32)
`define IE_I_JMPR_RANGE `IE_I_JMPR_UPPER_INDEX:`IE_I_JMPR_LOWER_INDEX
`define IE_I_JMPR_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_JMPR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_JMPR_IF_F_OPCODE_RANGE `IE_I_JMPR_IF_F_OPCODE_UPPER_INDEX:`IE_I_JMPR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_JMPR_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_JMPR_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_JMPR_IF_F_RZ_RANGE `IE_I_JMPR_IF_F_RZ_UPPER_INDEX:`IE_I_JMPR_IF_F_RZ_LOWER_INDEX

`define IE_I_JMPR_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_JMPR_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_JMPR_IF_F_ONE_RANGE `IE_I_JMPR_IF_F_ONE_UPPER_INDEX:`IE_I_JMPR_IF_F_ONE_LOWER_INDEX

`define IE_I_JMPR_IF_F_M_UPPER_INDEX  (18)
`define IE_I_JMPR_IF_F_M_LOWER_INDEX (0)
`define IE_I_JMPR_IF_F_M_RANGE `IE_I_JMPR_IF_F_M_UPPER_INDEX:`IE_I_JMPR_IF_F_M_LOWER_INDEX

`define IE_I_HALT_UPPER_INDEX (32-1)
`define IE_I_HALT_LOWER_INDEX (0)
`define IE_I_HALT_WIDTH (32)
`define IE_I_HALT_RANGE `IE_I_HALT_UPPER_INDEX:`IE_I_HALT_LOWER_INDEX
`define IE_I_HALT_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_HALT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_HALT_IF_F_OPCODE_RANGE `IE_I_HALT_IF_F_OPCODE_UPPER_INDEX:`IE_I_HALT_IF_F_OPCODE_LOWER_INDEX

`define IE_I_HALT_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_HALT_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_HALT_IF_F_RZ_RANGE `IE_I_HALT_IF_F_RZ_UPPER_INDEX:`IE_I_HALT_IF_F_RZ_LOWER_INDEX

`define IE_I_HALT_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_HALT_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_HALT_IF_F_ONE_RANGE `IE_I_HALT_IF_F_ONE_UPPER_INDEX:`IE_I_HALT_IF_F_ONE_LOWER_INDEX

`define IE_I_HALT_IF_F_M_UPPER_INDEX  (18)
`define IE_I_HALT_IF_F_M_LOWER_INDEX (0)
`define IE_I_HALT_IF_F_M_RANGE `IE_I_HALT_IF_F_M_UPPER_INDEX:`IE_I_HALT_IF_F_M_LOWER_INDEX

`define IE_I_RETI_UPPER_INDEX (32-1)
`define IE_I_RETI_LOWER_INDEX (0)
`define IE_I_RETI_WIDTH (32)
`define IE_I_RETI_RANGE `IE_I_RETI_UPPER_INDEX:`IE_I_RETI_LOWER_INDEX
`define IE_I_RETI_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_RETI_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_RETI_IF_F_OPCODE_RANGE `IE_I_RETI_IF_F_OPCODE_UPPER_INDEX:`IE_I_RETI_IF_F_OPCODE_LOWER_INDEX

`define IE_I_RETI_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_RETI_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_RETI_IF_F_RZ_RANGE `IE_I_RETI_IF_F_RZ_UPPER_INDEX:`IE_I_RETI_IF_F_RZ_LOWER_INDEX

`define IE_I_RETI_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_RETI_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_RETI_IF_F_ONE_RANGE `IE_I_RETI_IF_F_ONE_UPPER_INDEX:`IE_I_RETI_IF_F_ONE_LOWER_INDEX

`define IE_I_RETI_IF_F_M_UPPER_INDEX  (18)
`define IE_I_RETI_IF_F_M_LOWER_INDEX (0)
`define IE_I_RETI_IF_F_M_RANGE `IE_I_RETI_IF_F_M_UPPER_INDEX:`IE_I_RETI_IF_F_M_LOWER_INDEX

`define IE_I_TRAP_UPPER_INDEX (32-1)
`define IE_I_TRAP_LOWER_INDEX (0)
`define IE_I_TRAP_WIDTH (32)
`define IE_I_TRAP_RANGE `IE_I_TRAP_UPPER_INDEX:`IE_I_TRAP_LOWER_INDEX
`define IE_I_TRAP_IF_F_OPCODE_UPPER_INDEX  (5)
`define IE_I_TRAP_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_TRAP_IF_F_OPCODE_RANGE `IE_I_TRAP_IF_F_OPCODE_UPPER_INDEX:`IE_I_TRAP_IF_F_OPCODE_LOWER_INDEX

`define IE_I_TRAP_IF_F_RZ_UPPER_INDEX  (5)
`define IE_I_TRAP_IF_F_RZ_LOWER_INDEX (0)
`define IE_I_TRAP_IF_F_RZ_RANGE `IE_I_TRAP_IF_F_RZ_UPPER_INDEX:`IE_I_TRAP_IF_F_RZ_LOWER_INDEX

`define IE_I_TRAP_IF_F_ONE_UPPER_INDEX  (0)
`define IE_I_TRAP_IF_F_ONE_LOWER_INDEX (0)
`define IE_I_TRAP_IF_F_ONE_RANGE `IE_I_TRAP_IF_F_ONE_UPPER_INDEX:`IE_I_TRAP_IF_F_ONE_LOWER_INDEX

`define IE_I_TRAP_IF_F_M_UPPER_INDEX  (18)
`define IE_I_TRAP_IF_F_M_LOWER_INDEX (0)
`define IE_I_TRAP_IF_F_M_RANGE `IE_I_TRAP_IF_F_M_UPPER_INDEX:`IE_I_TRAP_IF_F_M_LOWER_INDEX


`endif
