`ifndef INC_GUARD_top
`define INC_GUARD_top

`define P_IN_UPPER_INDEX  (3-1)
`define P_IN_LOWER_INDEX  (0)
`define P_IN_WIDTH  (3)
`define P_IN_RANGE `P_IN_UPPER_INDEX:`P_IN_LOWER_INDEX
`define P_OUT1_UPPER_INDEX  (3-1)
`define P_OUT1_LOWER_INDEX  (0)
`define P_OUT1_WIDTH  (3)
`define P_OUT1_RANGE `P_OUT1_UPPER_INDEX:`P_OUT1_LOWER_INDEX
`define P_OUT2_UPPER_INDEX  (3-1)
`define P_OUT2_LOWER_INDEX  (0)
`define P_OUT2_WIDTH  (3)
`define P_OUT2_RANGE `P_OUT2_UPPER_INDEX:`P_OUT2_LOWER_INDEX
`define P_CLK_UPPER_INDEX  (0)
`define P_CLK_LOWER_INDEX  (0)
`define P_CLK_WIDTH  (0-0+1)
`define P_CLK_RANGE `P_CLK_UPPER_INDEX:`P_CLK_LOWER_INDEX

`endif
