`ifndef INC_GUARD_ua
`define INC_GUARD_ua

`define P_PAIN_UPPER_INDEX  (8-1)
`define P_PAIN_LOWER_INDEX  (0)
`define P_PAIN_WIDTH  (8)
`define P_PAIN_RANGE `P_PAIN_UPPER_INDEX:`P_PAIN_LOWER_INDEX
`define P_PAOUT_UPPER_INDEX  (8-1)
`define P_PAOUT_LOWER_INDEX  (0)
`define P_PAOUT_WIDTH  (8)
`define P_PAOUT_RANGE `P_PAOUT_UPPER_INDEX:`P_PAOUT_LOWER_INDEX
`define IFC_IFCRC_P_RESET_UPPER_INDEX  (0)
`define IFC_IFCRC_P_RESET_LOWER_INDEX  (0)
`define IFC_IFCRC_P_RESET_WIDTH  (0-0+1)
`define IFC_IFCRC_P_RESET_RANGE `IFC_IFCRC_P_RESET_UPPER_INDEX:`IFC_IFCRC_P_RESET_LOWER_INDEX
`define IFC_IFCRC_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IFCRC_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IFCRC_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IFCRC_P_CLOCK_RANGE `IFC_IFCRC_P_CLOCK_UPPER_INDEX:`IFC_IFCRC_P_CLOCK_LOWER_INDEX

`endif
