`ifndef INC_GUARD_ude
`define INC_GUARD_ude

`define IFC_IFCRC0_P_RESET_UPPER_INDEX  (1-1)
`define IFC_IFCRC0_P_RESET_LOWER_INDEX  (0)
`define IFC_IFCRC0_P_RESET_WIDTH  (1)
`define IFC_IFCRC0_P_RESET_RANGE `IFC_IFCRC0_P_RESET_UPPER_INDEX:`IFC_IFCRC0_P_RESET_LOWER_INDEX
`define IFC_IFCRC0_P_CLOCK_UPPER_INDEX  (1-1)
`define IFC_IFCRC0_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IFCRC0_P_CLOCK_WIDTH  (1)
`define IFC_IFCRC0_P_CLOCK_RANGE `IFC_IFCRC0_P_CLOCK_UPPER_INDEX:`IFC_IFCRC0_P_CLOCK_LOWER_INDEX
`define S_S_IN_UPPER_INDEX  (8-1)
`define S_S_IN_LOWER_INDEX  (0)
`define S_S_IN_WIDTH  (8)
`define S_S_IN_RANGE `S_S_IN_UPPER_INDEX:`S_S_IN_LOWER_INDEX
`define S_SE_IN_UPPER_INDEX  (16-1)
`define S_SE_IN_LOWER_INDEX  (0)
`define S_SE_IN_WIDTH  (16)
`define S_SE_IN_RANGE `S_SE_IN_UPPER_INDEX:`S_SE_IN_LOWER_INDEX
`define SG_SG01_S_HW_UPPER_INDEX  (16-1)
`define SG_SG01_S_HW_LOWER_INDEX  (0)
`define SG_SG01_S_HW_WIDTH  (16)
`define SG_SG01_S_HW_RANGE `SG_SG01_S_HW_UPPER_INDEX:`SG_SG01_S_HW_LOWER_INDEX
`define SG_SG01_S_W_UPPER_INDEX  (8-1)
`define SG_SG01_S_W_LOWER_INDEX  (0)
`define SG_SG01_S_W_WIDTH  (8)
`define SG_SG01_S_W_RANGE `SG_SG01_S_W_UPPER_INDEX:`SG_SG01_S_W_LOWER_INDEX
`define SG_SG02_S_HW_UPPER_INDEX  (16-1)
`define SG_SG02_S_HW_LOWER_INDEX  (0)
`define SG_SG02_S_HW_WIDTH  (16)
`define SG_SG02_S_HW_RANGE `SG_SG02_S_HW_UPPER_INDEX:`SG_SG02_S_HW_LOWER_INDEX
`define SG_SG02_S_W_UPPER_INDEX  (8-1)
`define SG_SG02_S_W_LOWER_INDEX  (0)
`define SG_SG02_S_W_WIDTH  (8)
`define SG_SG02_S_W_RANGE `SG_SG02_S_W_UPPER_INDEX:`SG_SG02_S_W_LOWER_INDEX
`define SG_SG1_S_HW_UPPER_INDEX  (16-1)
`define SG_SG1_S_HW_LOWER_INDEX  (0)
`define SG_SG1_S_HW_WIDTH  (16)
`define SG_SG1_S_HW_RANGE `SG_SG1_S_HW_UPPER_INDEX:`SG_SG1_S_HW_LOWER_INDEX
`define SG_SG1_S_W_UPPER_INDEX  (8-1)
`define SG_SG1_S_W_LOWER_INDEX  (0)
`define SG_SG1_S_W_WIDTH  (8)
`define SG_SG1_S_W_RANGE `SG_SG1_S_W_UPPER_INDEX:`SG_SG1_S_W_LOWER_INDEX
`define SG_SG1_S_C_UPPER_INDEX  (3-1)
`define SG_SG1_S_C_LOWER_INDEX  (0)
`define SG_SG1_S_C_WIDTH  (3)
`define SG_SG1_S_C_RANGE `SG_SG1_S_C_UPPER_INDEX:`SG_SG1_S_C_LOWER_INDEX

`endif
