`ifndef INC_GUARD_uf
`define INC_GUARD_uf

`define P_PFOUT_UPPER_INDEX  (8-1)
`define P_PFOUT_LOWER_INDEX  (0)
`define P_PFOUT_WIDTH  (8)
`define P_PFOUT_RANGE `P_PFOUT_UPPER_INDEX:`P_PFOUT_LOWER_INDEX
`define IFC_IFCFIN_P_HW_UPPER_INDEX  (16-1)
`define IFC_IFCFIN_P_HW_LOWER_INDEX  (0)
`define IFC_IFCFIN_P_HW_WIDTH  (16)
`define IFC_IFCFIN_P_HW_RANGE `IFC_IFCFIN_P_HW_UPPER_INDEX:`IFC_IFCFIN_P_HW_LOWER_INDEX
`define IFC_IFCFIN_P_W_UPPER_INDEX  (8-1)
`define IFC_IFCFIN_P_W_LOWER_INDEX  (0)
`define IFC_IFCFIN_P_W_WIDTH  (8)
`define IFC_IFCFIN_P_W_RANGE `IFC_IFCFIN_P_W_UPPER_INDEX:`IFC_IFCFIN_P_W_LOWER_INDEX
`define IFC_IFCFIN_P_C_UPPER_INDEX  (3-1)
`define IFC_IFCFIN_P_C_LOWER_INDEX  (0)
`define IFC_IFCFIN_P_C_WIDTH  (3)
`define IFC_IFCFIN_P_C_RANGE `IFC_IFCFIN_P_C_UPPER_INDEX:`IFC_IFCFIN_P_C_LOWER_INDEX
`define IFC_IFCRC_P_RESET_UPPER_INDEX  (0)
`define IFC_IFCRC_P_RESET_LOWER_INDEX  (0)
`define IFC_IFCRC_P_RESET_WIDTH  (0-0+1)
`define IFC_IFCRC_P_RESET_RANGE `IFC_IFCRC_P_RESET_UPPER_INDEX:`IFC_IFCRC_P_RESET_LOWER_INDEX
`define IFC_IFCRC_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IFCRC_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IFCRC_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IFCRC_P_CLOCK_RANGE `IFC_IFCRC_P_CLOCK_UPPER_INDEX:`IFC_IFCRC_P_CLOCK_LOWER_INDEX

`endif
