<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
	<!-- Column 1 start -->
	<h2 class="caps">Articles</h2>

	The articles page is under construction. Stay tuned.
	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->
	$articlesMenu$
	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

