<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
	<!-- Column 1 start -->
	Fastpath Logic is a privately owned early stage system level
	automation company. Fastpath Logic's mission is to
	reduce the amount of time spent on infrastructure development and 
	to reduce the amount of time spent making changes in design 
	proliferations and ECO's.
	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->
	$companyMenu$
	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

