<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" >

  <head>
    <title>Fastpath Logic&reg; Inc.</title>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
    <meta name="author" content="Derek Pappas" />
    <meta name="keywords" content="EDA, ESL, SoC, NoC, SystemC, RTL, Verification, infrastructure" />
    <meta name="description" content="Automating the design verification process." />
    <meta name="robots" content="all" />

	<link rel="stylesheet" type="text/css" href="style.css" media="all" />
	<link rel="stylesheet" type="text/css" href="star-light/star-light.css" media="all" />
	<link rel="stylesheet" type="text/css" href="../cssfpl/3_column_layout.css" media="all" />

	<script type="text/javascript" src="jquery.js"></script>
	<script type="text/javascript">
	  $nav_menu$
	</script>
	<style type="text/css">

/* Navigation */
.nav, .nav ul { 
	list-style: none;
	margin: 0;
	padding: 0;
}

.nav {
  font-family: Arial, Helvetica, sans-serif;
  z-index: 100;
  position: relative;
}
.nav li {
  border-left: 1px solid #000;
  float: left;
  margin: 0;
  padding: 0;
  position: relative;
}
.nav li a, .nav li a:link, .nav li a:active, .nav li a:visited {
  font: bold 1.22em/25px Arial, Helvetica, sans-serif;
  background: #565656;
  color: #959595;
  display: block;
  padding: 0 9px;
  text-transform: lowercase;
  text-decoration: none;
}

.nav li a:hover {
  background: 111;
  color: #000;	

}
#nav-one li:hover a, 
#nav-one li.sfHover a {
  background: 111;
  color: #000;
}
#nav-one li:hover ul a, 
#nav-one li.sfHover ul a {
  background: #565656;
  color: #959595;	
}
#nav-one li:hover ul a:hover, 
#nav-one li.sfHover ul a:hover {
  background: 111;
  color: #000;	
}

.nav ul {
  background: #565656;
  border-bottom: 1px solid #000;
  list-style: none;
  margin: 0;
  width: 100px;
  position: absolute;
  top: -999em;
  left: -1px;
}
.nav li:hover ul,
.nav li.sfHover ul {
  top: 25px;
}
.nav ul li {
  border: 0;
  float: none;
}
.nav ul a {
  border: 1px solid #000;
  border-bottom: 0;
  padding-right: 20px;
  width: 200px;
  white-space: nowrap;
}
.nav ul a:hover {
  background: 111;
  color: #000;
}
	</style>
</head>
<body>
    <div id="header">
      <div class="cell_nav_menu menu_font" align="right">
		<a style="font-weight: bold;" href="index.htm"       >Home | </a>
		<a style="font-weight: bold;" href="contact.htm" >Contact Us | </a>
		<a style="font-weight: bold;" href="sitemap.htm" >Sitemap</a>
      </div>
      <div>
		&nbsp;&nbsp;&nbsp;
		<a href="index.htm"><img src="../imagesfpl/fpl_new_logo.png"></img></a>
      </div>
	</div>


	<ul id="nav-one" class="nav" >
	  <li>
		<a href="products.htm"><b>PRODUCTS</b></a>
		<ul>
		  <li><a href="design_management_system.htm">Design Management System</a></li>
		  <li><a href="infrastructure_specification.htm">Infrastructure Specification</a></li>
		  <li><a href="infrastructure_compiler.htm">Infrastructure Compiler</a></li>
		  <li><a href="infrastructure_components.htm">Infrastructure Components</a></li>
		  <li><a href="interconnect.htm">Interconnect</a></li>
		  <li><a href="reference_model.htm">Reference Model</a></li>
		  <li><a href="testbench.htm">Test Benches</a></li>
		  <li><a href="memorymap.htm">Memory Map</a></li>
		  <li><a href="register_generator.htm">Registers</a></li>
		  <li><a href="register_file_generator.htm">Register Files</a></li>
		  <li><a href="isa.htm">Instruction Set Architecture</a></li>
		</ul>
	  </li>
<!--
	  <li>
		<a href="ip.htm"><b>IP</b></a>
		<ul>
		  <li><a href="ip.htm">IP</a></li>
		  <li><a href="risc_core.htm">RISC Core</a></li>
		  <li><a href="application_specific_processors.htm">Application Specific Processors</a></li>
		  <li><a href="mbist.htm">MBIST</a></li>
		  <li><a href="testability_controller.htm">Testability Controller</a></li>
		  <li><a href="processor_ring.htm">Processor Ring</a></li>
		</ul>
	  </li>
-->
	  <li>
		<a href="technology.htm">TECHNOLOGY</a>
		<ul>
		  <li><a href="overview.htm">Overview</a></li>
		  <li><a href="white_papers.htm">White Papers</a></li>
		  <li><a href="success_stories.htm">Success Stories</a></li>
		</ul>
	  </li>

	  <li>
		<a href="support.htm"><b>SUPPORT</b></a>
		<ul>
		  <li><a href="request_for_info.htm">Request For Info</a></li>
		  <li><a href="supported_platforms.htm">Supported Platforms</a></li>
		  <li><a href="support_centers.htm">Contact Support</a></li>
		</ul>
	  </li>

	  <li><a href="news.htm"><b>NEWS</b></a>
		<ul>
		  <li><a href="articles.htm">Press Articles</a></li>
		  <li><a href="industry.htm">Industry Links</a></li>
		  <li><a href="editorial.htm">Editorial Contacts</a></li>
		  <li><a href="trade_shows.htm">Trade Shows</a></li>
		</ul>
	  </li>

	  <li><a href="partners.htm"><b>PARTNERS</b></a>
		<ul>
		  <li><a href="tech_partners.htm">Technology Partners</a></li>
		  <li><a href="signup.htm">Fastpath Logic Partner Sign up</a></li>
		  <li><a href="universities.htm">University Program</a></li>
		</ul>
	  </li>
	  <li>
		<a href="company.htm"><b>About Fastpath Logic</b></a>
		<ul>
		  <li><a href="company.htm">Company Profile</a></li>
		  <li><a href="management.htm">Management</a></li>
		  <li><a href="directors.htm">Board of Directors</a></li>
		  <li><a href="advisory_board.htm">Advisory Board</a></li>
		  <li><a href="offices.htm">Offices</a></li>
		  <li><a href="careers.htm">Careers</a></li>
		  <li><a href="contact.htm">Contact</a></li>		
		</ul>
	  </li>


	</ul>

<div class="white_line"></div>
<div class="blue_line"></div>
<br clear="all" />

<div>
  <br/>
  <div class="taxonomy"> 
	&nbsp;&nbsp;&nbsp;<a href="index.htm">Home</a> > <a href="$pageName$.htm">$pageName$</a>
  </div>
  <br/>
</div>


