<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
		<!-- Column 1 start -->
		<h2>Automating the chip design and verification process</h2>
		<p>
		  Fastpath Logic is focused on managing the exploding
		  complexity of ASIC and FPGA designs. Fastpath Logic's tool set
		  automates and significantly reduces the amount of work required to
		  develop the chip/system level interconnect, the memory map and
		  registers, the vectors/transactions used for verification, the
		  functional simulator used to verify the design, the communication
		  mechanism between the functional simulator and the RTL design, the
		  instruction set architecture specification and implementation, and
		  the other infrasture related tasks.         
		</p>
	    <h2>Innovative Technology</h2>
	    <p>The Fastpath Logic synthesis engine is at the core of
	      the Fastpath Logic solution. The engine includes
	      an auto router to automatically
	      connect modules across design hierarchies.</p>

	    <h2>Preemptive benefits</h2>
	    <p>Customers have reported a 15-30x
	      reduction in the amount of time spent
	      architecting and building the
	      RTL design and functional simulator 
		  interconnect for SoC and NoC chips.</p>

	    <h2>Tape outs</h2>
	    <p>A large semi company recently taped
	      out a design that utilized the Fastpath Logic
	      tool to construct the SoC interconnect.</p>

		<h2>Infrastructure and Algorithmic Code</h2>
		<p>
		  Chip designs consist of the algorithmic and infrastructure components.
		  The infrastructure components are reused in the different domains such as 
		  verification, simulation and design by just converting the code to RTL or C++.
		  
		  The algorithmic parts are implemented in different forms in in the different domains.
		  The different algorithmic forms are simple in the simulator and complex and detailed
		  in the RTL design. 
		</p>

	</h2>
	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->	
	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

