
<!--|**START IMENUS**|imenus0,inline-->

<!--  ****** Infinite Menus Structure & Links ***** -->
<div class="imrcmain0 imgl" style="width:140px;z-index:999999;position:relative;">
  <div class="imcm imde" id="imouter0">
    <ul id="imenus0">
      <li class="imatm"  style="width:100%;">
	<a href="PagePartners.htm"><span class="imea imeam"><span></span></span>&nbsp;&nbsp;&nbsp;Partner Programs</a>
      </li>

      <li class="imatm"  style="width:100%;">
	<a href="PageTechPartners.htm"><span class="imea imeam"><span></span></span>&nbsp;&nbsp;&nbsp;Technology Partners</a>
      </li>

      <li class="imatm"  style="width:100%;">
	<a href="PageSignUp.htm"><span class="imea
	imeam"><span></span></span>&nbsp;&nbsp;&nbsp;Sign up to be a
	Fastpath Logic Partner</a>
      </li>

      <li class="imatm"  style="width:100%;">
	<a href="PageUniversities.htm"><span class="imea imeam"><span></span></span>&nbsp;&nbsp;&nbsp;Universities</a>		
      </li>
    </ul>
    <div class="imclear">&nbsp;
</div>

<script language="JavaScript" src="ocscript.js" type="text/javascript"></script>







