<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
	<!-- Column 1 start -->
<table class="content" border = "0" width ="95%" align = "right">
					<tr>
						<td width="100%" height = "100%">
							 <div class="taxonomy" ><a href="#">Home</a> > <a href="#">Support</a> > Support Request</div><br /><br />
						</td>
					</tr>
					<tr height="100%" width="100%">
							 <td height="100%" width="70%" valign="top" halign="left" >
	
								<table width=500 border=0 align=left cellpadding=0 cellspacing=0 >
									<tr>
										<td width=1 height=89 valign=top>&nbsp;</td>
										<td width=100 height=89 valign=top></td>
										<td width=15 height=89 valign=top></td>
										<td width=250 height=89 valign=middle><div><H1>Support request form</H1>Your personal information will be kept confidential .<br />It will not be released to a third party, but it will be exclusively used for an initial contact between you and Fastpath Logic.</div><p style="color: #8B0000">NOTE:&nbsp;&nbsp;&nbsp;The asterisk (*) designates required fields.</p></td>
									</tr>
									<tr><td><br /><br /></td></tr>
									<tr>
										<td width=1 height=29 valign=top  >&nbsp;</td>
										<td width=194><div align="right" > <font color="#FF0000">*</font>First&nbsp;name</div></td>
										<td width=15>&nbsp;</td>
										<td width=327  ><input type="text" name="first_name" size="40" maxlength="40"></td>
									</tr>
									<tr>
										<td width=1 height=29 valign=top  >&nbsp;</td>
										<td width=194><div align="right"  > <font color="#FF0000">*</font><font color="#666666">Last&nbsp;name</div></td>
										<td width=15>&nbsp;</td>
										<td width=327  ><input type="text" name="last_name" size="40" maxlength="40"></td>
									</tr>	
									<tr>
										<td width=1 height=29 valign=top  >&nbsp;</td>
										<td width=194><div align="right"  >  <font color="#FF0000">*</font>Organization</div></td>
										<td width=15>&nbsp;</td>
										<td width=327  ><input type="text" name="organization" size="40" maxlength="30"></td>
									</tr>
									<tr>
										<td width=1 height=29 valign=top  >&nbsp;</td>
										<td width=194><div align="right"  > Job&nbsp;title&nbsp;or&nbsp;position</div></td>
										<td width=15>&nbsp;</td>
										<td width=327  ><input type="text" name="position" size="40" maxlength="40"></td>
									</tr>
									<tr>
										<td width=1 height=29 valign=top  >&nbsp;</td>
										<td width=194><div align="right"  > <font color="#FF0000">*</font>E-mail</div></td>
										<td width=15>&nbsp;</td>
										<td width=327  ><font color="#FF0000"> 
								<input type="text" name="email" size="40" maxlength="30">
								</font></td>
									</tr>
								
									<tr>
										<td width=1 height=29 valign=top  >&nbsp;</td>
										<td width=194><div align="right"  > <font color="#FF0000"></font>Telephone</div></td>
										<td width=15>&nbsp;</td>
										<td width=327  ><input type="text" name="tel" size="40" maxlength="40"></td>
									</tr>
								
									<tr>
										<td width=1 height=21 valign=top  >&nbsp;</td>
										<td width=194 height=21><div align="right"  > <font color="#FF0000">*</font>Area</div></td>
										<td width=15 height=21>&nbsp;</td>
										<td width=327 height=21  ><select name="area">
								<option SELECTED value="">Choose an area 
								<option value="Asia">Asia
								<option value="Europe">Europe
								<option value="US_Central">US-Central
								<option value="US_East">US-East
								<option value="US_West">US-West
								</select></td>
									</tr>
									<tr>
										<td width=1 height=29 valign=top  >&nbsp;</td>
										<td width=194><div align="right"  > Comment</div></td>
										<td width=15>&nbsp;</td>
										<td width=327  ><textarea name="comment"   cols=30 rows=10></textarea></td>
									</tr>
									<tr><td><br /><br /></td></tr>
									<tr>
										<td width=1 height=89 valign=top>&nbsp;</td>
										<td width=194 height=89 valign=top></td>
										<td width=15 height=89 valign=top></td>
										<td width=327 height=89 valign=middle><div>To clear entered information, click the <b>Reset</b> button. To send the form, click the <b>Send form</b> button.<br /></div></td>
									</tr>
									<tr>
										<td width=1 height=45 valign=top>&nbsp;</td>
										<td width=100 height=45>&nbsp;</td>
										<td width=15 height=45>&nbsp;</td>
										<td width=250 height=45>
								<input type="reset" name="Undo" value="Reset">
								&nbsp;</font> 
								
								<input type="submit" name="submit" value="Send form"></td>
								
									</tr>
								</table>
							</td>
						</tr>

</table>
      </div>
      <div class="col2">
	<!-- Column 2 start -->

	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

