<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
	<!-- Column 1 start -->
	    <h2>Platform support</h2>
	    <p>The Fastpath Logic interconnect tool has been tested on the following platforms:</p>
	    <h3>Linux 32-bit</h3>
	    <ul>
	      <li>Redhat EL5</li>
	      <li>CentOS 5.2</li>
	      <li>Ubuntu</li>
	    </ul>
	    <h3>Linux 64-bit</h3>
	    <ul>
	      <li>Redhat EL5</li>
	      <li>CentOS 5.2</li>
	      <li>Ubuntu</li>
	    </ul>
	    <h3>Mac OS X 10.5.x 32-bit</h3>
	    <h3>Mac OS X 10.5.x 64-bit beta</h3>
	    <h3>Windows XP 32-bit beta</h3>
	    <h3>Windows XP 64-bit beta</h3>

	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->
	$supported_platformsMenu$
	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

