<div class="colmask threecol">
  <div class="colmid">
    <div class="colleft">
      <div class="col1">
	<!-- Column 1 start -->
	    <h2>Transaction Level Modeling</h2>
	    <p>SoC's designs are constructed using a design heirarchy
	    and interconnect. The design is verified at specific
	    points (interfaces) using simulation models, bus functional models,
	    and assertions. These interfaces change during the
	    development of the project in the verification test
	    benches, tranaction level interfaces, and the RTL module
	    interfaces. Maintenance of the consistency between these interfaces is a
	    consistency problem. </p>
	    <img  class="g1515" src="../imagesfpl/soc_tlm.png"  alt="soc" />

	<!-- Column 1 end -->
      </div>
      <div class="col2">
	<!-- Column 2 start -->

	<!-- Column 2 end -->
      </div>
      <div class="col3">
	<!-- Column 3 start -->
	<!-- Column 3 end -->
      </div>
    </div>
  </div>
</div>

