`ifndef INC_GUARD_u2
`define INC_GUARD_u2

`define SG_SG1_S_S1_UPPER_INDEX  (2-1)
`define SG_SG1_S_S1_LOWER_INDEX  (0)
`define SG_SG1_S_S1_WIDTH  (2)
`define SG_SG1_S_S1_RANGE `SG_SG1_S_S1_UPPER_INDEX:`SG_SG1_S_S1_LOWER_INDEX
`define SG_SG1_S_S2_UPPER_INDEX  (8-1)
`define SG_SG1_S_S2_LOWER_INDEX  (0)
`define SG_SG1_S_S2_WIDTH  (8)
`define SG_SG1_S_S2_RANGE `SG_SG1_S_S2_UPPER_INDEX:`SG_SG1_S_S2_LOWER_INDEX
`define SG_SG1_S_S3_UPPER_INDEX  (10-1)
`define SG_SG1_S_S3_LOWER_INDEX  (0)
`define SG_SG1_S_S3_WIDTH  (10)
`define SG_SG1_S_S3_RANGE `SG_SG1_S_S3_UPPER_INDEX:`SG_SG1_S_S3_LOWER_INDEX

`endif
