`ifndef INC_GUARD_u_rf
`define INC_GUARD_u_rf

`define IFC_IFC_RF_P_P_CLK_UPPER_INDEX  (0)
`define IFC_IFC_RF_P_P_CLK_LOWER_INDEX  (0)
`define IFC_IFC_RF_P_P_CLK_WIDTH  (0-0+1)
`define IFC_IFC_RF_P_P_CLK_RANGE `IFC_IFC_RF_P_P_CLK_UPPER_INDEX:`IFC_IFC_RF_P_P_CLK_LOWER_INDEX
`define IFC_IFC_RF_P_P_RST_UPPER_INDEX  (0)
`define IFC_IFC_RF_P_P_RST_LOWER_INDEX  (0)
`define IFC_IFC_RF_P_P_RST_WIDTH  (0-0+1)
`define IFC_IFC_RF_P_P_RST_RANGE `IFC_IFC_RF_P_P_RST_UPPER_INDEX:`IFC_IFC_RF_P_P_RST_LOWER_INDEX
`define IFC_IFC_RF_P_P_STALL_UPPER_INDEX  (0)
`define IFC_IFC_RF_P_P_STALL_LOWER_INDEX  (0)
`define IFC_IFC_RF_P_P_STALL_WIDTH  (0-0+1)
`define IFC_IFC_RF_P_P_STALL_RANGE `IFC_IFC_RF_P_P_STALL_UPPER_INDEX:`IFC_IFC_RF_P_P_STALL_LOWER_INDEX
`define IFC_IFC_UNIT_RF_L_P_P_UNITOUT_UPPER_INDEX  (32-1)
`define IFC_IFC_UNIT_RF_L_P_P_UNITOUT_LOWER_INDEX  (0)
`define IFC_IFC_UNIT_RF_L_P_P_UNITOUT_WIDTH  (32)
`define IFC_IFC_UNIT_RF_L_P_P_UNITOUT_RANGE `IFC_IFC_UNIT_RF_L_P_P_UNITOUT_UPPER_INDEX:`IFC_IFC_UNIT_RF_L_P_P_UNITOUT_LOWER_INDEX
`define IFC_IFC_UNIT_RF_L_P_P_UNITIN_UPPER_INDEX  (32-1)
`define IFC_IFC_UNIT_RF_L_P_P_UNITIN_LOWER_INDEX  (0)
`define IFC_IFC_UNIT_RF_L_P_P_UNITIN_WIDTH  (32)
`define IFC_IFC_UNIT_RF_L_P_P_UNITIN_RANGE `IFC_IFC_UNIT_RF_L_P_P_UNITIN_UPPER_INDEX:`IFC_IFC_UNIT_RF_L_P_P_UNITIN_LOWER_INDEX
`define IFC_IFC_UNIT_RF_R_P_P_UNITOUT_UPPER_INDEX  (32-1)
`define IFC_IFC_UNIT_RF_R_P_P_UNITOUT_LOWER_INDEX  (0)
`define IFC_IFC_UNIT_RF_R_P_P_UNITOUT_WIDTH  (32)
`define IFC_IFC_UNIT_RF_R_P_P_UNITOUT_RANGE `IFC_IFC_UNIT_RF_R_P_P_UNITOUT_UPPER_INDEX:`IFC_IFC_UNIT_RF_R_P_P_UNITOUT_LOWER_INDEX
`define IFC_IFC_UNIT_RF_R_P_P_UNITIN_UPPER_INDEX  (32-1)
`define IFC_IFC_UNIT_RF_R_P_P_UNITIN_LOWER_INDEX  (0)
`define IFC_IFC_UNIT_RF_R_P_P_UNITIN_WIDTH  (32)
`define IFC_IFC_UNIT_RF_R_P_P_UNITIN_RANGE `IFC_IFC_UNIT_RF_R_P_P_UNITIN_UPPER_INDEX:`IFC_IFC_UNIT_RF_R_P_P_UNITIN_LOWER_INDEX

`endif
