#!/usr/bin/perl

#Author Petronela
use strict;
use Switch;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 30; $i++) {
    my @map1  = ("p_a$i","pa","p");
    my @map11 = ("p_ifca$i","p_ifa");
    my @map12 = ("p_ifcb$i","p_ifb","p_if");
    my @map2  = ("p","p_b$i");
    my @map21 = ("p_ifca$i","p_ifa","p_if");
    my @map22 = ("p_ifcb$i","p_ifb");
    my @map3  = ("pc","p","p_c_br$i");
    my @map31 = ("p_ifca$i","p_ifa","p_if","p_ifta$i");
    my @map32 = ("p_ifcb$i","p_ifb","p_if","p_iftb$i","p_b");
    my @map4  = ("p_d$i","p"); 
    my @map5  = ("p_e$i","p","pe");
    my @map6  = ("p_top$i","p_top_br$i","p");
    if($i <= 5 ) {  
        foreach my $it1 (@map1) {
            if($i <= 2 ) {
                foreach my $it2 (@map11) {
                    &main($i,$it1,$it2);
                }
            }   
            else {
                foreach my $it3(@map12) { 
                    &main($i,$it1,$it3);
                }
            }
        }
    }
    elsif($i > 5 && $i <= 10) {
        foreach my $it1 (@map2) {
            if($i > 5 && $i <= 7) {
                foreach my $it2(@map21) {
                    &main($i,$it1,$it2);
                }
            }
            else {
                foreach my $it3(@map22) {
                    &main($i,$it1,$it3);
                }
            }
        }       
    }
    elsif($i > 10 && $i <= 15) {
        foreach my $it1 (@map3) {
            if($i > 10 && $i <= 12) {
                foreach my $it2(@map31) {
                    &main($i,$it1,$it2);
                }
            }
            else {
                foreach my $it3(@map32) {
                    &main($i,$it1,$it3);
                }
            }
        }       
    }
    elsif($i > 15 && $i <= 20) {
        foreach my $it1 (@map4) {
            if($i > 15 && $i <= 17) {
                foreach my $it2(@map31) {
                    &main($i,$it1,$it2);
                }
            }
            else {
                foreach my $it3(@map32) {
                    &main($i,$it1,$it3);
                }
            }
        }       
    }
    elsif($i > 20 && $i <= 25) {
        foreach my $it1 (@map5) {
            if($i > 20 && $i <= 22) {
                foreach my $it2(@map11) {
                    &main($i,$it1,$it2);
                }
            }
            else {
                foreach my $it3(@map12) {
                    &main($i,$it1,$it3);
                }
            }
        }       
    }
    elsif($i > 25 && $i <= 30) {
        foreach my $it1 (@map6) {
            if($i > 25 && $i <= 27) {
                foreach my $it2(@map31) {
                    &main($i,$it1,$it2);
                }
            }
            else {
                foreach my $it3(@map32) {
                    &main($i,$it1,$it3);
                }
            }
        }       
    }
}

sub main {
    my ($i,$it1,$it2) = @_;
    my $test_name = "connect_unit_p_ifc_ifcp".$i."_".$it1."_".$it2."_legal.csl";
    &createCslFile($test_name, $i,$it1,$it2);
}
sub createCslFile {
    my($test_name, $i,$it1,$it2) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
    my $val1 = int(rand(100)) + 1;
    my $val2 = int(rand(100)) + 1;
   
    &mkDir("$path/ar_p_ifc_ifcp_connect_valid");
    open(FH,">$path/ar_p_ifc_ifcp_connect_valid/$test_name");
    
    print FH "//Generated by Petronela\n\n";
    print FH "//conections port to ifc.ifc.port, signal to ifc.ifc.port, ifc.ifc.port to port and ifc.ifc.port to signal\n\n";
    print FH "csl_bitrange br($val1);\n";
    print FH "csl_bitrange brt($val2);\n";
    print FH "csl_interface ifca {\n";
    if($i <= 5 || ($i > 20 && $i <= 25) ) {
        print FH "  csl_port p_ifca$i(input,$val1);\n";
        print FH "  csl_port p_ifa(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_ifca$i(output,$val2);\n";
        print FH "  csl_port p_ifa(output,$val2);\n";
        print FH "  csl_port p_if(output,$val2);\n";
    }
    elsif($i > 10 ) { 
        print FH "  csl_port p_ifca$i(input,$val1);\n";
        print FH "  csl_port p_ifa(input,$val1);\n";
        print FH "  csl_port p_if(input,$val1);\n";
        print FH "  csl_port p_ifta$i(input,$val1);\n";
    }
    print FH "  ifca() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";

    print FH "csl_interface ifcb {\n";
    print FH "  ifca ifca0;\n";
    if($i <= 5 || ($i > 20 && $i <= 25)) {
        print FH "  csl_port p_ifcb$i(input,$val1);\n";
        print FH "  csl_port p_ifb(input,$val1);\n";
        print FH "  csl_port p_if(output,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_ifcb$i(output,$val2);\n";
        print FH "  csl_port p_ifb(output,$val2);\n";
        
    }
    elsif($i > 10) {  
        print FH "  csl_port p_ifcb$i(input,$val1);\n";
        print FH "  csl_port p_ifb(input,$val1);\n";
        print FH "  csl_port p_if(input,$val1);\n";
        print FH "  csl_port p_iftb$i(input,$val1);\n";
        print FH "  csl_port p_b(input,$val1);\n";
    }
    print FH "  ifcb() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_interface ifcd {\n";
    print FH "  ifcb ifcb0;\n";
    if($i <= 5 || ($i > 20 && $i <= 25)) {
        print FH "  csl_port p_ifcd$i(input,$val1);\n";
        print FH "  csl_port p_ifd(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_ifcd$i(output,$val2);\n";
        print FH "  csl_port p_ifd(output,$val2);\n";
        print FH "  csl_port p_if(output,$val1);\n";
        print FH "  csl_port p_iftd$i(output,$val1);\n";    
    }
    elsif($i > 10) {  
        print FH "  csl_port p_ifcd$i(input,$val1);\n";
        print FH "  csl_port p_ifd(input,$val1);\n";
        print FH "  csl_port p_d(input,$val1);\n";
        print FH "  csl_port p_if(input,$val1);\n";
    }
    print FH "  ifcd() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit a {\n";
    print FH "  ifcb ifcb0;\n";
    print FH "  ifcd ifcd0;\n";
    if($i <= 5  || ($i > 25 && $i <= 30)) {
        print FH "  csl_port p_a$i(input,$val1);\n"; 
        print FH "  csl_port pa(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal s_a$i($val1);\n";
        print FH "  csl_signal sa($val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_a$i(output,$val2);\n"; 
        print FH "  csl_port pa(output,$val2);\n";
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_signal s_a$i($val2);\n";
        print FH "  csl_signal sa($val2);\n";
    }
    elsif($i > 10 && $i <= 25) {
        print FH "  csl_port p_a$i(input,$val1);\n"; 
        print FH "  csl_port p_a_br$i(input,br);\n";
        print FH "  csl_port pa(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal s_a$i($val1);\n";
    }
    print FH "  a() {\n";
    if($i <= 2) {
        print FH "    $it1.connect(ifcb0.ifca0.$it2);\n";
    }
    elsif($i > 2 && $i <= 5) {
        print FH "    $it1.connect(ifcd0.ifcb0.$it2);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    ifcb0.ifca0.p_ifa.connect(pa);\n";
        print FH "    ifcd0.ifcb0.p_ifcb$i.connect(p);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    ifcb0.ifca0.p_ifta$i.connect(p_a_br$i);\n";
        print FH "    ifcb0.ifca0.p_if.connect(p_a$i);\n";
        print FH "    ifcd0.ifcb0.p_if.connect(pa);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    print FH "csl_unit b {\n";  
    print FH "  ifcb ifcb0;\n";
    print FH "  ifcd ifcd0;\n";
    if($i <= 5) {
        print FH "  csl_port p_b$i(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal s_b$i($val1);\n";
        print FH "  csl_signal sb($val1);\n";
    }
    elsif(($i > 5 && $i <= 10) || ($i > 20 && $i <= 25) ) {      
        print FH "  csl_port p_b$i(output,$val2);\n";
        print FH "  csl_port pb(output,$val2);\n";
        print FH "  csl_port p_b_br$i(output,brt);\n";
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_signal s_b_br$i(brt);\n";
        print FH "  csl_signal s_b$i($val2);\n";
    }
    elsif($i > 10) {      
        print FH "  csl_port p_b$i(input,$val1);\n";
        print FH "  csl_port p_b_br$i(input,br);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal sb($val1);\n";
        print FH "  csl_signal s_b_br$i(br);\n";
    }
    print FH "  b() {\n";
    if($i <= 5){
        print FH "    ifcd0.ifcb0.p_ifb.connect(p);\n";
        print FH "    ifcb0.ifca0.p_ifca$i.connect(p);\n";
    }
    elsif($i > 5 && $i <= 7) {
        print FH "    $it1.connect(ifcb0.ifca0.$it2);\n";
    }
    elsif($i > 7 && $i <=10) {
        print FH "    $it1.connect(ifcd0.ifcb0.$it2);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    ifcb0.ifca0.p_ifta$i.connect(p_b$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";  
    print FH "  ifcb ifcb0;\n";
    print FH "  ifcd ifcd0;\n";
    if($i <= 5 || $i > 20 && $i <= 25 ) {
        print FH "  csl_port p_c$i(input,$val1);\n";
        print FH "  csl_port pc(input,$val1);\n";
        print FH "  csl_port p_c_br$i(input,br);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal sc($val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_port p_c$i(output,$val2);\n";
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_signal sc($val2);\n";
        print FH "  csl_signal s_c$i($val2);\n";
        print FH "  csl_signal s_c_br$i(brt);\n";
    }
    elsif($i > 10 && $i <= 20) {      
        print FH "  csl_port pc(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port p_c_br$i(input,br);\n";
        print FH "  csl_signal s_c$i($val1);\n";
        print FH "  csl_signal s($val1);\n";
        print FH "  csl_signal sc($val1);\n";
    }
    print FH "  c() {\n";
    if($i <= 5){
        print FH "    ifcb0.ifca0.p_ifca$i.connect(pc);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    ifcd0.ifcb0.p_ifb.connect(p_c$i);\n";
        print FH "    ifcb0.ifca0.p_ifca$i.connect(p);\n";
    }
    elsif($i > 10 && $i <= 12) {
        print FH "    $it1.connect(ifcb0.ifca0.$it2);\n";
    }
    elsif($i > 12 && $i <= 15) {
        print FH "    $it1.connect(ifcd0.ifcb0.$it2);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n"; 
    print FH "  ifcb ifcb1;\n";
    print FH "  ifcd ifcd1;\n";
    if($i <= 5 || ($i > 25 && $i <= 30)) {
        print FH "  csl_port p_d$i(input,$val1);\n"; 
        print FH "  csl_port p_d_br$i(input,br);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal s_d$i($val1);\n";
        print FH "  csl_signal sd($val1);\n";
    }
    elsif($i > 5 && $i <= 10  ) {      
        print FH "  csl_port p_d$i(output,$val2);\n";
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port pd(output,$val2);\n";
        print FH "  csl_signal s_d$i($val2);\n";
        print FH "  csl_signal s_d_br$i($val2);\n";
    }
    elsif($i > 10 && $i <= 25) {      
       print FH "  csl_port p_d$i(input,$val1);\n";
       print FH "  csl_port p(input,$val1);\n";
       print FH "  csl_signal s_d$i($val1);\n";
       print FH "  csl_signal s_d_br$i($val1);\n";
    }
    print FH "  d() {\n";
    if($i <= 2) {
        print FH "    a0.p_a$i.connect(ifcb1.ifca0.$it2);\n";
        print FH "    c0.pc.connect(ifcd1.ifcb0.p_ifb);\n";
        print FH "    b0.sb.connect(ifcb1.ifca0.p_ifca$i);\n";
        print FH "    sd.connect(a0.ifcd0.ifcb0.p_ifcb$i);\n"
    }
    elsif($i >2 && $i <= 5) {
        print FH "    p_d$i.connect(ifcd1.ifcb0.$it2);\n";
        print FH "    s_d$i.connect(b0.ifcb0.ifca0.p_ifa);\n";
        print FH "    c0.ifcd0.ifcb0.p_ifb.connect(sd);\n";
        print FH "    a0.ifcb0.ifca0.p_ifca$i.connect(sd);\n";
    }
    elsif($i > 5 && $i <= 7) {
        print FH "    p_d$i.connect(a0.p_a$i);\n";
        print FH "    p.connect(b0.p_b$i);\n";
        print FH "    s_d$i.connect(c0.ifcb0.ifca0.p_ifca$i);\n";
        print FH "    c0.ifcd0.ifcb0.p_ifcb$i.connect(s_d_br$i);\n";
    }
    elsif($i > 7 && $i <= 10) {
        print FH "    p_d$i.connect(ifcd1.ifcb0.$it2);\n";
        print FH "    ifcb1.ifca0.p_ifa.connect(p_d$i);\n";
        print FH "    s_d_br$i.connect(a0.ifcb0.ifca0.p_ifa);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    p_d$i.connect(ifcd1.ifcb0.p_ifb);\n";
        print FH "    s_d$i.connect(b0.ifcd0.ifcb0.p_b);\n";
    }
    elsif($i > 15 && $i <= 17){
        print FH "    $it1.connect(ifcb1.ifca0.$it2);\n";
        print Fh "    p_d$i.connect(ifcd1.ifcb1.p_ifb);\n";
        print FH "    ifcd1.ifcb0.p_ifb.connect(s_b_br$i);\n";
    }
     elsif($i > 17 && $i <= 20){
        print FH "    $it1.connect(ifcd1.ifcb0.$it2);\n";
        print FH "    b0.p_b$i.connect(ifcb1.ifca0.p_if);\n";
        print FH "    s_d$i.connect(a0.ifcb0.ifca0.p_if);\n"
    }
    
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    

    print FH "csl_unit e {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n";
    print FH "  ifcb ifcb2;\n";
    print FH "  ifcd ifcd2;\n";
    if($i <= 5) {
        print FH "  csl_port p_e$i(input,$val1);\n"; 
        print FH "  csl_port p_e_br$i(input,br);\n";   
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal s_e$i($val1);\n";
        print FH "  csl_signal s_e_br(br);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_port p_e$i(output,$val2);\n";    
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port p_e_br$i(output,brt);\n";  
        print FH "  csl_signal se($val2);\n";
    }
    elsif($i > 10 && $i <= 30) {      
        print FH "  csl_port p_e$i(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port pe(input,$val1);\n";
        print FH "  csl_signal s_e_br$i(br);\n";
        print FH "  csl_signal se($val1);\n";
    }
    print FH "  e() {\n";
    if($i <= 5) {
        print FH "    p_e_br$i.connect(ifcb2.ifca0.p_ifa);\n";
        print FH "    a0.sa.connect(ifcb2.ifca0.p_ifca$i);\n"; 
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    p_e$i.connect(ifcb2.ifca0.p_ifca$i);\n";
        print FH "    se.connect(c0.ifcd0.ifcb0.p_ifb);\n";
        print FH "    b0.s_b_br$i.connect(ifcd2.ifcb0.p_ifcb$i);\n";
    }
    elsif($i > 10 && $i <= 20) {
        print FH "    ifcb2.ifca0.p_ifca$i.connect(a0.p_a_br$i);\n";
        print FH "    s_e_br$i.connect(b0.ifcb0.ifca0.p_ifa);\n";
    }
    elsif($i > 20 && $i <= 22) {
        print FH "    $it1.connect(ifcb2.ifca0.$it2);\n";
        print FH "    c0.ifcd0.ifcb0.p_ifb.connect(se);\n";
    }
    elsif($i > 22 && $i <= 25) {
        print FH "    $it1.connect(ifcd2.ifcb0.$it2);\n";
        print FH "    se.connect(a0.ifcb0.ifca0.p_ifca$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    print FH "  d d0;\n";
    print FH "  e e0;\n"; 
    print FH "  ifcb ifcb3;\n";
    print FH "  ifcd ifcd3;\n";
    if($i <= 5) {
        print FH "  csl_port ptop(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal s_top$i($val1);\n";
        print FH "  csl_signal stop($val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_top$i(output,$val2);\n";      
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port ptop(output,$val2);\n"; 
        print FH "  csl_signal st($val2);\n";
        print FH "  csl_signal s_top_br$i(brt);\n";
    }
    elsif($i > 10 && $i <= 30) {
        print FH "  csl_port p_top$i(input,$val1);\n";      
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port p_top_br$i(input,br);\n";
        print FH "  csl_signal s_top$i($val1);\n";
        print FH "  csl_signal stop($val1);\n";
    }
    
    print FH "  top(){\n";
    if($i <= 5) {
        print FH "    ifcb3.ifca0.p_ifca$i.connect(d0.a0.p_a$i);\n";
        print FH "    p.connect(ifcb3.ifca0.p_ifca$i);\n";
        print FH "    s_top$i.connect(d0.ifcb1.ifca0.p_ifca$i);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    ifcd3.ifcb0.p_ifcb$i.connect(e0.a0.p_a$i);\n";
        print FH "    ptop.connect(ifcb3.ifca0.p_ifa);\n";
        print FH "    e0.ifcd2.ifcb0.p_ifb.connect(st);\n";
        print FH "    s_top_br$i.connect(d0.b0.ifcd0.ifcb0.p_ifcb$i);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    p_top_br$i.connect(ifcb3.ifca0.p_ifta$i);\n";
        print FH "    ifcd3.ifcb0.p_iftb$i.connect(p);\n";
        print FH "    s_top$i.connect(e0.c0.ifcb0.ifca0.p_if);\n";
    }
    elsif($i > 25 && $i <= 27) {
        print FH "    $it1.connect(ifcb3.ifca0.$it2);\n";
        print FH "    d0.a0.p_a$i.connect(ifcb3.ifca0.$it2);\n";
        print FH "    stop.connect(e0.b0.ifcd0.ifcb0.p_ifcb$i);\n";
        print FH "    s_top$i.connect(e0.c0.ifcb0.ifca0.p_if);\n";
    }
    elsif($i > 27) {
        print FH "    $it1.connect(ifcd3.ifcb0.$it2);\n";
        print FH "    e0.b0.p.connect(ifcb3.ifca0.p_if);\n";
        print FH "    ifcb3.ifca0.p_ifa.connect(s_top$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);
}
