#!/usr/bin/perl

#Author Petronela
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

my @lower = (0,4,8,16,28);
my @upper = (43,55,63,77,93);

for (my $i = 1; $i <= 5; ++$i ) {
    foreach my $l(@lower) {
        foreach my $u(@upper) { 
            &main($i,$l,$u);
        }
    }
}

sub main {
    my ($i,$l, $u) = @_;
    my $test_name = "connect_replication_connect$i"."_".$l."_".$u."_illegal.csl";
    &createCslFile($test_name,$i, $l, $u);
}

sub createCslFile {
    my($test_name, $i,$l, $u) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
    my $w = $u - $l + 1;
    my $val = int(rand(20)) + 1;
    my $val12 = 2 * $val;
    my $val13 = 3 * $val;
    my $val14 = 4 * $val;
    my $val15 = 5 * $val;
    my $val16 = 6 * $val; 
   
    my $val2 = $w/2;
    my $val3 = 0;
    if($w % 3 == 0) {
        $val3 = $w/3;
    }
    my $val4 = 0;
    if($w % 4 == 0) {
        $val4 = $w/4;
    }
    my $val8 = $u + int(rand(50)) + 1;  
    my $val9 = $u + int(rand(50)) + 1;
    &mkDir("$path/ar_replication_connect_invalid");
    open(FH,">$path/ar_replication_connect_invalid/$test_name");

    print FH "//Generated by Petronela\n\n";
    print FH "csl_bitrange br($val);\n";
    print FH "csl_bitrange brt($val16);\n";
    print FH "csl_unit a {\n";
    if($i <= 2) {
        print FH "  csl_port p_a$i(input,$val);\n"; 
        print FH "  csl_port pa(input,$val2);\n";
        print FH "  csl_port p_a_br$i(input,br);\n";
        print FH "  csl_port p(input,$val);\n";
        print FH "  csl_signal sa($val2);\n";
        if($val4 != 0) {
            print FH "  csl_signal s_a$i($val4);\n";
        }
        else {
            print FH "  csl_signal s_a$i($val2);\n";
        }
    }
    elsif($i > 2 && $i <= 4) {
        print FH "  csl_port p_a$i(output,$val);\n"; 
        if($val3 != 0 ) {
            print FH "  csl_port pa(input,$val3);\n";
        }
        elsif($val4 != 0) {
            print FH "  csl_port pa(input,$val4);\n";
        }
        else {
             print FH "  csl_port pa(input,$val2);\n";
        }
        print FH "  csl_port p(output,$val2);\n";
        if($val4 != 0) {
            print FH "  csl_signal s_a$i($val4);\n";
        }
        else {
            print FH "  csl_signal s_a$i($val2);\n";
        }
        print FH "  csl_signal sa($val2);\n";
    }
    elsif($i > 4) {
        print FH "  csl_port p_a$i(input,$val8);\n"; 
        print FH "  csl_port p_a_br$i(input,brt);\n";
        print FH "  csl_port pa(input,$val2);\n";
        print FH "  csl_port p(input,$val9);\n";
        print FH "  csl_signal s_a$i($val);\n";
        print FH "  csl_signal sa($val2);\n";
    }
    print FH "  a() {\n";                
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    print FH "csl_unit b {\n";  
    if($i == 1) {
        print FH "  csl_port p_b$i(input,$val);\n";
        print FH "  csl_port p(input,$val12);\n";
        print FH "  csl_port pb(input,$val8);\n";
        print FH "  csl_signal s_b_br$i(br);\n";
        print FH "  csl_signal s_b$i($val);\n";
        print FH "  csl_signal sb($val2);\n";
    }
    elsif($i > 1 && $i <= 3) {      
        print FH "  csl_port p_b$i(output,$val2);\n";
        print FH "  csl_port pb(output,$val12);\n";
        print FH "  csl_port p_b_br$i(output,br);\n";
        print FH "  csl_port p(output,$val8);\n";
        print FH "  csl_signal s_b$i($w);\n";
        
    }
    elsif($i > 3) {      
        print FH "  csl_port p_b$i(output,$val8);\n";
        print FH "  csl_port p_b_br$i(input,brt);\n";
        print FH "  csl_port p(input,$val8);\n";
        print FH "  csl_port pb(input,$val2);\n";
        print FH "  csl_signal s_b$i($val2);\n";
        print FH "  csl_signal s_b_br$i(br);\n";
        print FH "  csl_signal sb($val9);\n";
    }
    print FH "  b() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";  
    if($i <= 3) {
        print FH "  csl_port p_c$i(input,$val);\n";
        print FH "  csl_port pc(input,$val2);\n";
        print FH "  csl_port p_c_br$i(output,brt);\n";
        print FH "  csl_port p(input,$val);\n";
        print FH "  csl_signal s_c$i($val);\n";
        print FH "  csl_signal sc($val8);\n";
    }
    elsif($i == 4) {      
        print FH "  csl_port p_c$i(output,$val2);\n";
        print FH "  csl_port p(output,$val12);\n";
        print FH "  csl_port pc(input,$val12);\n";
        print FH "  csl_signal sc($val3);\n";
        print FH "  csl_signal s_c_br$i(brt);\n";
        print FH "  csl_signal s_c$i($val2);\n";
    }
    elsif($i == 5) {      
        print FH "  csl_port pc(input,$val12);\n";
        print FH "  csl_port p(input,$val12);\n";
        print FH "  csl_port p_c_br$i(input,brt);\n";
        print FH "  csl_signal s_c$i($val8);\n";
        print FH "  csl_signal sc($val2);\n";
    }
    print FH "  c() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n"; 
    if($i <= 2) {
        print FH "  csl_port p_d$i(input,$val15);\n"; 
        print FH "  csl_port p_d_br$i(input,brt);\n";
        print FH "  csl_port p(input,$val8);\n";
        print FH "  csl_signal s_d_br$i($w);\n";
        print FH "  csl_signal s_d$i($w);\n";
    }
    elsif($i > 2 && $i <= 4) {      
        print FH "  csl_port p_d$i(output,$val);\n";
        if($val3 != 0) {
            print FH "  csl_port p(output,$val3);\n";
        }
        elsif($val4 != 0) {
            print FH "  csl_port p(output,$val4);\n"
        }
        else {
            print FH "  csl_port p(output,$val2);\n"
        }
        print FH "  csl_port pd(output,$val8);\n";
        print FH "  csl_signal s_d$i($val9);\n";
    }
    elsif($i > 4) {      
      print FH "  csl_port p_d$i(input,$val);\n";
      print FH "  csl_port p(input,$val2);\n";
      if($val4 != 0) {  
          print FH "  csl_signal s_d$i($val4);\n";
          print FH "  csl_signal s_d_br$i($val4);\n";
      }
      else {
          print FH "  csl_signal s_d$i($val2);\n";
          print FH "  csl_signal s_d_br$i($val2);\n"; 
      }
      print FH "  csl_signal sd($val14);\n";
    }
    print FH "  d() {\n";
    if($i <= 2) {
        print FH "    {5{a0.p_a$i}}.connect(p_d$i);\n";
        print FH "    {3{a0.p,a0.p_a_br$i}}.connect(p_d_br$i);\n";
        print FH "    {2{c0.p_c$i}}.connect(p[$l:$u]);\n";
    }
    elsif($i > 2 && $i <= 4) {
        if($val3 != 0){
            print FH "    {3{a0.pa}}.connect(s_d$i"."[$l:$u]);\n";   
            print FH "    {3{p}}.connect(b0.p".$i."[$l:$u]);\n";
        }
        elsif($val4 != 0) {
            print FH "    {4{a0.pa}}.connect(s_d$i"."[$l:$u]);\n";   
            print FH "    {4{p}}.connect(b0.p".$i."[$l:$u]);\n";
        }
        else {
            print FH "    {2{a0.pa}}.connect(s_d$i"."[$l:$u]);\n";
            print FH "    {2{p}}.connect(b0.p".$i."[$l:$u]);\n";
        }
        print FH "    {2{a0.sa}}.connect(pd[$l:$u]);\n";
    }
    elsif($i > 4) {
        print FH "    {2{c0.pc}}.connect(sd);\n";
        if($val4 != 0) {
            print FH "    {2{s_d_br$i,s_d$i}}.connect(b0.p[$l:$u]);\n";
        }
        else {  
            print FH "    {2{s_d_br$i}}.connect(b0.p[$l:$u]);\n";
        }
    }
    
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    

    print FH "csl_unit e {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n";
    if($i == 1 ) {
        print FH "  csl_port p_e$i(input,$val9);\n"; 
        print FH "  csl_port p_e_br$i(input,brt);\n";   
        print FH "  csl_port p(input,$val2);\n";
        print FH "  csl_signal s_e$i($val8);\n";
        if($val4 != 0) {
            print FH "  csl_signal se($val4);\n";
            print FH "  csl_signal s($val4);\n";
        }
        else {
            print FH "  csl_signal se($val2);\n";
            print FH "  csl_signal s($val2);\n";
        }
        print FH "  csl_signal s_e_br$i(brt);\n";
        
    }
    elsif($i > 1 && $i <= 3) {      
        print FH "  csl_port p_e$i(output,$val9);\n";    
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port p_e_br$i(output,brt);\n";
        print FH "  csl_signal s_e$i($val8);\n";
        print FH "  csl_signal s_e_br$i($val12);\n";
    }
    elsif($i > 3) {      
        print FH "  csl_port p_e$i(input,$val);\n";
        print FH "  csl_port p(input,$val8);\n";
        print FH "  csl_port pe(input,$val);\n";
        print FH "  csl_signal se($val15);\n";
    }
    print FH "  e() {\n";
    if($i == 1) {
        print FH "    {2{b0.p_b$i,b0.p}}.connect(s_e_br$i);\n";
        print FH "    {2{b0.sb}}.connect(p_e$i"."[$l:$u]);\n";
        if($val4 != 0){
            print FH "    {2{se,s}}.connect(b0.pb[$l:$u]);\n";
        }
        else {  
            print FH "    {2{se}}.connect(b0.pb[$l:$u]);\n";
        }
    }
    elsif($i > 1 && $i <= 3) {
        if($val4 != 0) {
            print FH "    {4{a0.s_a$i}}.connect(p_e$i"."[$l:$u]);\n";
        }
        else {
            print FH "    {2{a0.s_a$i}}.connect(p_e$i"."[$l:$u]);\n";
        }
        print FH "    {2{b0.p_b$i}}.connect(s_e$i"."[$l:$u]);\n";
    }
    elsif($i > 3) {
        print FH "    {2{b0.pb}}.connect(p[$l:$u]);\n";
        print FH "    {5{b0.p_b$i}}.connect(se);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    print FH "  d d0;\n";
    print FH "  e e0;\n"; 
    if($i <= 2) {
        print FH "  csl_port ptop(input,$val8);\n";
        print FH "  csl_port p(input,$val2);\n";
        print FH "  csl_signal s_top$i($val16);\n";
        print FH "  csl_signal stop($val14);\n";
    }
    elsif($i == 3) {
        print FH "  csl_port p_top$i(output,$val3);\n";      
        print FH "  csl_port p(output,$val9);\n";
        print FH "  csl_port ptop(output,$val8);\n"; 
        print FH "  csl_signal stop($val14);\n";
        print FH "  csl_signal s_top$i($val14);\n";
    }
    elsif($i > 3) {
        print FH "  csl_port p_top$i(input,$val2);\n";      
        print FH "  csl_port p(input,$val8);\n";
        print FH "  csl_port ptop(input,$val9);\n";
        print FH "  csl_signal s_top$i($w);\n";
        print FH "  csl_signal s_top_br$i(brt);\n";
        print FH "  csl_signal stop($w);\n";
    }
    
    print FH "  top(){\n";
    if($i <= 2) {
        print FH "    {2{a0.p_a_br$i,a0.p}}.connect(stop);\n";
        print FH "    {2{c0.p_c$i,c0.pc,c0.p}}.connect(s_top$i);\n";
        print FH "    {2{a0.sa}}.connect(d0.p"."[$l:$u]);\n";
    }
    elsif($i == 3) {
        print FH "    {4{a0.p_a$i}}.connect(s_top$i);\n";
        print FH "    {2{b0.pb}}.connect(stop);\n";
        print FH "    {2{a0.sa}}.connect(p[$l:$u]);\n";
    }
    elsif($i > 3) {
        print FH "    {2{e0.p_e$i,pe}}.connect(s_top_br$i);\n";
        print FH "    {4{p_d$i}}.connect(s_top_br$i);\n";
        print FH "    {2{p_top$i}}.connect(d0.b0.p_b$i"."[$l:$u]);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}
