#ifndef ETREECOLORING_H
#define ETREECOLORING_H

enum ETreeColorUnitFloorPlanning{
    ETREE_COLOR_UNIT_FLOORPLANNING_NORMAL             ,
    ETREE_COLOR_UNIT_FLOORPLANNING_DIVISION_POINT  // dividing point between top and bottom netlist
} ;

enum ETreeColorUnitLibraries {
    ETREE_COLOR_UNIT_LIBRARIES_NORMAL        ,
    ETREE_COLOR_UNIT_LIBRARIES_ASIC_LIBRARIES,
    ETREE_COLOR_UNIT_LIBRARIES_FPGA_LIBRARIES
} ;

enum ETreeColorConnectivity{
    ETREE_COLOR_CONNECTIVITY_NORMAL          ,
    ETREE_COLOR_CONNECTIVITY_ASIC_POWER_RAILS,
    ETREE_COLOR_CONNECTIVITY_FPGA_POWER_RAILS
} ;

#endif // ETREECOLORING_H
