`ifndef INC_GUARD_c
`define INC_GUARD_c

`define P_RESET_UPPER_INDEX  (0)
`define P_RESET_LOWER_INDEX  (0)
`define P_RESET_WIDTH  (0-0+1)
`define P_RESET_RANGE `P_RESET_UPPER_INDEX:`P_RESET_LOWER_INDEX
`define P_CK_PORT_UPPER_INDEX  (1-1)
`define P_CK_PORT_LOWER_INDEX  (0)
`define P_CK_PORT_WIDTH  (1)
`define P_CK_PORT_RANGE `P_CK_PORT_UPPER_INDEX:`P_CK_PORT_LOWER_INDEX

`endif
