`ifndef INC_GUARD_utop
`define INC_GUARD_utop

`define P_RST_UPPER_INDEX  (0)
`define P_RST_LOWER_INDEX  (0)
`define P_RST_WIDTH  (0-0+1)
`define P_RST_RANGE `P_RST_UPPER_INDEX:`P_RST_LOWER_INDEX
`define P_CLK_UPPER_INDEX  (0)
`define P_CLK_LOWER_INDEX  (0)
`define P_CLK_WIDTH  (0-0+1)
`define P_CLK_RANGE `P_CLK_UPPER_INDEX:`P_CLK_LOWER_INDEX
`define P_TIN1_UPPER_INDEX  (8-1)
`define P_TIN1_LOWER_INDEX  (0)
`define P_TIN1_WIDTH  (8)
`define P_TIN1_RANGE `P_TIN1_UPPER_INDEX:`P_TIN1_LOWER_INDEX
`define P_TIN2_UPPER_INDEX  (8-1)
`define P_TIN2_LOWER_INDEX  (0)
`define P_TIN2_WIDTH  (8)
`define P_TIN2_RANGE `P_TIN2_UPPER_INDEX:`P_TIN2_LOWER_INDEX
`define P_TOUT1_UPPER_INDEX  (36-1)
`define P_TOUT1_LOWER_INDEX  (0)
`define P_TOUT1_WIDTH  (36)
`define P_TOUT1_RANGE `P_TOUT1_UPPER_INDEX:`P_TOUT1_LOWER_INDEX
`define IFC_IFC11_I3_P_PIN_UPPER_INDEX  (8-1)
`define IFC_IFC11_I3_P_PIN_LOWER_INDEX  (0)
`define IFC_IFC11_I3_P_PIN_WIDTH  (8)
`define IFC_IFC11_I3_P_PIN_RANGE `IFC_IFC11_I3_P_PIN_UPPER_INDEX:`IFC_IFC11_I3_P_PIN_LOWER_INDEX
`define IFC_IFC11_I3_P_POUT_UPPER_INDEX  (8-1)
`define IFC_IFC11_I3_P_POUT_LOWER_INDEX  (0)
`define IFC_IFC11_I3_P_POUT_WIDTH  (8)
`define IFC_IFC11_I3_P_POUT_RANGE `IFC_IFC11_I3_P_POUT_UPPER_INDEX:`IFC_IFC11_I3_P_POUT_LOWER_INDEX
`define IFC_IFC12_I3_P_PIN_UPPER_INDEX  (8-1)
`define IFC_IFC12_I3_P_PIN_LOWER_INDEX  (0)
`define IFC_IFC12_I3_P_PIN_WIDTH  (8)
`define IFC_IFC12_I3_P_PIN_RANGE `IFC_IFC12_I3_P_PIN_UPPER_INDEX:`IFC_IFC12_I3_P_PIN_LOWER_INDEX
`define IFC_IFC12_I3_P_POUT1_UPPER_INDEX  (8-1)
`define IFC_IFC12_I3_P_POUT1_LOWER_INDEX  (0)
`define IFC_IFC12_I3_P_POUT1_WIDTH  (8)
`define IFC_IFC12_I3_P_POUT1_RANGE `IFC_IFC12_I3_P_POUT1_UPPER_INDEX:`IFC_IFC12_I3_P_POUT1_LOWER_INDEX
`define IFC_IFC12_I3_P_POUT2_UPPER_INDEX  (8-1)
`define IFC_IFC12_I3_P_POUT2_LOWER_INDEX  (0)
`define IFC_IFC12_I3_P_POUT2_WIDTH  (8)
`define IFC_IFC12_I3_P_POUT2_RANGE `IFC_IFC12_I3_P_POUT2_UPPER_INDEX:`IFC_IFC12_I3_P_POUT2_LOWER_INDEX

`endif
