`ifndef INC_GUARD_a2p
`define INC_GUARD_a2p

`define IFC_A2RTAP_MASTER_IFC_P_ADDRESS_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_MASTER_IFC_P_ADDRESS_LOWER_INDEX  (0)
`define IFC_A2RTAP_MASTER_IFC_P_ADDRESS_WIDTH  (1)
`define IFC_A2RTAP_MASTER_IFC_P_ADDRESS_RANGE `IFC_A2RTAP_MASTER_IFC_P_ADDRESS_UPPER_INDEX:`IFC_A2RTAP_MASTER_IFC_P_ADDRESS_LOWER_INDEX
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_DATA_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_DATA_LOWER_INDEX  (0)
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_DATA_WIDTH  (1)
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_DATA_RANGE `IFC_A2RTAP_MASTER_IFC_P_WRITE_DATA_UPPER_INDEX:`IFC_A2RTAP_MASTER_IFC_P_WRITE_DATA_LOWER_INDEX
`define IFC_A2RTAP_MASTER_IFC_P_READ_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_MASTER_IFC_P_READ_LOWER_INDEX  (0)
`define IFC_A2RTAP_MASTER_IFC_P_READ_WIDTH  (1)
`define IFC_A2RTAP_MASTER_IFC_P_READ_RANGE `IFC_A2RTAP_MASTER_IFC_P_READ_UPPER_INDEX:`IFC_A2RTAP_MASTER_IFC_P_READ_LOWER_INDEX
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_LOWER_INDEX  (0)
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_WIDTH  (1)
`define IFC_A2RTAP_MASTER_IFC_P_WRITE_RANGE `IFC_A2RTAP_MASTER_IFC_P_WRITE_UPPER_INDEX:`IFC_A2RTAP_MASTER_IFC_P_WRITE_LOWER_INDEX
`define IFC_A2RTAP_MASTER_IFC_P_READ_DATA_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_MASTER_IFC_P_READ_DATA_LOWER_INDEX  (0)
`define IFC_A2RTAP_MASTER_IFC_P_READ_DATA_WIDTH  (1)
`define IFC_A2RTAP_MASTER_IFC_P_READ_DATA_RANGE `IFC_A2RTAP_MASTER_IFC_P_READ_DATA_UPPER_INDEX:`IFC_A2RTAP_MASTER_IFC_P_READ_DATA_LOWER_INDEX
`define IFC_A2RTAP_MASTER_IFC_P_READY_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_MASTER_IFC_P_READY_LOWER_INDEX  (0)
`define IFC_A2RTAP_MASTER_IFC_P_READY_WIDTH  (1)
`define IFC_A2RTAP_MASTER_IFC_P_READY_RANGE `IFC_A2RTAP_MASTER_IFC_P_READY_UPPER_INDEX:`IFC_A2RTAP_MASTER_IFC_P_READY_LOWER_INDEX
`define IFC_A2RTAP_MASTER_IFC_P_ERROR_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_MASTER_IFC_P_ERROR_LOWER_INDEX  (0)
`define IFC_A2RTAP_MASTER_IFC_P_ERROR_WIDTH  (1)
`define IFC_A2RTAP_MASTER_IFC_P_ERROR_RANGE `IFC_A2RTAP_MASTER_IFC_P_ERROR_UPPER_INDEX:`IFC_A2RTAP_MASTER_IFC_P_ERROR_LOWER_INDEX
`define IFC_GBL_P_CLOCK_UPPER_INDEX  (1-1)
`define IFC_GBL_P_CLOCK_LOWER_INDEX  (0)
`define IFC_GBL_P_CLOCK_WIDTH  (1)
`define IFC_GBL_P_CLOCK_RANGE `IFC_GBL_P_CLOCK_UPPER_INDEX:`IFC_GBL_P_CLOCK_LOWER_INDEX
`define IFC_GBL_P_RESET_UPPER_INDEX  (1-1)
`define IFC_GBL_P_RESET_LOWER_INDEX  (0)
`define IFC_GBL_P_RESET_WIDTH  (1)
`define IFC_GBL_P_RESET_RANGE `IFC_GBL_P_RESET_UPPER_INDEX:`IFC_GBL_P_RESET_LOWER_INDEX
`define IFC_GBL_P_A2RTAP_PIPE_EN_UPPER_INDEX  (1-1)
`define IFC_GBL_P_A2RTAP_PIPE_EN_LOWER_INDEX  (0)
`define IFC_GBL_P_A2RTAP_PIPE_EN_WIDTH  (1)
`define IFC_GBL_P_A2RTAP_PIPE_EN_RANGE `IFC_GBL_P_A2RTAP_PIPE_EN_UPPER_INDEX:`IFC_GBL_P_A2RTAP_PIPE_EN_LOWER_INDEX

`endif
