`ifndef INC_GUARD_mcb
`define INC_GUARD_mcb

`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_DATA_UPPER_INDEX  (32-1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_DATA_LOWER_INDEX  (0)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_DATA_WIDTH  (32)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_DATA_RANGE `IFC_A2RTAP_SLAVE_IN_IFC_P_READ_DATA_UPPER_INDEX:`IFC_A2RTAP_SLAVE_IN_IFC_P_READ_DATA_LOWER_INDEX
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READY_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READY_LOWER_INDEX  (0)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READY_WIDTH  (1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READY_RANGE `IFC_A2RTAP_SLAVE_IN_IFC_P_READY_UPPER_INDEX:`IFC_A2RTAP_SLAVE_IN_IFC_P_READY_LOWER_INDEX
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ERROR_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ERROR_LOWER_INDEX  (0)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ERROR_WIDTH  (1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ERROR_RANGE `IFC_A2RTAP_SLAVE_IN_IFC_P_ERROR_UPPER_INDEX:`IFC_A2RTAP_SLAVE_IN_IFC_P_ERROR_LOWER_INDEX
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ADDRESS_UPPER_INDEX  (20-1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ADDRESS_LOWER_INDEX  (0)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ADDRESS_WIDTH  (20)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_ADDRESS_RANGE `IFC_A2RTAP_SLAVE_IN_IFC_P_ADDRESS_UPPER_INDEX:`IFC_A2RTAP_SLAVE_IN_IFC_P_ADDRESS_LOWER_INDEX
`define IFC_A2RTAP_SLAVE_IN_IFC_P_DATA_UPPER_INDEX  (32-1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_DATA_LOWER_INDEX  (0)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_DATA_WIDTH  (32)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_DATA_RANGE `IFC_A2RTAP_SLAVE_IN_IFC_P_DATA_UPPER_INDEX:`IFC_A2RTAP_SLAVE_IN_IFC_P_DATA_LOWER_INDEX
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_LOWER_INDEX  (0)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_WIDTH  (1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_READ_RANGE `IFC_A2RTAP_SLAVE_IN_IFC_P_READ_UPPER_INDEX:`IFC_A2RTAP_SLAVE_IN_IFC_P_READ_LOWER_INDEX
`define IFC_A2RTAP_SLAVE_IN_IFC_P_WRITE_UPPER_INDEX  (1-1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_WRITE_LOWER_INDEX  (0)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_WRITE_WIDTH  (1)
`define IFC_A2RTAP_SLAVE_IN_IFC_P_WRITE_RANGE `IFC_A2RTAP_SLAVE_IN_IFC_P_WRITE_UPPER_INDEX:`IFC_A2RTAP_SLAVE_IN_IFC_P_WRITE_LOWER_INDEX
`define IFC_MBC_IN_IFC_P_ADDRESS_UPPER_INDEX  (32-1)
`define IFC_MBC_IN_IFC_P_ADDRESS_LOWER_INDEX  (0)
`define IFC_MBC_IN_IFC_P_ADDRESS_WIDTH  (32)
`define IFC_MBC_IN_IFC_P_ADDRESS_RANGE `IFC_MBC_IN_IFC_P_ADDRESS_UPPER_INDEX:`IFC_MBC_IN_IFC_P_ADDRESS_LOWER_INDEX
`define IFC_MBC_IN_IFC_P_WRITE_DATA_UPPER_INDEX  (32-1)
`define IFC_MBC_IN_IFC_P_WRITE_DATA_LOWER_INDEX  (0)
`define IFC_MBC_IN_IFC_P_WRITE_DATA_WIDTH  (32)
`define IFC_MBC_IN_IFC_P_WRITE_DATA_RANGE `IFC_MBC_IN_IFC_P_WRITE_DATA_UPPER_INDEX:`IFC_MBC_IN_IFC_P_WRITE_DATA_LOWER_INDEX
`define IFC_MBC_IN_IFC_P_WRITE_UPPER_INDEX  (1-1)
`define IFC_MBC_IN_IFC_P_WRITE_LOWER_INDEX  (0)
`define IFC_MBC_IN_IFC_P_WRITE_WIDTH  (1)
`define IFC_MBC_IN_IFC_P_WRITE_RANGE `IFC_MBC_IN_IFC_P_WRITE_UPPER_INDEX:`IFC_MBC_IN_IFC_P_WRITE_LOWER_INDEX
`define IFC_MBC_IN_IFC_P_READ_UPPER_INDEX  (1-1)
`define IFC_MBC_IN_IFC_P_READ_LOWER_INDEX  (0)
`define IFC_MBC_IN_IFC_P_READ_WIDTH  (1)
`define IFC_MBC_IN_IFC_P_READ_RANGE `IFC_MBC_IN_IFC_P_READ_UPPER_INDEX:`IFC_MBC_IN_IFC_P_READ_LOWER_INDEX
`define IFC_MBC_IN_IFC_P_READ_DATA_UPPER_INDEX  (32-1)
`define IFC_MBC_IN_IFC_P_READ_DATA_LOWER_INDEX  (0)
`define IFC_MBC_IN_IFC_P_READ_DATA_WIDTH  (32)
`define IFC_MBC_IN_IFC_P_READ_DATA_RANGE `IFC_MBC_IN_IFC_P_READ_DATA_UPPER_INDEX:`IFC_MBC_IN_IFC_P_READ_DATA_LOWER_INDEX
`define IFC_MBC_IN_IFC_P_CONTROL_UPPER_INDEX  (32-1)
`define IFC_MBC_IN_IFC_P_CONTROL_LOWER_INDEX  (0)
`define IFC_MBC_IN_IFC_P_CONTROL_WIDTH  (32)
`define IFC_MBC_IN_IFC_P_CONTROL_RANGE `IFC_MBC_IN_IFC_P_CONTROL_UPPER_INDEX:`IFC_MBC_IN_IFC_P_CONTROL_LOWER_INDEX

`endif
