`ifndef INC_GUARD_rf
`define INC_GUARD_rf

`define IFC_IM_RF_IN_RFI_P_WR_ADDR_UPPER_INDEX  (4-1)
`define IFC_IM_RF_IN_RFI_P_WR_ADDR_LOWER_INDEX  (0)
`define IFC_IM_RF_IN_RFI_P_WR_ADDR_WIDTH  (4)
`define IFC_IM_RF_IN_RFI_P_WR_ADDR_RANGE `IFC_IM_RF_IN_RFI_P_WR_ADDR_UPPER_INDEX:`IFC_IM_RF_IN_RFI_P_WR_ADDR_LOWER_INDEX
`define IFC_IM_RF_IN_RFI_P_WR_EN_UPPER_INDEX  (1-1)
`define IFC_IM_RF_IN_RFI_P_WR_EN_LOWER_INDEX  (0)
`define IFC_IM_RF_IN_RFI_P_WR_EN_WIDTH  (1)
`define IFC_IM_RF_IN_RFI_P_WR_EN_RANGE `IFC_IM_RF_IN_RFI_P_WR_EN_UPPER_INDEX:`IFC_IM_RF_IN_RFI_P_WR_EN_LOWER_INDEX
`define IFC_IM_RF_IN_RFI_P_WR_DATA_UPPER_INDEX  (32-1)
`define IFC_IM_RF_IN_RFI_P_WR_DATA_LOWER_INDEX  (0)
`define IFC_IM_RF_IN_RFI_P_WR_DATA_WIDTH  (32)
`define IFC_IM_RF_IN_RFI_P_WR_DATA_RANGE `IFC_IM_RF_IN_RFI_P_WR_DATA_UPPER_INDEX:`IFC_IM_RF_IN_RFI_P_WR_DATA_LOWER_INDEX
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_A_UPPER_INDEX  (4-1)
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_A_LOWER_INDEX  (0)
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_A_WIDTH  (4)
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_A_RANGE `IFC_IM_RF_IN_RFI_P_RD_ADDR_A_UPPER_INDEX:`IFC_IM_RF_IN_RFI_P_RD_ADDR_A_LOWER_INDEX
`define IFC_IM_RF_IN_RFI_P_RD_EN_A_UPPER_INDEX  (1-1)
`define IFC_IM_RF_IN_RFI_P_RD_EN_A_LOWER_INDEX  (0)
`define IFC_IM_RF_IN_RFI_P_RD_EN_A_WIDTH  (1)
`define IFC_IM_RF_IN_RFI_P_RD_EN_A_RANGE `IFC_IM_RF_IN_RFI_P_RD_EN_A_UPPER_INDEX:`IFC_IM_RF_IN_RFI_P_RD_EN_A_LOWER_INDEX
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_B_UPPER_INDEX  (4-1)
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_B_LOWER_INDEX  (0)
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_B_WIDTH  (4)
`define IFC_IM_RF_IN_RFI_P_RD_ADDR_B_RANGE `IFC_IM_RF_IN_RFI_P_RD_ADDR_B_UPPER_INDEX:`IFC_IM_RF_IN_RFI_P_RD_ADDR_B_LOWER_INDEX
`define IFC_IM_RF_IN_RFI_P_RD_EN_B_UPPER_INDEX  (1-1)
`define IFC_IM_RF_IN_RFI_P_RD_EN_B_LOWER_INDEX  (0)
`define IFC_IM_RF_IN_RFI_P_RD_EN_B_WIDTH  (1)
`define IFC_IM_RF_IN_RFI_P_RD_EN_B_RANGE `IFC_IM_RF_IN_RFI_P_RD_EN_B_UPPER_INDEX:`IFC_IM_RF_IN_RFI_P_RD_EN_B_LOWER_INDEX
`define IFC_RF_EU_RFI_P_RD_DATA_A_UPPER_INDEX  (32-1)
`define IFC_RF_EU_RFI_P_RD_DATA_A_LOWER_INDEX  (0)
`define IFC_RF_EU_RFI_P_RD_DATA_A_WIDTH  (32)
`define IFC_RF_EU_RFI_P_RD_DATA_A_RANGE `IFC_RF_EU_RFI_P_RD_DATA_A_UPPER_INDEX:`IFC_RF_EU_RFI_P_RD_DATA_A_LOWER_INDEX
`define IFC_RF_EU_RFI_P_RD_DATA_B_UPPER_INDEX  (32-1)
`define IFC_RF_EU_RFI_P_RD_DATA_B_LOWER_INDEX  (0)
`define IFC_RF_EU_RFI_P_RD_DATA_B_WIDTH  (32)
`define IFC_RF_EU_RFI_P_RD_DATA_B_RANGE `IFC_RF_EU_RFI_P_RD_DATA_B_UPPER_INDEX:`IFC_RF_EU_RFI_P_RD_DATA_B_LOWER_INDEX
`define IFC_EU_RF_IN_P_RD_DATA_A_UPPER_INDEX  (32-1)
`define IFC_EU_RF_IN_P_RD_DATA_A_LOWER_INDEX  (0)
`define IFC_EU_RF_IN_P_RD_DATA_A_WIDTH  (32)
`define IFC_EU_RF_IN_P_RD_DATA_A_RANGE `IFC_EU_RF_IN_P_RD_DATA_A_UPPER_INDEX:`IFC_EU_RF_IN_P_RD_DATA_A_LOWER_INDEX
`define IFC_EU_RF_IN_P_RD_DATA_B_UPPER_INDEX  (32-1)
`define IFC_EU_RF_IN_P_RD_DATA_B_LOWER_INDEX  (0)
`define IFC_EU_RF_IN_P_RD_DATA_B_WIDTH  (32)
`define IFC_EU_RF_IN_P_RD_DATA_B_RANGE `IFC_EU_RF_IN_P_RD_DATA_B_UPPER_INDEX:`IFC_EU_RF_IN_P_RD_DATA_B_LOWER_INDEX
`define IFC_BR_IN_P_QUAL_BR_UPPER_INDEX  (1-1)
`define IFC_BR_IN_P_QUAL_BR_LOWER_INDEX  (0)
`define IFC_BR_IN_P_QUAL_BR_WIDTH  (1)
`define IFC_BR_IN_P_QUAL_BR_RANGE `IFC_BR_IN_P_QUAL_BR_UPPER_INDEX:`IFC_BR_IN_P_QUAL_BR_LOWER_INDEX

`endif
