`ifndef INC_GUARD_wb
`define INC_GUARD_wb

`define IFC_ME_CNTL_IN_P_V_UPPER_INDEX  (1-1)
`define IFC_ME_CNTL_IN_P_V_LOWER_INDEX  (0)
`define IFC_ME_CNTL_IN_P_V_WIDTH  (1)
`define IFC_ME_CNTL_IN_P_V_RANGE `IFC_ME_CNTL_IN_P_V_UPPER_INDEX:`IFC_ME_CNTL_IN_P_V_LOWER_INDEX
`define IFC_ME_CNTL_IN_P_PC_UPPER_INDEX  (8-1)
`define IFC_ME_CNTL_IN_P_PC_LOWER_INDEX  (0)
`define IFC_ME_CNTL_IN_P_PC_WIDTH  (8)
`define IFC_ME_CNTL_IN_P_PC_RANGE `IFC_ME_CNTL_IN_P_PC_UPPER_INDEX:`IFC_ME_CNTL_IN_P_PC_LOWER_INDEX
`define IFC_ME_CNTL_IN_P_NPC_UPPER_INDEX  (8-1)
`define IFC_ME_CNTL_IN_P_NPC_LOWER_INDEX  (0)
`define IFC_ME_CNTL_IN_P_NPC_WIDTH  (8)
`define IFC_ME_CNTL_IN_P_NPC_RANGE `IFC_ME_CNTL_IN_P_NPC_UPPER_INDEX:`IFC_ME_CNTL_IN_P_NPC_LOWER_INDEX
`define IFC_ME_CNTL_IN_P_IR_UPPER_INDEX  (32-1)
`define IFC_ME_CNTL_IN_P_IR_LOWER_INDEX  (0)
`define IFC_ME_CNTL_IN_P_IR_WIDTH  (32)
`define IFC_ME_CNTL_IN_P_IR_RANGE `IFC_ME_CNTL_IN_P_IR_UPPER_INDEX:`IFC_ME_CNTL_IN_P_IR_LOWER_INDEX
`define IFC_ME_CNTL_IN_P_BR_OFFSET_UPPER_INDEX  (8-1)
`define IFC_ME_CNTL_IN_P_BR_OFFSET_LOWER_INDEX  (0)
`define IFC_ME_CNTL_IN_P_BR_OFFSET_WIDTH  (8)
`define IFC_ME_CNTL_IN_P_BR_OFFSET_RANGE `IFC_ME_CNTL_IN_P_BR_OFFSET_UPPER_INDEX:`IFC_ME_CNTL_IN_P_BR_OFFSET_LOWER_INDEX
`define IFC_EU_WB_IN_P_RD_DATA_A_UPPER_INDEX  (32-1)
`define IFC_EU_WB_IN_P_RD_DATA_A_LOWER_INDEX  (0)
`define IFC_EU_WB_IN_P_RD_DATA_A_WIDTH  (32)
`define IFC_EU_WB_IN_P_RD_DATA_A_RANGE `IFC_EU_WB_IN_P_RD_DATA_A_UPPER_INDEX:`IFC_EU_WB_IN_P_RD_DATA_A_LOWER_INDEX
`define IFC_EU_WB_IN_P_RD_DATA_B_UPPER_INDEX  (32-1)
`define IFC_EU_WB_IN_P_RD_DATA_B_LOWER_INDEX  (0)
`define IFC_EU_WB_IN_P_RD_DATA_B_WIDTH  (32)
`define IFC_EU_WB_IN_P_RD_DATA_B_RANGE `IFC_EU_WB_IN_P_RD_DATA_B_UPPER_INDEX:`IFC_EU_WB_IN_P_RD_DATA_B_LOWER_INDEX
`define IFC_BR_OUT_P_QUAL_BR_UPPER_INDEX  (1-1)
`define IFC_BR_OUT_P_QUAL_BR_LOWER_INDEX  (0)
`define IFC_BR_OUT_P_QUAL_BR_WIDTH  (1)
`define IFC_BR_OUT_P_QUAL_BR_RANGE `IFC_BR_OUT_P_QUAL_BR_UPPER_INDEX:`IFC_BR_OUT_P_QUAL_BR_LOWER_INDEX

`endif
