`ifndef INC_GUARD_u11
`define INC_GUARD_u11

`define IFC_IFCRC1_P_RESET_UPPER_INDEX  (0)
`define IFC_IFCRC1_P_RESET_LOWER_INDEX  (0)
`define IFC_IFCRC1_P_RESET_WIDTH  (0-0+1)
`define IFC_IFCRC1_P_RESET_RANGE `IFC_IFCRC1_P_RESET_UPPER_INDEX:`IFC_IFCRC1_P_RESET_LOWER_INDEX
`define IFC_IFCRC1_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IFCRC1_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IFCRC1_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IFCRC1_P_CLOCK_RANGE `IFC_IFCRC1_P_CLOCK_UPPER_INDEX:`IFC_IFCRC1_P_CLOCK_LOWER_INDEX
`define IFC_IFC11_I0_P_PIN_UPPER_INDEX  (8-1)
`define IFC_IFC11_I0_P_PIN_LOWER_INDEX  (0)
`define IFC_IFC11_I0_P_PIN_WIDTH  (8)
`define IFC_IFC11_I0_P_PIN_RANGE `IFC_IFC11_I0_P_PIN_UPPER_INDEX:`IFC_IFC11_I0_P_PIN_LOWER_INDEX
`define IFC_IFC11_I0_P_POUT_UPPER_INDEX  (8-1)
`define IFC_IFC11_I0_P_POUT_LOWER_INDEX  (0)
`define IFC_IFC11_I0_P_POUT_WIDTH  (8)
`define IFC_IFC11_I0_P_POUT_RANGE `IFC_IFC11_I0_P_POUT_UPPER_INDEX:`IFC_IFC11_I0_P_POUT_LOWER_INDEX

`endif
