`ifndef INC_GUARD_u12
`define INC_GUARD_u12

`define IFC_IFCRC0_P_RESET_UPPER_INDEX  (0)
`define IFC_IFCRC0_P_RESET_LOWER_INDEX  (0)
`define IFC_IFCRC0_P_RESET_WIDTH  (0-0+1)
`define IFC_IFCRC0_P_RESET_RANGE `IFC_IFCRC0_P_RESET_UPPER_INDEX:`IFC_IFCRC0_P_RESET_LOWER_INDEX
`define IFC_IFCRC0_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IFCRC0_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IFCRC0_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IFCRC0_P_CLOCK_RANGE `IFC_IFCRC0_P_CLOCK_UPPER_INDEX:`IFC_IFCRC0_P_CLOCK_LOWER_INDEX
`define IFC_IFC12_I0_P_PIN_UPPER_INDEX  (8-1)
`define IFC_IFC12_I0_P_PIN_LOWER_INDEX  (0)
`define IFC_IFC12_I0_P_PIN_WIDTH  (8)
`define IFC_IFC12_I0_P_PIN_RANGE `IFC_IFC12_I0_P_PIN_UPPER_INDEX:`IFC_IFC12_I0_P_PIN_LOWER_INDEX
`define IFC_IFC12_I0_P_POUT1_UPPER_INDEX  (8-1)
`define IFC_IFC12_I0_P_POUT1_LOWER_INDEX  (0)
`define IFC_IFC12_I0_P_POUT1_WIDTH  (8)
`define IFC_IFC12_I0_P_POUT1_RANGE `IFC_IFC12_I0_P_POUT1_UPPER_INDEX:`IFC_IFC12_I0_P_POUT1_LOWER_INDEX
`define IFC_IFC12_I0_P_POUT2_UPPER_INDEX  (8-1)
`define IFC_IFC12_I0_P_POUT2_LOWER_INDEX  (0)
`define IFC_IFC12_I0_P_POUT2_WIDTH  (8)
`define IFC_IFC12_I0_P_POUT2_RANGE `IFC_IFC12_I0_P_POUT2_UPPER_INDEX:`IFC_IFC12_I0_P_POUT2_LOWER_INDEX

`endif
