`ifndef INC_GUARD_u21
`define INC_GUARD_u21

`define IFC_IFCRC2_P_RESET_UPPER_INDEX  (0)
`define IFC_IFCRC2_P_RESET_LOWER_INDEX  (0)
`define IFC_IFCRC2_P_RESET_WIDTH  (0-0+1)
`define IFC_IFCRC2_P_RESET_RANGE `IFC_IFCRC2_P_RESET_UPPER_INDEX:`IFC_IFCRC2_P_RESET_LOWER_INDEX
`define IFC_IFCRC2_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IFCRC2_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IFCRC2_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IFCRC2_P_CLOCK_RANGE `IFC_IFCRC2_P_CLOCK_UPPER_INDEX:`IFC_IFCRC2_P_CLOCK_LOWER_INDEX
`define P_PIN1_UPPER_INDEX  (8-1)
`define P_PIN1_LOWER_INDEX  (0)
`define P_PIN1_WIDTH  (8)
`define P_PIN1_RANGE `P_PIN1_UPPER_INDEX:`P_PIN1_LOWER_INDEX
`define P_PIN2_UPPER_INDEX  (8-1)
`define P_PIN2_LOWER_INDEX  (0)
`define P_PIN2_WIDTH  (8)
`define P_PIN2_RANGE `P_PIN2_UPPER_INDEX:`P_PIN2_LOWER_INDEX
`define P_POUT_UPPER_INDEX  (36-1)
`define P_POUT_LOWER_INDEX  (0)
`define P_POUT_WIDTH  (36)
`define P_POUT_RANGE `P_POUT_UPPER_INDEX:`P_POUT_LOWER_INDEX

`endif
