`ifndef INC_GUARD_uabc
`define INC_GUARD_uabc

`define IFC_IFC11_I2_P_PIN_UPPER_INDEX  (8-1)
`define IFC_IFC11_I2_P_PIN_LOWER_INDEX  (0)
`define IFC_IFC11_I2_P_PIN_WIDTH  (8)
`define IFC_IFC11_I2_P_PIN_RANGE `IFC_IFC11_I2_P_PIN_UPPER_INDEX:`IFC_IFC11_I2_P_PIN_LOWER_INDEX
`define IFC_IFC11_I2_P_POUT_UPPER_INDEX  (8-1)
`define IFC_IFC11_I2_P_POUT_LOWER_INDEX  (0)
`define IFC_IFC11_I2_P_POUT_WIDTH  (8)
`define IFC_IFC11_I2_P_POUT_RANGE `IFC_IFC11_I2_P_POUT_UPPER_INDEX:`IFC_IFC11_I2_P_POUT_LOWER_INDEX
`define IFC_IFC12_I2_P_PIN_UPPER_INDEX  (8-1)
`define IFC_IFC12_I2_P_PIN_LOWER_INDEX  (0)
`define IFC_IFC12_I2_P_PIN_WIDTH  (8)
`define IFC_IFC12_I2_P_PIN_RANGE `IFC_IFC12_I2_P_PIN_UPPER_INDEX:`IFC_IFC12_I2_P_PIN_LOWER_INDEX
`define IFC_IFC12_I2_P_POUT1_UPPER_INDEX  (8-1)
`define IFC_IFC12_I2_P_POUT1_LOWER_INDEX  (0)
`define IFC_IFC12_I2_P_POUT1_WIDTH  (8)
`define IFC_IFC12_I2_P_POUT1_RANGE `IFC_IFC12_I2_P_POUT1_UPPER_INDEX:`IFC_IFC12_I2_P_POUT1_LOWER_INDEX
`define IFC_IFC12_I2_P_POUT2_UPPER_INDEX  (8-1)
`define IFC_IFC12_I2_P_POUT2_LOWER_INDEX  (0)
`define IFC_IFC12_I2_P_POUT2_WIDTH  (8)
`define IFC_IFC12_I2_P_POUT2_RANGE `IFC_IFC12_I2_P_POUT2_UPPER_INDEX:`IFC_IFC12_I2_P_POUT2_LOWER_INDEX
`define P_AR_RST_RESET_UPPER_INDEX  (1-1)
`define P_AR_RST_RESET_LOWER_INDEX  (0)
`define P_AR_RST_RESET_WIDTH  (1)
`define P_AR_RST_RESET_RANGE `P_AR_RST_RESET_UPPER_INDEX:`P_AR_RST_RESET_LOWER_INDEX
`define P_AR_CLK_CLOCK_UPPER_INDEX  (1-1)
`define P_AR_CLK_CLOCK_LOWER_INDEX  (0)
`define P_AR_CLK_CLOCK_WIDTH  (1)
`define P_AR_CLK_CLOCK_RANGE `P_AR_CLK_CLOCK_UPPER_INDEX:`P_AR_CLK_CLOCK_LOWER_INDEX

`endif
