`ifndef INC_GUARD_upair
`define INC_GUARD_upair

`define IFC_IFCBU1_IFC_IFCUP_P_IIN_UPPER_INDEX  (16-1)
`define IFC_IFCBU1_IFC_IFCUP_P_IIN_LOWER_INDEX  (0)
`define IFC_IFCBU1_IFC_IFCUP_P_IIN_WIDTH  (16)
`define IFC_IFCBU1_IFC_IFCUP_P_IIN_RANGE `IFC_IFCBU1_IFC_IFCUP_P_IIN_UPPER_INDEX:`IFC_IFCBU1_IFC_IFCUP_P_IIN_LOWER_INDEX
`define IFC_IFCBU1_IFC_IFCUP_P_IOUT_UPPER_INDEX  (16-1)
`define IFC_IFCBU1_IFC_IFCUP_P_IOUT_LOWER_INDEX  (0)
`define IFC_IFCBU1_IFC_IFCUP_P_IOUT_WIDTH  (16)
`define IFC_IFCBU1_IFC_IFCUP_P_IOUT_RANGE `IFC_IFCBU1_IFC_IFCUP_P_IOUT_UPPER_INDEX:`IFC_IFCBU1_IFC_IFCUP_P_IOUT_LOWER_INDEX
`define IFC_IFCBU1_IFC_IFCDW_P_IIN_UPPER_INDEX  (16-1)
`define IFC_IFCBU1_IFC_IFCDW_P_IIN_LOWER_INDEX  (0)
`define IFC_IFCBU1_IFC_IFCDW_P_IIN_WIDTH  (16)
`define IFC_IFCBU1_IFC_IFCDW_P_IIN_RANGE `IFC_IFCBU1_IFC_IFCDW_P_IIN_UPPER_INDEX:`IFC_IFCBU1_IFC_IFCDW_P_IIN_LOWER_INDEX
`define IFC_IFCBU1_IFC_IFCDW_P_IOUT_UPPER_INDEX  (16-1)
`define IFC_IFCBU1_IFC_IFCDW_P_IOUT_LOWER_INDEX  (0)
`define IFC_IFCBU1_IFC_IFCDW_P_IOUT_WIDTH  (16)
`define IFC_IFCBU1_IFC_IFCDW_P_IOUT_RANGE `IFC_IFCBU1_IFC_IFCDW_P_IOUT_UPPER_INDEX:`IFC_IFCBU1_IFC_IFCDW_P_IOUT_LOWER_INDEX
`define IFC_IFCSU1_P_IIN_UPPER_INDEX  (16-1)
`define IFC_IFCSU1_P_IIN_LOWER_INDEX  (0)
`define IFC_IFCSU1_P_IIN_WIDTH  (16)
`define IFC_IFCSU1_P_IIN_RANGE `IFC_IFCSU1_P_IIN_UPPER_INDEX:`IFC_IFCSU1_P_IIN_LOWER_INDEX
`define IFC_IFCSU1_P_IOUT_UPPER_INDEX  (16-1)
`define IFC_IFCSU1_P_IOUT_LOWER_INDEX  (0)
`define IFC_IFCSU1_P_IOUT_WIDTH  (16)
`define IFC_IFCSU1_P_IOUT_RANGE `IFC_IFCSU1_P_IOUT_UPPER_INDEX:`IFC_IFCSU1_P_IOUT_LOWER_INDEX

`endif
