`ifndef INC_GUARD_usu
`define INC_GUARD_usu

`define IFC_IFCSU0_P_IIN_UPPER_INDEX  (16-1)
`define IFC_IFCSU0_P_IIN_LOWER_INDEX  (0)
`define IFC_IFCSU0_P_IIN_WIDTH  (16)
`define IFC_IFCSU0_P_IIN_RANGE `IFC_IFCSU0_P_IIN_UPPER_INDEX:`IFC_IFCSU0_P_IIN_LOWER_INDEX
`define IFC_IFCSU0_P_IOUT_UPPER_INDEX  (16-1)
`define IFC_IFCSU0_P_IOUT_LOWER_INDEX  (0)
`define IFC_IFCSU0_P_IOUT_WIDTH  (16)
`define IFC_IFCSU0_P_IOUT_RANGE `IFC_IFCSU0_P_IOUT_UPPER_INDEX:`IFC_IFCSU0_P_IOUT_LOWER_INDEX

`endif
