`ifndef INC_GUARD_c
`define INC_GUARD_c

`define IFC_IFC10_P_P_X_UPPER_INDEX  (88-1)
`define IFC_IFC10_P_P_X_LOWER_INDEX  (0)
`define IFC_IFC10_P_P_X_WIDTH  (88)
`define IFC_IFC10_P_P_X_RANGE `IFC_IFC10_P_P_X_UPPER_INDEX:`IFC_IFC10_P_P_X_LOWER_INDEX
`define IFC_IFC10_IFC_IFC00_P_P_M_UPPER_INDEX  (78-1)
`define IFC_IFC10_IFC_IFC00_P_P_M_LOWER_INDEX  (0)
`define IFC_IFC10_IFC_IFC00_P_P_M_WIDTH  (78)
`define IFC_IFC10_IFC_IFC00_P_P_M_RANGE `IFC_IFC10_IFC_IFC00_P_P_M_UPPER_INDEX:`IFC_IFC10_IFC_IFC00_P_P_M_LOWER_INDEX
`define IFC_IFC10_IFC_IFC00_P_P_N_UPPER_INDEX  (64-1)
`define IFC_IFC10_IFC_IFC00_P_P_N_LOWER_INDEX  (0)
`define IFC_IFC10_IFC_IFC00_P_P_N_WIDTH  (64)
`define IFC_IFC10_IFC_IFC00_P_P_N_RANGE `IFC_IFC10_IFC_IFC00_P_P_N_UPPER_INDEX:`IFC_IFC10_IFC_IFC00_P_P_N_LOWER_INDEX
`define IFC_IFC10_IFC_IFC00_P_P_O_UPPER_INDEX  (78-1)
`define IFC_IFC10_IFC_IFC00_P_P_O_LOWER_INDEX  (0)
`define IFC_IFC10_IFC_IFC00_P_P_O_WIDTH  (78)
`define IFC_IFC10_IFC_IFC00_P_P_O_RANGE `IFC_IFC10_IFC_IFC00_P_P_O_UPPER_INDEX:`IFC_IFC10_IFC_IFC00_P_P_O_LOWER_INDEX
`define IFC_IFC10_IFC_IFC01_P_P_M_UPPER_INDEX  (78-1)
`define IFC_IFC10_IFC_IFC01_P_P_M_LOWER_INDEX  (0)
`define IFC_IFC10_IFC_IFC01_P_P_M_WIDTH  (78)
`define IFC_IFC10_IFC_IFC01_P_P_M_RANGE `IFC_IFC10_IFC_IFC01_P_P_M_UPPER_INDEX:`IFC_IFC10_IFC_IFC01_P_P_M_LOWER_INDEX
`define IFC_IFC10_IFC_IFC01_P_P_N_UPPER_INDEX  (64-1)
`define IFC_IFC10_IFC_IFC01_P_P_N_LOWER_INDEX  (0)
`define IFC_IFC10_IFC_IFC01_P_P_N_WIDTH  (64)
`define IFC_IFC10_IFC_IFC01_P_P_N_RANGE `IFC_IFC10_IFC_IFC01_P_P_N_UPPER_INDEX:`IFC_IFC10_IFC_IFC01_P_P_N_LOWER_INDEX
`define IFC_IFC10_IFC_IFC01_P_P_O_UPPER_INDEX  (78-1)
`define IFC_IFC10_IFC_IFC01_P_P_O_LOWER_INDEX  (0)
`define IFC_IFC10_IFC_IFC01_P_P_O_WIDTH  (78)
`define IFC_IFC10_IFC_IFC01_P_P_O_RANGE `IFC_IFC10_IFC_IFC01_P_P_O_UPPER_INDEX:`IFC_IFC10_IFC_IFC01_P_P_O_LOWER_INDEX
`define S_S_M_UPPER_INDEX  (78-1)
`define S_S_M_LOWER_INDEX  (0)
`define S_S_M_WIDTH  (78)
`define S_S_M_RANGE `S_S_M_UPPER_INDEX:`S_S_M_LOWER_INDEX
`define S_S_C_UPPER_INDEX  (152-1)
`define S_S_C_LOWER_INDEX  (0)
`define S_S_C_WIDTH  (152)
`define S_S_C_RANGE `S_S_C_UPPER_INDEX:`S_S_C_LOWER_INDEX

`endif
