#!/usr/bin/perl

#Author Anamaria
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}


foreach (my $k = 1; $k <= 20; $k++) {
 my @a1 = ("s1_sg1_$k", "s2_sg1_$k", "s3_sg1_$k", "s4_sg1_$k","s5_sg1_$k", "s6_sg1_$k", "p1_ifc1_$k", "p2_ifc1_$k", "p3_ifc1_$k","p4_ifc1_$k", "p5_ifc1_$k", "p1_ifc2_$k", "p2_ifc2_$k","p3_ifc2_$k", "p4_ifc2_$k","p5_ifc2_$k", "s1_sg2_$k","s2_sg2_$k", "s3_sg2_$k", "p1_ifc3_$k", "p2_ifc3_$k", "s1_sg3_$k", "s2_sg3_$k");
 my @a2 = ("s1_sg1_$k", "s2_sg1_$k", "s3_sg1_$k", "s4_sg1_$k", "p1_ifc1_$k", "p2_ifc1_$k", "p3_ifc1_$k","p4_ifc1_$k", "p5_ifc1_$k", "p1_ifc2_$k", "p2_ifc2_$k", "p3_ifc2_$k","p4_ifc2_$k", "p1_ifc3_$k","p2_ifc3_$k", "s1_sg2_$k", "s2_sg2_$k", "s3_sg2_$k", "s1_sg3_$k", "s2_sg3_$k");
 my @a3 = ("p2_ifc1_$k", "p1_ifc1_$k","p3_ifc1_$k","s1_sg1_$k", "s2_sg1_$k", "s3_sg1_$k", "s4_sg1_$k", "s5_sg1_$k", "s6_sg1_$k", "s1_sg2_$k","s2_sg2_$k", "s3_sg2_$k", "p1_ifc2_$k", "p2_ifc2_$k","p3_ifc2_$k","p4_ifc2_$k", "p1_ifc3_$k","p2_ifc3_$k", "s1_sg3_$k", "s2_sg3_$k");
 my @a4 = ("p1_ifc1_$k","p2_ifc1_$k", "p3_ifc1_$k", "s1_sg1_$k", "s2_sg1_$k", "s3_sg1_$k", "s4_sg1_$k", "s5_sg1_$k", "s6_sg1_$k", "s1_sg2_$k", "s2_sg2_$k", "s3_sg2_$k", "p2_ifc2_$k", "p1_ifc2_$k", "p3_ifc2_$k", "s1_sg3_$k", "s2_sg3_$k", "p1_ifc3_$k","p2_ifc3_$k");
    my $ctests;
    if($k <= 5) {   
        foreach my $u (@a1) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        }
    }
    elsif($k > 5 && $k <= 10) {
         foreach my $u(@a2) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
    elsif($k > 10 && $k <= 15) {
         foreach my $u(@a3) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
    elsif($k > 15 && $k <= 20) {
         foreach my $u(@a4) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
}
sub main {     
    my ($k, $ctests, $u) = @_; 
    my $test_name = "concat_in_connect".$k."_".$u."_legal.csl";
    &createCslFile($test_name, $k, $ctests);
}
sub createCslFile {
    my($test_name, $k, $ctests) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
    my $val1 = int(rand(300));
    my $val2 = int(rand(50));
    my $val3 = int(rand(350));
    
    if($val1 == 0) { $val1 = 1; }
    if($val2 == 0) { $val2 = 1; }
    if($val3 == 0) { $val3 = 1; }
   
    my $val4 = $val1 + $val2;
    my $val5 = $val1 + $val2 + $val3;
    my $val6 = $val2 + $val3;
    if($test_name=~/(_legal)/){
        &mkDir("$path/concat_in_connect_valid");
        open(FH,">$path/concat_in_connect_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/concat_in_connect_invalid"); 
        open(FH,">$path/concat_in_connect_invalid/$test_name");
    }
      
    print FH "// Generated by  AnamariaH \n\n";
    print FH "// Connect ifc_p_concat . \n\n";


    print FH "csl_signal_group sg1{ \n";
    if ($k <= 10){
    print FH "csl_signal s1_sg1_$k($val1); \n";
    print FH "csl_signal s2_sg1_$k($val2); \n";
    print FH "csl_signal s3_sg1_$k($val4); \n";
    print FH "csl_signal s4_sg1_$k($val3); \n";
    }
    elsif($k > 10 && $k <= 20){
    print FH "csl_signal s1_sg1_$k($val4); \n";
    print FH "csl_signal s2_sg1_$k($val6); \n";
    print FH "csl_signal s3_sg1_$k($val5); \n";
    print FH "csl_signal s4_sg1_$k($val2); \n";
    print FH "csl_signal s5_sg1_$k($val3); \n";
    print FH "csl_signal s6_sg1_$k($val1); \n";
    }
    print FH " sg1() {} \n";
    print FH "};\n";

    print FH "csl_signal_group sg2{ \n";
    print FH "sg1 sgn1; \n";
    if ($k <= 10 ) {
    print FH "csl_signal s1_sg2_$k($val1); \n";
    print FH "csl_signal s2_sg2_$k($val2); \n";
    print FH "csl_signal s3_sg2_$k($val3); \n";
    }
    elsif($k > 10 && $k <= 20){ 
    print FH "csl_signal s1_sg2_$k($val1); \n";
    print FH "csl_signal s2_sg2_$k($val2); \n";
    print FH "csl_signal s3_sg2_$k($val6); \n";
    }
    print FH "  sg2() {} \n";
    print FH "};\n";
    
    print FH "csl_signal_group sg3{ \n";
    print FH "  sg2 sgn2; \n";
    if($k <= 10) {
    print FH "csl_signal s1_sg3_$k($val4); \n";
    print FH "csl_signal s2_sg3_$k($val3); \n";
    }
    elsif($k > 10 && $k <= 20) {
    print FH "csl_signal s1_sg3_$k($val6); \n";
    print FH "csl_signal s2_sg3_$k($val5); \n";
    }    
    print FH "  sg3() {} \n";
    print FH "};\n";


    print FH "csl_interface ifc1{ \n";
    if ($k <= 5){
    print FH "csl_port p1_ifc1_$k(input,$val1); \n";
    print FH "csl_port p3_ifc1_$k(inout,$val4); \n";
    print FH "csl_port p4_ifc1_$k(input,$val2); \n";
    print FH "csl_port p2_ifc1_$k(output,$val2); \n";
    print FH "csl_port p5_ifc1_$k(output,$val3);\n";
    }
    elsif($k > 5 && $k <= 10){
    print FH "csl_port p1_ifc1_$k(input,$val6); \n";
    print FH "csl_port p3_ifc1_$k(output,$val5); \n";
    print FH "csl_port p4_ifc1_$k(input,$val2); \n";
    print FH "csl_port p2_ifc1_$k(inout,$val4); \n";
    print FH "csl_port p5_ifc1_$k(input,$val3);\n";
    }
    elsif($k > 10 && $k <= 20){
    print FH "csl_port p1_ifc1_$k(input,$val1); \n";
    print FH "csl_port p2_ifc1_$k(input,$val2); \n";
    print FH "csl_port p3_ifc1_$k(input,$val3); \n";

    }
    print FH "  ifc1() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc2{ \n";
    print FH "   ifc1 inter1; \n";
    if($k <= 5 ){
    print FH "csl_port p1_ifc2_$k(input,$val5);\n";
    print FH "csl_port p2_ifc2_$k(output,$val6);\n";
    print FH "csl_port p3_ifc2_$k(input,$val4);\n";
    print FH "csl_port p4_ifc2_$k(inout,$val2);\n"; 
    print FH "csl_port p5_ifc2_$k(input,$val3);\n";
    }
    elsif($k > 5 && $k <= 15) {
    print FH "csl_port p1_ifc2_$k(output,$val4);\n";
    print FH "csl_port p2_ifc2_$k(output,$val3);\n";
    print FH "csl_port p3_ifc2_$k(input,$val2);\n";
    print FH "csl_port p4_ifc2_$k(input,$val3);\n";
    
    }
    elsif($k > 15 && $k <= 20){
    print FH "csl_port p1_ifc2_$k(input,$val3);\n";
    print FH "csl_port p2_ifc2_$k(input,$val2);\n";
    print FH "csl_port p3_ifc2_$k(input,$val1);\n";
    }
    print FH "  ifc2() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc3{ \n";
    print FH " ifc1 inter11; \n";
    print FH " ifc2 inter2; \n";
    if($k <= 15) {
    print FH "csl_port p1_ifc3_$k(input,$val3); \n";
    print FH "csl_port p2_ifc3_$k(input,$val5); \n";
    }
    elsif($k > 15 && $k <= 20){
    print FH "csl_port p1_ifc3_$k(inout,$val2); \n";
    print FH "csl_port p2_ifc3_$k(inout,$val1); \n";   
    }
    print FH "  ifc3() {} \n";
    print FH "};\n";
   
    print FH "csl_unit unit_a{ \n";
    print FH "  sg1 sgn10; \n";
    print FH "  ifc1 inter10; \n";
    print FH "  unit_a() { \n"; 
    if($k <= 10) {
    print FH " inter10.p3_ifc1_$k.connect({inter10.p1_ifc1_$k,inter10.p4_ifc1_$k}); \n";   
    print FH " // Connect ifc_p_concat_ifc_p(same direction). \n";
    }
    elsif($k > 10 && $k <= 20){
    print FH " sgn10.s3_sg1_$k.connect({sgn10.s1_sg1_$k, sgn10.s2_sg1_$k});\n";
    print FH " // Connect sg_s_concat_sg_s. \n";
    }   
    print FH " } \n";
    print FH "}; \n";

    print FH "csl_unit unit_b{ \n";
    print FH " sg2 sgn20; \n";
    print FH " sg1 sgn11; \n";
    print FH " ifc2 inter20; \n";
    print FH " unit_a a0; \n";
    print FH " unit_a a1; \n";   
    print FH "   unit_b() { \n"; 

    if($k <= 5) {
    print FH " inter20.p3_ifc2_$k.connect({a0.inter10.p1_ifc1_$k,a1.inter10.p4_ifc1_$k} ); \n";
    print FH " inter20.p2_ifc2_$k.connect({inter20.inter1.p2_ifc1_$k, inter20.inter1.p5_ifc1_$k}); \n";   
    print FH " inter20.p1_ifc2_$k.connect({sgn20.s1_sg2_$k, sgn20.s2_sg2_$k, sgn20.s4_sg2_$k}); \n";
    print FH " inter20.p2_ifc2_$k.connect({sgn20.sgn1.s2_sg1_$k, sgn20.sgn1.s4_sg1_$k}); \n";
    print FH " // Connect ifc_p_concat. \n";

    }
    elsif($k > 5 && $k <= 10){
    print FH " inter20.inter1.p3_ifc1_$k.connect({inter20.p1_ifc2_$k, inter20.p2_ifc2_$k}); \n";
    print FH " inter20.inter1.p1_ifc1_$k.connect({inter20.inter1.p4_ifc1_$k, inter20.inter1.p5_ifc1_$k}); \n";   
    print FH " inter20.inter1.p2_ifc1_$k.connect({sgn11.s1_sg1_$k, sgn11.s2_sg1_$k}); \n";
    print FH " inter20.inter1.p1_ifc1_$k.connect({sgn20.sgn1.s2_sg1_$k, sgn20.sgn1.s3_sg1_$k}); \n";       
    print FH " // Connect ifc_ifc_p_concat. \n";
    }
    elsif($k > 10 && $k <= 15){
    print FH " sgn11.s1_sg1_$k.connect({sgn20.s1_sg2_$k, sgn20.s2_sg2_$k}); \n";
    print FH " sgn11.s2_sg1_$k.connect({sgn20.sgn1.s4_sg1_$k, sgn20.sgn1.s5_sg1_$k}); \n";   
    print FH " sgn11.s3_sg1_$k.connect({inter20.p1_ifc2_$k, inter20.p2_ifc2_$k}); \n";
    print FH " sgn11.s3_sg1_$k.connect({inter20.inter1.p1_ifc1_$k, inter20.inter1.p2_ifc1_$k, inter20.inter1.p3_ifc1_$k}); \n";       
    print FH " // Connect sg_s_concat. \n";
    }
    elsif($k > 15 && $k <= 20){
    print FH " sgn20.sgn1.s3_sg1_$k.connect({sgn11.s1_sg1_$k, sgn11.s5_sg1_$k}); \n";
    print FH " sgn20.sgn1.s1_sg1_$k.connect({sgn20.sgn1.s6_sg1_$k, sgn20.sgn1.s4_sg1_$k}); \n";   
    print FH " sgn20.sgn1.s2_sg1_$k.connect({inter20.p1_ifc2_$k, inter20.p2_ifc2_$k}); \n";
    print FH " sgn20.sgn1.s3_sg1_$k.connect({inter20.inter1.p1_ifc1_$k, inter20.inter1.p2_ifc1_$k, inter20.inter1.p3_ifc1_$k}); \n";       
    print FH " //Connect sg_sg_s_concat. \n";
    }
    print FH " } \n";
    print FH "}; \n";
 

    print FH "csl_unit unit_top{ \n";
    print FH "  sg3 sgn3; \n";
    print FH "  ifc3 inter3; \n";
    print FH " unit_b b0; \n";
    print FH " unit_b b1; \n";
    print FH " unit_a a2;\n";
    print FH "  unit_top() { \n";  
    if($k <= 5) {
    print FH " inter3.p2_ifc3_$k.connect({b0.inter20.p3_ifc2_$k, b1.inter20.p5_ifc2_$k} ); \n";
    print FH " b1.inter20.p2_ifc2_$k.connect({inter3.inter11.p2_ifc1_$k, inter3.inter11.p5_ifc1_$k}); \n";   
    print FH " b0.inter20.p1_ifc2_$k.connect({sgn3.s1_sg3_$k, sgn3.s2_sg3_$k}); \n";
    print FH " a2.inter10.p3_ifc1_$k.connect({b0.sgn20.sgn1.s1_sg1_$k, b0.sgn20.sgn1.s2_sg1_$k}); \n";
    print FH " // Connect ifc_p_concat. \n";
    }
    elsif($k > 5 && $k <= 10) {
    print FH " inter3.inter11.p1_ifc1_$k.connect({b1.inter20.p3_ifc2_$k, b1.inter20.p4_ifc2_$k}); \n";
    print FH " b1.inter20.inter1.p1_ifc1_$k.connect({b0.inter20.inter1.p4_ifc1_$k, b0.inter20.inter1.p5_ifc1_$k}); \n";   
    print FH " inter3.inter11.p2_ifc1_$k.connect({a2.sgn10.s1_sg1_$k, a2.sgn10.s2_sg1_$k}); \n";
    print FH " inter3.inter2.p1_ifc2_$k.connect({b0.sgn20.sgn1.s2_sg1_$k, b1.sgn20.sgn1.s1_sg1_$k}); \n";       
    print FH " // Connect ifc_ifc_p_concat. \n";
    }
    elsif($k > 10 && $k <= 15) {
    print FH " b1.sgn11.s1_sg1_$k.connect({b0.sgn20.s1_sg2_$k, b0.sgn20.s2_sg2_$k}); \n";
    print FH " a2.sgn10.s2_sg1_$k.connect({b1.sgn20.sgn1.s4_sg1_$k, b0.sgn20.sgn1.s5_sg1_$k}); \n";   
    print FH " sgn3.s2_sg3_$k.connect({b1.inter20.p1_ifc2_$k, a2.inter10.p5_ifc1_$k}); \n";
    print FH " b0.sgn11.s3_sg1_$k.connect({inter3.inter11.p1_ifc1_$k, inter3.inter11.p2_ifc1_$k}); \n";       
    print FH " // Connect sg_s_concat. \n";
    }   
    elsif($k > 15 && $k <= 20) {
    print FH " sgn3.sgn2.s3_sg2_$k.connect({b0.sgn11.s4_sg1_$k, b1.sgn11.s5_sg1_$k}); \n";
    print FH " b0.sgn20.sgn1.s1_sg1_$k.connect({b1.sgn20.sgn1.s6_sg1_$k, b1.sgn20.sgn1.s4_sg1_$k}); \n";   
    print FH " b1.sgn20.sgn1.s1_sg1_$k.connect({inter3.p1_ifc3_$k, inter3.p2_ifc3_$k}); \n";
    print FH " b1.sgn20.sgn1.s3_sg1_$k.connect({inter3.inter11.p1_ifc1_$k, inter3.inter11.p2_ifc1_$k, inter3.inter11.p3_ifc1_$k}); \n";       
    print FH " //Connect sg_sg_s_concat. \n";
    }
    print FH "  }\n";         
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}



