#!/usr/bin/perl

#Author Petronela
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

my @lower = (0,6,8,19,31);
my @upper = (34,48,52,66,87);

for (my $i = 1; $i <= 5; ++$i ) {
    foreach my $l(@lower) {
        foreach my $u(@upper) { 
            &main($i,$l,$u);
        }
    }
}

sub main {
    my ($i,$l, $u) = @_;
    my $test_name = "connect_unit_p_sps_p$i"."_".$l."_".$u."_legal.csl";
    &createCslFile($test_name,$i, $l, $u);
}

sub createCslFile {
    my($test_name, $i,$l, $u) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
    my $val1 = $u + int(rand(100)) + 1;
    my $w = $u - $l + 1;
    my $val2 = $val1 + int(rand(100)) + 1;
    my $val3 = $val1 + int(rand(50)) + 1;
    &mkDir("$path/ar_p_sps_p_connect_valid");
    open(FH,">$path/ar_p_sps_p_connect_valid/$test_name");

    print FH "//Generated by Petronela\n";
    print FH "//connections port to signal[part select], port[part select] to signal[part select], signal[part select] to port[part select] and signal[part select] to port\n\n";
    print FH "csl_bitrange br($w);\n";
    print FH "csl_bitrange brt($val2);\n";
    print FH "csl_unit a {\n";
    if($i <= 2) {
        print FH "  csl_port p_a$i(input,$val1);\n"; 
        print FH "  csl_port pa(input,$w);\n";
        print FH "  csl_signal sa($val1);\n";
        print FH "  csl_signal s_a$i($val3);\n";
    }
    elsif($i > 2 && $i <= 4) {
        print FH "  csl_port p_a$i(output,$val2);\n"; 
        print FH "  csl_port pa(input,$val1);\n";
        print FH "  csl_port p(output,$w);\n";
        print FH "  csl_signal s_a$i($val1);\n";
        print FH "  csl_signal s_a_br$i($val2);\n";
    }
    elsif($i > 4) {
        print FH "  csl_port p_a$i(input,$val1);\n"; 
        print FH "  csl_port p_a_br$i(input,br);\n";
        print FH "  csl_port pa(input,$val2);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_signal s_a$i($val3);\n";
        print FH "  csl_signal sa($val2);\n";
    }
    print FH "  a() {\n";                
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    print FH "csl_unit b {\n";  
    if($i == 1) {
        print FH "  csl_port p_b$i(input,$val1);\n";
        print FH "  csl_port p(input,$w);\n";
        print FH "  csl_signal s_b_br$i($val2);\n";
        print FH "  csl_signal s_b$i($val3);\n";
        print FH "  csl_signal sb($val1);\n";
    }
    elsif($i > 1 && $i <= 3) {      
        print FH "  csl_port p_b$i(output,$w);\n";
        print FH "  csl_port pb(output,$w);\n";
        print FH "  csl_port p_b_br$i(output,brt);\n";
        print FH "  csl_port p(output,$val1);\n";
        print FH "  csl_signal s_b$i($val3);\n";
        
    }
    elsif($i > 3) {      
        print FH "  csl_port p_b$i(output,$w);\n";
        print FH "  csl_port p_b_br$i(input,br);\n";
        print FH "  csl_port p(input,$val3);\n";
        print FH "  csl_signal s_b$i($val2);\n";
        print FH "  csl_signal s_b_br$i($val1);\n";
        print FH "  csl_signal sb($val3);\n";
    }
    print FH "  b() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";  
    if($i <= 3) {
        print FH "  csl_port p_c$i(input,$val2);\n";
        print FH "  csl_port pc(input,$val1);\n";
        print FH "  csl_port p_c_br$i(output,br);\n";
        print FH "  csl_port p(input,$val3);\n";
        print FH "  csl_signal s_c$i($val2);\n";
    }
    elsif($i == 4) {      
        print FH "  csl_port p_c$i(output,$w);\n";
        print FH "  csl_port p(output,$val3);\n";
        print FH "  csl_port pc(input,$val1);\n";
        print FH "  csl_signal sc($val3);\n";
        print FH "  csl_signal s_c_br$i(brt);\n";
        print FH "  csl_signal s_c$i($val2);\n";
    }
    elsif($i == 5) {      
        print FH "  csl_port pc(input,$val1);\n";
        print FH "  csl_port p(input,$val2);\n";
        print FH "  csl_port p_c_br$i(input,br);\n";
        print FH "  csl_signal s_c$i($val3);\n";
        print FH "  csl_signal sc($val2);\n";
    }
    print FH "  c() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n"; 
    if($i <= 2) {
        print FH "  csl_port p_d$i(input,$val1);\n"; 
        print FH "  csl_port p_d_br$i(input,br);\n";
        print FH "  csl_port p(input,$val2);\n";
        print FH "  csl_signal s_d_br$i($val3);\n";
        print FH "  csl_signal s_d$i($val2);\n";
    }
    elsif($i > 2 && $i <= 4) {      
        print FH "  csl_port p_d$i(input,$val1);\n";
        print FH "  csl_port p(output,$w);\n";
        print FH "  csl_port pd(output,$val2);\n";
        print FH "  csl_signal s_d$i($val3);\n";
        print FH "  csl_signal sd($val2);\n";
    }
    elsif($i > 4) {      
       print FH "  csl_port p_d$i(input,$val1);\n";
       print FH "  csl_port p(input,$val2);\n";
       print FH "  csl_signal s_d$i($val1);\n";
       print FH "  csl_signal s_d_br$i($val2);\n";
       print FH "  csl_signal sd($val3);\n";
    }
    print FH "  d() {\n";
    if($i <= 2) {
        print FH "    s_d$i"."[$l:$u].connect(p_a$i"."[$l:$u]);\n";
        print FH "    c0.p_c$i"."[$l:$u].connect(s_d_br$i"."[$l:$u]);\n";
        print FH "    p_d_br$i.connect(s_a$i"."[$l:$u]);\n";
    }
    elsif($i > 2 && $i <= 4) {
        print FH "    s_d$i"."[$l:$u].connect(pc[$l:$u]);\n";
        print FH "    b0.p_b$i.connect(s_d$i"."[$l:$u]);\n";
        print FH "    pd[$l:$u].connect(s_a$i"."[$u:$l]);\n";
        print FH "    sd[$l:$u].connect(d.p);\n";
    }
    elsif($i > 4) {
        print FH "    s_d$i"."[$l:$u].connect(a0.p[$l:$u]);\n";
        print FH "    c0.p_c_br$i.connect(sd[$l:$u]);\n";
        print FH "    s_d_br$i"."[$l:$u].connect(a0.p_a_br$i);\n";
    }
    
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    

    print FH "csl_unit e {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n";
    if($i == 1 ) {
        print FH "  csl_port p_e$i(input,$val1);\n"; 
        print FH "  csl_port p_e_br$i(input,br);\n";   
        print FH "  csl_port p(input,$val2);\n";
        print FH "  csl_signal s_e$i($val1);\n";
        print FH "  csl_signal se($val2);\n";
        print FH "  csl_signal s_e_br$i($val3);\n";
    }
    elsif($i > 1 && $i <= 3) {      
        print FH "  csl_port p_e$i(output,$val1);\n";    
        print FH "  csl_port p(output,$val3);\n";
        print FH "  csl_port p_e_br$i(output,br);\n";
        print FH "  csl_signal s_e$i($val3);\n";
        print FH "  csl_signal s_e_br$i($val1);\n";
    }
    elsif($i > 3) {      
        print FH "  csl_port p_e$i(input,$w);\n";
        print FH "  csl_port p(input,$val3);\n";
        print FH "  csl_port pe(input,$w);\n";
        print FH "  csl_signal se($val3);\n";
    }
    print FH "  e() {\n";
    if($i == 1) {
        print FH "    s_e_br$i"."[$l:$u].connect(a0.pa);\n";
        print FH "    b0.p.connect(s_e$i"."[$l:$u]);\n";
        print FH "    b0.p.connect(s_e_br$i"."[$l:$u]);\n";
    }
    elsif($i > 1 && $i <= 3) {
        print FH "    s_e$i"."[$l:$u].connect(c0.p[$l:$u]);\n";
        print FH "    b0.s_b$i"."[$l:$u].connect(p_e$i"."[$l:$u]);\n";
    }
    elsif($i > 3) {
        print FH "    p[$l:$u].connect(s_b_br$i"."[$l:$u]);\n";
        print FH "    se[$l:$u].connect(a0.p_a_br$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    print FH "  d d0;\n";
    print FH "  e e0;\n"; 
    if($i <= 2) {
        print FH "  csl_port ptop(input,$val1);\n";
        print FH "  csl_port p(input,$val2);\n";
        print FH "  csl_signal s_top$i($val3);\n";
        print FH "  csl_signal stop($val1);\n";
    }
    elsif($i == 3) {
        print FH "  csl_port p_top$i(output,$val3);\n";      
        print FH "  csl_port p(output,$w);\n";
        print FH "  csl_port ptop(output,$val1);\n"; 
        print FH "  csl_signal stop($val2);\n";
    }
    elsif($i > 3) {
        print FH "  csl_port p_top$i(input,$val2);\n";      
        print FH "  csl_port p(input,$val3);\n";
        print FH "  csl_port p_top_br$i(input,br);\n";
        print FH "  csl_signal s_top$i($val3);\n";
        print FH "  csl_signal s_top_br$i(br);\n";
        print FH "  csl_signal stop($val1);\n";
    }
    
    print FH "  top(){\n";
    if($i <= 2) {
        print FH "    stop[$l:$u].connect(d0.a0.p_a$i"."[$l:$u]);\n";
        print FH "    s_top$i"."[$l:$u].connect(e0.c0.p_c_br$i);\n";
        print FH "    d0.p_d_br$i"."[$l:$u].connect(e0.a0.s_a$i"."[$l:$u]);\n";
    }
    elsif($i == 3) {
        print FH "    stop[$l:$u].connect(e0.a0.p_a$i"."[$l:$u]);\n";
        print FH "    d0.a0.s_a$i"."[$l:$u].connect(d0.b0.p_b_br$i"."[$l:$u]);\n";
        print FH "    p.connect(e0.b0.s_b$i"."[$l:$u]);\n";
    }
    elsif($i > 3) {
        print FH "    s_top_br$i"."[$l:$u].connect(e0.p_e$i"."[$l:$u]);\n";
        print FH "    s_top_br$i"."[$l:$u].connect(e0.p[$l:$u]);\n";
        print FH "    d0.a0.pa[$l:$u].connect(stop[$l:$u]);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}
