#!/usr/bin/perl

#Author Petronela
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 15; $i++) {
    my @map1 = ("s_a$i","sa","s","s_b$i","s_c$i","sc","s_c_br$i","s_d$i","s_d_br$i");
    my @map2 = ("s_a$i","sa","s","s_b$i","sb","s_b_br$i","s_c$i","s_e$i","s_e_br$i");
    my @map3 = ("s_a$i","sa","s_a_br$i","s","s_b$i","s_b_br$i","sc","s_c_br$i","s_d$i","s_e$i","se","s_top$i","s_top_br$i");
    my $var;
    if($i <= 5) {   
        foreach my $it1 (@map1) {
            $var = $it1; 
            &main($i,$var,$it1);
        }
    }
    elsif($i > 5 && $i <= 10) {
        foreach my $it1(@map2) {
            $var = $it1; 
            &main($i,$var,$it1);
        }
    }
    else {
        foreach my $it1(@map3) {
            $var = $it1; 
            &main($i,$var,$it1);
        }  
    }
}

sub main {
    my ($i,$var,$it1) = @_;
    my $test_name = "connect_unit_s_s".$i."_".$it1."_illegal.csl";
    &createCslFile($test_name, $i,$var);
}
sub createCslFile {
    my($test_name, $i,$var) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
    my $val1 = int(rand(100)) + 1;
    my $val2 = int(rand(100)) + 1;
    &mkDir("$path/ar_s_s_connect_invalid");
    open(FH,">$path/ar_s_s_connect_invalid/$test_name");
    
    print FH "//Generated by Petronela\n";
    print FH "//illegal connections signal to signal\n\n";
    print FH "csl_bitrange br($val1);\n";
    print FH "csl_bitrange brt($val2);\n";
    print FH "csl_unit a {\n";
    if($i <= 5) {
        print FH "  csl_signal s_a$i($val1);\n"; 
        print FH "  csl_signal sa($val2);\n";
        print FH "  csl_signal s;\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_signal s_a$i($val2);\n"; 
        print FH "  csl_signal sa($val1);\n";
        print FH "  csl_signal s($val2);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "  csl_signal s_a$i($val1);\n"; 
        print FH "  csl_signal s_a_br$i(br);\n";
        print FH "  csl_signal sa($val2);\n";
        print FH "  csl_signal s($val2);\n";
    }
    print FH "  a() {\n";                
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    print FH "csl_unit b {\n";  
    if($i <= 5) {
        print FH "  csl_signal s_b$i($val1);\n";
        print FH "  csl_signal s($val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_signal s_b$i($val2);\n";
        print FH "  csl_signal sb($val2);\n";
        print FH "  csl_signal s_b_br$i(brt);\n";
        print FH "  csl_signal s($val1);\n";
    }
    elsif($i > 10 && $i <= 15) {      
        print FH "  csl_signal s_b$i($val1);\n";
        print FH "  csl_signal s_b_br$i(br);\n";
        print FH "  csl_signal s($val1);\n";
    }
    print FH "  b() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";  
    if($i <= 5) {
        print FH "  csl_signal s_c$i($val1);\n";
        print FH "  csl_signal sc($val1);\n";
        print FH "  csl_signal s_c_br$i(br);\n";
        print FH "  csl_signal s($val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_signal s_c$i($val2);\n";
        print FH "  csl_signal s($val2);\n";
    }
    elsif($i > 10 && $i <= 15) {      
        print FH "  csl_signal sc($val1);\n";
        print FH "  csl_signal s($val1);\n";
        print FH "  csl_signal s_c_br$i(br);\n";
    }
    print FH "  c() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n"; 
    if($i <= 5) {
        print FH "  csl_signal s_d$i($val1);\n"; 
        print FH "  csl_signal s_d_br$i(br);\n";
        print FH "  csl_signal s($val2);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_signal s_d$i($val2);\n";
        print FH "  csl_signal s($val2);\n";
        print FH "  csl_signal sd($val1);\n";
    }
    elsif($i > 10 && $i <= 15) {      
       print FH "  csl_signal s_d$i($val1);\n";
       print FH "  csl_signal s($val2);\n";
    }
    print FH "  d() {\n";
    if($i <= 5) {
        print FH "    s_d$i.connect($var);\n";
        print FH "    c0.sc.connect(s_d_br$i);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    s_d$i.connect(a0.s_a$i);\n";
        print FH "    s.connect(b0.s_b$i);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    s_d$i.connect(s);\n";
    }
    
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    

    print FH "csl_unit e {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n";
    if($i <= 5) {
        print FH "  csl_signal s_e$i($val1);\n"; 
        print FH "  csl_signal s_e_br$i(br);\n";   
        print FH "  csl_signal s($val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_signal s_e$i($val2);\n";    
        print FH "  csl_signal s($val2);\n";
        print FH "  csl_signal s_e_br$i(brt);\n";
    }
    elsif($i > 10 && $i <= 15) {      
        print FH "  csl_signal s_e$i($val1);\n";
        print FH "  csl_signal s($val1);\n";
        print FH "  csl_signal se($val1);\n";
    }
    print FH "  e() {\n";
    if($i <= 5) {
        print FH "    s_e_br$i.connect(a0.sa);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    s_e$i.connect($var);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    s_e$i.connect(a0.s_a_br$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    print FH "  d d0;\n";
    print FH "  e e0;\n"; 
    if($i <= 5) {
        print FH "  csl_signal stop($val2);\n";
        print FH "  csl_signal s($val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_signal s_top$i($val2);\n";      
        print FH "  csl_signal s($val2);\n";
        print FH "  csl_signal stop($val2);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "  csl_signal s_top$i($val1);\n";      
        print FH "  csl_signal s($val1);\n";
        print FH "  csl_signal s_top_br$i(br);\n";
    }
    
    print FH "  top(){\n";
    if($i <= 5) {
        print FH "    stop.connect(d0.a0.s_a$i);\n";
        print FH "    s.connect($var);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    s_top$i.connect(e0.a0.s_a$i);\n";
        print FH "    stop.connect($var);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    s_top_br$i.connect($var);\n";
        print FH "    s.connect(s);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}
