#!/usr/bin/perl

#Author Monica
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 90; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $test_name = "connect_sg_sig_concat_test".$i."_legal.csl";
    &createCslFile($test_name, $i);
}
sub createCslFile {
    my($test_name, $i) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen";
   if($i==1){
        print (" Generated path: $path/ar_connect_sg_sig_concat_valid/\n");}
    my $val = int(rand(500));
    if($val == 0) { $val = 1; }
    my $val1 =int(rand(25))+1;
    my $val2 =int(rand(100))+1;

    my $br_1= $val+$val1;
    my $br_2= $val+1;
    my $br_3=$val1+$val1+$val;

    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_connect_sg_sig_concat_valid");
        open(FH,">$path/ar_connect_sg_sig_concat_valid/$test_name");
    }

if($i>0 && $i<=90){
if($i>0 &&  $i<=70){  
    print FH "//Generated by Monica\n";
    print FH "//Connect sg.sig/sg.sg.sig--concat_exp\n\n";
    print FH "// VALID TEST $i;\n";
    print FH "csl_bitrange br($val);\n";
    print FH "csl_bitrange br1($val1);\n\n";

#sg.sig --{port1,port2,...}
  if($i>0 &&  $i<=50){     
       
    print FH "csl_unit u1_$i {\n";
    print FH "  csl_port p_data1(input,br1);\n";
    print FH "  csl_port p_data2(input,br1);\n";
    print FH "  csl_port p_data3(input,br);\n";
    print FH "  csl_port p_v(output);\n";
    print FH "u1_$i() {\n";
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
 
    print FH "csl_unit u2_$i {\n";
    print FH "  csl_port p_data1(output,br1);\n";
    print FH "  csl_port p_data2(output,br1);\n";
    print FH "  csl_port p_data3(output,br);\n";
    print FH "  csl_port p_v(input);\n";
    print FH " u2_$i() {\n";
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";

    print FH "csl_signal_group sg1_$i {\n";
    print FH "  csl_signal s1_$i($br_1);\n";
    print FH "  csl_signal s2_$i($br_2);\n";
    print FH "  csl_signal s3_$i($br_3);\n";
    print FH "sg1_$i() {\n";
    print FH "  }\n";
    print FH "};\n";
    print FH "\n"; 

  if($i>0 && $i<=10){
     
    print FH "csl_unit u3_$i {\n";
    print FH "  csl_port p_data1(output,br1);\n";
    print FH "  csl_port p_data2(input,br1);\n";
    print FH "  csl_port p_data3(output,br);\n";
    print FH "  csl_port p_data4(input,br);\n";
    print FH "  csl_port p_v(input);\n\n";
    print FH "  sg1_$i sg1_i$i;\n";
    print FH "  u1_$i u1_i$i;\n";
    print FH "  u2_$i u2_i$i;\n\n";
    print FH "  u3_$i() {\n";
    print FH "  sg1_i$i.s1_$i.connect({p_data1,p_data3});\n";
    print FH "  sg1_i$i.s1_$i.connect({p_data2,p_data3});\n";
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
 }
    elsif($i>10 && $i<=20){

    print FH "csl_unit u3_$i {\n";
    print FH "  csl_port p_data1(output,br1);\n";
    print FH "  csl_port p_data2(input,br1);\n";
    print FH "  csl_port p_data3(output,br);\n";
    print FH "  csl_port p_data4(input,br);\n";
    print FH "  csl_port p_v(input);\n\n";
    print FH "  sg1_$i sg1_i$i;\n";
    print FH "  u1_$i u1_i$i;\n";
    print FH "  u2_$i u2_i$i;\n\n";
    print FH "  u3_$i() {\n";
    print FH "  sg1_i$i.s1_$i.connect({p_data1,p_data3});\n";
    print FH "  sg1_i$i.s1_$i.connect({p_data2,p_data3});\n";
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";

    print FH "csl_unit u_top{\n";
    print FH "  sg1_$i sg1_i1_$i;\n";
    print FH "  sg1_$i sg1_i2_$i;\n";
    print FH "  u3_$i u3_i;\n";
    print FH "  u_top() {\n";
  
    print FH "  sg1_i1_$i.s2_$i.connect({p_data1,p_v});\n";
    print FH "  sg1_i2_$i.s2_$i.connect({p_data1,p_v});\n";
    print FH "  u3_i.sg1_i$i.s3_$i.connect({p_data1,p_data2,p_data3});\n";
    print FH "  sg1_i2_$i.s3_$i.connect({p_data1,p_data2,p_data3});\n"; 
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
}
    elsif($i>20 && $i<=30){
    print FH "csl_unit u3_$i {\n";
    print FH "  csl_port p_data1(output,br1);\n";
    print FH "  csl_port p_data2(input,br1);\n";
    print FH "  csl_port p_data3(output,br);\n";
    print FH "  csl_port p_data4(input,br);\n";
    print FH "  csl_port p_v(input);\n\n";
    print FH "  sg1_$i sg1_i1_$i;\n";
    print FH "  sg1_$i sg1_i2_$i;\n";
    print FH "  u1_$i u1_i$i;\n";
    print FH "  u2_$i u2_i$i;\n\n";
    print FH "  u3_$i() {\n";

    print FH "  sg1_i2_$i.s1_$i.connect({p_data1,p_data3});\n";
    print FH "  sg1_i1_$i.s1_$i.connect({p_data1,p_data3});\n";
   
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";

    print FH "csl_unit u_top1 {\n";
    print FH "  sg1_$i sg1_i1_$i;\n";
    print FH "  sg1_$i sg1_i2_$i;\n";
    print FH "  u3_$i u3_i$i;\n";
    print FH "  u_top1() {\n";

    print FH "  sg1_i1_$i.s2_$i.connect({p_data1,p_v});\n";
    print FH "  sg1_i2_$i.s2_$i.connect({p_data1,p_v});\n";
    print FH "  sg1_i1_$i.s3_$i.connect({p_data1,p_data2,p_data3});\n";
    print FH "  sg1_i2_$i.s3_$i.connect({p_data1,p_data2,p_data3});\n";
    print FH "  u3_i$i.sg1_i1_$i.s3_$i.connect({p_data1,p_data2,p_data3});\n";
    print FH "  u3_i$i.sg1_i1_$i.s3_$i.connect({p_data1,p_v});\n";
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";

    print FH "csl_unit u_top2 {\n";
    print FH "  sg1_$i sg1_i1_$i;\n";
    print FH "  sg1_$i sg1_i2_$i;\n";
    print FH "  u_top1 u_topi;\n";
    print FH "  u_top2() {\n";

    print FH "  sg1_i1_$i.s2_$i.connect({p_data1,p_v});\n";
    print FH "  u_topi.sg1_i2_$i.s2_$i.connect({p_data1,p_v});\n";
    print FH "  sg1_i2_$i.s3_$i.connect({p_data1,p_data2,p_data3});\n";
    print FH "  u_topi.sg1_i2_$i.s3_$i.connect({p_data1,p_data2,p_data3});\n";
    print FH "  u_topi.u3_i$i.sg1_i1_$i.connect({p_data1,p_data3});\n";
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
}
 elsif($i>30 && $i<=40){
   print FH "csl_unit u3_$i {\n";
    print FH "  csl_port p_data1(output,br1);\n";
    print FH "  csl_port p_data2(input,br1);\n";
    print FH "  csl_port p_data3(output,br);\n";
    print FH "  csl_port p_data4(input,br);\n";
    print FH "  csl_port p_v(input);\n\n";
     foreach (my $j=30; $j<=$i; $j++){
         print FH " sg1_$i sg_i$j;\n";
     }
    foreach (my $j=30; $j<=$i; $j++){
         print FH " u1_$i u1_i$j;\n";
         print FH " u2_$i u2_i$j;\n";
     }
   print FH " u3_$i(){\n";
   foreach (my $j=30; $j<=$i; $j++){
       print FH " sg_i$j.s1_$i.connect({p_data1,p_data3});\n";
       
   }
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
    print FH " csl_unit u_top{\n";
     foreach (my $j=30; $j<=$i; $j++){
         print FH " sg1_$i sg_$i$j;\n";
     }
    foreach (my $j=30; $j<=$i; $j++){
         print FH " u3_$i u3_i$j;\n";
     }
   print FH " u_top(){\n";
    foreach (my $j=30; $j<=$i; $j++){

       print FH " sg_$i$j.s2_$i.connect({p_data2,p_v});\n";
       print FH " sg_$i$j.s2_$i.connect({p_data1,p_v});\n";
       print FH " sg_$i$j.s1_$i.connect({p_data2,p_data3});\n";
       print FH " u3_i$j.sg_i$j.s1_$i.connect({p_data1,p_data3});\n";
       print FH " sg_$i$j.s3_$i.connect({p_data1,p_data2,p_data3});\n";
       print FH " u3_i$j.sg_i$j.s3_$i.connect({p_data1,p_data2,p_data3});\n";
   }
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
}
 elsif($i>40 && $i<=50){
  print FH "csl_unit u3_$i {\n";
    print FH "  csl_port p_data1(output,br1);\n";
    print FH "  csl_port p_data2(input,br1);\n";
    print FH "  csl_port p_data3(output,br);\n";
    print FH "  csl_port p_data4(input,br);\n";
    print FH "  csl_port p_v(input);\n\n";
     foreach (my $j=40; $j<=$i; $j++){
         print FH " sg1_$i sg_i$j;\n";
     }
    foreach (my $j=40; $j<=$i; $j++){
         print FH " u1_$i u1_i$j;\n";
         print FH " u2_$i u2_i$j;\n";
     }
   print FH " u3_$i() {\n";
   foreach (my $j=40; $j<=$i; $j++){
   
       print FH " sg_i$j.s1_$i.connect({p_data1,p_data3});\n";
       print FH " sg_i$j.s2_$i.connect({p_data1,p_v});\n";
   }
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
    print FH " csl_unit u_top {\n";
     foreach (my $j=40; $j<=$i; $j++){
         print FH " sg1_$i sg_$i$j;\n";
     }
    foreach (my $j=40; $j<=$i; $j++){
         print FH " u3_$i u3_i$j;\n";
     }
   print FH " u_top() {\n";
    foreach (my $j=40; $j<=$i; $j++){
       print FH " sg_$i$j.s2_$i.connect({p_data2,p_v});\n";
       print FH " sg_$i$j.s1_$i.connect({p_data1,p_data3});\n";
       print FH " sg_$i$j.s3_$i.connect({p_data1,p_data2,p_data3});\n";
      
       print FH " u3_i$j.sg_i$j.s2_$i.connect({p_data2,p_v});\n";
       print FH " u3_i$j.sg_i$j.s1_$i.connect({p_data1,p_data3});\n";
       print FH " u3_i$j.sg_i$j.s3_$i.connect({p_data1,p_data2,p_data3});\n";
   }
    print FH "  }\n";
    print FH "};\n";
    print FH "\n";
}
}
#sg.sg.sig.connect({port1,port2...})
    if($i>50 && $i<=70){
        print FH "csl_signal_group sg1 {\n";
        print FH "  csl_signal s1($br_1);\n";
        print FH "  csl_signal s2($br_2);\n";
        print FH "  csl_signal s3($br_3);\n";
        print FH "  csl_signal s4(br);\n";
        print FH "  csl_signal s5(br1);\n";
        print FH "  sg1() {\n";
        print FH "  }\n";
        print FH "};\n";
        print FH "\n";

        print FH "csl_signal_group sg2 {\n";
        print FH "  csl_signal s21($br_1);\n";
        print FH "  csl_signal s22($br_2);\n";
        print FH "  csl_signal s23($br_3);\n";
        print FH "  csl_signal s24(br);\n";
        print FH "  csl_signal s25(br1);\n";
        foreach(my $j=50; $j<=$i; $j++){
            print FH "  sg1  sg1_i$j;\n";
          }
        print FH "  sg2() {\n";
        print FH "  }\n";
        print FH "};\n";
        print FH "\n";

        print FH " csl_unit u1_$i {\n";
        print FH "   csl_port p11(input,$br_1);\n";
        print FH "   csl_port p12(input,br);\n";
        print FH "   csl_port p13(output,$br_2);\n";
        print FH "   sg1  sg1i;\n";
        print FH "     u1_$i(){\n";
        print FH "  }\n";
        print FH "};\n";
        print FH "\n";

        print FH " csl_unit u2_$i {\n";
        print FH "   csl_port p21(output,$br_1);\n";
        print FH "   csl_port p22(output,br);\n";
        print FH "   csl_port p23(input,$br_2);\n";
        print FH "   csl_signal s21(br1);\n";
        print FH "   csl_signal s22($br_2);\n";
        print FH "   sg2  sg2i;\n";
        print FH "     u2_$i(){\n";
        print FH "  }\n";
        print FH "};\n";
        print FH "\n";
    
   if ($i>50 && $i<=60){
       print FH "csl_unit top1 {\n";
       print FH "   csl_port pt11(input,br);\n";
       print FH "   csl_port pt12(input,$br_1);\n";
       print FH "   csl_port pt13(input);\n";
       print FH "   csl_port pt14(output,$br_1);\n";
    
       print FH "   sg2   sg2_$i;\n";
       print FH "   sg1   sg1_$i;\n\n";
       print FH "   u1_$i  u1_i$i;\n";
       print FH "   u2_$i  u2_i$i;\n";
      
       print FH "   top1(){\n";
      
       print FH "    u1_i$i.sg1i.s1.connect(pt12);\n";
       print FH "    u1_i$i.sg1i.s2.connect({pt11,pt13});\n";
       print FH "    u1_i$i.sg1i.s3.connect({pt14,pt12,pt13});\n";
   
       print FH "    u2_i$i.sg2i.s21.connect(pt12);\n";
       print FH "    u2_i$i.sg2i.s22.connect({pt11,1'b1});\n";
       print FH " }\n";
       print FH "};\n";
       print FH "\n";
   }
 if($i>60 && $i<=70){
     print FH " csl_unit top1{\n";
       print FH "   csl_port pt11(input,br);\n";
       print FH "   csl_port pt12(input,$br_1);\n";
       print FH "   csl_port pt13(input);\n";
       print FH "   csl_port pt14(output,$br_1);\n";
     foreach(my $j=60; $j<=$i; $j++){
     print FH "   u1_$i  u1_i$j;\n";
     }
     print FH "   u2_$i  u2_i$i;\n";
     foreach(my $j=60; $j<=$i; $j++){
     print FH "   sg1  sgt1_i$j;\n";
     }
     print FH " top1(){\n";
       foreach(my $j=60; $j<=$i; $j++){
         
               print FH " u2_i$i.sg2i.s21.connect(pt14);\n";
               print FH " u2_i$i.sg2i.s22.connect({pt11,1'b0});\n";
               print FH " u2_i$i.sg2i.s23.connect({pt12,pt14,pt11});\n";
               print FH " u2_i$i.sg2i.s24.connect(pt11);\n";                    

       }
       print FH " }\n";
       print FH "};\n";
       print FH "\n";
     print FH " csl_unit top2{\n";
     print FH "  csl_port pt21(input,br);\n";
     print FH "  csl_port pt22(input,br1);\n";
     print FH "  csl_port pt23(input,$br_1);\n";
     print FH "  csl_port pt24(output,$br_1);\n";
     print FH "  csl_port pt25(input);\n";
     print FH "  top1 top1i;\n";
     print FH "   top2(){\n";
 foreach(my $j=60; $j<=$i; $j++){
     print FH "   top1i.sgt1_i$j.s1.connect({pt21,pt22});\n";
     print FH "   top1i.sgt1_i$j.s2.connect({pt21,pt25});\n";
     print FH "   top1i.sgt1_i$j.s3.connect({pt23,pt24,pt21});\n";
     print FH "   top1i.sgt1_i$j.s5.connect(pt22);\n";
      }   
       print FH " }\n";
       print FH "};\n";
       print FH "\n";
 }

    }
}
#***********************************************
# sg.sig[part_select].connect({concat_expr});

    if ($i>70 && $i<=80){
    print FH "//Generated by Monica\n";
    print FH "//Connect sg.sig[part_select]--concat_exp\n\n";
    print FH "// VALID TEST $i;\n";
    print FH "csl_bitrange br($val);\n";
    print FH "csl_bitrange br1($val1);\n\n";

   my $o = 0;
        
         
      foreach( my $j=71; $j<=$i; $j++){
          my $k=2*$j;
          my $l=3*$j;
         print FH " csl_signal_group sg1_$j {\n";
         print FH "   csl_signal  s11_$j($k);\n";
         print FH "   csl_signal  s12_$j($l);\n";
         print FH " sg1_$j(){}\n";
         print FH " };\n";
    }
        
         print FH " csl_unit u1{\n";
      foreach( my $j=71; $j<=$i; $j++){
          
          print FH "   csl_port p11_$j(input,$j);\n";
          print FH "   csl_port p12_$j(output,$j);\n";
          print FH "   sg1_$j  sg_1i$j;\n";         
     }

         print FH "  u1(){}\n";
         print FH " };\n";
        
         print FH " csl_unit u2{\n";
         
        foreach( my $j=71; $j<=$i; $j++){
       my   $k=$j-1;
       my   $l=$j-3;
          print FH "   csl_port p21_$j(input,$j);\n";
          print FH "   csl_port p22_$j(output,$j);\n";
          print FH "   csl_port p23_$j(output,$k);\n";
          print FH "   csl_port p24_$j(input,$l);\n";
          print FH "   csl_port p25_$j(input,$j);\n";
                 
         print FH " sg1_$j sg_2i$j;\n"; 
      }
         print FH "    u1 u1_i;\n";
         print FH " u2(){\n";
    foreach( my $j=71; $j<=$i; $j++){
      my $k=2*$j;
      my $l=3*$j;
      my $ui=$k-1;                             #upper_index
      my $k1=$l-1;
      
         print FH " sg1_2i$j.s11_$j [$o: $ui].connect({p21_$j,p22_$j});\n";  
         print FH " sg1_2i$j.s12_$j [$o: $k1].connect({p21_$j,p22_$j,p25_$j});\n";  
         print FH " sg1_2i$j.s11_$j [$o: $ui].connect({p21_$j,p24_$j,3'b001});\n"; 
         print FH " u1_i.sg1_1i$j.s11_$j [$o: $ui].connect({p21_$j,p24_$j,3'b111});\n"; 
         print FH " u1_i.sg1_1i$j.s12_$j [$o: $k1].connect({p21_$j,p24_$j,3'b111,p23_$j,1'b0});\n"
     
        }
  
         print FH "}\n";
         print FH " };\n"; 
     }

#***********************************************************************
# sg.sg1.sig[part_select].connect({concat_expr});
 if($i>80 && $i<=90){
    print FH "//Generated by Monica\n";
    print FH "//Connect SG.sg1.signal[part_select]--concat_expr\n\n";
    print FH "// TEST $i;\n";
my $o=0;
     print FH " csl_bitrange br1($val1);\n";
     print FH " csl_bitrange br2($val2);\n\n";

foreach( my $j=81; $j<=$i; $j++){
          my $k=2*$j;
          my $l=3*$j;
         print FH " csl_signal_group sg1_$j {\n";
         print FH "   csl_signal  s11_$j($k);\n";
         print FH "   csl_signal  s12_$j($l);\n";
     
         print FH " sg1_$j(){}\n";
         print FH " };\n";
    }
       
    print FH " csl_signal_group sg2{\n";
    print FH "  csl_signal s21(br1);\n";
    print FH "  csl_signal s22(br3);\n";
 foreach( my $j=81; $j<=$i; $j++){
         
         print FH " sg1_$j sg1_i$j;\n"; 
      }
    print FH " sg2(){}\n";
    print FH " };\n";
 
         print FH " csl_unit u1{\n";
     foreach( my $j=81; $j<=$i; $j++){
     
         print FH "   csl_port p11_$j(input,$j);\n";
         print FH "   csl_port p12_$j(output,$j);\n";
     
        }
         print FH " sg2  sg2_1i;\n";
         print FH "  u1(){}\n";
         print FH " };\n";

         print FH " csl_unit u2{\n";
     foreach( my $j=81; $j<=$i; $j++){
      my    $k=$j-1;
      my    $l=$j-3;
          print FH "   csl_port p21_$j(input,$j);\n";
          print FH "   csl_port p22_$j(output,$j);\n";
          print FH "   csl_port p23_$j(output,$k);\n";
          print FH "   csl_port p24_$j(input,$l);\n";
          print FH "   csl_port p25_$j(input,$j);\n";
      }
         print FH "    u1 u1_i;\n";
         print FH "    sg2 sg2_2i;\n"; 
         print FH " u2(){\n";
    foreach( my $j=81; $j<=$i; $j++){
      my $k=2*$j;
      my $l=3*$j;
      my $ui=$k-1;                             #upper_index
      my $k1=$l-1;      
  
         print FH " sg2_2i.sg1_i$j.s11_$j [$o:$ui].connect({p21_$j,p22_$j});\n";  
         print FH " sg2_2i.sg1_i$j.s12_$j [$o:$k1].connect({p21_$j,p22_$j,p25_$j});\n";  
         print FH " sg2_2i.sg1_i$j.s11_$j [$o: $ui].connect({p21_$j,p24_$j,3'b001});\n"; 
         print FH " u1_i.sg2_1i.sg1_i$j.s11_$j [$o: $ui].connect({p21_$j,p24_$j,3'b111});\n"; 
         print FH " u1_i.sg2_1i.sg1_i$j.s12_$j [$o: $k1].connect({p21_$j,p24_$j,3'b000,p23_$j,1'b0});\n" ; 
  
   }   
    print FH " }\n";
    print FH " };\n";
 
print FH " csl_unit  top_$i {\n";
print FH "   u2 u2_i;\n";
print FH "   sg2 sg2_3i;\n";
print FH "   top_$i(){\n";
   foreach( my $j=81; $j<=$i; $j++){
      my $k=2*$j;
      my $l=3*$j;
      my $ui=$k-1;                             #upper_index
      my $k1=$l-1;      
        
         print FH " sg2_3i.sg1_i$j.s11_$j [$o:$ui].connect({p21_$j,p22_$j});\n"; 
         print FH " sg2_3i.sg1_i$j.s12_$j [$o: $k1].connect({p21_$j,p24_$j,3'b011,p23_$j,1'b0});\n" ; 
         print FH " u2_i.sg2_2i.sg1_i$j.s11_$j [$o:$ui].connect({p21_$j,p22_$j});\n";  
         print FH " u2_i.sg2_2i.sg1_i$j.s12_$j [$o:$k1].connect({p21_$j,p22_$j,p25_$j});\n";  
         print FH " u2_i.sg2_2i.sg1_i$j.s11_$j [$o: $ui].connect({p21_$j,p24_$j,3'b001});\n"; 
         print FH " u2_i.u1_i.sg2_1i.sg1_i$j.s11_$j [$o: $ui].connect({p21_$j,p24_$j,3'b101});\n"; 
         print FH " u2_i.u1_i.sg2_1i.sg1_i$j.s12_$j [$o: $k1].connect({p21_$j,p24_$j,3'b111,p23_$j,1'b0});\n" ; 
  
   }   
    print FH " }\n";
    print FH " };\n";
 
}
}
    
    close(FH);
}
