#!/usr/bin/perl

#Author Anamaria
#Modified by Monica
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}
 my $path = "$ENV{WORK}/test/csl_test_gen";
print "Generated tests path: $path/f2a_ifc_ifc_p_valid/\n";

foreach (my $k = 1; $k <= 20; $k++) {
 my @a1 = ("s1_sg1_$k", "s2_sg1_$k", "s3_sg1_$k", "p1_ifc1_$k", "p2_ifc1_$k", "p3_ifc1_$k", "p1_ifc2_$k", "p2_ifc2_$k", "s1_sg2_$k","p1_ifc3_$k", "p2_ifc3_$k", "s1_sg3_$k", "s2_sg3_$k");
 my @a2 = ("s1_sg1_$k", "s2_sg1_$k", "p1_ifc1_$k", "p2_ifc1_$k", "p1_ifc2_$k", "p3_ifc2_$k", "p2_ifc3_$k", "s3_sg1_$k", "s1_sg2_$k");
 my @a3 = ("p2_ifc1_$k", "p1_ifc1_$k","s1_sg1_$k", "s2_sg1_$k", "s3_sg1_$k", "s1_sg2_$k", "p1_ifc2_$k", "p3_ifc2_$k", "p1_ifc3_$k", "s1_sg3_$k", "s2_sg3_$k");
 my @a4 = ("p2_ifc1_$k", "p3_ifc1_$k", "s1_sg1_$k", "s2_sg1_$k", "s3_sg1_$k", "s1_sg2_$k", "p2_ifc2_$k", "p4_ifc2_$k", "p3_ifc2_$k", "s1_sg3_$k", "s2_sg3_$k", "p1_ifc3_$k");
    my $ctests;
    if($k <= 5) {   
        foreach my $u (@a1) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        }
    }
    elsif($k > 5 && $k <= 10) {
         foreach my $u(@a2) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
    elsif($k > 10 && $k <= 15) {
         foreach my $u(@a3) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
    elsif($k > 15 && $k <= 20) {
         foreach my $u(@a4) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
}
sub main {     
    my ($k, $ctests, $u) = @_; 
    my $test_name = "f2a_ifc_ifc_p_sg_s_or_ifc_ifc_p_ifc_ifc_p".$k."_".$u."_legal.csl";
    &createCslFile($test_name, $k, $ctests);
}
   
sub createCslFile {
    my($test_name, $k, $ctests) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen";
    my $val1 = int(rand(300));
    my $val2 = int(rand(50));
    
    if($val1 == 0) { $val1 = 1; }
    if($val2 == 0) { $val2 = 1; }
    my $val3 = $val1 + $val2;
    
	my $zero=0;
        my $v1=$val1-1;
        my $v2=$val2-1;
        my $v3=$val3-1;
    
    &mkDir("$path/f2a_ifc_ifc_p_valid");
    open(FH,">$path/f2a_ifc_ifc_p_valid/$test_name");
    
      
    print FH "// Generated by  AnamariaH \n";
    print FH "// Test cases from: Interconnect_F2A_matrix.ods \n";
  if(($k <= 5) || ($k>10 && $k<=15)){ 
    print FH "csl_signal_group sg1{ \n";
    print FH "csl_signal p11_$k($val1); \n";
    print FH "csl_signal p12_$k($val3); \n";
    print FH "csl_signal p13_$k($val2); \n";
    print FH " sg1() {} \n";
    print FH "};\n";

    print FH "csl_signal_group sg2{ \n";
    print FH "  sg1 sgn1; \n";
    print FH "csl_signal p21_$k($val2); \n";
    print FH "csl_signal p22_$k($val2); \n";
    print FH "  sg2() {} \n";
    print FH "};\n";

    print FH "csl_signal_group sg3{ \n";
    print FH "  sg1 sgn1;\n";
    print FH "  sg2 sgn2; \n";
    print FH "csl_signal p31_$k($val3); \n";
    print FH "csl_signal p32_$k($val2); \n";
    print FH "  sg3() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc1{ \n";
    print FH "csl_port p11_$k(input,$val1); \n";
    print FH "csl_port p12_$k(output,$val3); \n";
    print FH "csl_port p13_$k(input,$val2); \n";
    print FH "  ifc1() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc2{ \n";
    print FH " ifc1 inter1; \n";
    print FH "csl_port p21_$k(input,$val2);\n";
    print FH "csl_port p22_$k(output,$val2);\n";
    print FH "  ifc2() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc3{ \n";
    print FH "  ifc1 inter1; \n";
    print FH "  ifc2 inter2; \n";
    print FH "csl_port p31_$k(output,$val3); \n";
    print FH "csl_port p32_$k(input,$val2); \n";
    print FH "  ifc3() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc4{ \n";
    print FH "  ifc3 inter3; \n";
    print FH "csl_port p41_$k(input,$val1); \n";
    print FH "csl_port p42_$k(output,$val2); \n";
    print FH "csl_port p43_$k(output,$val1); \n";
    print FH "  ifc4() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc5{ \n";
    print FH "  ifc4 inter4; \n";
    print FH "  ifc3 inter31; \n";
    print FH "  ifc1 inter11; \n";
    print FH "  ifc5() {} \n";
    print FH "};\n";

    print FH "csl_unit unit_a{ \n";
    print FH "  ifc1 inter12; \n";
    print FH "  ifc2 inter21; \n";
    print FH "  unit_a() { \n"; 
    print FH " } \n";
    print FH "}; \n";

    print FH "csl_unit unit_b{ \n";
    
    print FH "  ifc3 inter32; \n";
    print FH "  sg2 sgn21; \n";
    print FH "  sg1 sgn11;\n";
    print FH "  ifc5 inter51;\n";
    if($k<=5){
    print FH "  unit_a a0(.inter21(sgn21),.inter12.p11_$k(sgn11.p11_$k),.inter12.p12_$k(sgn11.p12_$k),.inter12.p13_$k(sgn11.p13_$k));  // f2a: ifc(sg), ifc.p(sg.s)  \n"; 
    }
    elsif($k>10 && $k<=15){
    print FH "  unit_a a0(.inter21(sgn21),.inter12.p11_$k(sgn11.p11_$k [$v1:$zero]),.inter12.p12_$k(sgn11.p12_$k [$v3:$zero]),.inter12.p13_$k(sgn11.p13_$k [$v2:$zero]));  // f2a: ifc(sg), ifc.p(sg.s.ps)  \n"; 
   }
    print FH "   unit_b() { \n"; 
    print FH " } \n";
    print FH "}; \n";

    print FH "csl_unit unit_c{ \n";
#    print FH " sg2 sgn2; \n";
    print FH " ifc3 inter33; \n";
    print FH " ifc3 inter34; \n";
    print FH " ifc5 inter52;\n";
    print FH " ifc5 inter53;\n";
   if($k<=5){   
	print FH " unit_b b0(.inter32.inter2.p21_$k(inter33.inter2.p21_$k),.inter32.inter2.p22_$k(inter33.inter2.p22_$k),.inter32.inter2.inter1(inter33.inter2.inter1),   //f2a: ifc.ifc.p(ifc.ifc.p), ifc.ifc.ifc(sg.sg.sg)\n";
        print FH "           .inter32.inter1(inter33.inter1),.inter32.p31_$k(inter33.p31_$k),.inter32.p32_$k(inter33.p32_$k),  // f2a: ifc.ifc(ifc.ifc),ifc.p(ifc.p) \n";
        print FH "           .inter51(inter52));  // f2a: ifc(ifc) \n";
        print FH " unit_b b1(.inter32.inter2.p21_$k(inter34.inter2.p21_$k),.inter32.inter2.p22_$k(inter34.inter2.p22_$k),.inter32.inter2.inter1(inter34.inter2.inter1),   //f2a: ifc.ifc.p(ifc.ifc.p)\n";
        print FH "           .inter32.inter1(inter34.inter1),.inter32.p31_$k(inter34.p31_$k),.inter32.p32_$k(inter34.p32_$k),.inter51(inter53));  // f2a: ifc.ifc(ifc.ifc),ifc.p(ifc.p), ifc(ifc) \n";
    }

 elsif($k>10 && $k<=15){
 	print FH " unit_b b0(.inter32.inter2.p21_$k(inter33.inter2.p21_$k [$v2:$zero]),.inter32.inter2.p22_$k(inter33.inter2.p22_$k [$v2:$zero]),.inter32.inter2.inter1(inter33.inter2.inter1),   //f2a: ifc.ifc.p(ifc.ifc.p.ps), ifc.ifc.ifc(sg.sg.sg)\n";
        print FH "           .inter32.inter1(inter33.inter1),.inter32.p31_$k(inter33.p31_$k [$v3:$zero]),.inter32.p32_$k(inter33.p32_$k [$v2:$zero]),  // f2a: ifc.ifc(ifc.ifc),ifc.p(ifc.p.ps) \n";
        print FH "           .inter51(inter52));  // f2a: ifc(ifc) \n";
        print FH " unit_b b1(.inter32.inter2.p21_$k(inter34.inter2.p21_$k [$v2:$zero]),.inter32.inter2.p22_$k(inter34.inter2.p22_$k [$v2:$zero]),.inter32.inter2.inter1(inter34.inter2.inter1),   //f2a: ifc.ifc.p(ifc.ifc.p.ps)\n";
        print FH "           .inter32.inter1(inter34.inter1),.inter32.p31_$k(inter34.p31_$k [$v3:$zero]),.inter32.p32_$k(inter34.p32_$k [$v2:$zero]),.inter51(inter53));  // f2a: ifc.ifc(ifc.ifc),ifc.p(ifc.p.ps), ifc(ifc) \n";
 }
}
    
    elsif(($k > 5 && $k <=10) || ($k>15 && $k<=20)){

    print FH "csl_unit unit_a{ \n";
    print FH " csl_port p1(input,$val1); \n";
    print FH " csl_port p2(output,$val2); \n";
    print FH "  unit_a() { \n"; 
    print FH " } \n";
    print FH "}; \n";

    print FH "csl_unit unit_b{ \n";
    print FH " csl_port p1(input,$val1); \n";
    print FH " csl_port p2(output,$val3);\n";
    print FH " csl_signal s1($val2); \n";
	if($k <=10 ){
    print FH " unit_a a1(.p1(p1),.p2(s1));  //f2a: port(port), port(sig)\n";
     }
	elsif ($k>15){
   print FH " unit_a a1(.p1(p1[$v1:$zero]),.p2(s1[$v2:$zero]));  //f2a: port(port.ps), port(sig.ps)\n";
	}
    print FH "  unit_b() { \n"; 
    print FH " } \n";
    print FH "}; \n";
  
    print FH " csl_unit unit_c{\n";
    print FH " csl_port p11(input,$val1);\n";
    print FH " csl_port p12(input,$val1);\n";
    print FH " csl_signal s1($val3);\n";
	if($k<=10){
    print FH " unit_b b1(.p1(p11),.p2(s1)); //f2a: port(port), port(sig)\n";
    print FH " unit_b b2(.p1(p12),.p2(s1));\n";
     }
	if($k>15){
     print FH " unit_b b1(.p1(p11[$v1:$zero]),.p2(s1[$v3:$zero])); //f2a: port(port.ps), port(sig.ps)\n";
     print FH " unit_b b2(.p1(p12[$v1:$zero]),.p2(s1[$v3:$zero]));\n";
	}

   
    }

 
    print FH "   unit_c() { \n"; 
    print FH " } \n";
    print FH "}; \n";

 if($k <= 5) {
    print FH "csl_unit unit_top{ \n";
    print FH "  sg3 sgn31; \n";
    print FH "  ifc3 inter35; \n";
    print FH "  ifc5 inter54; \n";
    print FH "  ifc5 inter55;\n";
   

	print FH "  unit_c c0(.inter33.inter2.p22_$k(sgn31.sgn2.p22_$k),.inter33.inter2.p21_$k(sgn31.sgn2.p21_$k),.inter33.inter2.inter1(sgn31.sgn2.sgn1), //f2a: ifc.ifc.p(sg.sg.s), ifc.ifc.ifc(sg.sg.sg) \n";
        print FH "            .inter33.inter1(sgn31.sgn1),.inter33.p31_$k(sgn31.p31_$k),.inter33.p32_$k(sgn31.p32_$k),  //f2a: ifc.ifc(sg.sg), ifc.p(sg.s)\n";
        print FH "            .inter52(inter54),.inter53(inter55),.inter34(inter35));                                   //ifc(ifc)\n";
  
    
   
    print FH "  unit_top() { \n";  
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
 }  
    close(FH);

}
