`ifndef INC_GUARD_eu
`define INC_GUARD_eu

`define IFC_RF_EU_RFI_P_RD_DATA_A_UPPER_INDEX  (32-1)
`define IFC_RF_EU_RFI_P_RD_DATA_A_LOWER_INDEX  (0)
`define IFC_RF_EU_RFI_P_RD_DATA_A_WIDTH  (32)
`define IFC_RF_EU_RFI_P_RD_DATA_A_RANGE `IFC_RF_EU_RFI_P_RD_DATA_A_UPPER_INDEX:`IFC_RF_EU_RFI_P_RD_DATA_A_LOWER_INDEX
`define IFC_RF_EU_RFI_P_RD_DATA_B_UPPER_INDEX  (32-1)
`define IFC_RF_EU_RFI_P_RD_DATA_B_LOWER_INDEX  (0)
`define IFC_RF_EU_RFI_P_RD_DATA_B_WIDTH  (32)
`define IFC_RF_EU_RFI_P_RD_DATA_B_RANGE `IFC_RF_EU_RFI_P_RD_DATA_B_UPPER_INDEX:`IFC_RF_EU_RFI_P_RD_DATA_B_LOWER_INDEX
`define IFC_EU_IM_OUT_P_RD_DATA_A_UPPER_INDEX  (32-1)
`define IFC_EU_IM_OUT_P_RD_DATA_A_LOWER_INDEX  (0)
`define IFC_EU_IM_OUT_P_RD_DATA_A_WIDTH  (32)
`define IFC_EU_IM_OUT_P_RD_DATA_A_RANGE `IFC_EU_IM_OUT_P_RD_DATA_A_UPPER_INDEX:`IFC_EU_IM_OUT_P_RD_DATA_A_LOWER_INDEX
`define IFC_EU_IM_OUT_P_RD_DATA_B_UPPER_INDEX  (32-1)
`define IFC_EU_IM_OUT_P_RD_DATA_B_LOWER_INDEX  (0)
`define IFC_EU_IM_OUT_P_RD_DATA_B_WIDTH  (32)
`define IFC_EU_IM_OUT_P_RD_DATA_B_RANGE `IFC_EU_IM_OUT_P_RD_DATA_B_UPPER_INDEX:`IFC_EU_IM_OUT_P_RD_DATA_B_LOWER_INDEX
`define IFC_EU_RF_OUT_P_RD_DATA_A_UPPER_INDEX  (32-1)
`define IFC_EU_RF_OUT_P_RD_DATA_A_LOWER_INDEX  (0)
`define IFC_EU_RF_OUT_P_RD_DATA_A_WIDTH  (32)
`define IFC_EU_RF_OUT_P_RD_DATA_A_RANGE `IFC_EU_RF_OUT_P_RD_DATA_A_UPPER_INDEX:`IFC_EU_RF_OUT_P_RD_DATA_A_LOWER_INDEX
`define IFC_EU_RF_OUT_P_RD_DATA_B_UPPER_INDEX  (32-1)
`define IFC_EU_RF_OUT_P_RD_DATA_B_LOWER_INDEX  (0)
`define IFC_EU_RF_OUT_P_RD_DATA_B_WIDTH  (32)
`define IFC_EU_RF_OUT_P_RD_DATA_B_RANGE `IFC_EU_RF_OUT_P_RD_DATA_B_UPPER_INDEX:`IFC_EU_RF_OUT_P_RD_DATA_B_LOWER_INDEX
`define IFC_BR_IN_P_QUAL_BR_UPPER_INDEX  (1-1)
`define IFC_BR_IN_P_QUAL_BR_LOWER_INDEX  (0)
`define IFC_BR_IN_P_QUAL_BR_WIDTH  (1)
`define IFC_BR_IN_P_QUAL_BR_RANGE `IFC_BR_IN_P_QUAL_BR_UPPER_INDEX:`IFC_BR_IN_P_QUAL_BR_LOWER_INDEX

`endif
