`ifndef INC_GUARD_pc
`define INC_GUARD_pc

`define IFC_ME_CNTL_OUT_P_V_UPPER_INDEX  (1-1)
`define IFC_ME_CNTL_OUT_P_V_LOWER_INDEX  (0)
`define IFC_ME_CNTL_OUT_P_V_WIDTH  (1)
`define IFC_ME_CNTL_OUT_P_V_RANGE `IFC_ME_CNTL_OUT_P_V_UPPER_INDEX:`IFC_ME_CNTL_OUT_P_V_LOWER_INDEX
`define IFC_ME_CNTL_OUT_P_PC_UPPER_INDEX  (8-1)
`define IFC_ME_CNTL_OUT_P_PC_LOWER_INDEX  (0)
`define IFC_ME_CNTL_OUT_P_PC_WIDTH  (8)
`define IFC_ME_CNTL_OUT_P_PC_RANGE `IFC_ME_CNTL_OUT_P_PC_UPPER_INDEX:`IFC_ME_CNTL_OUT_P_PC_LOWER_INDEX
`define IFC_ME_CNTL_OUT_P_NPC_UPPER_INDEX  (8-1)
`define IFC_ME_CNTL_OUT_P_NPC_LOWER_INDEX  (0)
`define IFC_ME_CNTL_OUT_P_NPC_WIDTH  (8)
`define IFC_ME_CNTL_OUT_P_NPC_RANGE `IFC_ME_CNTL_OUT_P_NPC_UPPER_INDEX:`IFC_ME_CNTL_OUT_P_NPC_LOWER_INDEX
`define IFC_ME_CNTL_OUT_P_IR_UPPER_INDEX  (32-1)
`define IFC_ME_CNTL_OUT_P_IR_LOWER_INDEX  (0)
`define IFC_ME_CNTL_OUT_P_IR_WIDTH  (32)
`define IFC_ME_CNTL_OUT_P_IR_RANGE `IFC_ME_CNTL_OUT_P_IR_UPPER_INDEX:`IFC_ME_CNTL_OUT_P_IR_LOWER_INDEX
`define IFC_ME_CNTL_OUT_P_BR_OFFSET_UPPER_INDEX  (8-1)
`define IFC_ME_CNTL_OUT_P_BR_OFFSET_LOWER_INDEX  (0)
`define IFC_ME_CNTL_OUT_P_BR_OFFSET_WIDTH  (8)
`define IFC_ME_CNTL_OUT_P_BR_OFFSET_RANGE `IFC_ME_CNTL_OUT_P_BR_OFFSET_UPPER_INDEX:`IFC_ME_CNTL_OUT_P_BR_OFFSET_LOWER_INDEX

`endif
