`ifndef INC_GUARD_arb
`define INC_GUARD_arb

`define IFC_ADWR_P_ADDR_UPPER_INDEX  17
`define IFC_ADWR_P_ADDR_LOWER_INDEX  0
`define IFC_ADWR_P_ADDR_WIDTH  18
`define IFC_ADWR_P_ADDR_RANGE `IFC_ADWR_P_ADDR_UPPER_INDEX:`IFC_ADWR_P_ADDR_LOWER_INDEX
`define IFC_ADWR_P_DATA_UPPER_INDEX  31
`define IFC_ADWR_P_DATA_LOWER_INDEX  0
`define IFC_ADWR_P_DATA_WIDTH  32
`define IFC_ADWR_P_DATA_RANGE `IFC_ADWR_P_DATA_UPPER_INDEX:`IFC_ADWR_P_DATA_LOWER_INDEX
`define IFC_ADWR_P_WR_UPPER_INDEX  0
`define IFC_ADWR_P_WR_LOWER_INDEX  0
`define IFC_ADWR_P_WR_WIDTH  1
`define IFC_ADWR_P_WR_RANGE `IFC_ADWR_P_WR_UPPER_INDEX:`IFC_ADWR_P_WR_LOWER_INDEX
`define IFC_ADWR_P_RD_UPPER_INDEX  0
`define IFC_ADWR_P_RD_LOWER_INDEX  0
`define IFC_ADWR_P_RD_WIDTH  1
`define IFC_ADWR_P_RD_RANGE `IFC_ADWR_P_RD_UPPER_INDEX:`IFC_ADWR_P_RD_LOWER_INDEX

`endif
