`ifndef INC_GUARD_doorbell
`define INC_GUARD_doorbell

`define IFC_VRR_P_VALID_UPPER_INDEX  0
`define IFC_VRR_P_VALID_LOWER_INDEX  0
`define IFC_VRR_P_VALID_WIDTH  1
`define IFC_VRR_P_VALID_RANGE `IFC_VRR_P_VALID_UPPER_INDEX:`IFC_VRR_P_VALID_LOWER_INDEX
`define IFC_VRR_P_RD_UPPER_INDEX  0
`define IFC_VRR_P_RD_LOWER_INDEX  0
`define IFC_VRR_P_RD_WIDTH  1
`define IFC_VRR_P_RD_RANGE `IFC_VRR_P_RD_UPPER_INDEX:`IFC_VRR_P_RD_LOWER_INDEX
`define IFC_VRR_P_RESULT_UPPER_INDEX  31
`define IFC_VRR_P_RESULT_LOWER_INDEX  0
`define IFC_VRR_P_RESULT_WIDTH  32
`define IFC_VRR_P_RESULT_RANGE `IFC_VRR_P_RESULT_UPPER_INDEX:`IFC_VRR_P_RESULT_LOWER_INDEX
`define IFC_DW_P_DATA_UPPER_INDEX  31
`define IFC_DW_P_DATA_LOWER_INDEX  0
`define IFC_DW_P_DATA_WIDTH  32
`define IFC_DW_P_DATA_RANGE `IFC_DW_P_DATA_UPPER_INDEX:`IFC_DW_P_DATA_LOWER_INDEX
`define IFC_DW_P_WR_UPPER_INDEX  0
`define IFC_DW_P_WR_LOWER_INDEX  0
`define IFC_DW_P_WR_WIDTH  1
`define IFC_DW_P_WR_RANGE `IFC_DW_P_WR_UPPER_INDEX:`IFC_DW_P_WR_LOWER_INDEX

`endif
