`ifndef INC_GUARD_fabric_dma
`define INC_GUARD_fabric_dma

`define IFC_SBFD_P_START_UPPER_INDEX  0
`define IFC_SBFD_P_START_LOWER_INDEX  0
`define IFC_SBFD_P_START_WIDTH  1
`define IFC_SBFD_P_START_RANGE `IFC_SBFD_P_START_UPPER_INDEX:`IFC_SBFD_P_START_LOWER_INDEX
`define IFC_SBFD_P_BUSY_UPPER_INDEX  0
`define IFC_SBFD_P_BUSY_LOWER_INDEX  0
`define IFC_SBFD_P_BUSY_WIDTH  1
`define IFC_SBFD_P_BUSY_RANGE `IFC_SBFD_P_BUSY_UPPER_INDEX:`IFC_SBFD_P_BUSY_LOWER_INDEX

`endif
