`ifndef INC_GUARD_maclu
`define INC_GUARD_maclu

`define IFC_MALT_P_BUSY_UPPER_INDEX  0
`define IFC_MALT_P_BUSY_LOWER_INDEX  0
`define IFC_MALT_P_BUSY_WIDTH  1
`define IFC_MALT_P_BUSY_RANGE `IFC_MALT_P_BUSY_UPPER_INDEX:`IFC_MALT_P_BUSY_LOWER_INDEX
`define IFC_MALT_P_HIT_UPPER_INDEX  0
`define IFC_MALT_P_HIT_LOWER_INDEX  0
`define IFC_MALT_P_HIT_WIDTH  1
`define IFC_MALT_P_HIT_RANGE `IFC_MALT_P_HIT_UPPER_INDEX:`IFC_MALT_P_HIT_LOWER_INDEX
`define IFC_MALT_P_PORT_UPPER_INDEX  0
`define IFC_MALT_P_PORT_LOWER_INDEX  0
`define IFC_MALT_P_PORT_WIDTH  1
`define IFC_MALT_P_PORT_RANGE `IFC_MALT_P_PORT_UPPER_INDEX:`IFC_MALT_P_PORT_LOWER_INDEX
`define IFC_MALT_P_START_UPPER_INDEX  0
`define IFC_MALT_P_START_LOWER_INDEX  0
`define IFC_MALT_P_START_WIDTH  1
`define IFC_MALT_P_START_RANGE `IFC_MALT_P_START_UPPER_INDEX:`IFC_MALT_P_START_LOWER_INDEX
`define IFC_ADW_P_ADDR_UPPER_INDEX  17
`define IFC_ADW_P_ADDR_LOWER_INDEX  0
`define IFC_ADW_P_ADDR_WIDTH  18
`define IFC_ADW_P_ADDR_RANGE `IFC_ADW_P_ADDR_UPPER_INDEX:`IFC_ADW_P_ADDR_LOWER_INDEX
`define IFC_ADW_P_DATA_UPPER_INDEX  31
`define IFC_ADW_P_DATA_LOWER_INDEX  0
`define IFC_ADW_P_DATA_WIDTH  32
`define IFC_ADW_P_DATA_RANGE `IFC_ADW_P_DATA_UPPER_INDEX:`IFC_ADW_P_DATA_LOWER_INDEX
`define IFC_ADW_P_WR_UPPER_INDEX  0
`define IFC_ADW_P_WR_LOWER_INDEX  0
`define IFC_ADW_P_WR_WIDTH  1
`define IFC_ADW_P_WR_RANGE `IFC_ADW_P_WR_UPPER_INDEX:`IFC_ADW_P_WR_LOWER_INDEX

`endif
