`ifndef INC_GUARD_put_dma
`define INC_GUARD_put_dma

`define IFC_CDRV_P_CMD_UPPER_INDEX  0
`define IFC_CDRV_P_CMD_LOWER_INDEX  0
`define IFC_CDRV_P_CMD_WIDTH  1
`define IFC_CDRV_P_CMD_RANGE `IFC_CDRV_P_CMD_UPPER_INDEX:`IFC_CDRV_P_CMD_LOWER_INDEX
`define IFC_CDRV_P_DATA_UPPER_INDEX  31
`define IFC_CDRV_P_DATA_LOWER_INDEX  0
`define IFC_CDRV_P_DATA_WIDTH  32
`define IFC_CDRV_P_DATA_RANGE `IFC_CDRV_P_DATA_UPPER_INDEX:`IFC_CDRV_P_DATA_LOWER_INDEX
`define IFC_CDRV_P_READY_UPPER_INDEX  0
`define IFC_CDRV_P_READY_LOWER_INDEX  0
`define IFC_CDRV_P_READY_WIDTH  1
`define IFC_CDRV_P_READY_RANGE `IFC_CDRV_P_READY_UPPER_INDEX:`IFC_CDRV_P_READY_LOWER_INDEX
`define IFC_CDRV_P_VALID_UPPER_INDEX  0
`define IFC_CDRV_P_VALID_LOWER_INDEX  0
`define IFC_CDRV_P_VALID_WIDTH  1
`define IFC_CDRV_P_VALID_RANGE `IFC_CDRV_P_VALID_UPPER_INDEX:`IFC_CDRV_P_VALID_LOWER_INDEX
`define IFC_SB_P_START_UPPER_INDEX  0
`define IFC_SB_P_START_LOWER_INDEX  0
`define IFC_SB_P_START_WIDTH  1
`define IFC_SB_P_START_RANGE `IFC_SB_P_START_UPPER_INDEX:`IFC_SB_P_START_LOWER_INDEX
`define IFC_SB_P_BUSY_UPPER_INDEX  0
`define IFC_SB_P_BUSY_LOWER_INDEX  0
`define IFC_SB_P_BUSY_WIDTH  1
`define IFC_SB_P_BUSY_RANGE `IFC_SB_P_BUSY_UPPER_INDEX:`IFC_SB_P_BUSY_LOWER_INDEX

`endif
