`ifndef INC_GUARD_m1
`define INC_GUARD_m1

`define P_AR_SA0_S10_UPPER_INDEX  (1-1)
`define P_AR_SA0_S10_LOWER_INDEX  (0)
`define P_AR_SA0_S10_WIDTH  (1)
`define P_AR_SA0_S10_RANGE `P_AR_SA0_S10_UPPER_INDEX:`P_AR_SA0_S10_LOWER_INDEX

`endif
