`ifndef INC_GUARD_x1
`define INC_GUARD_x1

`define P_SX1_UPPER_INDEX  (0)
`define P_SX1_LOWER_INDEX  (0)
`define P_SX1_WIDTH  (0-0+1)
`define P_SX1_RANGE `P_SX1_UPPER_INDEX:`P_SX1_LOWER_INDEX
`define P_AR_SA0_S10_UPPER_INDEX  (1-1)
`define P_AR_SA0_S10_LOWER_INDEX  (0)
`define P_AR_SA0_S10_WIDTH  (1)
`define P_AR_SA0_S10_RANGE `P_AR_SA0_S10_UPPER_INDEX:`P_AR_SA0_S10_LOWER_INDEX

`endif
