`ifndef INC_GUARD_arm
`define INC_GUARD_arm

`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_DATA_UPPER_INDEX  (32-1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_DATA_LOWER_INDEX  (0)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_DATA_WIDTH  (32)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_DATA_RANGE `IFC_SLAVE_VA2R_TAP_ARM_P_READ_DATA_UPPER_INDEX:`IFC_SLAVE_VA2R_TAP_ARM_P_READ_DATA_LOWER_INDEX
`define IFC_SLAVE_VA2R_TAP_ARM_P_READY_UPPER_INDEX  (1-1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READY_LOWER_INDEX  (0)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READY_WIDTH  (1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READY_RANGE `IFC_SLAVE_VA2R_TAP_ARM_P_READY_UPPER_INDEX:`IFC_SLAVE_VA2R_TAP_ARM_P_READY_LOWER_INDEX
`define IFC_SLAVE_VA2R_TAP_ARM_P_ERROR_UPPER_INDEX  (1-1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_ERROR_LOWER_INDEX  (0)
`define IFC_SLAVE_VA2R_TAP_ARM_P_ERROR_WIDTH  (1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_ERROR_RANGE `IFC_SLAVE_VA2R_TAP_ARM_P_ERROR_UPPER_INDEX:`IFC_SLAVE_VA2R_TAP_ARM_P_ERROR_LOWER_INDEX
`define IFC_SLAVE_VA2R_TAP_ARM_P_ADDRESS_UPPER_INDEX  (20-1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_ADDRESS_LOWER_INDEX  (0)
`define IFC_SLAVE_VA2R_TAP_ARM_P_ADDRESS_WIDTH  (20)
`define IFC_SLAVE_VA2R_TAP_ARM_P_ADDRESS_RANGE `IFC_SLAVE_VA2R_TAP_ARM_P_ADDRESS_UPPER_INDEX:`IFC_SLAVE_VA2R_TAP_ARM_P_ADDRESS_LOWER_INDEX
`define IFC_SLAVE_VA2R_TAP_ARM_P_DATA_UPPER_INDEX  (32-1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_DATA_LOWER_INDEX  (0)
`define IFC_SLAVE_VA2R_TAP_ARM_P_DATA_WIDTH  (32)
`define IFC_SLAVE_VA2R_TAP_ARM_P_DATA_RANGE `IFC_SLAVE_VA2R_TAP_ARM_P_DATA_UPPER_INDEX:`IFC_SLAVE_VA2R_TAP_ARM_P_DATA_LOWER_INDEX
`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_UPPER_INDEX  (1-1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_LOWER_INDEX  (0)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_WIDTH  (1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_READ_RANGE `IFC_SLAVE_VA2R_TAP_ARM_P_READ_UPPER_INDEX:`IFC_SLAVE_VA2R_TAP_ARM_P_READ_LOWER_INDEX
`define IFC_SLAVE_VA2R_TAP_ARM_P_WRITE_UPPER_INDEX  (1-1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_WRITE_LOWER_INDEX  (0)
`define IFC_SLAVE_VA2R_TAP_ARM_P_WRITE_WIDTH  (1)
`define IFC_SLAVE_VA2R_TAP_ARM_P_WRITE_RANGE `IFC_SLAVE_VA2R_TAP_ARM_P_WRITE_UPPER_INDEX:`IFC_SLAVE_VA2R_TAP_ARM_P_WRITE_LOWER_INDEX
`define IFC_GBL_P_CLK_UPPER_INDEX  (1-1)
`define IFC_GBL_P_CLK_LOWER_INDEX  (0)
`define IFC_GBL_P_CLK_WIDTH  (1)
`define IFC_GBL_P_CLK_RANGE `IFC_GBL_P_CLK_UPPER_INDEX:`IFC_GBL_P_CLK_LOWER_INDEX
`define IFC_GBL_P_RESET__UPPER_INDEX  (1-1)
`define IFC_GBL_P_RESET__LOWER_INDEX  (0)
`define IFC_GBL_P_RESET__WIDTH  (1)
`define IFC_GBL_P_RESET__RANGE `IFC_GBL_P_RESET__UPPER_INDEX:`IFC_GBL_P_RESET__LOWER_INDEX
`define IFC_GBL_P_ENABLE_UPPER_INDEX  (1-1)
`define IFC_GBL_P_ENABLE_LOWER_INDEX  (0)
`define IFC_GBL_P_ENABLE_WIDTH  (1)
`define IFC_GBL_P_ENABLE_RANGE `IFC_GBL_P_ENABLE_UPPER_INDEX:`IFC_GBL_P_ENABLE_LOWER_INDEX

`endif
