`ifndef INC_GUARD_b_unit
`define INC_GUARD_b_unit

`define P_IN1_UPPER_INDEX  (4-1)
`define P_IN1_LOWER_INDEX  (0)
`define P_IN1_WIDTH  (4)
`define P_IN1_RANGE `P_IN1_UPPER_INDEX:`P_IN1_LOWER_INDEX
`define P_IN2_UPPER_INDEX  (0)
`define P_IN2_LOWER_INDEX  (0)
`define P_IN2_WIDTH  (0-0+1)
`define P_IN2_RANGE `P_IN2_UPPER_INDEX:`P_IN2_LOWER_INDEX
`define P_OUT1_UPPER_INDEX  (4-1)
`define P_OUT1_LOWER_INDEX  (0)
`define P_OUT1_WIDTH  (4)
`define P_OUT1_RANGE `P_OUT1_UPPER_INDEX:`P_OUT1_LOWER_INDEX
`define P_OUT2_UPPER_INDEX  (4-1)
`define P_OUT2_LOWER_INDEX  (0)
`define P_OUT2_WIDTH  (4)
`define P_OUT2_RANGE `P_OUT2_UPPER_INDEX:`P_OUT2_LOWER_INDEX
`define P_OUT3_UPPER_INDEX  (4-1)
`define P_OUT3_LOWER_INDEX  (0)
`define P_OUT3_WIDTH  (4)
`define P_OUT3_RANGE `P_OUT3_UPPER_INDEX:`P_OUT3_LOWER_INDEX
`define P_OUT4_UPPER_INDEX  (4-1)
`define P_OUT4_LOWER_INDEX  (0)
`define P_OUT4_WIDTH  (4)
`define P_OUT4_RANGE `P_OUT4_UPPER_INDEX:`P_OUT4_LOWER_INDEX
`define P_CLK_UPPER_INDEX  (0)
`define P_CLK_LOWER_INDEX  (0)
`define P_CLK_WIDTH  (0-0+1)
`define P_CLK_RANGE `P_CLK_UPPER_INDEX:`P_CLK_LOWER_INDEX

`endif
