#!/usr/bin/perl

#Author Anamaria
#Modified by Monica
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

print "Generated tests path: f2a_ifc_p_sg_s_valid/\n";

foreach (my $k = 1; $k <= 15; $k++) {
 my @a1 = ("s1_sg1_$k", "s2_sg1_$k", "p2_ifc1_$k", "p3_ifc1_$k", "p1_ifc2_$k", "p2_ifc2_$k", "p3_ifc2_$k", "s1_sg2_$k", "s2_sg2_$k", "s3_sg2_$k", "p1_ifc3_$k", "p2_ifc3_$k");
 my @a2 = ("s1_sg1_$k", "s2_sg1_$k", "p1_ifc1_$k", "p2_ifc1_$k", "p3_ifc1_$k", "p1_ifc2_$k", "p2_ifc2_$k","p4_ifc2_$k","s1_sg1_$k", "p1_ifc3_$k", "s2_sg1_$k", "s1_sg2_$k");
 my @a3 = ("p2_ifc1_$k", "p3_ifc1_$k", "s2_sg1_$k", "s1_sg2_$k", "s3_sg2_$k", "p1_ifc2_$k", "p3_ifc2_$k", "p4_ifc2_$k", "s_b_$k", "s_k2_$k", "p_out_$k", "s_u2_$k", "s_u3_$k");
 my @a4 = ("p1_ifc1_$k", "p2_ifc1_$k", "p3_ifc1_$k", "s1_sg1_$k", "s2_sg1_$k", "s1_sg2_$k", "s2_sg2_$k", "p1_ifc2_$k", "p4_ifc2_$k");
    my $ctests;
    if($k <= 5) {   
        foreach my $u (@a1) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        }
    }
    elsif($k > 5 && $k <= 10) {
         foreach my $u(@a2) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
    elsif($k > 10 && $k <= 15) {
         foreach my $u(@a3) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
    elsif($k > 15 && $k <= 20) {
         foreach my $u(@a4) {
            $ctests = $u; 
            &main($k, $ctests, $u);
        } 
     }
}
sub main {     
    my ($k, $ctests, $u) = @_; 
    my $test_name = "f2a_ifc_p_sg_s".$k."_".$u."_legal.csl";
    &createCslFile($test_name, $k, $ctests);
}
   
sub createCslFile {
    my($test_name, $k, $ctests) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen";
    my $val1 = int(rand(300));
    my $val2 = int(rand(50));
    my $val3 = int(rand(350));
    
    if($val1 == 0) { $val1 = 1; }
    if($val2 == 0) { $val2 = 1; }
    if($val3 == 0) { $val3 = 1; }
   
    my $v1=$val1-1;
    my $v2=$val2-1;
    my $v3=$val3-1;
    my $zero=0;
  
    &mkDir("$path/f2a_ifc_p_sg_s_valid");
    open(FH,">$path/f2a_ifc_p_sg_s_valid/$test_name");
    
      
    print FH "// Generated by  AnamariaH \n";
    print FH "// Test cases from: Interconnect_F2A_matrix.ods \n";
    print FH "// F2a ifc_p_sg_signal/sg_signal_ifc_p . \n\n";

  
    print FH "csl_signal_group sg1{ \n";
    print FH "csl_signal s1_sg1_$k($val1); \n";
    print FH "csl_signal s2_sg1_$k($val2); \n";
    print FH " sg1() {} \n";
    print FH "};\n";

    print FH "csl_signal_group sg2{ \n";
    print FH "csl_signal s1_sg2_$k($val3); \n";
    print FH "csl_signal s2_sg2_$k($val2); \n";
    print FH "csl_signal s3_sg2_$k($val3); \n";
    print FH "csl_signal s4_sg2_$k($val2); \n";
    print FH "  sg2() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc1{ \n";
    print FH "csl_port p1_ifc1_$k(input,$val3); \n";
    print FH "csl_port p2_ifc1_$k(input,$val2); \n";
    print FH "  ifc1() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc2{ \n";
    print FH "csl_port p1_ifc2_$k(output,$val1);\n";
    print FH "csl_port p2_ifc2_$k(output,$val1);\n";
    print FH "csl_port p3_ifc2_$k(input,$val3);\n";
    print FH "  ifc2() {} \n";
    print FH "};\n";

    print FH "csl_interface ifc3{ \n";
    print FH "csl_port p1_ifc3_$k(input,$val1); \n";
    print FH "csl_port p2_ifc3_$k(input,$val3); \n";
    print FH "  ifc3() {} \n";
    print FH "};\n";

    print FH "csl_unit unit_a{ \n";
    print FH "  csl_port p1(output,$val1);\n";
    print FH "  ifc1 inter11; \n";
    print FH "  unit_a() { \n"; 
    print FH " } \n";
    print FH "}; \n";

    print FH "csl_unit unit_b{ \n";
    if ($k<=10){
    print FH "  csl_port p1(input,$val3); \n";
    print FH "  csl_port p2(input,$val2); \n";
    print FH "  csl_port p3(input,$val3); \n";
    print FH "  csl_port p4(input,$val2); \n";
    print FH "  ifc2 inter21; \n";
    }
    if($k <= 5) { 
    print FH " unit_a a0(.inter11.p1_ifc1_$k(p1),.inter11.p2_ifc1_$k(p2),.p1(inter21.p1_ifc2_$k));    //f2a: ifc.p(p), p(ifc.p) \n";
    print FH " unit_a a1(.inter11.p1_ifc1_$k(p3),.inter11.p2_ifc1_$k(p4),.p1(inter21.p2_ifc2_$k));    //f2a: ifc.p(p), p(ifc.p) \n";   
    
    }
    elsif($k > 5 && $k <= 10) {
    print FH " unit_a a0(.inter11.p1_ifc1_$k(p1[$v3:$zero]),.inter11.p2_ifc1_$k(p2[$v2:$zero]),.p1(inter21.p1_ifc2_$k [$v1:$zero]));    //f2a: ifc.p(p.ps), p(ifc.p.ps) \n";
    print FH " unit_a a1(.inter11.p1_ifc1_$k(p3[$v3:$zero]),.inter11.p2_ifc1_$k(p4[$v2:$zero]),.p1(inter21.p2_ifc2_$k [$v1:$zero]));    //f2a: ifc.p(p.ps), p(ifc.p.ps) \n";   
    
    }

    elsif($k > 10 && $k <= 15) {
	print FH "  csl_signal s1($val3);\n";
        print FH "  csl_signal s2($val2);\n";
   	print FH "  csl_signal s3($val3);\n";
        print FH "  csl_signal s4($val2);\n";
        print FH "  csl_port p1(output,$val1);\n";
        print FH "  csl_port p2(output,$val1);\n";
    print FH "  unit_a a0(.inter11.p1_ifc1_$k(s1),.inter11.p2_ifc1_$k(s2),.p1(p1)) ;   //f2a:ifc.p(s),p(p)\n";
    print FH "  unit_a a1(.inter11.p1_ifc1_$k(s3[$v3:$zero]),.inter11.p2_ifc1_$k(s4[$v2:$zero]),.p1(p2[$v1:$zero])) ;  //f2a: ifc.p(s.ps),p(p.ps) \n";
    
    }
    print FH "   unit_b() { \n"; 
    print FH " } \n";
    print FH "}; \n";
 
    print FH "csl_unit unit_top{ \n";
    if($k <= 10) {
    print FH "  csl_port p1(output,$val1);\n";
    print FH "  csl_port p2(output,$val1);\n";
    print FH "  csl_port p3(input,$val3);\n";

    print FH "  sg2 sgn21; \n";

    }
    elsif($k > 10 && $k <= 15) {
    print FH "  csl_port p1(output,$val1); \n";
    print FH "  csl_signal s2($val1); \n";
    }
    if($k <= 5) {
    print FH "  unit_b b0(.p1(sgn21.s1_sg2_$k),.p2(sgn21.s2_sg2_$k),.p3(sgn21.s3_sg2_$k),.p4(sgn21.s4_sg2_$k),.inter21.p1_ifc2_$k(p1),.inter21.p2_ifc2_$k(p2),.inter21.p3_ifc2_$k(p3));   //f2a: p(sg.s), ifc.p(p) \n"; 
   
    }
    elsif($k > 5 && $k <= 10) {
  print FH "  unit_b b0(.p1(sgn21.s1_sg2_$k [$v3:$zero]),.p2(sgn21.s2_sg2_$k [$v2:$zero]),.p3(sgn21.s3_sg2_$k [$v3:$zero]),.p4(sgn21.s4_sg2_$k [$v2:$zero]),.inter21.p1_ifc2_$k(p1[$v1:$zero]),.inter21.p2_ifc2_$k(p2[$v1:$zero]),.inter21.p3_ifc2_$k(p3[$v3:$zero]));   //f2a: p(sg.s.ps), ifc.p(p.ps) \n"; 
    }
    elsif($k > 10 && $k <= 15) {
    print FH "  unit_b b0(.p1(p1),.p2(s2[$v1:$zero])) ;  //f2a: p(p), p(s.ps)\n";
   
    }   
    print FH "  unit_top() { \n";  
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}
