`ifndef INC_GUARD_u22
`define INC_GUARD_u22

`define IFC_IFC_IN1_P_AR_PI1_S1_UPPER_INDEX  (2-1)
`define IFC_IFC_IN1_P_AR_PI1_S1_LOWER_INDEX  (0)
`define IFC_IFC_IN1_P_AR_PI1_S1_WIDTH  (2)
`define IFC_IFC_IN1_P_AR_PI1_S1_RANGE `IFC_IFC_IN1_P_AR_PI1_S1_UPPER_INDEX:`IFC_IFC_IN1_P_AR_PI1_S1_LOWER_INDEX
`define IFC_IFC_IN1_P_AR_PI2_S2_UPPER_INDEX  (4-1)
`define IFC_IFC_IN1_P_AR_PI2_S2_LOWER_INDEX  (0)
`define IFC_IFC_IN1_P_AR_PI2_S2_WIDTH  (4)
`define IFC_IFC_IN1_P_AR_PI2_S2_RANGE `IFC_IFC_IN1_P_AR_PI2_S2_UPPER_INDEX:`IFC_IFC_IN1_P_AR_PI2_S2_LOWER_INDEX
`define IFC_IFC_IN1_P_AR_PI3_S3_UPPER_INDEX  (1-1)
`define IFC_IFC_IN1_P_AR_PI3_S3_LOWER_INDEX  (0)
`define IFC_IFC_IN1_P_AR_PI3_S3_WIDTH  (1)
`define IFC_IFC_IN1_P_AR_PI3_S3_RANGE `IFC_IFC_IN1_P_AR_PI3_S3_UPPER_INDEX:`IFC_IFC_IN1_P_AR_PI3_S3_LOWER_INDEX

`endif
