`ifndef INC_GUARD_u_bc
`define INC_GUARD_u_bc

`define P_CK_UPPER_INDEX  (0)
`define P_CK_LOWER_INDEX  (0)
`define P_CK_WIDTH  (0-0+1)
`define P_CK_RANGE `P_CK_UPPER_INDEX:`P_CK_LOWER_INDEX
`define P_RESET_UPPER_INDEX  (0)
`define P_RESET_LOWER_INDEX  (0)
`define P_RESET_WIDTH  (0-0+1)
`define P_RESET_RANGE `P_RESET_UPPER_INDEX:`P_RESET_LOWER_INDEX
`define P_P_BC_IN_UPPER_INDEX  (8-1)
`define P_P_BC_IN_LOWER_INDEX  (0)
`define P_P_BC_IN_WIDTH  (8)
`define P_P_BC_IN_RANGE `P_P_BC_IN_UPPER_INDEX:`P_P_BC_IN_LOWER_INDEX
`define P_P_BC_OUT_UPPER_INDEX  (8-1)
`define P_P_BC_OUT_LOWER_INDEX  (0)
`define P_P_BC_OUT_WIDTH  (8)
`define P_P_BC_OUT_RANGE `P_P_BC_OUT_UPPER_INDEX:`P_P_BC_OUT_LOWER_INDEX
`define P_AR_P_A_OUT_P_B_IN_UPPER_INDEX  (8-1)
`define P_AR_P_A_OUT_P_B_IN_LOWER_INDEX  (0)
`define P_AR_P_A_OUT_P_B_IN_WIDTH  (8)
`define P_AR_P_A_OUT_P_B_IN_RANGE `P_AR_P_A_OUT_P_B_IN_UPPER_INDEX:`P_AR_P_A_OUT_P_B_IN_LOWER_INDEX
`define P_AR_P_C_OUT_P_D_IN_UPPER_INDEX  (8-1)
`define P_AR_P_C_OUT_P_D_IN_LOWER_INDEX  (0)
`define P_AR_P_C_OUT_P_D_IN_WIDTH  (8)
`define P_AR_P_C_OUT_P_D_IN_RANGE `P_AR_P_C_OUT_P_D_IN_UPPER_INDEX:`P_AR_P_C_OUT_P_D_IN_LOWER_INDEX
`define S_AR_P_B_OUT_P_C_IN_UPPER_INDEX  (8-1)
`define S_AR_P_B_OUT_P_C_IN_LOWER_INDEX  (0)
`define S_AR_P_B_OUT_P_C_IN_WIDTH  (8)
`define S_AR_P_B_OUT_P_C_IN_RANGE `S_AR_P_B_OUT_P_C_IN_UPPER_INDEX:`S_AR_P_B_OUT_P_C_IN_LOWER_INDEX

`endif
