`ifndef INC_GUARD_uxy
`define INC_GUARD_uxy

`define IFC_IRC_P_RESET_UPPER_INDEX  (0)
`define IFC_IRC_P_RESET_LOWER_INDEX  (0)
`define IFC_IRC_P_RESET_WIDTH  (0-0+1)
`define IFC_IRC_P_RESET_RANGE `IFC_IRC_P_RESET_UPPER_INDEX:`IFC_IRC_P_RESET_LOWER_INDEX
`define IFC_IRC_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IRC_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IRC_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IRC_P_CLOCK_RANGE `IFC_IRC_P_CLOCK_UPPER_INDEX:`IFC_IRC_P_CLOCK_LOWER_INDEX
`define IFC_IFCXIN_P_PINX_UPPER_INDEX  (8-1)
`define IFC_IFCXIN_P_PINX_LOWER_INDEX  (0)
`define IFC_IFCXIN_P_PINX_WIDTH  (8)
`define IFC_IFCXIN_P_PINX_RANGE `IFC_IFCXIN_P_PINX_UPPER_INDEX:`IFC_IFCXIN_P_PINX_LOWER_INDEX
`define IFC_IFCXIN_P_PINY_UPPER_INDEX  (8-1)
`define IFC_IFCXIN_P_PINY_LOWER_INDEX  (0)
`define IFC_IFCXIN_P_PINY_WIDTH  (8)
`define IFC_IFCXIN_P_PINY_RANGE `IFC_IFCXIN_P_PINY_UPPER_INDEX:`IFC_IFCXIN_P_PINY_LOWER_INDEX
`define IFC_IIN1_P_PINX_UPPER_INDEX  (8-1)
`define IFC_IIN1_P_PINX_LOWER_INDEX  (0)
`define IFC_IIN1_P_PINX_WIDTH  (8)
`define IFC_IIN1_P_PINX_RANGE `IFC_IIN1_P_PINX_UPPER_INDEX:`IFC_IIN1_P_PINX_LOWER_INDEX
`define IFC_IIN1_P_PINY_UPPER_INDEX  (8-1)
`define IFC_IIN1_P_PINY_LOWER_INDEX  (0)
`define IFC_IIN1_P_PINY_WIDTH  (8)
`define IFC_IIN1_P_PINY_RANGE `IFC_IIN1_P_PINY_UPPER_INDEX:`IFC_IIN1_P_PINY_LOWER_INDEX
`define IFC_IIN2_P_PINX_UPPER_INDEX  (8-1)
`define IFC_IIN2_P_PINX_LOWER_INDEX  (0)
`define IFC_IIN2_P_PINX_WIDTH  (8)
`define IFC_IIN2_P_PINX_RANGE `IFC_IIN2_P_PINX_UPPER_INDEX:`IFC_IIN2_P_PINX_LOWER_INDEX
`define IFC_IIN2_P_PINY_UPPER_INDEX  (8-1)
`define IFC_IIN2_P_PINY_LOWER_INDEX  (0)
`define IFC_IIN2_P_PINY_WIDTH  (8)
`define IFC_IIN2_P_PINY_RANGE `IFC_IIN2_P_PINY_UPPER_INDEX:`IFC_IIN2_P_PINY_LOWER_INDEX
`define P_AR_TSEL1_SEL_UPPER_INDEX  (2-1)
`define P_AR_TSEL1_SEL_LOWER_INDEX  (0)
`define P_AR_TSEL1_SEL_WIDTH  (2)
`define P_AR_TSEL1_SEL_RANGE `P_AR_TSEL1_SEL_UPPER_INDEX:`P_AR_TSEL1_SEL_LOWER_INDEX
`define P_AR_TSEL2_SEL_UPPER_INDEX  (2-1)
`define P_AR_TSEL2_SEL_LOWER_INDEX  (0)
`define P_AR_TSEL2_SEL_WIDTH  (2)
`define P_AR_TSEL2_SEL_RANGE `P_AR_TSEL2_SEL_UPPER_INDEX:`P_AR_TSEL2_SEL_LOWER_INDEX

`endif
