`ifndef INC_GUARD_sfd_stig
`define INC_GUARD_sfd_stig

`define IFC_LB_P_DUMMY3_UPPER_INDEX  0
`define IFC_LB_P_DUMMY3_LOWER_INDEX  0
`define IFC_LB_P_DUMMY3_WIDTH  1
`define IFC_LB_P_DUMMY3_RANGE `IFC_LB_P_DUMMY3_UPPER_INDEX:`IFC_LB_P_DUMMY3_LOWER_INDEX

`endif
