#!/usr/bin/perl

#Author Petronela
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 15; $i++) {
    my @map1 = ("p_a$i","pa","p","p_b$i","p_c$i","pc","p_c_br$i","p_d$i","p_d_br$i");
    my @map2 = ("p_a$i","pa","p","p_b$i","pb","p_b_br$i","p_c$i","p_e$i","p_e_br$i");
    my @map3 = ("p_a$i","pa","p_a_br$i","p","p_b$i","p_b_br$i","pc","p_c_br$i","p_d$i","p_e$i","pe","p_top$i","p_top_br$i");
    my $var;
    if($i <= 5) {   
        foreach my $it1 (@map1) {
            $var = $it1; 
            &main($i,$var,$it1);
        }
    }
    elsif($i > 5 && $i <= 10) {
        foreach my $it1(@map2) {
            $var = $it1; 
            &main($i,$var,$it1);
        }
    }
    else {
        foreach my $it1(@map3) {
            $var = $it1; 
            &main($i,$var,$it1);
        }  
    }
}

sub main {
    my ($i,$var,$it1) = @_;
    my $test_name = "connect_unit_p_p".$i."_".$it1."_legal.csl";
    &createCslFile($test_name, $i,$var);
}
sub createCslFile {
    my($test_name, $i,$var) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
    my $val1 = int(rand(100)) + 1;
    my $val2 = int(rand(100)) + 1;
    &mkDir("$path/ar_pp_connect_valid");
    open(FH,">$path/ar_pp_connect_valid/$test_name");
    
    print FH "//Generated by Petronela\n";
    print FH "//connections port to port\n\n";
    print FH "csl_bitrange br($val1);\n";
    print FH "csl_bitrange brt($val2);\n";
    print FH "csl_unit a {\n";
    if($i <= 5) {
        print FH "  csl_port p_a$i(input,$val1);\n"; 
        print FH "  csl_port pa(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_a$i(output,$val2);\n"; 
        print FH "  csl_port pa(output,$val2);\n";
        print FH "  csl_port p(output,$val2);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "  csl_port p_a$i(input,$val1);\n"; 
        print FH "  csl_port p_a_br$i(input,br);\n";
        print FH "  csl_port pa(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
    }
    print FH "  a() {\n";                
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    print FH "csl_unit b {\n";  
    if($i <= 5) {
        print FH "  csl_port p_b$i(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_port p_b$i(output,$val2);\n";
        print FH "  csl_port pb(output,$val2);\n";
        print FH "  csl_port p_b_br$i(output,brt);\n";
        print FH "  csl_port p(output,$val2);\n";
    }
    elsif($i > 10 && $i <= 15) {      
        print FH "  csl_port p_b$i(input,$val1);\n";
        print FH "  csl_port p_b_br$i(input,br);\n";
        print FH "  csl_port p(input,$val1);\n";
    }
    print FH "  b() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";  
    if($i <= 5) {
        print FH "  csl_port p_c$i(input,$val1);\n";
        print FH "  csl_port pc(input,$val1);\n";
        print FH "  csl_port p_c_br$i(input,br);\n";
        print FH "  csl_port p(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_port p_c$i(output,$val2);\n";
        print FH "  csl_port p(output,$val2);\n";
    }
    elsif($i > 10 && $i <= 15) {      
        print FH "  csl_port pc(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port p_c_br$i(input,br);\n";
    }
    print FH "  c() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n"; 
    if($i <= 5) {
        print FH "  csl_port p_d$i(input,$val1);\n"; 
        print FH "  csl_port p_d_br$i(input,br);\n";
        print FH "  csl_port p(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_port p_d$i(output,$val2);\n";
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port pd(output,$val2);\n";
    }
    elsif($i > 10 && $i <= 15) {      
       print FH "  csl_port p_d$i(input,$val1);\n";
       print FH "  csl_port p(input,$val1);\n";
    }
    print FH "  d() {\n";
    if($i <= 5) {
        print FH "    p_d$i.connect($var);\n";
        print FH "    c0.pc.connect(p_d_br$i);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    p_d$i.connect(a0.p_a$i);\n";
        print FH "    p.connect(b0.p_b$i);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    p_d$i.connect(p);\n";
    }
    
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    

    print FH "csl_unit e {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  c c0;\n";
    if($i <= 5) {
        print FH "  csl_port p_e$i(input,$val1);\n"; 
        print FH "  csl_port p_e_br$i(input,br);\n";   
        print FH "  csl_port p(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {      
        print FH "  csl_port p_e$i(output,$val2);\n";    
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port p_e_br$i(output,brt);\n";
    }
    elsif($i > 10 && $i <= 15) {      
        print FH "  csl_port p_e$i(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port pe(input,$val1);\n";
    }
    print FH "  e() {\n";
    if($i <= 5) {
        print FH "    p_e_br$i.connect(a0.pa);\n";
        print
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    p_e$i.connect($var);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    p_e$i.connect(a0.p_a_br$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    print FH "  d d0;\n";
    print FH "  e e0;\n"; 
    if($i <= 5) {
        print FH "  csl_port ptop(input,$val1);\n";
        print FH "  csl_port p(input,$val1);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_top$i(output,$val2);\n";      
        print FH "  csl_port p(output,$val2);\n";
        print FH "  csl_port ptop(output,$val2);\n";
        
        
    }
    elsif($i > 10 && $i <= 15) {
        print FH "  csl_port p_top$i(input,$val1);\n";      
        print FH "  csl_port p(input,$val1);\n";
        print FH "  csl_port p_top_br$i(input,br);\n";
    }
    
    print FH "  top(){\n";
    if($i <= 5) {
        print FH "    ptop.connect(d0.a0.p_a$i);\n";
        print FH "    p.connect($var);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "    p_top$i.connect(e0.a0.p_a$i);\n";
        print FH "    ptop.connect($var);\n";
    }
    elsif($i > 10 && $i <= 15) {
        print FH "    p_top_br$i.connect($var);\n";
        print FH "    p.connect(p);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}

`./ar_ps_sp_connect_invalid.pl`;
`./ar_ps_sp_connect_valid.pl`;
`./ar_pp_connect_invalid.pl`;
`./ar_p_ifcp_connect.pl`;
`./ar_p_ifc_ifcp_connect.pl`;
`./ar_p_ps_connect.pl`;
`./ar_pps_s_pps_connect.pl`;
`./ar_p_sps_p_connect.pl`;
`./ar_s_s_connect_invalid.pl`;
`./ar_s_sps_connect.pl`;
`./ar_connect_concat.pl`;
`./ar_connect_replication.pl`;
`./ar_concat_connect_invalid.pl`;
`./ar_replication_connect_invalid.pl`;
`./ar_ps_ifcp_ps_connect.pl`;
`./ar_p_ps_s_ps_ifcp_connect.pl`;

`./ar_sg_ifc.pl`;
`./ar_sps_assign.pl`;



