#!/usr/bin/perl

#Author Petronela
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

my @map1 = ("","a0","b0");
my @map3 = ("","a0","b0","c0","d0");
my $dot = ".";

foreach(my $i = 1; $i <= 20; $i++) {    
    my @map2 = ("s_a$i","s_b$i");
    my $var;
    my @map4 = ("s_a$i","s_b$i","s_c$i","s_d$i","s_top$i");
    my @map5 = ("s_a$i","s_b$i","s_c$i","s_d$i");
    if($i <= 10) {
        foreach my $it2 (@map2) {
            $var = $it2; 
            my $it = "";     
            &main($i,$var,$it,$it2);
        }
    }
    elsif($i > 10 && $i >= 15 ) {
        foreach my $it1(@map1) {
            foreach my $it2 (@map5) {
                if($it1 ne "") {
                    $var = $it1.$dot.$it2;
                }
                else {
                    $var =$it2; 
                }   
                &main($i,$var,$it1,$it2);
            }
        }
    }
    else {
        foreach my $it1(@map3) {
            foreach my $it2 (@map4) {
                if($it1 ne "") {
                    $var = $it1.$dot.$it2;
                }
                else {
                    $var =$it2; 
                }   
                &main($i,$var,$it1,$it2);
            }
        }
    }
}

sub main {
    my ($i,$var,$it1,$it2) = @_;
    my $test_name;
    if($it1 ne "") {
        $test_name = "connect_unit_p_s".$i."_".$it1."_".$it2."_illegal.csl";
    }
    else {
        $test_name = "connect_unit_p_s".$i."_".$it2."_illegal.csl";
    }
    &createCslFile($test_name, $i,$var);
}

sub createCslFile {
    my($test_name, $i, $var) = @_;
    my $path = "$ENV{WORK}/test/csl_ar_gen/";
    my $val1 = int(rand(100));
    my $val2 = int(rand(100));
    my $val3 = int(rand(30))+100;
    &mkDir("$path/ar_connect_ps_invalid"); 
    open(FH,">$path/ar_connect_ps_invalid/$test_name");
    
    print FH "//Generated by Petronela\n\n";
    print FH "csl_bitrange br($val2);\n";
    print FH "csl_unit a {\n";
    print FH "  csl_port pt(input,$val2);\n";
    if($i <= 10) {
        print FH "  csl_port p_a$i(input,$val1);\n"; 
        print FH "  csl_signal s_a$i;\n";
    }
    elsif($i > 10 && $i <= 20) {
        print FH "  csl_port p_a$i(output,$val2);\n"; 
        print FH "  csl_signal s_a$i($val1);\n";
    }
    print FH "  a() {\n";                
    if($i > 5 && $i <= 10) {
        print FH "    pt.connect(pt);\n";
    }   
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit b {\n";
    print FH "  csl_port pt(input,$val2);\n";
    if($i <= 5) {
        print FH "  csl_port p_b$i(input,$val2);\n"; 
        print FH "  csl_signal s_b$i(br);\n";
    }
    elsif($i > 5 && $i <= 10) {
        print FH "  csl_port p_b$i(output,$val3);\n";
        print FH "  csl_signal s_b$i($val1);\n";
    }
    elsif($i > 10 && $i <= 20) {
        print FH "  csl_signal s_b$i;\n"; 
        print FH "  csl_port p_b$i(output);\n";
    }
    print FH "  b() {\n";                
    if($i <= 5) {
        
        print FH "   p_b$i.connect(s_b$i);\n"; 
        print FH "   p_a$i.connect($var);\n";
    }
    elsif($i > 5 && $i <= 20) {
        print FH "   p_b$i.connect(s_b$i);\n";
        print FH "   pt.connect(pt);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";


    print FH "csl_unit c {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  csl_port pt(input,br);\n";
    if($i <= 10) {
        print FH "  csl_port p_c$i(input,$val2);\n"; 
        print FH "  csl_signal s_c$i;\n";
    }
    elsif($i > 10 && $i <= 20) {   
        print FH "  csl_port p_c$i(input,$val2);\n";
        print FH "  csl_signal s_a$i($val2);\n";
    }
    print FH "  c() {\n";
    if($i > 5 && $i <= 10) {
        #if($var eq "s_b$i") {
            print FH "    b0.p_b$i.connect(s_a$i);\n";
        #}
        #else {
         #   print FH "    b0.p_b$i.connect($var);\n"; 
        #}
    }
    elsif($i > 5 && $i <= 15) {
        if($var ne "a0.p_a$i") {
            print FH "    p_c$i.connect(s_a$i);\n";
            print FH "    p_c$i.connect($var);\n";
            print FH "    pt.connect(pt);\n";
        }
        else {
            print FH "    a0.p_a$i.connect(b0.p_b$i);\n";
        }
    }
    elsif($i > 15 && $i <= 20) {
        print FH "    a0.s_a$i.connect(s_a$i);\n";
        print FH "    $var.connect(a0.p_a$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    print FH "  a a0;\n";
    print FH "  b b0;\n";
    print FH "  csl_port pt(input,$val2);\n";
    if($i <= 10) {
        print FH "  csl_port p_d$i(input,$val2);\n"; 
        print FH "  csl_signal s_d$i($val1);\n";
    }
    elsif($i > 10 && $i <= 20) {      
        print FH "  csl_port p_d$i(output,$val2);\n";
        print FH "  csl_signal s_d$i;\n";
    }
    print FH "  d() {\n";
    if($i > 10 && $i <= 15) {
        if($var ne "a0.p_a$i") {
            print FH "    p_d$i.connect($var);\n";      
            print FH "    pt.connect(pt);\n";
        }
        else {
            print FH "    var$i.connect(a0.p_a$i);\n";
            print FH "    pt.connect(pt);\n";
        }
    }
    elsif($i > 15 && $i <= 20 ) {
        print FH "    $var.connect(b0.s_b$i);\n";
        print FH "    pt.connect(pt);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    print FH "csl_unit top {\n";
    print FH "  c c0;\n";
    print FH "  d d0;\n";
    print FH "  csl_port pt(input,$val2);\n";
    if($i <= 15) {
        print FH "  csl_port p_top$i(input,$val1);\n";      
        print FH "  csl_signal s_top$i;\n";
    }
    else {
        print FH "  csl_port p_top".$i."(output,101);\n";
        print FH "  csl_signal s_top$i;\n";
        print FH "  csl_signal s_a$i;\n";
    }
    print FH "  top(){\n";
    if($i > 10 && $i <= 15) {
        print FH "    $var.connect(p_top$i);\n";
        print FH "    s_top$i.connect(pt);\n";
    }
    elsif($i > 15 && $i <= 20) {
        print FH "    p_a$i.connect($var);\n";
        print FH "    s_a$i.connect(s_a$i);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}
