`ifndef INC_GUARD_b
`define INC_GUARD_b

`define P_IN_B1_UPPER_INDEX  (0)
`define P_IN_B1_LOWER_INDEX  (0)
`define P_IN_B1_WIDTH  (0-0+1)
`define P_IN_B1_RANGE `P_IN_B1_UPPER_INDEX:`P_IN_B1_LOWER_INDEX
`define P_IN_B2_UPPER_INDEX  (0)
`define P_IN_B2_LOWER_INDEX  (0)
`define P_IN_B2_WIDTH  (0-0+1)
`define P_IN_B2_RANGE `P_IN_B2_UPPER_INDEX:`P_IN_B2_LOWER_INDEX
`define P_OUT_B1_UPPER_INDEX  (0)
`define P_OUT_B1_LOWER_INDEX  (0)
`define P_OUT_B1_WIDTH  (0-0+1)
`define P_OUT_B1_RANGE `P_OUT_B1_UPPER_INDEX:`P_OUT_B1_LOWER_INDEX
`define P_OUT_B2_UPPER_INDEX  (0)
`define P_OUT_B2_LOWER_INDEX  (0)
`define P_OUT_B2_WIDTH  (0-0+1)
`define P_OUT_B2_RANGE `P_OUT_B2_UPPER_INDEX:`P_OUT_B2_LOWER_INDEX
`define P_CLK_UPPER_INDEX  (0)
`define P_CLK_LOWER_INDEX  (0)
`define P_CLK_WIDTH  (0-0+1)
`define P_CLK_RANGE `P_CLK_UPPER_INDEX:`P_CLK_LOWER_INDEX
`define S_S1_UPPER_INDEX  (0)
`define S_S1_LOWER_INDEX  (0)
`define S_S1_WIDTH  (0-0+1)
`define S_S1_RANGE `S_S1_UPPER_INDEX:`S_S1_LOWER_INDEX
`define S_S2_UPPER_INDEX  (0)
`define S_S2_LOWER_INDEX  (0)
`define S_S2_WIDTH  (0-0+1)
`define S_S2_RANGE `S_S2_UPPER_INDEX:`S_S2_LOWER_INDEX
`define S_S3_UPPER_INDEX  (0)
`define S_S3_LOWER_INDEX  (0)
`define S_S3_WIDTH  (0-0+1)
`define S_S3_RANGE `S_S3_UPPER_INDEX:`S_S3_LOWER_INDEX

`endif
