`ifndef INC_GUARD_u_mux41
`define INC_GUARD_u_mux41

`define P_IN0_UPPER_INDEX  (15)
`define P_IN0_LOWER_INDEX  (0)
`define P_IN0_WIDTH  (15-0+1)
`define P_IN0_RANGE `P_IN0_UPPER_INDEX:`P_IN0_LOWER_INDEX
`define P_IN1_UPPER_INDEX  (15)
`define P_IN1_LOWER_INDEX  (0)
`define P_IN1_WIDTH  (15-0+1)
`define P_IN1_RANGE `P_IN1_UPPER_INDEX:`P_IN1_LOWER_INDEX
`define P_IN2_UPPER_INDEX  (15)
`define P_IN2_LOWER_INDEX  (0)
`define P_IN2_WIDTH  (15-0+1)
`define P_IN2_RANGE `P_IN2_UPPER_INDEX:`P_IN2_LOWER_INDEX
`define P_IN3_UPPER_INDEX  (15)
`define P_IN3_LOWER_INDEX  (0)
`define P_IN3_WIDTH  (15-0+1)
`define P_IN3_RANGE `P_IN3_UPPER_INDEX:`P_IN3_LOWER_INDEX
`define P_SEL_UPPER_INDEX  (4-1)
`define P_SEL_LOWER_INDEX  (0)
`define P_SEL_WIDTH  (4)
`define P_SEL_RANGE `P_SEL_UPPER_INDEX:`P_SEL_LOWER_INDEX
`define IFC_IFC_OUT0_P_O_UPPER_INDEX  (15)
`define IFC_IFC_OUT0_P_O_LOWER_INDEX  (0)
`define IFC_IFC_OUT0_P_O_WIDTH  (15-0+1)
`define IFC_IFC_OUT0_P_O_RANGE `IFC_IFC_OUT0_P_O_UPPER_INDEX:`IFC_IFC_OUT0_P_O_LOWER_INDEX

`endif
