`ifndef INC_GUARD_unit_b
`define INC_GUARD_unit_b

`define IFC_IFCAI_P_P_IFC5_UPPER_INDEX  (w5-1)
`define IFC_IFCAI_P_P_IFC5_LOWER_INDEX  (0)
`define IFC_IFCAI_P_P_IFC5_WIDTH  (w5)
`define IFC_IFCAI_P_P_IFC5_RANGE `IFC_IFCAI_P_P_IFC5_UPPER_INDEX:`IFC_IFCAI_P_P_IFC5_LOWER_INDEX

`endif
