#Script library file that contains the common functions that are used in the scripts!!!

#!/usr/bin/perl
use strict;

if(! defined $ENV{WORK}) {
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

sub mkName {
    my($path,$test_dir,$project_name,$test_file)=@_;


if($project_name=~/(_legal)/){
        &mkDir("$path/$test_dir");
        &mkDir("$path/$test_dir/$project_name");
        open(FH,">$path/$test_dir/$project_name/$test_file");

    }
    elsif($project_name=~/(_illegal)/) {
        &mkDir("$path/$test_dir/$project_name");
        open(FH,">$path/$test_dir/$project_name/$test_file");

    }
}

sub each_test{
    my($author,$test_matr)=@_;
    print FH "//Generated by : $author\n\n";
    print FH "//Test_Matrix: /test_matrices/$test_matr\n\n";
}
1;
