`ifndef INC_GUARD_u_dep
`define INC_GUARD_u_dep

`define S_RESET_UPPER_INDEX  (0)
`define S_RESET_LOWER_INDEX  (0)
`define S_RESET_WIDTH  (0-0+1)
`define S_RESET_RANGE `S_RESET_UPPER_INDEX:`S_RESET_LOWER_INDEX
`define S_ENABLE_UPPER_INDEX  (0)
`define S_ENABLE_LOWER_INDEX  (0)
`define S_ENABLE_WIDTH  (0-0+1)
`define S_ENABLE_RANGE `S_ENABLE_UPPER_INDEX:`S_ENABLE_LOWER_INDEX
`define S_CLK_UPPER_INDEX  (0)
`define S_CLK_LOWER_INDEX  (0)
`define S_CLK_WIDTH  (0-0+1)
`define S_CLK_RANGE `S_CLK_UPPER_INDEX:`S_CLK_LOWER_INDEX
`define S_D1_UPPER_INDEX  (4-1)
`define S_D1_LOWER_INDEX  (0)
`define S_D1_WIDTH  (4)
`define S_D1_RANGE `S_D1_UPPER_INDEX:`S_D1_LOWER_INDEX
`define S_D2_UPPER_INDEX  (8-1)
`define S_D2_LOWER_INDEX  (0)
`define S_D2_WIDTH  (8)
`define S_D2_RANGE `S_D2_UPPER_INDEX:`S_D2_LOWER_INDEX
`define S_D3_UPPER_INDEX  (16-1)
`define S_D3_LOWER_INDEX  (0)
`define S_D3_WIDTH  (16)
`define S_D3_RANGE `S_D3_UPPER_INDEX:`S_D3_LOWER_INDEX
`define S_Q1_UPPER_INDEX  (4-1)
`define S_Q1_LOWER_INDEX  (0)
`define S_Q1_WIDTH  (4)
`define S_Q1_RANGE `S_Q1_UPPER_INDEX:`S_Q1_LOWER_INDEX
`define S_Q2_UPPER_INDEX  (8-1)
`define S_Q2_LOWER_INDEX  (0)
`define S_Q2_WIDTH  (8)
`define S_Q2_RANGE `S_Q2_UPPER_INDEX:`S_Q2_LOWER_INDEX
`define S_Q3_UPPER_INDEX  (16-1)
`define S_Q3_LOWER_INDEX  (0)
`define S_Q3_WIDTH  (16)
`define S_Q3_RANGE `S_Q3_UPPER_INDEX:`S_Q3_LOWER_INDEX

`endif
