//gcc has a problem with instantiating templates inside a template
//this is why we have to instantiate templates by hand
//template NSCSLOm::RefTVec_RefCSLOmUnitInstantiation NSCSLOm::CSLOmBase::getChildren<NSCSLOm::CSLOmUnitInstantiation>(NSCSLOm::_ECSLOmType) const;
//template NSCSLOm::RefTVec_RefCSLOmIdentifier NSCSLOm::CSLOmBase::getChildren<NSCSLOm::CSLOmIdentifier>(NSCSLOm::_ECSLOmType) const;
