`ifndef INC_GUARD_a
`define INC_GUARD_a

`define S_S_UPPER_INDEX  (10-1)
`define S_S_LOWER_INDEX  (0)
`define S_S_WIDTH  (10)
`define S_S_RANGE `S_S_UPPER_INDEX:`S_S_LOWER_INDEX
`define SG_SG0_S_S1_UPPER_INDEX  (21-1)
`define SG_SG0_S_S1_LOWER_INDEX  (0)
`define SG_SG0_S_S1_WIDTH  (21)
`define SG_SG0_S_S1_RANGE `SG_SG0_S_S1_UPPER_INDEX:`SG_SG0_S_S1_LOWER_INDEX
`define SG_SG0_S_S2_UPPER_INDEX  (10-1)
`define SG_SG0_S_S2_LOWER_INDEX  (0)
`define SG_SG0_S_S2_WIDTH  (10)
`define SG_SG0_S_S2_RANGE `SG_SG0_S_S2_UPPER_INDEX:`SG_SG0_S_S2_LOWER_INDEX
`define UPPER_INDEX  (20)
`define LOWER_INDEX  (11)
`define WIDTH  (20-11+1)
`define RANGE `UPPER_INDEX:`LOWER_INDEX

`endif
