`ifndef INC_GUARD_ISA
`define INC_GUARD_ISA

`define IF_F_OPCODE_UPPER_INDEX  (4-1)
`define IF_F_OPCODE_LOWER_INDEX (0)
`define IF_F_OPCODE_WIDTH (4)
`define IF_F_OPCODE_RANGE `IF_F_OPCODE_UPPER_INDEX:`IF_F_OPCODE_LOWER_INDEX

`define IF_R_FIELD_UPPER_INDEX  (4-1)
`define IF_R_FIELD_LOWER_INDEX (0)
`define IF_R_FIELD_WIDTH (4)
`define IF_R_FIELD_RANGE `IF_R_FIELD_UPPER_INDEX:`IF_R_FIELD_LOWER_INDEX

`define IF_C_FIELD_UPPER_INDEX  (8-1)
`define IF_C_FIELD_LOWER_INDEX (0)
`define IF_C_FIELD_WIDTH (8)
`define IF_C_FIELD_RANGE `IF_C_FIELD_UPPER_INDEX:`IF_C_FIELD_LOWER_INDEX

`define IF_B_FIELD_UPPER_INDEX  (11-1)
`define IF_B_FIELD_LOWER_INDEX (0)
`define IF_B_FIELD_WIDTH (11)
`define IF_B_FIELD_RANGE `IF_B_FIELD_UPPER_INDEX:`IF_B_FIELD_LOWER_INDEX

`define IF_O_FIELD_UPPER_INDEX  (4-1)
`define IF_O_FIELD_LOWER_INDEX (0)
`define IF_O_FIELD_WIDTH (4)
`define IF_O_FIELD_RANGE `IF_O_FIELD_UPPER_INDEX:`IF_O_FIELD_LOWER_INDEX

`define IF_ROM_FIELD_UPPER_INDEX  (8-1)
`define IF_ROM_FIELD_LOWER_INDEX (0)
`define IF_ROM_FIELD_WIDTH (8)
`define IF_ROM_FIELD_RANGE `IF_ROM_FIELD_UPPER_INDEX:`IF_ROM_FIELD_LOWER_INDEX

`define IF_COND_FIELD_UPPER_INDEX  (1-1)
`define IF_COND_FIELD_LOWER_INDEX (0)
`define IF_COND_FIELD_WIDTH (1)
`define IF_COND_FIELD_RANGE `IF_COND_FIELD_UPPER_INDEX:`IF_COND_FIELD_LOWER_INDEX

`define IF_DIR_FIELD_UPPER_INDEX  (1-1)
`define IF_DIR_FIELD_LOWER_INDEX (0)
`define IF_DIR_FIELD_WIDTH (1)
`define IF_DIR_FIELD_RANGE `IF_DIR_FIELD_UPPER_INDEX:`IF_DIR_FIELD_LOWER_INDEX

`define IE_ISA_ROOT_UPPER_INDEX (16-1)
`define IE_ISA_ROOT_LOWER_INDEX (0)
`define IE_ISA_ROOT_WIDTH (16)
`define IE_ISA_ROOT_RANGE `IE_ISA_ROOT_UPPER_INDEX:`IE_ISA_ROOT_LOWER_INDEX
`define IE_BASE_FORMAT_UPPER_INDEX (16-1)
`define IE_BASE_FORMAT_LOWER_INDEX (0)
`define IE_BASE_FORMAT_WIDTH (16)
`define IE_BASE_FORMAT_RANGE `IE_BASE_FORMAT_UPPER_INDEX:`IE_BASE_FORMAT_LOWER_INDEX
`define IE_BASE_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_BASE_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_BASE_FORMAT_IF_F_OPCODE_RANGE `IE_BASE_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_BASE_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_F1_FORMAT_UPPER_INDEX (16-1)
`define IE_F1_FORMAT_LOWER_INDEX (0)
`define IE_F1_FORMAT_WIDTH (16)
`define IE_F1_FORMAT_RANGE `IE_F1_FORMAT_UPPER_INDEX:`IE_F1_FORMAT_LOWER_INDEX
`define IE_F1_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_F1_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_F1_FORMAT_IF_F_OPCODE_RANGE `IE_F1_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_F1_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_F1_FORMAT_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_F1_FORMAT_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_F1_FORMAT_IF_DST_R_FIELD_RANGE `IE_F1_FORMAT_IF_DST_R_FIELD_UPPER_INDEX:`IE_F1_FORMAT_IF_DST_R_FIELD_LOWER_INDEX

`define IE_OP_FORMAT_UPPER_INDEX (16-1)
`define IE_OP_FORMAT_LOWER_INDEX (0)
`define IE_OP_FORMAT_WIDTH (16)
`define IE_OP_FORMAT_RANGE `IE_OP_FORMAT_UPPER_INDEX:`IE_OP_FORMAT_LOWER_INDEX
`define IE_OP_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_OP_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_OP_FORMAT_IF_F_OPCODE_RANGE `IE_OP_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_OP_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_OP_FORMAT_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_OP_FORMAT_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_OP_FORMAT_IF_DST_R_FIELD_RANGE `IE_OP_FORMAT_IF_DST_R_FIELD_UPPER_INDEX:`IE_OP_FORMAT_IF_DST_R_FIELD_LOWER_INDEX

`define IE_OP_FORMAT_IF_OP1_FIELD_UPPER_INDEX  (3)
`define IE_OP_FORMAT_IF_OP1_FIELD_LOWER_INDEX (0)
`define IE_OP_FORMAT_IF_OP1_FIELD_RANGE `IE_OP_FORMAT_IF_OP1_FIELD_UPPER_INDEX:`IE_OP_FORMAT_IF_OP1_FIELD_LOWER_INDEX

`define IE_OP_FORMAT_IF_OP2_FIELD_UPPER_INDEX  (3)
`define IE_OP_FORMAT_IF_OP2_FIELD_LOWER_INDEX (0)
`define IE_OP_FORMAT_IF_OP2_FIELD_RANGE `IE_OP_FORMAT_IF_OP2_FIELD_UPPER_INDEX:`IE_OP_FORMAT_IF_OP2_FIELD_LOWER_INDEX

`define IE_BR_FORMAT_UPPER_INDEX (16-1)
`define IE_BR_FORMAT_LOWER_INDEX (0)
`define IE_BR_FORMAT_WIDTH (16)
`define IE_BR_FORMAT_RANGE `IE_BR_FORMAT_UPPER_INDEX:`IE_BR_FORMAT_LOWER_INDEX
`define IE_BR_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_BR_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_BR_FORMAT_IF_F_OPCODE_RANGE `IE_BR_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_BR_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_BR_FORMAT_IF_COND_FIELD0_UPPER_INDEX  (0)
`define IE_BR_FORMAT_IF_COND_FIELD0_LOWER_INDEX (0)
`define IE_BR_FORMAT_IF_COND_FIELD0_RANGE `IE_BR_FORMAT_IF_COND_FIELD0_UPPER_INDEX:`IE_BR_FORMAT_IF_COND_FIELD0_LOWER_INDEX

`define IE_BR_FORMAT_IF_BR_ADDR_UPPER_INDEX  (10)
`define IE_BR_FORMAT_IF_BR_ADDR_LOWER_INDEX (0)
`define IE_BR_FORMAT_IF_BR_ADDR_RANGE `IE_BR_FORMAT_IF_BR_ADDR_UPPER_INDEX:`IE_BR_FORMAT_IF_BR_ADDR_LOWER_INDEX

`define IE_R_FORMAT_UPPER_INDEX (16-1)
`define IE_R_FORMAT_LOWER_INDEX (0)
`define IE_R_FORMAT_WIDTH (16)
`define IE_R_FORMAT_RANGE `IE_R_FORMAT_UPPER_INDEX:`IE_R_FORMAT_LOWER_INDEX
`define IE_R_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_R_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_R_FORMAT_IF_F_OPCODE_RANGE `IE_R_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_R_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_R_FORMAT_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_R_FORMAT_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_R_FORMAT_IF_DST_R_FIELD_RANGE `IE_R_FORMAT_IF_DST_R_FIELD_UPPER_INDEX:`IE_R_FORMAT_IF_DST_R_FIELD_LOWER_INDEX

`define IE_R_FORMAT_IF_R_SRC_UPPER_INDEX  (3)
`define IE_R_FORMAT_IF_R_SRC_LOWER_INDEX (0)
`define IE_R_FORMAT_IF_R_SRC_RANGE `IE_R_FORMAT_IF_R_SRC_UPPER_INDEX:`IE_R_FORMAT_IF_R_SRC_LOWER_INDEX

`define IE_ROM_FORMAT_UPPER_INDEX (16-1)
`define IE_ROM_FORMAT_LOWER_INDEX (0)
`define IE_ROM_FORMAT_WIDTH (16)
`define IE_ROM_FORMAT_RANGE `IE_ROM_FORMAT_UPPER_INDEX:`IE_ROM_FORMAT_LOWER_INDEX
`define IE_ROM_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_ROM_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_ROM_FORMAT_IF_F_OPCODE_RANGE `IE_ROM_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_ROM_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_ROM_FORMAT_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_ROM_FORMAT_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_ROM_FORMAT_IF_DST_R_FIELD_RANGE `IE_ROM_FORMAT_IF_DST_R_FIELD_UPPER_INDEX:`IE_ROM_FORMAT_IF_DST_R_FIELD_LOWER_INDEX

`define IE_ROM_FORMAT_IF_ROM_ADDR_UPPER_INDEX  (7)
`define IE_ROM_FORMAT_IF_ROM_ADDR_LOWER_INDEX (0)
`define IE_ROM_FORMAT_IF_ROM_ADDR_RANGE `IE_ROM_FORMAT_IF_ROM_ADDR_UPPER_INDEX:`IE_ROM_FORMAT_IF_ROM_ADDR_LOWER_INDEX

`define IE_CONST_FORMAT_UPPER_INDEX (16-1)
`define IE_CONST_FORMAT_LOWER_INDEX (0)
`define IE_CONST_FORMAT_WIDTH (16)
`define IE_CONST_FORMAT_RANGE `IE_CONST_FORMAT_UPPER_INDEX:`IE_CONST_FORMAT_LOWER_INDEX
`define IE_CONST_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_CONST_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_CONST_FORMAT_IF_F_OPCODE_RANGE `IE_CONST_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_CONST_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_CONST_FORMAT_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_CONST_FORMAT_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_CONST_FORMAT_IF_DST_R_FIELD_RANGE `IE_CONST_FORMAT_IF_DST_R_FIELD_UPPER_INDEX:`IE_CONST_FORMAT_IF_DST_R_FIELD_LOWER_INDEX

`define IE_CONST_FORMAT_IF_CONST_NMB_UPPER_INDEX  (7)
`define IE_CONST_FORMAT_IF_CONST_NMB_LOWER_INDEX (0)
`define IE_CONST_FORMAT_IF_CONST_NMB_RANGE `IE_CONST_FORMAT_IF_CONST_NMB_UPPER_INDEX:`IE_CONST_FORMAT_IF_CONST_NMB_LOWER_INDEX

`define IE_SRS_FORMAT_UPPER_INDEX (16-1)
`define IE_SRS_FORMAT_LOWER_INDEX (0)
`define IE_SRS_FORMAT_WIDTH (16)
`define IE_SRS_FORMAT_RANGE `IE_SRS_FORMAT_UPPER_INDEX:`IE_SRS_FORMAT_LOWER_INDEX
`define IE_SRS_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_SRS_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_SRS_FORMAT_IF_F_OPCODE_RANGE `IE_SRS_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_SRS_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_SRS_FORMAT_IF_DST_UPPER_INDEX  (3)
`define IE_SRS_FORMAT_IF_DST_LOWER_INDEX (0)
`define IE_SRS_FORMAT_IF_DST_RANGE `IE_SRS_FORMAT_IF_DST_UPPER_INDEX:`IE_SRS_FORMAT_IF_DST_LOWER_INDEX

`define IE_SRS_FORMAT_IF_SRC_UPPER_INDEX  (3)
`define IE_SRS_FORMAT_IF_SRC_LOWER_INDEX (0)
`define IE_SRS_FORMAT_IF_SRC_RANGE `IE_SRS_FORMAT_IF_SRC_UPPER_INDEX:`IE_SRS_FORMAT_IF_SRC_LOWER_INDEX

`define IE_SRS_FORMAT_IF_D_UPPER_INDEX  (0)
`define IE_SRS_FORMAT_IF_D_LOWER_INDEX (0)
`define IE_SRS_FORMAT_IF_D_RANGE `IE_SRS_FORMAT_IF_D_UPPER_INDEX:`IE_SRS_FORMAT_IF_D_LOWER_INDEX

`define IE_SH_FORMAT_UPPER_INDEX (16-1)
`define IE_SH_FORMAT_LOWER_INDEX (0)
`define IE_SH_FORMAT_WIDTH (16)
`define IE_SH_FORMAT_RANGE `IE_SH_FORMAT_UPPER_INDEX:`IE_SH_FORMAT_LOWER_INDEX
`define IE_SH_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_SH_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_SH_FORMAT_IF_F_OPCODE_RANGE `IE_SH_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_SH_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_SH_FORMAT_IF_SHA_UPPER_INDEX  (3)
`define IE_SH_FORMAT_IF_SHA_LOWER_INDEX (0)
`define IE_SH_FORMAT_IF_SHA_RANGE `IE_SH_FORMAT_IF_SHA_UPPER_INDEX:`IE_SH_FORMAT_IF_SHA_LOWER_INDEX

`define IE_SH_FORMAT_IF_R_SRC_UPPER_INDEX  (3)
`define IE_SH_FORMAT_IF_R_SRC_LOWER_INDEX (0)
`define IE_SH_FORMAT_IF_R_SRC_RANGE `IE_SH_FORMAT_IF_R_SRC_UPPER_INDEX:`IE_SH_FORMAT_IF_R_SRC_LOWER_INDEX

`define IE_RAM_FORMAT_UPPER_INDEX (16-1)
`define IE_RAM_FORMAT_LOWER_INDEX (0)
`define IE_RAM_FORMAT_WIDTH (16)
`define IE_RAM_FORMAT_RANGE `IE_RAM_FORMAT_UPPER_INDEX:`IE_RAM_FORMAT_LOWER_INDEX
`define IE_RAM_FORMAT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_RAM_FORMAT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_RAM_FORMAT_IF_F_OPCODE_RANGE `IE_RAM_FORMAT_IF_F_OPCODE_UPPER_INDEX:`IE_RAM_FORMAT_IF_F_OPCODE_LOWER_INDEX

`define IE_RAM_FORMAT_IF_R_SRC_UPPER_INDEX  (3)
`define IE_RAM_FORMAT_IF_R_SRC_LOWER_INDEX (0)
`define IE_RAM_FORMAT_IF_R_SRC_RANGE `IE_RAM_FORMAT_IF_R_SRC_UPPER_INDEX:`IE_RAM_FORMAT_IF_R_SRC_LOWER_INDEX

`define IE_RAM_FORMAT_IF_D_UPPER_INDEX  (0)
`define IE_RAM_FORMAT_IF_D_LOWER_INDEX (0)
`define IE_RAM_FORMAT_IF_D_RANGE `IE_RAM_FORMAT_IF_D_UPPER_INDEX:`IE_RAM_FORMAT_IF_D_LOWER_INDEX

`define IE_I_ADD_UPPER_INDEX (16-1)
`define IE_I_ADD_LOWER_INDEX (0)
`define IE_I_ADD_WIDTH (16)
`define IE_I_ADD_RANGE `IE_I_ADD_UPPER_INDEX:`IE_I_ADD_LOWER_INDEX
`define IE_I_ADD_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_ADD_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_ADD_IF_F_OPCODE_RANGE `IE_I_ADD_IF_F_OPCODE_UPPER_INDEX:`IE_I_ADD_IF_F_OPCODE_LOWER_INDEX

`define IE_I_ADD_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_ADD_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_ADD_IF_DST_R_FIELD_RANGE `IE_I_ADD_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_ADD_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_ADD_IF_OP1_FIELD_UPPER_INDEX  (3)
`define IE_I_ADD_IF_OP1_FIELD_LOWER_INDEX (0)
`define IE_I_ADD_IF_OP1_FIELD_RANGE `IE_I_ADD_IF_OP1_FIELD_UPPER_INDEX:`IE_I_ADD_IF_OP1_FIELD_LOWER_INDEX

`define IE_I_ADD_IF_OP2_FIELD_UPPER_INDEX  (3)
`define IE_I_ADD_IF_OP2_FIELD_LOWER_INDEX (0)
`define IE_I_ADD_IF_OP2_FIELD_RANGE `IE_I_ADD_IF_OP2_FIELD_UPPER_INDEX:`IE_I_ADD_IF_OP2_FIELD_LOWER_INDEX

`define IE_I_SUB_UPPER_INDEX (16-1)
`define IE_I_SUB_LOWER_INDEX (0)
`define IE_I_SUB_WIDTH (16)
`define IE_I_SUB_RANGE `IE_I_SUB_UPPER_INDEX:`IE_I_SUB_LOWER_INDEX
`define IE_I_SUB_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_SUB_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SUB_IF_F_OPCODE_RANGE `IE_I_SUB_IF_F_OPCODE_UPPER_INDEX:`IE_I_SUB_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SUB_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_SUB_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_SUB_IF_DST_R_FIELD_RANGE `IE_I_SUB_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_SUB_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_SUB_IF_OP1_FIELD_UPPER_INDEX  (3)
`define IE_I_SUB_IF_OP1_FIELD_LOWER_INDEX (0)
`define IE_I_SUB_IF_OP1_FIELD_RANGE `IE_I_SUB_IF_OP1_FIELD_UPPER_INDEX:`IE_I_SUB_IF_OP1_FIELD_LOWER_INDEX

`define IE_I_SUB_IF_OP2_FIELD_UPPER_INDEX  (3)
`define IE_I_SUB_IF_OP2_FIELD_LOWER_INDEX (0)
`define IE_I_SUB_IF_OP2_FIELD_RANGE `IE_I_SUB_IF_OP2_FIELD_UPPER_INDEX:`IE_I_SUB_IF_OP2_FIELD_LOWER_INDEX

`define IE_I_OR_UPPER_INDEX (16-1)
`define IE_I_OR_LOWER_INDEX (0)
`define IE_I_OR_WIDTH (16)
`define IE_I_OR_RANGE `IE_I_OR_UPPER_INDEX:`IE_I_OR_LOWER_INDEX
`define IE_I_OR_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_OR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_OR_IF_F_OPCODE_RANGE `IE_I_OR_IF_F_OPCODE_UPPER_INDEX:`IE_I_OR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_OR_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_OR_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_OR_IF_DST_R_FIELD_RANGE `IE_I_OR_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_OR_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_OR_IF_OP1_FIELD_UPPER_INDEX  (3)
`define IE_I_OR_IF_OP1_FIELD_LOWER_INDEX (0)
`define IE_I_OR_IF_OP1_FIELD_RANGE `IE_I_OR_IF_OP1_FIELD_UPPER_INDEX:`IE_I_OR_IF_OP1_FIELD_LOWER_INDEX

`define IE_I_OR_IF_OP2_FIELD_UPPER_INDEX  (3)
`define IE_I_OR_IF_OP2_FIELD_LOWER_INDEX (0)
`define IE_I_OR_IF_OP2_FIELD_RANGE `IE_I_OR_IF_OP2_FIELD_UPPER_INDEX:`IE_I_OR_IF_OP2_FIELD_LOWER_INDEX

`define IE_I_AND_UPPER_INDEX (16-1)
`define IE_I_AND_LOWER_INDEX (0)
`define IE_I_AND_WIDTH (16)
`define IE_I_AND_RANGE `IE_I_AND_UPPER_INDEX:`IE_I_AND_LOWER_INDEX
`define IE_I_AND_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_AND_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_AND_IF_F_OPCODE_RANGE `IE_I_AND_IF_F_OPCODE_UPPER_INDEX:`IE_I_AND_IF_F_OPCODE_LOWER_INDEX

`define IE_I_AND_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_AND_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_AND_IF_DST_R_FIELD_RANGE `IE_I_AND_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_AND_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_AND_IF_OP1_FIELD_UPPER_INDEX  (3)
`define IE_I_AND_IF_OP1_FIELD_LOWER_INDEX (0)
`define IE_I_AND_IF_OP1_FIELD_RANGE `IE_I_AND_IF_OP1_FIELD_UPPER_INDEX:`IE_I_AND_IF_OP1_FIELD_LOWER_INDEX

`define IE_I_AND_IF_OP2_FIELD_UPPER_INDEX  (3)
`define IE_I_AND_IF_OP2_FIELD_LOWER_INDEX (0)
`define IE_I_AND_IF_OP2_FIELD_RANGE `IE_I_AND_IF_OP2_FIELD_UPPER_INDEX:`IE_I_AND_IF_OP2_FIELD_LOWER_INDEX

`define IE_I_CMP_UPPER_INDEX (16-1)
`define IE_I_CMP_LOWER_INDEX (0)
`define IE_I_CMP_WIDTH (16)
`define IE_I_CMP_RANGE `IE_I_CMP_UPPER_INDEX:`IE_I_CMP_LOWER_INDEX
`define IE_I_CMP_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_CMP_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_CMP_IF_F_OPCODE_RANGE `IE_I_CMP_IF_F_OPCODE_UPPER_INDEX:`IE_I_CMP_IF_F_OPCODE_LOWER_INDEX

`define IE_I_CMP_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_CMP_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_CMP_IF_DST_R_FIELD_RANGE `IE_I_CMP_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_CMP_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_CMP_IF_OP1_FIELD_UPPER_INDEX  (3)
`define IE_I_CMP_IF_OP1_FIELD_LOWER_INDEX (0)
`define IE_I_CMP_IF_OP1_FIELD_RANGE `IE_I_CMP_IF_OP1_FIELD_UPPER_INDEX:`IE_I_CMP_IF_OP1_FIELD_LOWER_INDEX

`define IE_I_CMP_IF_OP2_FIELD_UPPER_INDEX  (3)
`define IE_I_CMP_IF_OP2_FIELD_LOWER_INDEX (0)
`define IE_I_CMP_IF_OP2_FIELD_RANGE `IE_I_CMP_IF_OP2_FIELD_UPPER_INDEX:`IE_I_CMP_IF_OP2_FIELD_LOWER_INDEX

`define IE_I_SH_UPPER_INDEX (16-1)
`define IE_I_SH_LOWER_INDEX (0)
`define IE_I_SH_WIDTH (16)
`define IE_I_SH_RANGE `IE_I_SH_UPPER_INDEX:`IE_I_SH_LOWER_INDEX
`define IE_I_SH_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_SH_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SH_IF_F_OPCODE_RANGE `IE_I_SH_IF_F_OPCODE_UPPER_INDEX:`IE_I_SH_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SH_IF_SHA_UPPER_INDEX  (3)
`define IE_I_SH_IF_SHA_LOWER_INDEX (0)
`define IE_I_SH_IF_SHA_RANGE `IE_I_SH_IF_SHA_UPPER_INDEX:`IE_I_SH_IF_SHA_LOWER_INDEX

`define IE_I_SH_IF_R_SRC_UPPER_INDEX  (3)
`define IE_I_SH_IF_R_SRC_LOWER_INDEX (0)
`define IE_I_SH_IF_R_SRC_RANGE `IE_I_SH_IF_R_SRC_UPPER_INDEX:`IE_I_SH_IF_R_SRC_LOWER_INDEX

`define IE_I_NOT_UPPER_INDEX (16-1)
`define IE_I_NOT_LOWER_INDEX (0)
`define IE_I_NOT_WIDTH (16)
`define IE_I_NOT_RANGE `IE_I_NOT_UPPER_INDEX:`IE_I_NOT_LOWER_INDEX
`define IE_I_NOT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_NOT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_NOT_IF_F_OPCODE_RANGE `IE_I_NOT_IF_F_OPCODE_UPPER_INDEX:`IE_I_NOT_IF_F_OPCODE_LOWER_INDEX

`define IE_I_NOT_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_NOT_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_NOT_IF_DST_R_FIELD_RANGE `IE_I_NOT_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_NOT_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_NOT_IF_R_SRC_UPPER_INDEX  (3)
`define IE_I_NOT_IF_R_SRC_LOWER_INDEX (0)
`define IE_I_NOT_IF_R_SRC_RANGE `IE_I_NOT_IF_R_SRC_UPPER_INDEX:`IE_I_NOT_IF_R_SRC_LOWER_INDEX

`define IE_I_SWP_UPPER_INDEX (16-1)
`define IE_I_SWP_LOWER_INDEX (0)
`define IE_I_SWP_WIDTH (16)
`define IE_I_SWP_RANGE `IE_I_SWP_UPPER_INDEX:`IE_I_SWP_LOWER_INDEX
`define IE_I_SWP_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_SWP_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_SWP_IF_F_OPCODE_RANGE `IE_I_SWP_IF_F_OPCODE_UPPER_INDEX:`IE_I_SWP_IF_F_OPCODE_LOWER_INDEX

`define IE_I_SWP_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_SWP_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_SWP_IF_DST_R_FIELD_RANGE `IE_I_SWP_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_SWP_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_SWP_IF_R_SRC_UPPER_INDEX  (3)
`define IE_I_SWP_IF_R_SRC_LOWER_INDEX (0)
`define IE_I_SWP_IF_R_SRC_RANGE `IE_I_SWP_IF_R_SRC_UPPER_INDEX:`IE_I_SWP_IF_R_SRC_LOWER_INDEX

`define IE_I_ROM_UPPER_INDEX (16-1)
`define IE_I_ROM_LOWER_INDEX (0)
`define IE_I_ROM_WIDTH (16)
`define IE_I_ROM_RANGE `IE_I_ROM_UPPER_INDEX:`IE_I_ROM_LOWER_INDEX
`define IE_I_ROM_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_ROM_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_ROM_IF_F_OPCODE_RANGE `IE_I_ROM_IF_F_OPCODE_UPPER_INDEX:`IE_I_ROM_IF_F_OPCODE_LOWER_INDEX

`define IE_I_ROM_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_ROM_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_ROM_IF_DST_R_FIELD_RANGE `IE_I_ROM_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_ROM_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_ROM_IF_R_SRC_UPPER_INDEX  (3)
`define IE_I_ROM_IF_R_SRC_LOWER_INDEX (0)
`define IE_I_ROM_IF_R_SRC_RANGE `IE_I_ROM_IF_R_SRC_UPPER_INDEX:`IE_I_ROM_IF_R_SRC_LOWER_INDEX

`define IE_I_CTOR_UPPER_INDEX (16-1)
`define IE_I_CTOR_LOWER_INDEX (0)
`define IE_I_CTOR_WIDTH (16)
`define IE_I_CTOR_RANGE `IE_I_CTOR_UPPER_INDEX:`IE_I_CTOR_LOWER_INDEX
`define IE_I_CTOR_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_CTOR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_CTOR_IF_F_OPCODE_RANGE `IE_I_CTOR_IF_F_OPCODE_UPPER_INDEX:`IE_I_CTOR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_CTOR_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_CTOR_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_CTOR_IF_DST_R_FIELD_RANGE `IE_I_CTOR_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_CTOR_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_CTOR_IF_ROM_ADDR_UPPER_INDEX  (7)
`define IE_I_CTOR_IF_ROM_ADDR_LOWER_INDEX (0)
`define IE_I_CTOR_IF_ROM_ADDR_RANGE `IE_I_CTOR_IF_ROM_ADDR_UPPER_INDEX:`IE_I_CTOR_IF_ROM_ADDR_LOWER_INDEX

`define IE_I_RT_UPPER_INDEX (16-1)
`define IE_I_RT_LOWER_INDEX (0)
`define IE_I_RT_WIDTH (16)
`define IE_I_RT_RANGE `IE_I_RT_UPPER_INDEX:`IE_I_RT_LOWER_INDEX
`define IE_I_RT_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_RT_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_RT_IF_F_OPCODE_RANGE `IE_I_RT_IF_F_OPCODE_UPPER_INDEX:`IE_I_RT_IF_F_OPCODE_LOWER_INDEX

`define IE_I_RT_IF_DST_R_FIELD_UPPER_INDEX  (3)
`define IE_I_RT_IF_DST_R_FIELD_LOWER_INDEX (0)
`define IE_I_RT_IF_DST_R_FIELD_RANGE `IE_I_RT_IF_DST_R_FIELD_UPPER_INDEX:`IE_I_RT_IF_DST_R_FIELD_LOWER_INDEX

`define IE_I_RT_IF_CONST_NMB_UPPER_INDEX  (7)
`define IE_I_RT_IF_CONST_NMB_LOWER_INDEX (0)
`define IE_I_RT_IF_CONST_NMB_RANGE `IE_I_RT_IF_CONST_NMB_UPPER_INDEX:`IE_I_RT_IF_CONST_NMB_LOWER_INDEX

`define IE_I_TOSR_UPPER_INDEX (16-1)
`define IE_I_TOSR_LOWER_INDEX (0)
`define IE_I_TOSR_WIDTH (16)
`define IE_I_TOSR_RANGE `IE_I_TOSR_UPPER_INDEX:`IE_I_TOSR_LOWER_INDEX
`define IE_I_TOSR_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_TOSR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_TOSR_IF_F_OPCODE_RANGE `IE_I_TOSR_IF_F_OPCODE_UPPER_INDEX:`IE_I_TOSR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_TOSR_IF_DST_UPPER_INDEX  (3)
`define IE_I_TOSR_IF_DST_LOWER_INDEX (0)
`define IE_I_TOSR_IF_DST_RANGE `IE_I_TOSR_IF_DST_UPPER_INDEX:`IE_I_TOSR_IF_DST_LOWER_INDEX

`define IE_I_TOSR_IF_SRC_UPPER_INDEX  (3)
`define IE_I_TOSR_IF_SRC_LOWER_INDEX (0)
`define IE_I_TOSR_IF_SRC_RANGE `IE_I_TOSR_IF_SRC_UPPER_INDEX:`IE_I_TOSR_IF_SRC_LOWER_INDEX

`define IE_I_TOSR_IF_D_UPPER_INDEX  (0)
`define IE_I_TOSR_IF_D_LOWER_INDEX (0)
`define IE_I_TOSR_IF_D_RANGE `IE_I_TOSR_IF_D_UPPER_INDEX:`IE_I_TOSR_IF_D_LOWER_INDEX

`define IE_I_FROMSR_UPPER_INDEX (16-1)
`define IE_I_FROMSR_LOWER_INDEX (0)
`define IE_I_FROMSR_WIDTH (16)
`define IE_I_FROMSR_RANGE `IE_I_FROMSR_UPPER_INDEX:`IE_I_FROMSR_LOWER_INDEX
`define IE_I_FROMSR_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_FROMSR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_FROMSR_IF_F_OPCODE_RANGE `IE_I_FROMSR_IF_F_OPCODE_UPPER_INDEX:`IE_I_FROMSR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_FROMSR_IF_DST_UPPER_INDEX  (3)
`define IE_I_FROMSR_IF_DST_LOWER_INDEX (0)
`define IE_I_FROMSR_IF_DST_RANGE `IE_I_FROMSR_IF_DST_UPPER_INDEX:`IE_I_FROMSR_IF_DST_LOWER_INDEX

`define IE_I_FROMSR_IF_SRC_UPPER_INDEX  (3)
`define IE_I_FROMSR_IF_SRC_LOWER_INDEX (0)
`define IE_I_FROMSR_IF_SRC_RANGE `IE_I_FROMSR_IF_SRC_UPPER_INDEX:`IE_I_FROMSR_IF_SRC_LOWER_INDEX

`define IE_I_FROMSR_IF_D_UPPER_INDEX  (0)
`define IE_I_FROMSR_IF_D_LOWER_INDEX (0)
`define IE_I_FROMSR_IF_D_RANGE `IE_I_FROMSR_IF_D_UPPER_INDEX:`IE_I_FROMSR_IF_D_LOWER_INDEX

`define IE_I_TORAM_UPPER_INDEX (16-1)
`define IE_I_TORAM_LOWER_INDEX (0)
`define IE_I_TORAM_WIDTH (16)
`define IE_I_TORAM_RANGE `IE_I_TORAM_UPPER_INDEX:`IE_I_TORAM_LOWER_INDEX
`define IE_I_TORAM_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_TORAM_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_TORAM_IF_F_OPCODE_RANGE `IE_I_TORAM_IF_F_OPCODE_UPPER_INDEX:`IE_I_TORAM_IF_F_OPCODE_LOWER_INDEX

`define IE_I_TORAM_IF_R_SRC_UPPER_INDEX  (3)
`define IE_I_TORAM_IF_R_SRC_LOWER_INDEX (0)
`define IE_I_TORAM_IF_R_SRC_RANGE `IE_I_TORAM_IF_R_SRC_UPPER_INDEX:`IE_I_TORAM_IF_R_SRC_LOWER_INDEX

`define IE_I_TORAM_IF_D_UPPER_INDEX  (0)
`define IE_I_TORAM_IF_D_LOWER_INDEX (0)
`define IE_I_TORAM_IF_D_RANGE `IE_I_TORAM_IF_D_UPPER_INDEX:`IE_I_TORAM_IF_D_LOWER_INDEX

`define IE_I_FROMRAM_UPPER_INDEX (16-1)
`define IE_I_FROMRAM_LOWER_INDEX (0)
`define IE_I_FROMRAM_WIDTH (16)
`define IE_I_FROMRAM_RANGE `IE_I_FROMRAM_UPPER_INDEX:`IE_I_FROMRAM_LOWER_INDEX
`define IE_I_FROMRAM_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_FROMRAM_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_FROMRAM_IF_F_OPCODE_RANGE `IE_I_FROMRAM_IF_F_OPCODE_UPPER_INDEX:`IE_I_FROMRAM_IF_F_OPCODE_LOWER_INDEX

`define IE_I_FROMRAM_IF_R_SRC_UPPER_INDEX  (3)
`define IE_I_FROMRAM_IF_R_SRC_LOWER_INDEX (0)
`define IE_I_FROMRAM_IF_R_SRC_RANGE `IE_I_FROMRAM_IF_R_SRC_UPPER_INDEX:`IE_I_FROMRAM_IF_R_SRC_LOWER_INDEX

`define IE_I_FROMRAM_IF_D_UPPER_INDEX  (0)
`define IE_I_FROMRAM_IF_D_LOWER_INDEX (0)
`define IE_I_FROMRAM_IF_D_RANGE `IE_I_FROMRAM_IF_D_UPPER_INDEX:`IE_I_FROMRAM_IF_D_LOWER_INDEX

`define IE_I_BR_UPPER_INDEX (16-1)
`define IE_I_BR_LOWER_INDEX (0)
`define IE_I_BR_WIDTH (16)
`define IE_I_BR_RANGE `IE_I_BR_UPPER_INDEX:`IE_I_BR_LOWER_INDEX
`define IE_I_BR_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_BR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_BR_IF_F_OPCODE_RANGE `IE_I_BR_IF_F_OPCODE_UPPER_INDEX:`IE_I_BR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_BR_IF_COND_FIELD0_UPPER_INDEX  (0)
`define IE_I_BR_IF_COND_FIELD0_LOWER_INDEX (0)
`define IE_I_BR_IF_COND_FIELD0_RANGE `IE_I_BR_IF_COND_FIELD0_UPPER_INDEX:`IE_I_BR_IF_COND_FIELD0_LOWER_INDEX

`define IE_I_BR_IF_BR_ADDR_UPPER_INDEX  (10)
`define IE_I_BR_IF_BR_ADDR_LOWER_INDEX (0)
`define IE_I_BR_IF_BR_ADDR_RANGE `IE_I_BR_IF_BR_ADDR_UPPER_INDEX:`IE_I_BR_IF_BR_ADDR_LOWER_INDEX

`define IE_I_INCR_UPPER_INDEX (16-1)
`define IE_I_INCR_LOWER_INDEX (0)
`define IE_I_INCR_WIDTH (16)
`define IE_I_INCR_RANGE `IE_I_INCR_UPPER_INDEX:`IE_I_INCR_LOWER_INDEX
`define IE_I_INCR_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_INCR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_INCR_IF_F_OPCODE_RANGE `IE_I_INCR_IF_F_OPCODE_UPPER_INDEX:`IE_I_INCR_IF_F_OPCODE_LOWER_INDEX

`define IE_I_DECR_UPPER_INDEX (16-1)
`define IE_I_DECR_LOWER_INDEX (0)
`define IE_I_DECR_WIDTH (16)
`define IE_I_DECR_RANGE `IE_I_DECR_UPPER_INDEX:`IE_I_DECR_LOWER_INDEX
`define IE_I_DECR_IF_F_OPCODE_UPPER_INDEX  (3)
`define IE_I_DECR_IF_F_OPCODE_LOWER_INDEX (0)
`define IE_I_DECR_IF_F_OPCODE_RANGE `IE_I_DECR_IF_F_OPCODE_UPPER_INDEX:`IE_I_DECR_IF_F_OPCODE_LOWER_INDEX


`endif
