`ifndef INC_GUARD_i2c
`define INC_GUARD_i2c

`define IFC_LBA_P_DUMMY3_UPPER_INDEX  0
`define IFC_LBA_P_DUMMY3_LOWER_INDEX  0
`define IFC_LBA_P_DUMMY3_WIDTH  1
`define IFC_LBA_P_DUMMY3_RANGE `IFC_LBA_P_DUMMY3_UPPER_INDEX:`IFC_LBA_P_DUMMY3_LOWER_INDEX

`endif
