`ifndef INC_GUARD_u
`define INC_GUARD_u

`define IFC_IFC0_P_P_P1_UPPER_INDEX  (0)
`define IFC_IFC0_P_P_P1_LOWER_INDEX  (0)
`define IFC_IFC0_P_P_P1_WIDTH  (0-0+1)
`define IFC_IFC0_P_P_P1_RANGE `IFC_IFC0_P_P_P1_UPPER_INDEX:`IFC_IFC0_P_P_P1_LOWER_INDEX
`define IFC_IFC0_P_P_P2_UPPER_INDEX  (8-1)
`define IFC_IFC0_P_P_P2_LOWER_INDEX  (0)
`define IFC_IFC0_P_P_P2_WIDTH  (8)
`define IFC_IFC0_P_P_P2_RANGE `IFC_IFC0_P_P_P2_UPPER_INDEX:`IFC_IFC0_P_P_P2_LOWER_INDEX
`define IFC_IFC0_P_P_P3_UPPER_INDEX  (32-1)
`define IFC_IFC0_P_P_P3_LOWER_INDEX  (0)
`define IFC_IFC0_P_P_P3_WIDTH  (32)
`define IFC_IFC0_P_P_P3_RANGE `IFC_IFC0_P_P_P3_UPPER_INDEX:`IFC_IFC0_P_P_P3_LOWER_INDEX

`endif
