`ifndef INC_GUARD_u1
`define INC_GUARD_u1

`define IFC_IFCA1_P_X1_UPPER_INDEX  (68-1)
`define IFC_IFCA1_P_X1_LOWER_INDEX  (0)
`define IFC_IFCA1_P_X1_WIDTH  (68)
`define IFC_IFCA1_P_X1_RANGE `IFC_IFCA1_P_X1_UPPER_INDEX:`IFC_IFCA1_P_X1_LOWER_INDEX
`define IFC_IFCA1_P_X2_UPPER_INDEX  (68-1)
`define IFC_IFCA1_P_X2_LOWER_INDEX  (0)
`define IFC_IFCA1_P_X2_WIDTH  (68)
`define IFC_IFCA1_P_X2_RANGE `IFC_IFCA1_P_X2_UPPER_INDEX:`IFC_IFCA1_P_X2_LOWER_INDEX

`endif
