`ifndef INC_GUARD_u2
`define INC_GUARD_u2

`define SG_SGA1_S_X1_UPPER_INDEX  (param_y-1)
`define SG_SGA1_S_X1_LOWER_INDEX  (0)
`define SG_SGA1_S_X1_WIDTH  (param_y)
`define SG_SGA1_S_X1_RANGE `SG_SGA1_S_X1_UPPER_INDEX:`SG_SGA1_S_X1_LOWER_INDEX
`define SG_SGA1_S_X2_UPPER_INDEX  (param_x-1)
`define SG_SGA1_S_X2_LOWER_INDEX  (0)
`define SG_SGA1_S_X2_WIDTH  (param_x)
`define SG_SGA1_S_X2_RANGE `SG_SGA1_S_X2_UPPER_INDEX:`SG_SGA1_S_X2_LOWER_INDEX

`endif
