`ifndef INC_GUARD_fifo
`define INC_GUARD_fifo

`define P_PUSH_UPPER_INDEX  (1-1)
`define P_PUSH_LOWER_INDEX  (0)
`define P_PUSH_WIDTH  (1)
`define P_PUSH_RANGE `P_PUSH_UPPER_INDEX:`P_PUSH_LOWER_INDEX
`define P_POP_UPPER_INDEX  (1-1)
`define P_POP_LOWER_INDEX  (0)
`define P_POP_WIDTH  (1)
`define P_POP_RANGE `P_POP_UPPER_INDEX:`P_POP_LOWER_INDEX
`define P_FULL_UPPER_INDEX  (1-1)
`define P_FULL_LOWER_INDEX  (0)
`define P_FULL_WIDTH  (1)
`define P_FULL_RANGE `P_FULL_UPPER_INDEX:`P_FULL_LOWER_INDEX
`define P_EMPTY_UPPER_INDEX  (1-1)
`define P_EMPTY_LOWER_INDEX  (0)
`define P_EMPTY_WIDTH  (1)
`define P_EMPTY_RANGE `P_EMPTY_UPPER_INDEX:`P_EMPTY_LOWER_INDEX
`define P_RD_DATA_UPPER_INDEX  (y-1)
`define P_RD_DATA_LOWER_INDEX  (0)
`define P_RD_DATA_WIDTH  (y)
`define P_RD_DATA_RANGE `P_RD_DATA_UPPER_INDEX:`P_RD_DATA_LOWER_INDEX
`define P_WR_DATA_UPPER_INDEX  (y-1)
`define P_WR_DATA_LOWER_INDEX  (0)
`define P_WR_DATA_WIDTH  (y)
`define P_WR_DATA_RANGE `P_WR_DATA_UPPER_INDEX:`P_WR_DATA_LOWER_INDEX
`define P_RESET__UPPER_INDEX  (1-1)
`define P_RESET__LOWER_INDEX  (0)
`define P_RESET__WIDTH  (1)
`define P_RESET__RANGE `P_RESET__UPPER_INDEX:`P_RESET__LOWER_INDEX
`define P_CLOCK_UPPER_INDEX  (1-1)
`define P_CLOCK_LOWER_INDEX  (0)
`define P_CLOCK_WIDTH  (1)
`define P_CLOCK_RANGE `P_CLOCK_UPPER_INDEX:`P_CLOCK_LOWER_INDEX
`define P_VALID_UPPER_INDEX  (1-1)
`define P_VALID_LOWER_INDEX  (0)
`define P_VALID_WIDTH  (1)
`define P_VALID_RANGE `P_VALID_UPPER_INDEX:`P_VALID_LOWER_INDEX

`endif
