#!/usr/bin/perl

#oanab
#tb,verif comp methods; part select also

use strict;

print "Generated tests path : test/csl_test_gen/tb_verif_comp_invalid/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "tb_verif_comp".$i."_illegal.csl";
   	&createCslFile($test_name, $i, %dir);
}

sub createCslFile {
    my ($test_name, $i, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(20))+1;
    my $val2 = int(rand(100))+4;
    my $val3 = int(rand(100))+3;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/tb_verif_comp_valid");
        open(FH,">$path/tb_verif_comp_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/tb_verif_comp_invalid"); 
        open(FH,">$path/tb_verif_comp_invalid/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n";
    print FH "csl_bitrange br2($val2);\n";
    print FH "csl_bitrange br3(".($val1+$val2+$val3).");\n";

#interface ifc
    if($i > 100 && $i <= 200) {
	print FH "csl_interface ifc$k {\n";
	print FH "  csl_port p_x$i(input,$val2);\n";
	print FH "  csl_port p_y$i(input,br1);\n";
	if($i <= 150) {
	    print FH "  csl_port p_z$i(output,br3\[".($val2+$val3)."\:".($val2+1)."\]);\n";
	}
	print FH "  ifc$k () {}\n";
	print FH "};\n\n";
    }  

#signal group sg
    if($i > 50 && $i <= 150) {
	print FH "csl_signal_group sg$k {\n";
	print FH "  csl_signal s_x$i($val2);\n";
	print FH "  csl_signal s_y$i(br3\[".($val1+$val2)."\-\:".($val1+1)."\]);\n";
	print FH "  csl_signal s_z$i($val3);\n";
	print FH "  sg$k () {}\n";
	print FH "};\n\n";
    }


#unit a
    print FH "csl_unit a$k {\n";
    print FH "  csl_port p$i($dir{$l},$val1);\n";
    if($i <= 100) {
	print FH "  csl_port p_in(input,$val1);\n";
	print FH "  csl_port p_out(output,$val1);\n";
	print FH "  csl_port clk(input);\n";
	if($i <= 50) {
	    print FH "  csl_signal s_a$i(br3\[".($val1+$val2)."\-\:".($val2)."\]);\n";
	    print FH "  csl_signal s_b$i($val3);\n";
	}
	elsif($i > 50 && $i <= 100) {
	    print FH "  csl_signal s$i($val2);\n";
	    print FH "  sg$k sg$k\_$zero;\n";
	}
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_in(input,br1);\n";
	print FH "  csl_port p_out(output,$val1);\n";
	print FH "  csl_port p_x$i(input,br3\[".($val1+$val2+$val3)."\-\:".($val3)."\]);\n";
	print FH "  csl_port p_y$i(output,br1);\n";
	print FH "  csl_port clk(input);\n";
    }
    print FH "  a$k () {\n";
    if($i <= 100 || $i > 200) {
	print FH "    clk.set_attr(clock);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";
    

#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i > 100 && $i <= 150) {
	print FH "  csl_port clk(input);\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  sg$k sg$k\_$zero;\n";
    }
    print FH "  b$k () {\n";
    if($i > 100 && $i <= 150) {
	print FH "    clk.set_attr(clock);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i > 150 && $i <= 200) {
	print FH "  csl_port p_out(output,$val1);\n";
	print FH "  csl_port p_y$i(output);\n";
	print FH "  csl_port clk(input);\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    print FH "  c$k () {\n";
    if($i > 150 && $i <= 200) {
	print FH "    clk.set_attr(clock);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#stim vector
    print FH "csl_vector stim_vect$k {\n";
    print FH "  stim_vect$k () {\n";
#Invalid : sig.ps []
    if($i <= 50) {
	print FH "    set_unit_name(a$k);\n";
	print FH "    set_direction(input);\n";
	print FH "    exclusion_list(s_a$i\[3\]);  // Invalid : sig.ps as argument\n";
    }
#Invalid : sig
    elsif($i > 50 && $i <= 100) {
	print FH "    set_unit_name(a$k);\n";
	print FH "    set_direction(input);\n";
	print FH "    include_only(s$i);  // Invalid : sig as argument\n";
    }
#Invalid : ifc,sg
    elsif($i > 100 && $i <= 150) {
	print FH "    set_unit_name(b$k);\n";
	print FH "    set_direction(input);\n";
	print FH "    include_only(ifc$k\_$zero);  // Invalid : ifc as argument\n";
	print FH "    exclusion_list(sg$k\_$zero);  // Invalid : sg as argument\n";
    }
#Invalid : ifc
    elsif($i > 150 && $i <= 200) {
	print FH "    set_unit_name(c$k);\n";
	print FH "    set_direction(input);\n";
	print FH "    include_only(ifc$k\_$zero.p_x$i);\n";
	print FH "    exclusion_list(ifc$k\_$zero);  // Invalid : ifc as argument\n";
    }
#Invalid range for ps : p.ps [:]
    elsif($i > 200 && $i <= 250) {
	print FH "    set_unit_name(a$k);\n";
	print FH "    set_direction(input);\n";
	print FH "    exclusion_list(p_x$i\[".($val2+$val3+$val1)."\:".($val2)."\]);  Invalid range for ps\n";
    }
    print FH "  }\n";
    print FH "};\n\n";
    

#exp vector
    print FH "csl_vector exp_vect$k {\n";
    print FH "  exp_vect$k () {\n";
#Invalid : sig.ps [-:]
    if($i <= 50) {
	print FH "    set_unit_name(a$k);\n";
	print FH "    set_direction(output);\n";
	print FH "    include_only(s_b$i\[".$val3."\-\:".(3)."\]);  // Invalid : sig.ps as argument\n";
    }
#Invalid : sg.sig
    elsif($i > 50 && $i <= 100) {
	print FH "    set_unit_name(a$k);\n";
	print FH "    set_direction(output);\n";
	print FH "    exclusion_list(sg$k\_$zero.s_x$i,sg$k\_$zero.s_z$i);  // Invalid : sg.sig as argument\n";
    }
#Invalid : sg
    elsif($i > 100 && $i <= 150) {
	print FH "    set_unit_name(b$k);\n";
	print FH "    set_direction(output);\n";
	print FH "    include_only(sg$k\_$zero);  // Invalid : sg as argument\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    set_unit_name(c$k);\n";
	print FH "    set_direction(output);\n";
    }
#Invalid range for ps (upper limit) : p.ps [-:]
    elsif($i > 200 && $i <= 250) {
	print FH "    set_unit_name(a$k);\n";
	print FH "    set_direction(output);\n";
	print FH "    include_only(p_y$i\[".($val1+$val2)."\-\:".(2)."\]);  Invalid range for ps (upper limit)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";
    

#testbench tb
    print FH "csl_testbench tb$k {\n";
    if($i <= 100 || $i > 200) {
	print FH "  csl_signal clk(reg);\n";
 	print FH "  a$k a$k\_$zero(.clk(clk));\n";
    }
    elsif($i > 100 && $i <= 200) {
	print FH "  csl_signal clk(reg);\n";
	if($i <= 150) {
	    print FH "  b$k b$k\_$zero(.clk(clk));\n";
	}
	else {
	    print FH "  c$k c$k\_$zero(.clk(clk));\n";
	}
    }
    print FH "  tb$k () {\n";
#Invalid : sig.ps []
    if($i <= 50) {
	print FH "    clk.set_attr(clock);\n";
	print FH "    add_logic(clock,clk[1],10,ps);  // Invalid use of part select\n";
    }
    elsif($i > 50 && $i <= 250) {
	print FH "    clk.set_attr(clock);\n";
	print FH "    add_logic(clock,clk,10,ps);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";
    

}
