`ifndef INC_GUARD_ddr_buf_ctrl
`define INC_GUARD_ddr_buf_ctrl

`define IFC_LB_P_DUMMY2_UPPER_INDEX  0
`define IFC_LB_P_DUMMY2_LOWER_INDEX  0
`define IFC_LB_P_DUMMY2_WIDTH  1
`define IFC_LB_P_DUMMY2_RANGE `IFC_LB_P_DUMMY2_UPPER_INDEX:`IFC_LB_P_DUMMY2_LOWER_INDEX
`define IFC_DC_DBC_P_DUMMY5_UPPER_INDEX  0
`define IFC_DC_DBC_P_DUMMY5_LOWER_INDEX  0
`define IFC_DC_DBC_P_DUMMY5_WIDTH  1
`define IFC_DC_DBC_P_DUMMY5_RANGE `IFC_DC_DBC_P_DUMMY5_UPPER_INDEX:`IFC_DC_DBC_P_DUMMY5_LOWER_INDEX

`endif
