#!/usr/bin/perl

#oanab
#method called for a port,signal,ifc,sg, unit, register, register file

use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

print "Generated scripts path : inter_set_clock_invalid1/\n";

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 300; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    #my @dir = ("input","output","inout");
    #my $l = int(rand($#dir+1));
    my @sp = ("  csl_port clk(input);","  csl_signal clk(reg);");
    my $test_name = "inter_set_clock".$i."_illegal.csl";
   	&createCslFile($test_name, $i, @sp);
}

sub createCslFile {
    my ($test_name, $i, @sp) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+1;
    my $val2 = int(rand(100))+2;
    my $val3 = int(rand(100))+3;
    if($test_name=~/(_legal)/){
        &mkDir("$path/inter_set_clock_valid");
        open(FH,">$path/inter_set_clock_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/inter_set_clock_invalid1"); 
        open(FH,">$path/inter_set_clock_invalid1/$test_name");
    }
    print FH "//Generated by oanab\n\n";
    print FH "//Test cases from: set_clock_matrix.ods\n";

#interface ifck
    if($i > 50 && $i <= 250) {
	print FH "csl_interface ifc$k {\n";
	print FH "  csl_port p_x$i(input,$val2);\n";
	print FH "  csl_port p_y$i(output,$val3);\n";
	print FH "  csl_port p_z$i(input,$val1);\n";
	if($i > 100 && $i <= 125) {
	    print FH "  csl_port p_w$i(inout,$val2);\n";
	}
	print FH "  ifc$k () {\n";
	if($i > 200 && $i <= 250) {
	    print FH "    set_clock(clk);\n";
	}
	print FH "  }\n";
	print FH "};\n\n";
    }

#signal group sgk
    if($i > 50 && $i <= 150 || $i > 200 && $i <= 300) {
	print FH "csl_signal_group sg$k {\n";
	print FH "  csl_signal s_x$i($val1);\n";
	print FH "  csl_signal s_y$i(".($val2+5).");\n";
	if($i > 175) {
	    print FH "  csl_signal s_z$i($val3);\n";
	    print FH "  csl_signal s_w$i(".($val2+1).");\n";
	}
	print FH "  sg$k () {\n";
	if($i > 250 && $i <= 300) {
	    print FH "    set_clock(clk);\n";
	}
	print FH "  }\n";
	print FH "};\n\n";
    }

#register reg
    if($i <= 150) {
	print FH "csl_register reg$k {\n";
	print FH "  reg$k () {\n";
	print FH "    set_width($val2);\n";
	print FH "    set_type(register);\n";
	if($i <= 25 || $i > 50 && $i <= 150) {
	    print FH "    set_clock(clk);\n";
	}
	print FH "  }\n";
	print FH "};\n\n";
    }

#register file rf
    if($i > 150 && $i <= 300) {
	print FH "csl_register_file rf$k {\n";
	print FH "  rf$k () {\n";
	print FH "    set_width($val3);\n";
	print FH "    set_depth(".($val2+$val3).");\n";
	if($i > 150 && $i <= 175 || $i > 200) {
	    print FH "    set_clock(clk);\n";
	}
	print FH "  }\n";
	print FH "};\n\n";
    }

#unit a
    print FH "csl_unit a$k {\n";
    print FH $sp[int rand($#sp+1)];
    print FH "\n";
    if($i <= 25) {
	print FH "  csl_port p_$i(input,$val3);\n";
    }
    elsif($i > 25 && $i <= 50) {
	print FH "  csl_signal s_$i(".($val2+1).");\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  reg$k reg$k\_$zero;\n";
    } 
    elsif($i > 150 && $i <= 200) {
	print FH "  rf$k rf$k\_$zero;\n";
	print FH "  csl_port p_a$i(output,$val2);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  rf$k rf$k\_$one;\n";
	print FH "  sg$k sg$k\_$one;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  rf$k rf$k\_$one;\n";
    }
    print FH "  a$k () {\n";
    print FH "    clk.set_attr(clock);\n";
    if($i <= 25) {
	print FH "    p_$i.set_clock(clk);\n";
    }
    elsif($i > 25 && $i <= 50) {
	print FH "    s_$i.set_clock(clk);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    ifc$k\_$zero.p_y$i.set_clock(clk);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    set_clock(clk);\n";
    }
    elsif($i > 175 && $i <= 200) {
	print FH "    rf$k\_$zero.set_clock(clk);\n";
	print FH "    p_a$i.set_clock(clk);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "    sg$k\_$one.s_w$i.set_clock(clk);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


# unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    print FH $sp[int rand($#sp+1)];
    print FH "\n";
    if($i <= 50) {
	print FH "  reg$k reg$k\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$k sg$k\_$zero;\n";
    } 
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$k ifc$k\_$one;\n";
	print FH "  sg$k sg$k\_$one;\n";
	print FH "  reg$k reg$k\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$k ifc$k\_$one;\n";
	print FH "  csl_signal s_a$i($val2);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  ifc$k ifc$k\_$one;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$k sg$k\_$two;\n";
    }
    print FH "  b$k () {\n";
    print FH "    clk.set_attr(clock);\n";
    if($i > 25 && $i <= 50) {
	print FH "    reg$k\_$zero.set_clock(clk);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$k\_$zero.s_x$i.set_clock(clk);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    ifc$k\_$one.set_clock(clk);\n";
	print FH "    ifc$k\_$one.set_clock(clk);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    ifc$k\_$one.p_z$i.set_clock(clk);\n";
	print FH "    s_a$i.set_clock(clk);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "    a$k\_$zero.set_clock(clk);\n";
    }
    print FH "  }\n";
    print FH "};\n";









}
