`ifndef INC_GUARD_rf_reg
`define INC_GUARD_rf_reg

`define P_RESET__UPPER_INDEX  (0)
`define P_RESET__LOWER_INDEX  (0)
`define P_RESET__WIDTH  (0-0+1)
`define P_RESET__RANGE `P_RESET__UPPER_INDEX:`P_RESET__LOWER_INDEX
`define P_ENABLE_UPPER_INDEX  (0)
`define P_ENABLE_LOWER_INDEX  (0)
`define P_ENABLE_WIDTH  (0-0+1)
`define P_ENABLE_RANGE `P_ENABLE_UPPER_INDEX:`P_ENABLE_LOWER_INDEX
`define P_CLOCK_UPPER_INDEX  (0)
`define P_CLOCK_LOWER_INDEX  (0)
`define P_CLOCK_WIDTH  (0-0+1)
`define P_CLOCK_RANGE `P_CLOCK_UPPER_INDEX:`P_CLOCK_LOWER_INDEX
`define P_REG_OUT_UPPER_INDEX  (32-1)
`define P_REG_OUT_LOWER_INDEX  (0)
`define P_REG_OUT_WIDTH  (32)
`define P_REG_OUT_RANGE `P_REG_OUT_UPPER_INDEX:`P_REG_OUT_LOWER_INDEX
`define P_REG_IN_UPPER_INDEX  (32-1)
`define P_REG_IN_LOWER_INDEX  (0)
`define P_REG_IN_WIDTH  (32)
`define P_REG_IN_RANGE `P_REG_IN_UPPER_INDEX:`P_REG_IN_LOWER_INDEX

`endif
