`ifndef INC_GUARD_fifo_regs
`define INC_GUARD_fifo_regs

`define IFC_FIFO_REG_BUS0_P_WRITE_EN_UPPER_INDEX  (0)
`define IFC_FIFO_REG_BUS0_P_WRITE_EN_LOWER_INDEX  (0)
`define IFC_FIFO_REG_BUS0_P_WRITE_EN_WIDTH  (0-0+1)
`define IFC_FIFO_REG_BUS0_P_WRITE_EN_RANGE `IFC_FIFO_REG_BUS0_P_WRITE_EN_UPPER_INDEX:`IFC_FIFO_REG_BUS0_P_WRITE_EN_LOWER_INDEX
`define IFC_FIFO_REG_BUS0_P_ADDR_UPPER_INDEX  (5-1)
`define IFC_FIFO_REG_BUS0_P_ADDR_LOWER_INDEX  (0)
`define IFC_FIFO_REG_BUS0_P_ADDR_WIDTH  (5)
`define IFC_FIFO_REG_BUS0_P_ADDR_RANGE `IFC_FIFO_REG_BUS0_P_ADDR_UPPER_INDEX:`IFC_FIFO_REG_BUS0_P_ADDR_LOWER_INDEX
`define IFC_FIFO_REG_BUS0_P_WRITE_DATA_UPPER_INDEX  (12-1)
`define IFC_FIFO_REG_BUS0_P_WRITE_DATA_LOWER_INDEX  (0)
`define IFC_FIFO_REG_BUS0_P_WRITE_DATA_WIDTH  (12)
`define IFC_FIFO_REG_BUS0_P_WRITE_DATA_RANGE `IFC_FIFO_REG_BUS0_P_WRITE_DATA_UPPER_INDEX:`IFC_FIFO_REG_BUS0_P_WRITE_DATA_LOWER_INDEX
`define IFC_FIFO_REG_BUS0_P_READ_DATA_UPPER_INDEX  (12-1)
`define IFC_FIFO_REG_BUS0_P_READ_DATA_LOWER_INDEX  (0)
`define IFC_FIFO_REG_BUS0_P_READ_DATA_WIDTH  (12)
`define IFC_FIFO_REG_BUS0_P_READ_DATA_RANGE `IFC_FIFO_REG_BUS0_P_READ_DATA_UPPER_INDEX:`IFC_FIFO_REG_BUS0_P_READ_DATA_LOWER_INDEX
`define IFC_FIFO_REG_P_WRITE_EN_UPPER_INDEX  (0)
`define IFC_FIFO_REG_P_WRITE_EN_LOWER_INDEX  (0)
`define IFC_FIFO_REG_P_WRITE_EN_WIDTH  (0-0+1)
`define IFC_FIFO_REG_P_WRITE_EN_RANGE `IFC_FIFO_REG_P_WRITE_EN_UPPER_INDEX:`IFC_FIFO_REG_P_WRITE_EN_LOWER_INDEX
`define IFC_FIFO_REG_P_ADDR_UPPER_INDEX  (5-1)
`define IFC_FIFO_REG_P_ADDR_LOWER_INDEX  (0)
`define IFC_FIFO_REG_P_ADDR_WIDTH  (5)
`define IFC_FIFO_REG_P_ADDR_RANGE `IFC_FIFO_REG_P_ADDR_UPPER_INDEX:`IFC_FIFO_REG_P_ADDR_LOWER_INDEX
`define IFC_FIFO_REG_P_WRITE_DATA_UPPER_INDEX  (12-1)
`define IFC_FIFO_REG_P_WRITE_DATA_LOWER_INDEX  (0)
`define IFC_FIFO_REG_P_WRITE_DATA_WIDTH  (12)
`define IFC_FIFO_REG_P_WRITE_DATA_RANGE `IFC_FIFO_REG_P_WRITE_DATA_UPPER_INDEX:`IFC_FIFO_REG_P_WRITE_DATA_LOWER_INDEX
`define IFC_FIFO_REG_P_READ_DATA_UPPER_INDEX  (12-1)
`define IFC_FIFO_REG_P_READ_DATA_LOWER_INDEX  (0)
`define IFC_FIFO_REG_P_READ_DATA_WIDTH  (12)
`define IFC_FIFO_REG_P_READ_DATA_RANGE `IFC_FIFO_REG_P_READ_DATA_UPPER_INDEX:`IFC_FIFO_REG_P_READ_DATA_LOWER_INDEX

`endif
