`ifndef INC_GUARD_io_cell
`define INC_GUARD_io_cell

`define IFC_PAD_P_IN_UPPER_INDEX  (0)
`define IFC_PAD_P_IN_LOWER_INDEX  (0)
`define IFC_PAD_P_IN_WIDTH  (0-0+1)
`define IFC_PAD_P_IN_RANGE `IFC_PAD_P_IN_UPPER_INDEX:`IFC_PAD_P_IN_LOWER_INDEX
`define IFC_PAD_P_OUT_UPPER_INDEX  (0)
`define IFC_PAD_P_OUT_LOWER_INDEX  (0)
`define IFC_PAD_P_OUT_WIDTH  (0-0+1)
`define IFC_PAD_P_OUT_RANGE `IFC_PAD_P_OUT_UPPER_INDEX:`IFC_PAD_P_OUT_LOWER_INDEX
`define IFC_PAD_P_EN_UPPER_INDEX  (0)
`define IFC_PAD_P_EN_LOWER_INDEX  (0)
`define IFC_PAD_P_EN_WIDTH  (0-0+1)
`define IFC_PAD_P_EN_RANGE `IFC_PAD_P_EN_UPPER_INDEX:`IFC_PAD_P_EN_LOWER_INDEX
`define P_PAD_PIN_UPPER_INDEX  (0)
`define P_PAD_PIN_LOWER_INDEX  (0)
`define P_PAD_PIN_WIDTH  (0-0+1)
`define P_PAD_PIN_RANGE `P_PAD_PIN_UPPER_INDEX:`P_PAD_PIN_LOWER_INDEX

`endif
