`ifndef INC_GUARD_u_c
`define INC_GUARD_u_c

`define P_AR_P_T_IN_P_A_IN_UPPER_INDEX  (2-1)
`define P_AR_P_T_IN_P_A_IN_LOWER_INDEX  (0)
`define P_AR_P_T_IN_P_A_IN_WIDTH  (2)
`define P_AR_P_T_IN_P_A_IN_RANGE `P_AR_P_T_IN_P_A_IN_UPPER_INDEX:`P_AR_P_T_IN_P_A_IN_LOWER_INDEX
`define P_AR_P_T_OUT1_P_A_OUT_UPPER_INDEX  (1-1)
`define P_AR_P_T_OUT1_P_A_OUT_LOWER_INDEX  (0)
`define P_AR_P_T_OUT1_P_A_OUT_WIDTH  (1)
`define P_AR_P_T_OUT1_P_A_OUT_RANGE `P_AR_P_T_OUT1_P_A_OUT_UPPER_INDEX:`P_AR_P_T_OUT1_P_A_OUT_LOWER_INDEX

`endif
