`ifndef INC_GUARD_u3
`define INC_GUARD_u3

`define P_X_UPPER_INDEX  (18-1)
`define P_X_LOWER_INDEX  (0)
`define P_X_WIDTH  (18)
`define P_X_RANGE `P_X_UPPER_INDEX:`P_X_LOWER_INDEX
`define IFC_IFC10_P_Y1_UPPER_INDEX  (0)
`define IFC_IFC10_P_Y1_LOWER_INDEX  (0)
`define IFC_IFC10_P_Y1_WIDTH  (0-0+1)
`define IFC_IFC10_P_Y1_RANGE `IFC_IFC10_P_Y1_UPPER_INDEX:`IFC_IFC10_P_Y1_LOWER_INDEX
`define IFC_IFC10_P_Y2_UPPER_INDEX  (5-1)
`define IFC_IFC10_P_Y2_LOWER_INDEX  (0)
`define IFC_IFC10_P_Y2_WIDTH  (5)
`define IFC_IFC10_P_Y2_RANGE `IFC_IFC10_P_Y2_UPPER_INDEX:`IFC_IFC10_P_Y2_LOWER_INDEX
`define IFC_IFC20_P_Y_UPPER_INDEX  (5-1)
`define IFC_IFC20_P_Y_LOWER_INDEX  (0)
`define IFC_IFC20_P_Y_WIDTH  (5)
`define IFC_IFC20_P_Y_RANGE `IFC_IFC20_P_Y_UPPER_INDEX:`IFC_IFC20_P_Y_LOWER_INDEX
`define IFC_IFC20_P_X_UPPER_INDEX  (7-1)
`define IFC_IFC20_P_X_LOWER_INDEX  (0)
`define IFC_IFC20_P_X_WIDTH  (7)
`define IFC_IFC20_P_X_RANGE `IFC_IFC20_P_X_UPPER_INDEX:`IFC_IFC20_P_X_LOWER_INDEX

`endif
