`ifndef INC_GUARD_u_logic
`define INC_GUARD_u_logic

`define IFC_IFC_OP0_P_OP1_UPPER_INDEX  (15)
`define IFC_IFC_OP0_P_OP1_LOWER_INDEX  (0)
`define IFC_IFC_OP0_P_OP1_WIDTH  (15-0+1)
`define IFC_IFC_OP0_P_OP1_RANGE `IFC_IFC_OP0_P_OP1_UPPER_INDEX:`IFC_IFC_OP0_P_OP1_LOWER_INDEX
`define IFC_IFC_OP0_P_OP2_UPPER_INDEX  (15)
`define IFC_IFC_OP0_P_OP2_LOWER_INDEX  (0)
`define IFC_IFC_OP0_P_OP2_WIDTH  (15-0+1)
`define IFC_IFC_OP0_P_OP2_RANGE `IFC_IFC_OP0_P_OP2_UPPER_INDEX:`IFC_IFC_OP0_P_OP2_LOWER_INDEX
`define IFC_IFC_SEL0_P_SEL_UPPER_INDEX  (3)
`define IFC_IFC_SEL0_P_SEL_LOWER_INDEX  (0)
`define IFC_IFC_SEL0_P_SEL_WIDTH  (3-0+1)
`define IFC_IFC_SEL0_P_SEL_RANGE `IFC_IFC_SEL0_P_SEL_UPPER_INDEX:`IFC_IFC_SEL0_P_SEL_LOWER_INDEX
`define IFC_IFC_OUT0_P_O_UPPER_INDEX  (15)
`define IFC_IFC_OUT0_P_O_LOWER_INDEX  (0)
`define IFC_IFC_OUT0_P_O_WIDTH  (15-0+1)
`define IFC_IFC_OUT0_P_O_RANGE `IFC_IFC_OUT0_P_O_UPPER_INDEX:`IFC_IFC_OUT0_P_O_LOWER_INDEX

`endif
