`ifndef INC_GUARD_u_sh
`define INC_GUARD_u_sh

`define IFC_IFC_DIN_P_O_UPPER_INDEX  (15)
`define IFC_IFC_DIN_P_O_LOWER_INDEX  (0)
`define IFC_IFC_DIN_P_O_WIDTH  (15-0+1)
`define IFC_IFC_DIN_P_O_RANGE `IFC_IFC_DIN_P_O_UPPER_INDEX:`IFC_IFC_DIN_P_O_LOWER_INDEX
`define IFC_IFC_DOUT_P_O_UPPER_INDEX  (15)
`define IFC_IFC_DOUT_P_O_LOWER_INDEX  (0)
`define IFC_IFC_DOUT_P_O_WIDTH  (15-0+1)
`define IFC_IFC_DOUT_P_O_RANGE `IFC_IFC_DOUT_P_O_UPPER_INDEX:`IFC_IFC_DOUT_P_O_LOWER_INDEX
`define P_P_SHAM_UPPER_INDEX  (15)
`define P_P_SHAM_LOWER_INDEX  (0)
`define P_P_SHAM_WIDTH  (15-0+1)
`define P_P_SHAM_RANGE `P_P_SHAM_UPPER_INDEX:`P_P_SHAM_LOWER_INDEX

`endif
