`ifndef INC_GUARD_dram
`define INC_GUARD_dram

`define P_RESET_UPPER_INDEX  (0)
`define P_RESET_LOWER_INDEX  (0)
`define P_RESET_WIDTH  (0-0+1)
`define P_RESET_RANGE `P_RESET_UPPER_INDEX:`P_RESET_LOWER_INDEX
`define P_CLEAR_UPPER_INDEX  (0)
`define P_CLEAR_LOWER_INDEX  (0)
`define P_CLEAR_WIDTH  (0-0+1)
`define P_CLEAR_RANGE `P_CLEAR_UPPER_INDEX:`P_CLEAR_LOWER_INDEX
`define P_CLOCK_UPPER_INDEX  (0)
`define P_CLOCK_LOWER_INDEX  (0)
`define P_CLOCK_WIDTH  (0-0+1)
`define P_CLOCK_RANGE `P_CLOCK_UPPER_INDEX:`P_CLOCK_LOWER_INDEX
`define P_WR_ADDR_UPPER_INDEX  (log2128-1)
`define P_WR_ADDR_LOWER_INDEX  (0)
`define P_WR_ADDR_WIDTH  (log2128)
`define P_WR_ADDR_RANGE `P_WR_ADDR_UPPER_INDEX:`P_WR_ADDR_LOWER_INDEX
`define P_RD_ADDR0_UPPER_INDEX  (log2128-1)
`define P_RD_ADDR0_LOWER_INDEX  (0)
`define P_RD_ADDR0_WIDTH  (log2128)
`define P_RD_ADDR0_RANGE `P_RD_ADDR0_UPPER_INDEX:`P_RD_ADDR0_LOWER_INDEX
`define P_RD_ADDR1_UPPER_INDEX  (log2128-1)
`define P_RD_ADDR1_LOWER_INDEX  (0)
`define P_RD_ADDR1_WIDTH  (log2128)
`define P_RD_ADDR1_RANGE `P_RD_ADDR1_UPPER_INDEX:`P_RD_ADDR1_LOWER_INDEX
`define P_DATA_IN_UPPER_INDEX  (32-1)
`define P_DATA_IN_LOWER_INDEX  (0)
`define P_DATA_IN_WIDTH  (32)
`define P_DATA_IN_RANGE `P_DATA_IN_UPPER_INDEX:`P_DATA_IN_LOWER_INDEX
`define P_DATA_OUT0_UPPER_INDEX  (32-1)
`define P_DATA_OUT0_LOWER_INDEX  (0)
`define P_DATA_OUT0_WIDTH  (32)
`define P_DATA_OUT0_RANGE `P_DATA_OUT0_UPPER_INDEX:`P_DATA_OUT0_LOWER_INDEX
`define P_DATA_OUT1_UPPER_INDEX  (32-1)
`define P_DATA_OUT1_LOWER_INDEX  (0)
`define P_DATA_OUT1_WIDTH  (32)
`define P_DATA_OUT1_RANGE `P_DATA_OUT1_UPPER_INDEX:`P_DATA_OUT1_LOWER_INDEX
`define P_WR_EN_UPPER_INDEX  (0)
`define P_WR_EN_LOWER_INDEX  (0)
`define P_WR_EN_WIDTH  (0-0+1)
`define P_WR_EN_RANGE `P_WR_EN_UPPER_INDEX:`P_WR_EN_LOWER_INDEX
`define P_RD_EN0_UPPER_INDEX  (0)
`define P_RD_EN0_LOWER_INDEX  (0)
`define P_RD_EN0_WIDTH  (0-0+1)
`define P_RD_EN0_RANGE `P_RD_EN0_UPPER_INDEX:`P_RD_EN0_LOWER_INDEX
`define P_RD_EN1_UPPER_INDEX  (0)
`define P_RD_EN1_LOWER_INDEX  (0)
`define P_RD_EN1_WIDTH  (0-0+1)
`define P_RD_EN1_RANGE `P_RD_EN1_UPPER_INDEX:`P_RD_EN1_LOWER_INDEX
`define P_VALID_UPPER_INDEX  (0)
`define P_VALID_LOWER_INDEX  (0)
`define P_VALID_WIDTH  (0-0+1)
`define P_VALID_RANGE `P_VALID_UPPER_INDEX:`P_VALID_LOWER_INDEX

`endif
