`ifndef INC_GUARD_b
`define INC_GUARD_b

`define P_P_B_UPPER_INDEX  (b_x-1)
`define P_P_B_LOWER_INDEX  (0)
`define P_P_B_WIDTH  (b_x)
`define P_P_B_RANGE `P_P_B_UPPER_INDEX:`P_P_B_LOWER_INDEX
`define P_PB_UPPER_INDEX  (b_z-1)
`define P_PB_LOWER_INDEX  (0)
`define P_PB_WIDTH  (b_z)
`define P_PB_RANGE `P_PB_UPPER_INDEX:`P_PB_LOWER_INDEX
`define IFC_IFCA0_P_P_IFCA_UPPER_INDEX  (ifa_x-1)
`define IFC_IFCA0_P_P_IFCA_LOWER_INDEX  (0)
`define IFC_IFCA0_P_P_IFCA_WIDTH  (ifa_x)
`define IFC_IFCA0_P_P_IFCA_RANGE `IFC_IFCA0_P_P_IFCA_UPPER_INDEX:`IFC_IFCA0_P_P_IFCA_LOWER_INDEX
`define IFC_IFCA0_P_P_IFA_UPPER_INDEX  (ifa_y-1)
`define IFC_IFCA0_P_P_IFA_LOWER_INDEX  (0)
`define IFC_IFCA0_P_P_IFA_WIDTH  (ifa_y)
`define IFC_IFCA0_P_P_IFA_RANGE `IFC_IFCA0_P_P_IFA_UPPER_INDEX:`IFC_IFCA0_P_P_IFA_LOWER_INDEX
`define IFC_IFCA0_P_P_IFA1_UPPER_INDEX  (51-1)
`define IFC_IFCA0_P_P_IFA1_LOWER_INDEX  (0)
`define IFC_IFCA0_P_P_IFA1_WIDTH  (51)
`define IFC_IFCA0_P_P_IFA1_RANGE `IFC_IFCA0_P_P_IFA1_UPPER_INDEX:`IFC_IFCA0_P_P_IFA1_LOWER_INDEX
`define IFC_ARIFC_SGA0_P_ARS_P_IFCA_UPPER_INDEX  (20-1)
`define IFC_ARIFC_SGA0_P_ARS_P_IFCA_LOWER_INDEX  (0)
`define IFC_ARIFC_SGA0_P_ARS_P_IFCA_WIDTH  (20)
`define IFC_ARIFC_SGA0_P_ARS_P_IFCA_RANGE `IFC_ARIFC_SGA0_P_ARS_P_IFCA_UPPER_INDEX:`IFC_ARIFC_SGA0_P_ARS_P_IFCA_LOWER_INDEX
`define IFC_ARIFC_SGA0_P_ARS_P_IFA_UPPER_INDEX  (27-1)
`define IFC_ARIFC_SGA0_P_ARS_P_IFA_LOWER_INDEX  (0)
`define IFC_ARIFC_SGA0_P_ARS_P_IFA_WIDTH  (27)
`define IFC_ARIFC_SGA0_P_ARS_P_IFA_RANGE `IFC_ARIFC_SGA0_P_ARS_P_IFA_UPPER_INDEX:`IFC_ARIFC_SGA0_P_ARS_P_IFA_LOWER_INDEX
`define IFC_ARIFC_SGA0_P_ARS_P_IFA1_UPPER_INDEX  (51-1)
`define IFC_ARIFC_SGA0_P_ARS_P_IFA1_LOWER_INDEX  (0)
`define IFC_ARIFC_SGA0_P_ARS_P_IFA1_WIDTH  (51)
`define IFC_ARIFC_SGA0_P_ARS_P_IFA1_RANGE `IFC_ARIFC_SGA0_P_ARS_P_IFA1_UPPER_INDEX:`IFC_ARIFC_SGA0_P_ARS_P_IFA1_LOWER_INDEX
`define SG_SGA0_S_P_IFCA_UPPER_INDEX  (sga_z-1)
`define SG_SGA0_S_P_IFCA_LOWER_INDEX  (0)
`define SG_SGA0_S_P_IFCA_WIDTH  (sga_z)
`define SG_SGA0_S_P_IFCA_RANGE `SG_SGA0_S_P_IFCA_UPPER_INDEX:`SG_SGA0_S_P_IFCA_LOWER_INDEX
`define SG_SGA0_S_P_IFA_UPPER_INDEX  (sga_x-1)
`define SG_SGA0_S_P_IFA_LOWER_INDEX  (0)
`define SG_SGA0_S_P_IFA_WIDTH  (sga_x)
`define SG_SGA0_S_P_IFA_RANGE `SG_SGA0_S_P_IFA_UPPER_INDEX:`SG_SGA0_S_P_IFA_LOWER_INDEX
`define SG_SGA0_S_P_IFA1_UPPER_INDEX  (sga_y-1)
`define SG_SGA0_S_P_IFA1_LOWER_INDEX  (0)
`define SG_SGA0_S_P_IFA1_WIDTH  (sga_y)
`define SG_SGA0_S_P_IFA1_RANGE `SG_SGA0_S_P_IFA1_UPPER_INDEX:`SG_SGA0_S_P_IFA1_LOWER_INDEX

`endif
