`ifndef INC_GUARD_top
`define INC_GUARD_top

`define IFC_IFC0_P_P_IFC1_UPPER_INDEX  (8-1)
`define IFC_IFC0_P_P_IFC1_LOWER_INDEX  (0)
`define IFC_IFC0_P_P_IFC1_WIDTH  (8)
`define IFC_IFC0_P_P_IFC1_RANGE `IFC_IFC0_P_P_IFC1_UPPER_INDEX:`IFC_IFC0_P_P_IFC1_LOWER_INDEX
`define IFC_IFC0_P_P_IFC2_UPPER_INDEX  (8-1)
`define IFC_IFC0_P_P_IFC2_LOWER_INDEX  (0)
`define IFC_IFC0_P_P_IFC2_WIDTH  (8)
`define IFC_IFC0_P_P_IFC2_RANGE `IFC_IFC0_P_P_IFC2_UPPER_INDEX:`IFC_IFC0_P_P_IFC2_LOWER_INDEX
`define SG_SG0_S_S_SG1_UPPER_INDEX  (8-1)
`define SG_SG0_S_S_SG1_LOWER_INDEX  (0)
`define SG_SG0_S_S_SG1_WIDTH  (8)
`define SG_SG0_S_S_SG1_RANGE `SG_SG0_S_S_SG1_UPPER_INDEX:`SG_SG0_S_S_SG1_LOWER_INDEX
`define SG_SG0_S_S_SG2_UPPER_INDEX  (8-1)
`define SG_SG0_S_S_SG2_LOWER_INDEX  (0)
`define SG_SG0_S_S_SG2_WIDTH  (8)
`define SG_SG0_S_S_SG2_RANGE `SG_SG0_S_S_SG2_UPPER_INDEX:`SG_SG0_S_S_SG2_LOWER_INDEX

`endif
