`ifndef INC_GUARD_ue
`define INC_GUARD_ue

`define P_PEIN_UPPER_INDEX  (16-1)
`define P_PEIN_LOWER_INDEX  (0)
`define P_PEIN_WIDTH  (16)
`define P_PEIN_RANGE `P_PEIN_UPPER_INDEX:`P_PEIN_LOWER_INDEX
`define P_PEOUT_UPPER_INDEX  (8-1)
`define P_PEOUT_LOWER_INDEX  (0)
`define P_PEOUT_WIDTH  (8)
`define P_PEOUT_RANGE `P_PEOUT_UPPER_INDEX:`P_PEOUT_LOWER_INDEX
`define IFC_IFCIN_P_HW_UPPER_INDEX  (16-1)
`define IFC_IFCIN_P_HW_LOWER_INDEX  (0)
`define IFC_IFCIN_P_HW_WIDTH  (16)
`define IFC_IFCIN_P_HW_RANGE `IFC_IFCIN_P_HW_UPPER_INDEX:`IFC_IFCIN_P_HW_LOWER_INDEX
`define IFC_IFCIN_P_W_UPPER_INDEX  (8-1)
`define IFC_IFCIN_P_W_LOWER_INDEX  (0)
`define IFC_IFCIN_P_W_WIDTH  (8)
`define IFC_IFCIN_P_W_RANGE `IFC_IFCIN_P_W_UPPER_INDEX:`IFC_IFCIN_P_W_LOWER_INDEX
`define IFC_IFCRC_P_RESET_UPPER_INDEX  (0)
`define IFC_IFCRC_P_RESET_LOWER_INDEX  (0)
`define IFC_IFCRC_P_RESET_WIDTH  (0-0+1)
`define IFC_IFCRC_P_RESET_RANGE `IFC_IFCRC_P_RESET_UPPER_INDEX:`IFC_IFCRC_P_RESET_LOWER_INDEX
`define IFC_IFCRC_P_CLOCK_UPPER_INDEX  (0)
`define IFC_IFCRC_P_CLOCK_LOWER_INDEX  (0)
`define IFC_IFCRC_P_CLOCK_WIDTH  (0-0+1)
`define IFC_IFCRC_P_CLOCK_RANGE `IFC_IFCRC_P_CLOCK_UPPER_INDEX:`IFC_IFCRC_P_CLOCK_LOWER_INDEX

`endif
