#!/usr/bin/perl

#oanab
#assign with part select

use strict;

print "Generated tests path : test/csl_test_gen/assign_part_sel_invalid2/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 350; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "assign_part_sel".$i."_illegal.csl";
   	&createCslFile($test_name, $i, %dir);
}

sub createCslFile {
    my ($test_name, $i, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(20)) + 2;
    my $val2 = int(rand(100)) + 3;
    my $val3 = int(rand(100)) + 4;
    my $l = int(rand(3))+1;
    my $m = $k + int(rand(10)) + 1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/assign_part_sel_valid");
        open(FH,">$path/assign_part_sel_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/assign_part_sel_invalid2"); 
        open(FH,">$path/assign_part_sel_invalid2/$test_name");
    }
    print FH "//Generated by oanab\n";
    print FH "//Test cases from: assign_test_matrix.odg, part_select_matrix.odg\n\n"; 

#bitranges and fields
    print FH "csl_bitrange br1($val1);\n";
    print FH "csl_field f2($val2);\n";
    print FH "csl_bitrange br3($val3);\n";
    print FH "csl_bitrange br4(".($val2+$val3).");\n";
    print FH "csl_bitrange br5(".($val1+$val2+$val3).");\n";

#ifck
    if($i <= 150) {
	print FH "csl_interface ifc$k {\n";
	print FH "  csl_port p_a$i(input,br3);\n";
	print FH "  csl_port p_b$i(output,f2);\n";
	print FH "  csl_port p_c$i(input,br1);\n";
	print FH "  csl_port p_d$i(output,br4);\n";
	print FH "  ifc$k () {}\n";
	print FH "};\n\n";
    }

#ifcm
    if($i > 50 && $i <= 100) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_x$i(input,br3);\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  ifc$k ifc$k\_$one;\n";
	print FH "  ifc$k ifc$k\_$two;\n";
	print FH "  ifc$m () {}\n";
	print FH "};\n\n";
    }

#sgk
    if($i > 50 && $i <= 150 || $i > 200 && $i <= 350) {
	print FH "csl_signal_group sg$k {\n";
	print FH "  csl_signal s_a$i(f2);\n";
	print FH "  csl_signal s_b$i(br3);\n";
	print FH "  csl_signal s_c$i($val2);\n";
	print FH "  csl_signal s_d$i(br4);\n";
	print FH "  sg$k () {}\n";
	print FH "};\n\n";
    }

#sgm
    if($i > 100 && $i <= 150 || $i > 250 && $i <= 300) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  csl_signal s_x$i(f2);\n";
	print FH "  csl_signal s_y$i(br3);\n";
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
	print FH "  sg$m () {}\n";
	print FH "};\n\n";
    }

#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  csl_signal s_x$i(f2);\n";
	print FH "  csl_port p_x$i(output,".(1+$val2).");\n";
	print FH "  csl_port p_y$i(inout,br4);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  csl_port p_a$i(output,br4);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal s_a$i(br1);\n";
	print FH "  csl_port p_a$i(output,".($val1+$val2).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_x$i(inout,".($val3+21).");\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_port p_a$i(output,br5);\n";
	print FH "  sg$m sg$m\_$one;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  csl_port p_x$i(input,br4);\n";
    }
    print FH "  a$k () {\n";
#Invalid assign between sig.ps and p.ps - p
    if($i <= 50) {
	print FH "    s_x$i\[2\] = p_x$i\[2\];   // Invalid assign between sig.ps and p.ps - p\n";
    }
#Invalid assign between sg.sig.ps and p.ps - p
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$k\_$zero.s_d$i\[".($val2+$val3)."\-\:".($val3)."\] = p_a$i\[".($val2+$val3)."\:".($val2)."\];    // Invalid assign between sg.sig.ps and p.ps - p\n";
    }
#Invalid assign between sg.sg.sig.ps and ifc.p.ps - p
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$m\_$zero.sg$k\_$one.s_d$i\[".($val2+$val3)."\:".($val2-1)."\] = ifc$k\_$zero.p_d$i\[".($val2+$val3)."\:".($val2)."\];   // Invalid assign between sg.sg.sig.ps and ifc.p.ps - p\n";
    }
#Invalid assign between sig and p.ps - p
    elsif($i > 150 && $i <= 200) {
	print FH "    s_a$i = p_a$i\[".($val1+$val2)."\-\:".($val1)."\];    // Invalid assign between sig and p.ps - p\n";
    }
#Invalid assign between sg.sg.sig and p.ps - p
    elsif($i > 250 && $i <= 300) {
	print FH "    sg$m\_$one.sg$k\_$zero.s_b$i = p_a$i\[".($val1+$val2+$val3)."\:".($val1+$val2-1)."\];   // Invalid assign between sg.sg.sig and p.ps - p\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit b
    print FH "csl_unit b$k {\n";
    print FH "  csl_signal s_a$i(br4);\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i > 50 && $i <= 100) {
	print FH "  csl_port p_b$i(inout,br3);\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_port p_n$i(inout,f2);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_port p_c$i(inout,".($val1+$val3+2).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  csl_port p_x$i(output,".($val2+$val3-3).");\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_port p_z$i(inout,br4);\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  csl_signal s_x$i($val2);\n";
    }
    print FH "  b$k () {\n";
#Invalid assign between sig.ps and p.ps - c
    if($i <= 50) {
	print FH "    s_a$i\[".($val2+$val3)."\:".($val2)."\] = a$k\_$zero.p_y$i\[".($val2+$val3)."\:".($val2-1)."\];    // Invalid assign between sig.ps and p.ps - c\n";
    }
#Invalid assign between sg.sig.ps and ifc.ifc.p.ps - p
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$k\_$one.s_c$i\[1\] = ifc$m\_$zero.ifc$k\_$zero.p_b$i\[2\];   // Invalid assign between sg.sig.ps and ifc.ifc.p.ps - p\n";
    }
#Invalid assign between sg.sig and p.ps - p
    elsif($i > 200 && $i <= 250) {
	print FH "    sg$k\_$zero.s_b$i = p_x$i\[".($val2+$val3-3)."\:".($val2-3)."\];   // Invalid assign between sg.sig and p.ps - p\n";
    }
#Invalid assign between a signal and a p.ps - c
    elsif($i > 300 && $i <= 350) {
	print FH "    s_x$i = a0.p_x$i\[".($val2+$val3)."\-\:".($val2)."\];   // Invalid assign between a signal and a p.ps - c\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_signal s_x$i($val1);\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$k sg$k\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  csl_port p_m$i(output,".($val1+1).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal s_b$i(br3);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$k sg$k\_$zero;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  b$k b$k\_$one;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  sg$k sg$k\_$zero;\n";
    }
    print FH "  c$k () {\n";
#Invalid assign between sig.ps and ifc.p.ps - p
    if($i <= 50) {
	print FH "  s_x$i\[".$val1."\:".($val1-1)."\] = ifc$k\_$zero.p_d$i\[1\];   // Invalid assign between sig.ps and ifc.p.ps - p\n";
    }
#Invalid assign between sg.sig.ps and p.ps - c
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$k\_$one.s_c$i\[".($val2-2)."\] = b$k\_$zero.p_b$i\[3\];   // Invalid assign between sg.sig.ps and p.ps - c\n";
    }
#Invalid assign between sg.sg.sig.ps and p.ps - p, sg.sg.sig.ps and p.ps - c
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$m\_$zero.sg$k\_$one.s_d$i\[".($val2+$val3)."\:".($val2-1)."\] = p_m$i\[".$val1."\:".(0)."\];   // Invalid assign between sg.sg.sig.ps and p.ps - p\n";
	print FH "    sg$m\_$zero.sg$k\_$one.s_d$i\[".($val2+$val3)."\:".($val2-1)."\] = b$k\_$zero.p_n$i\[2\];    // Invalid assign between sg.sg.sig.ps and p.ps - c\n";
    }
#Invalid assign between sig and p.ps - c
    elsif($i > 150 && $i <= 200) {
	print FH "    s_b$i = b$k\_$zero.p_c$i\[".($val3+$val1)."\:".($val1-1)."\];     // Invalid assign between sig and p.ps - c\n";
    }
#Invalid assign between sg.sig and p.ps - c
    elsif($i > 200 && $i <= 250) {
	print FH "    sg$k\_$zero.s_b$i = b$k\_$zero.a$k\_$zero.p_x$i\[".($val3+21)."\-\:".($val3)."\];    // Invalid assign between sg.sig and p.ps - c\n";
    }
#Invalid assign between sg.sg.sig and p.ps - c
    elsif($i > 250 && $i <= 300) {
	print FH "    sg$m\_$zero.sg$k\_$one.s_a$i = b$k\_$zero.p_z$i\[".($val2+$val3-1)."\:".$val3."\];   // Invalid assign between sg.sg.sig and p.ps - c\n";
	print FH "    sg$m\_$zero.sg$k\_$one.s_b$i = b$k\_$one.p_z$i\[".($val2+$val3-1)."\:".$val2."\];   // Invalid assign between sg.sg.sig and p.ps - c\n";
    }
#Invalid assign between sg and p.ps - c
    elsif($i > 300 && $i <= 350) {
print FH "    sg$k\_$zero = b0.a0.p_x$i\[".($val2+$val3)."\:".$val3."\];   // Invalid assign between sg and p.ps - c\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
