#!/usr/bin/perl

#oanab

use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "assign_ps_op_cc".$i."_illegal.csl";
   	&createCslFile($test_name, $i, %dir);
}

sub createCslFile {
    my ($test_name, $i, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(20)) + 2;
    my $val2 = int(rand(100)) + 3;
    my $val3 = int(rand(100)) + 4;
    my $l = int(rand(3))+1;
    my $m = $k + int(rand(10)) + 1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/assign_part_sel_valid1");
        open(FH,">$path/assign_part_sel_valid1/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/assign_ps_op_cc_invalid"); 
        open(FH,">$path/assign_ps_op_cc_invalid/$test_name");
    }
    print FH "//Generated by oanab\n\n";
    print FH "//Test cases from: assign_test_matrix.odg, part_select_matrix.odg\n"; 
    print FH "csl_bitrange br1($val1);\n";
    print FH "csl_bitrange br2($val2);\n";
    print FH "csl_bitrange br3($val3);\n";
    print FH "csl_bitrange br4(".($val2+$val3).");\n\n";


 
#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  csl_port p_x$i(output,br1);\n";
	print FH "  csl_signal s_a$i(br3);\n";
	print FH "  csl_signal s_b$i(".($val2+2*$val1).");\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_port p_a$i($dir{$l},br1);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_port p_a$i(input,".($val1+3*$val2).");\n";
	print FH "  csl_port p_b$i(input,".(2*$val2).");\n";
	print FH "  csl_signal s_a$i(".($val2+$val1+$val3).");\n";
	print FH "  csl_signal s_b$i(".(2*$val2+2*$val1).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_port p_x$i(input,br2);\n";
	print FH "  csl_port p_y$i(output,".($val1+$val2).");\n";
	print FH "  csl_port p_a$i(input,".(2*$val2+$val1).");\n";
	print FH "  csl_port p_b$i(input,".($val2+2*$val1).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_a$i(inout,br4);\n";
    }
    print FH "  a$k () {\n";
    if($i <= 50) {
	print FH "    s_a$i\[".($val3)."\:".($val3)."\] | s_b$i\[".($val2+2*$val1)."\:".($val2+$val1+1)."\] = p_x$i\[".($val1)."\:".(2)."\];  // assign between op expr and p.ps\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    p_a$i\[".($val1+3*$val2)."\:".($val1+2*$val2+1)."\] | p_b$i\[".($val2)."\:".(1)."\] = s_a$i\[".($val2+$val1+$val3)."\:".($val1+$val3+1)."\] & s_b$i\[".($val1+$val2)."\:".($val1+1)."\];  // assign between op expr and op expr\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    {p_a$i\[".(2*$val2+$val1)."\:".($val2+$val1+1)."\],p_b$i\[".($val2+$val1)."\:".($val2+1)."\]} = p_y$i;  // assign between concat expr and port\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_port p_x$i($dir{$l},br4);\n";
	print FH "  csl_port p_a$i(input,".($val1+3*$val2).");\n";
	print FH "  csl_port p_b$i(input,".(2*$val3).");\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_a$i(".($val2+$val1+$val3).");\n";
	print FH "  csl_signal s_b$i(".($val2+2*$val1).");\n";
	print FH "  csl_port p_x$i($dir{$l},br4);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_signal s_a$i(br4);\n";
	print FH "  csl_signal s_b$i(".($val3+2*$val2).");\n";
	print FH "  csl_signal s_x$i(".(2*$val3+3*$val2).");\n";
	print FH "  csl_signal s_y$i(".(2*$val2+$val1).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal s_a$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_b$i(".($val2+2*$val1).");\n";
	print FH "  csl_port p_x$i(inout,br1);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_m$i(output,".($val1+$val2).");\n";
	print FH "  csl_port p_a$i(input,".(2*$val2+3*$val1).");\n";
	print FH "  csl_port p_b$i(input,".($val3+2*$val1).");\n";
    }
    print FH "  b$k () {\n";
    if($i <= 50) {
	print FH "    p_a$i\[".($val1+2*$val2)."\:".($val1+2*$val2-2)."\] & p_b$i\[".(2)."\] = p_x$i\[".(4)."\];  // assign between op expr and p.ps\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    s_a$i\[".($val2+$val1+$val3)."\:".($val3+$val2+1)."\] | s_b$i\[".($val2+$val1)."\:".($val2+1)."\] = a$k\_$zero.p_a$i;  // assign between op expr and port\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    s_x$i\[".(2*$val3+3*$val2)."\:".(2*$val3+2*$val2+1)."\] & s_y$i\[".($val2+$val1)."\:".($val1+1)."\] = {s_a$i\[".(3)."\],s_b$i\[".($val3+2*$val2)."\:".($val3+$val2+2)."\]};  // assign between op expr and concat expr\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    {s_a$i\[".(3)."\],s_b$i\[".($val2+2*$val1)."\:".(2*$val1+2)."\]} = a$k\_$zero.p_x$i;  // assign between concat expr and port\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "    {p_a$i\[".(2*$val2+$val1)."\:".(2*$val2+2)."\],p_b$i\[".(2)."\]} = p_m$i\[".($val1+$val2)."\:".($val2+1)."\];  // assign between concat expr and p.ps\n";
	print FH "    {p_a$i\[".($val2+3*$val1)."\:".(3*$val1+2)."\],p_b$i\[".(0)."\]} = a$k\_$zero.p_a$i\[".($val2+$val3)."\:".($val2+1)."\];  // assign between concat expr and p.ps\n";
    }
    print FH "  }\n";
    print FH "};\n\n";
    
    
#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_signal s_x$i(".($val2+2*$val3).");\n";
	print FH "  csl_signal s_y$i(br4);\n";
	print FH "  csl_port p_a$i($dir{$l},br4);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_x$i(".(2*$val3+3*$val1).");\n";
	print FH "  csl_signal s_y$i(".(2*$val2+$val1).");\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_signal s_a$i(".($val3+2*$val1).");\n";
	print FH "  csl_signal s_b$i(".($val2+$val1).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_port p_a$i(input,".($val1+3*$val2).");\n";
	print FH "  csl_port p_b$i(input,".(2*$val3).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_x$i(".(2*$val3+3*$val1).");\n";
	print FH "  csl_signal s_y$i(".(2*$val2+$val1).");\n";
    }
    print FH "  c$k () {\n";
    if($i <= 50) {
	print FH "    s_x$i\[".($val2+2*$val3)."\:".($val3+1)."\] & s_y$i\[".($val2+$val3)."\:".(1)."\] = p_a$i;  // assign between op expr and port\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    s_x$i\[".(2*$val3+3*$val1)."\:".(2*$val3+3*$val1-$val2+1)."\] & s_y$i \[".(2*$val2+$val1)."\:".($val2+$val1+1)."\] = b$k\_$zero.p_x$i\[".($val2+$val3)."\:".($val3+1)."\];  // assign between op expr and p.ps\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    ~s_x$i\[".($val3+2*$val1)."\:".($val3+1)."\] = {2{s_y$i\[".($val2+$val1)."\:".($val2+1)."\]}};  // assign between op expr and repl expr\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    {p_a$i\[".($val1+2*$val2)."\:".(2*$val2+2)."\],p_b$i\[".(5)."\]} = b$k\_$zero.p_x$i;  // assign between concat expr and port\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "   {s_x$i\[".($val3+2*$val1)."\:".($val3+$val1+1)."\],s_y$i\[".(2*$val2+$val1)."\:".($val2+$val1+1)."\]} = b$k\_$zero.p_a$i\[".(2*$val2+3*$val1)."\:".($val2+2*$val1+1)."\];\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
