#!/usr/bin/perl

#oanab

use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_unit_mem".$i."_illegal.csl";
    if($j != $m && $j != $n && $m != $n) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+2;
    my $val2 = int(rand(100))+3;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_unit_mem_valid");
        open(FH,">$path/ar_conn_name_unit_mem_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_unit_mem_invalid1"); 
        open(FH,">$path/ar_conn_name_unit_mem_invalid1/$test_name");
    }
    print FH "//Generated by oanab\n\n";

    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#ifcj
    if($i > 100 && $i <= 150 || $i > 200 && $i <= 250) {
	print FH "csl_interface ifc$j {\n";
	print FH "  csl_port ps_m$i($dir{$l},br1);\n";
	if($l < 3) {
	    print FH "  csl_port ps_n$i($dir{$l+1},br3);\n";
	}
	else {
	    print FH "  csl_port ps_n$i($dir{$l-1},br3);\n";
	}
	print FH "  csl_port ps_o$i(inout,$val1);\n";
	print FH "  ifc$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }


#sgj
    if($i > 100 && $i <= 150 || $i > 200 && $i <= 250) {
	print FH "csl_signal_group sg$j {\n";
	print FH "  csl_signal s_a$i(".($val2+$val1).");\n";
	print FH "  csl_signal s_b$i(br1);\n";
	print FH "  csl_signal s_c$i(br3);\n";
	print FH "  sg$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }
    

#memory mem
    if($i <= 50 || $i > 150) {
	print FH "csl_memory mem$k {\n";
	print FH "  mem$k () {\n";
	print FH "    set_width($val2);\n";
	print FH "    set_depth(".($val2+$val1).");\n";
	print FH "  }\n";
	print FH "};\n\n";
    }
    

#unit a
    print FH "csl_unit a$k {\n";
    print FH "  csl_port p_a$i(inout,br3);\n";
    if($i <= 100) {
	print FH "  csl_signal s_x$i(br1);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  mem$k mem$k\_$zero;\n";
	print FH "  mem$k mem$k\_$one;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_port p_x$i($dir{$l},".($val2+$val3).");\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  csl_signal s_y$i($val3);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_port p_z$i($dir{$l},br2);\n";
	print FH "  csl_signal s_z$i($val1);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  mem$k mem$k\_$zero;\n";
    }
    print FH "  b$k () {\n";
 
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  mem$k mem$k\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  b$k b$k\_$one;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  mem$k mem$k\_$one;\n";
    }
    print FH "  c$k () {\n";
    if($i <= 50) {
	print FH "    b$k\_$zero.connect_by_name(b$k\_$zero.a$k\_$zero.s_x$i,pa_s$i);\n";
	print FH "    mem$k\_$zero.connect_by_name(b$k\_$zero.p_x$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.connect_by_name(b$k\_$zero.a$k\_$zero.s_x$i\[".$val1."\:".($val1-2)."\]);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    b$k\_$zero.a$k\_$zero.connect_by_name(b$k\_$zero.a$k\_$zero.ifc$j\_$zero.ps_n$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.a$k\_$zero.mem$k\_$zero.connect_by_name(b$k\_$zero.s_z$i\[".$val1."\:".($val1-1)."\]);\n";
	print FH "    b$k\_$zero.a$k\_$zero.mem$k\_$one.connect_by_name(b$k\_$zero.p_z$i\[".$val2."\:".($val2-3)."\]);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "    b$k\_$zero.mem$k\_$zero.connect_by_name(ifc$j\_$one.ps_o$i);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    print FH "  c$k c$k\_$zero;\n";
    if($i <= 50) {
	print FH "  mem$k mem$k\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_port p_y$i($dir{$l},$val2);\n";
    }
    print FH "  d$k () {\n";
    if($i <= 50) {
	print FH "    c$k\_$zero.b$k\_$zero.connect_by_name(c$k\_$zero.b$k\_$zero.p_x$i);\n";
	print FH "    mem$k\_$one.connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.s_x$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.connect_by_name(p_y$i\[".$val2."\:".($val2-3)."\],pa_y$i);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.b$k\_$one.connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$zero.s_a$i);\n";
	print FH "    c$k\_$zero.b$k\_$zero.s_y$i.connect_by_name(c$k\_$zero);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.mem$k\_$one.connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.sg$j\_$one.s_b$i);\n";
    }
    print FH "  }\n";
    print FH "};\n\n";









}
