#!/usr/bin/perl

#oanab
#connect_by_name() with sig's

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_sig_invalid1/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_sig".$i."_illegal.csl";
    if($j != $m && $j != $n && $m != $n) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+2;
    my $val2 = int(rand(100))+3;
    my $val3 = int(rand(100))+8;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_sig_valid");
        open(FH,">$path/ar_conn_name_sig_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_sig_invalid1"); 
        open(FH,">$path/ar_conn_name_sig_invalid1/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#sgj
    if($i > 100) {
	print FH "csl_signal_group sg$j {\n";
	print FH "  csl_signal s_a$i(".($val2+$val1).");\n";
	print FH "  csl_signal s_b$i(br1);\n";
	print FH "  csl_signal s_c$i(br3);\n";
	print FH "  sg$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgm
    if($i > 150 && $i <= 250) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  sg$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }


#unit a
    print FH "csl_unit a$k {\n";
    print FH "  csl_port p_a$i(inout,br3);\n";
    if($i <= 50) {
	print FH "  csl_signal s_d$i(br2);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_b$i(".($val2+$val3).");\n";
    }
    elsif($i > 100 && $i <= 200) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_y$i($val2);\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 100) {
	print FH "  csl_signal s_a$i(br3);\n";
	if($i > 50) {
	    print FH "  csl_signal s_d$i(br1);\n";
	}
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  csl_signal s_n$i(".($val2+$val3).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    print FH "  b$k () {\n";
#connect_by_name : Invalid connection : sig.ps---sg.sig (PC)
    if($i > 150 && $i <= 200) {
	print FH "    s_n$i\[".($val2+$val3)."\:".$val2."\].connect_by_name(a$k\_$zero.sg$j\_$zero.s_c$i);  // Invalid connection : sig.ps---sg.sig (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_signal s_b$i($val2);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  a$k a$k\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  csl_signal s_x$i($val1);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal s_m$i($val3);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_x$i(br2);\n";
	print FH "  a$k a$k\_$one;\n";
    }
    print FH "  c$k () {\n";
#connect_by_name : Invalid connection : sig---sig (PC)
    if($i <= 50) {
	print FH "    s_b$i.connect_by_name(b$k\_$zero.a$k\_$zero.s_d$i);  // Invalid connection : sig---sig (PC)\n";
    }
#connect_by_name : Invalid connection : sig---sig.ps (SS)
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.s_a$i.connect_by_name(a$k\_$one.s_b$i\[".($val2+$val3)."\:".$val2."\]);  // Invalid connection : sig---sig.ps (SS)\n";
    }
#connect_by_name : Invalid connection : sg.sig---sig (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    b$k\_$zero.a$k\_$zero.sg$j\_$zero.s_b$i.connect_by_name(s_x$i,pa_s$i);  // Invalid connection : sg.sig---sig (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    print FH "  c$k c$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_signal s_c$i($val3);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_c$i(".($val3+$val1).");\n";
	print FH "  b$k b$k\_$one;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$m sg$m\_$zero;\n";
    }
    print FH "  d$k () {\n";
#connect_by_name : Invalid connection : sig---sig (PC)
    if($i <= 50) {
	print FH "    s_c$i.connect_by_name(c$k\_$zero.b$k\_$zero.s_a$i,pa_s$i);  // Invalid connection : sig---sig (PC)\n";
    }
#connect_by_name : Invalid connection : sig.ps---sig (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    s_c$i\[".($val3+$val1)."\:".$val3."\].connect_by_name(b$k\_$one.s_d$i,pa_s$i);  // Invalid connection : sig.ps---sig (PC)\n";
    }
#connect_by_name : Invalid connection : sg.sig---sg.sig.ps (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.sg$j\_$one.s_b$i.connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.sg$j\_$zero.s_a$i\[".($val2+$val1)."\:".$val2."\]);  // Invalid connection : sg.sig---sg.sig.ps (PC)\n";
    }
#connect_by_name : Invalid connection : sig---sg.sg.sig (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    c$k\_$zero.s_m$i.connect_by_name(c$k\_$zero.b$k\_$zero.sg$m\_$zero.sg$j\_$zero.s_c$i);  // Invalid connection : sig---sg.sg.sig (PC)\n";
    }
#connect_by_name : Invalid connection : sig.ps---sig.ps (PC), Invalid connection : sg.sg.sig---sg.sig (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.s_x$i\[".($val2)."\-\:".(4)."\].connect_by_name(c$k\_$zero.a$k\_$one.s_y$i\[".$val2."\:".($val2-3)."\],pa_s$i);  // Invalid connection : sig.ps---sig.ps (PC)\n";
	print FH "    sg$m\_$zero.sg$j\_$one.s_a$i.connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$zero.s_a$i);  // Invalid connection : sg.sg.sig---sg.sig (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";









}
