#!/usr/bin/perl

#oanab
#connect_by_name() method with ifc.p and sg.s
# Test Matrix: /test_matrices/ar_conn_by_name_matr.ods, 9 test cases covered

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_ifcp_sgs_valid/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_ifcp_sgs".$i."_legal.csl";
    if($j != $m && $j != $n && $m != $n) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    elsif($j == $m) {
	&createCslFile($test_name, $i, $j+1, $m+2, $n, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = 4*int(rand(20));
    if($val1 == 0) {
	$val1 = 4;
    }
    my $val2 = int(rand(100))+3;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_ifcp_sgs_valid");
        open(FH,">$path/ar_conn_name_ifcp_sgs_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_ifcp_sgs_invalid"); 
        open(FH,">$path/ar_conn_name_ifcp_sgs_invalid/$test_name");
    }
    print FH "//Generated by oanab\n\n";
    print FH "//Test_Matrix: /test_matrices/ar_conn_by_name_matr.ods\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";


#ifcj
    print FH "csl_interface ifc$j {\n";
    print FH "  csl_port p_m$i(input,br1);\n";
    print FH "  csl_port p_n$i(output,br3);\n";
    print FH "  csl_port p_o$i(input,$val1);\n";
    print FH "  ifc$j () {\n";
    print FH "  }\n";
    print FH "};\n\n";


#ifcm
    if($i <= 50 || $i > 100 && $i <= 200) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_x$i(input,br2);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  ifc$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgj
    if($i > 50 && $i <= 100 || $i > 150 && $i <= 200) {
	print FH "csl_signal_group sg$j {\n";
	print FH "  csl_signal p_m$i($val1);\n";
	print FH "  csl_signal p_n$i(br3);\n";
	print FH "  csl_signal p_o$i(br1);\n";
	print FH "  sg$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgm
    if($i > 150 && $i <= 200) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  csl_signal p_x$i(br2);\n";
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  sg$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }


#unit a
    print FH "csl_unit a$k {\n";
    if($i > 50 && $i <= 100) {
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_port p_a$i(output,$val1);\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
	print FH "  csl_signal s_m$i($val1);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n"
    }
    print FH "  a$k () {\n";
    if($i > 50 && $i <= 100) {
	print FH "    ifc$j\_$zero = sg$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    p_a$i = s_m$i;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "    ifc$j\_$zero = sg$j\_$zero;\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    if($i <= 50) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_port p_n$i(inout,$val3);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$zero(ifc$j\_$one));\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  csl_port p_b$i(input,$val1);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$m ifc$m\_$one;\n";
	print FH "  a$k a$k\_$zero(.ifc$m\_$zero(ifc$m\_$one));\n";
	print FH "  a$k a$k\_$one(.ifc$m\_$zero.ifc$j\_$zero.p_n$i(ifc$m\_$one.ifc$j\_$zero.p_n$i),.ifc$m\_$zero.ifc$j\_$zero.p_o$i(ifc$m\_$one.ifc$j\_$zero.p_o$i),.ifc$m\_$zero.ifc$j\_$one.p_m$i(ifc$m\_$one.ifc$j\_$one.p_m$i),.ifc$m\_$zero.ifc$j\_$one.p_o$i(ifc$m\_$one.ifc$j\_$one.p_o$i),.ifc$m\_$zero.p_x$i(ifc$m\_$one.p_x$i));\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$zero(ifc$m\_$two.ifc$j\_$zero));\n";
	print FH "  ifc$m ifc$m\_$two;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    print FH "  b$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    if($i <= 50) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero.p_n$i(p_c$i),.ifc$j\_$zero.p_o$i(p_m$i));\n";
	print FH "  csl_port p_m$i(input,$val1);\n";
	print FH "  csl_port p_c$i(output,br3);\n";
	print FH "  ifc$m ifc$m\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_port p_c$i(input,".($val3+$val1).");\n";
	print FH "  csl_port p_a$i(input,$val3);\n";
	print FH "  b$k b$k\_$zero(.ifc$j\_$one.p_m$i(ifc$j\_$zero.p_m$i),.ifc$j\_$one.p_n$i(ifc$j\_$zero.p_n$i));  // f2a : ifc.p---ifc.p\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  b$k b$k\_$zero(.ifc$m\_$one(ifc$m\_$one));\n";
	print FH "  ifc$m ifc$m\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  b$k b$k\_$zero(.ifc$m\_$two.ifc$j\_$one(ifc$m\_$zero.ifc$j\_$one),.ifc$m\_$two.ifc$j\_$zero.p_n$i(ifc$m\_$zero.ifc$j\_$zero.p_n$i),.ifc$m\_$two.ifc$j\_$zero.p_o$i(ifc$m\_$zero.ifc$j\_$zero.p_o$i),.ifc$m\_$two.p_x$i(ifc$m\_$zero.p_x$i));  // f2a : ifc.ifc---ifc.ifc, ifc.ifc.p---ifc.ifc.p, ifc.p---ifc.p\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
	print FH "  sg$m sg$m\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero.p_m$i(ifc$j\_$one.p_m$i),.ifc$j\_$zero.p_n$i(ifc$j\_$one.p_n$i));\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  csl_signal s_x$i(".($val1/4).");\n";
	print FH "  csl_signal s_y$i(".($val1/4).");\n";
    }
    print FH "  c$k () {\n";
#connect_by_name : ifc.p---port (CP)
    if($i <= 50) {
	print FH "    b$k\_$zero.ifc$j\_$zero.p_m$i.connect_by_name(p_m$i,pa_m$i);  // ifc.p---port (CP)\n";
    }
#connect_by_name : ifc.p---p.ps (PC), sg.sig---ps (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.ifc$j\_$one.p_o$i.connect_by_name(p_c$i\[".($val3+$val1-1)."\-\:".($val1)."\]);  // ifc.p---p.ps (CP)\n";
	print FH "    b$k\_$zero.a$k\_$zero.sg$j\_$zero.p_n$i.connect_by_name(p_a$i\[".($val3-1)."\:0\],pa_a$i);  // sg.sig---p.ps (CP)\n";
    }
#connect_by_name : ifc.ifc.p---sig (SS)
    elsif($i > 100 && $i <= 150) {
	print FH "    b$k\_$zero.a$k\_$one.ifc$m\_$zero.ifc$j\_$zero.p_m$i.connect_by_name(b$k\_$zero.a$k\_$zero.s_m$i);  // ifc.ifc.p---sig (SS\n";
    }
#connect_by_name : sg.sig---ifc.ifc.p (CP)  print FH "//Test_Matrix: /test_matrices/ar_conn_by_name_matr.ods\n\n";
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.a$k\_$zero.sg$j\_$zero.p_n$i.connect_by_name(ifc$m\_$zero.ifc$j\_$zero.p_n$i);  // sg.sig---ifc.ifc.p (CP)\n";
	print FH "    ifc$m\_$zero = sg$m\_$zero;\n";
    }
#connect_by_name : ifc.p---repl expr (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    b$k\_$zero.ifc$j\_$zero.p_o$i.connect_by_name({2{s_x$i,s_y$i}});  // ifc.p.ps---repl expr (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    if($i <= 50) {
	print FH "  c$k c$k\_$zero(.ifc$m\_$one(ifc$m\_$zero),.p_m$i(s_m$i),.p_c$i(s_c$i\[".($val2+$val3-1)."\:".($val2)."\]));  // f2a : ifc---ifc, port--sig, port---s.ps\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
	print FH "  csl_signal s_m$i(br1);\n";
	print FH "  csl_signal s_c$i(".($val2+$val3).");\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  c$k c$k\_$zero(.ifc$j\_$zero(sg$j\_$one),.p_c$i(s_c$i));  // f2a : ifc---sg, port---sig\n";
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  csl_signal s_c$i(".($val1+$val3).");\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$m ifc$m\_$two;\n";
	print FH "  c$k c$k\_$zero(.ifc$m\_$one(ifc$m\_$two));  // f2a : ifc---ifc\n";
	print FH "  csl_signal s_n$i(".($val1+$val3).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  c$k c$k\_$zero(.ifc$m\_$zero(ifc$m\_$one));  // f2a : ifc---ifc\n";
	print FH "  ifc$m ifc$m\_$one;\n";
	print FH "  b$k b$k\_$one(.ifc$m\_$two.ifc$j\_$zero(ifc$m\_$one.ifc$j\_$zero),.ifc$m\_$two.ifc$j\_$one.p_m$i(ifc$m\_$one.ifc$j\_$one.p_m$i),.ifc$m\_$two.ifc$j\_$one.p_o$i(ifc$m\_$one.ifc$j\_$one.p_o$i),.ifc$m\_$two.p_x$i(ifc$m\_$one.p_x$i));  // f2a : ifc---ifc\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  c$k c$k\_$zero(.ifc$j\_$one.p_o$i(s_o$i),.ifc$j\_$one.p_m$i(s_o$i));  // f2a : ifc.p---spar\n";
	print FH "  csl_signal s_m$i($val3);\n";
	print FH "  csl_signal s_n$i(br3);\n";
	print FH "  csl_parameter par_o$i(".($val1).");\n";
	print FH "  csl_signal s_o$i(par_o$i);\n";
    }
    print FH "  d$k () {\n";
#connect_by_name : ifc.ifc.p---port (PC)
    if($i <= 50) {
	print FH "    ifc$m\_$zero.ifc$j\_$zero.p_n$i.connect_by_name(c$k\_$zero.b$k\_$zero.p_n$i);  // ifc.ifc.p---port (PC)\n";
    }
#connect_by_name : sg.sig---port (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$j\_$one.p_o$i.connect_by_name(c$k\_$zero.b$k\_$zero.p_b$i);  // sg.sig---port (PC)\n";
    }
#connect_by_name : ifc.ifc.p---sig.ps (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$one.ifc$m\_$zero.ifc$j\_$one.p_n$i.connect_by_name(s_n$i\[".($val1+$val3-1)."\:".($val1)."\],pa_m$i);  // ifc.ifc.p---sig.ps (CP)\n";
    }
#connect_by_name : ifc.ifc.p---ifc.ifc.p (PC), ifc.ifc.p---sg.sg.sig (SS), sg.sig---ifc.ifc.p (CP)
    elsif($i > 150 && $i <= 200) {
	print FH "    ifc$m\_$one.ifc$j\_$one.p_o$i.connect_by_name(c$k\_$zero.b$k\_$zero.ifc$m\_$two.ifc$j\_$zero.p_m$i,pa_m$i);  // ifc.ifc.p---ifc.ifc.p (PC)\n";
	print FH "    b$k\_$one.ifc$m\_$two.ifc$j\_$one.p_n$i.connect_by_name(c$k\_$zero.sg$m\_$zero.sg$j\_$one.p_n$i);  // ifc.ifc.p---sg.sg.sig (SS)\n";
	print FH "    b$k\_$one.a$k\_$zero.sg$j\_$zero.p_n$i.connect_by_name(ifc$m\_$one.ifc$j\_$zero.p_n$i);  // sg.sig---ifc.ifc.p (CP)\n";
    }
#connect_by_name : ifc.p---op expr (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.b$k\_$zero.ifc$j\_$zero.p_n$i.connect_by_name(s_m$i & s_n$i,pa_n$i);  // ifc.p---op expr (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";



}
