#!/usr/bin/perl

#oanab
#connect_by_name() with sg's

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_sg_invalid/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 250; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_sg".$i."_illegal.csl";
    if($j != $m && $j != $n && $m != $n) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+2;
    my $val2 = int(rand(100))+3;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_sg_valid");
        open(FH,">$path/ar_conn_name_sg_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_sg_invalid"); 
        open(FH,">$path/ar_conn_name_sg_invalid/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#ifcj
    if($i > 100 && $i <= 150) {
	print FH "csl_interface ifc$j {\n";
	print FH "  csl_port ps_m$i($dir{$l},br1);\n";
	if($l < 3) {
	    print FH "  csl_port ps_n$i($dir{$l+1},br3);\n";
	}
	else {
	    print FH "  csl_port ps_n$i($dir{$l-1},br3);\n";
	}
	print FH "  csl_port ps_o$i(inout,$val1);\n";
	print FH "  ifc$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }


#ifcm
    if($i > 100 && $i <= 150) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_x$i($dir{$l},br2);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  ifc$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgj
    print FH "csl_signal_group sg$j {\n";
    print FH "  csl_signal s_a$i(".($val2+$val1).");\n";
    print FH "  csl_signal s_b$i(br1);\n";
    print FH "  csl_signal s_c$i(br3);\n";
    print FH "  sg$j () {\n";
    print FH "  }\n";
    print FH "};\n\n";
    
#sgm
    if($i > 100 && $i <= 150) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  sg$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#fifo f
    if($i > 50 && $i <= 100) {
	print FH "csl_fifo f$k {\n";
	print FH "  f$k () {\n";
	print FH "    set_width($val1);\n";
	print FH "    set_depth(".($val2+$val1).");\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#register reg
    if($i > 150 && $i <= 200) {
	print FH "csl_register reg$k {\n";
	print FH "  reg$k () {\n";
	print FH "    set_width($val2);\n";
	print FH "    set_type(register);\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#register file rf
    if($i > 150 && $i <= 200) {
	print FH "csl_register_file rf$k {\n";
	print FH "  rf$k () {\n";
	print FH "    set_width($val3);\n";
	print FH "    set_depth(".($val2+$val3).");\n";
	print FH "  }\n";
	print FH "};\n\n";
}

#memory mem
    if($i > 500) {
	print FH "csl_memory mem$k {\n";
	print FH "  mem$k () {\n";
	print FH "    set_width($val2);\n";
	print FH "    set_depth(".($val2+$val1).");\n";
	print FH "  }\n";
	print FH "};\n\n";
    }
    

#unit a
    print FH "csl_unit a$k {\n";
    print FH "  csl_port p_a$i(inout,br3);\n";
    if($i > 50 && $i <= 100) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  reg$k reg$k\_$zero;\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_port p_m$i($dir{$l},br3);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_$i(br2);\n";
	print FH "  a$k a$k\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  rf$k rf$k\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    print FH "  b$k () {\n";
 
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_signal s_m$i($val2);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  f$k f$k\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  sg$m sg$m\_$two;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_x$i($val2);\n";
	print FH "  csl_signal s_y$i(br3);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    print FH "  c$k () {\n";
#connect_by_name : Invalid connection : sg---port (PC)
    if($i <= 50) {
	print FH "    sg$j\_$zero.connect_by_name(b$k\_$zero.p_m$i);  // Invalid connection : sg---port (PC)\n";
    }
#connect_by_name : Invalid connection : sg---sig.ps (CP), Invalid connection : sg---fifo (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.a$k\_$zero.sg$j\_$zero.connect_by_name(b$k\_$zero.s_$i\[".$val2."\:".($val2-2)."\],ps$i);  // Invalid connection : sg---sig.ps (CP)\n";
	print FH "    b$k\_$zero.a$k\_$one.sg$j\_$zero.connect_by_name(f$k\_$zero);  // Invalid connection : sg---fifo (CP)\n";
    }
#connect_by_name : Invalid connection : sg---ifc.ifc.p (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$m\_$zero.connect_by_name(b$k\_$zero.a$k\_$zero.ifc$m\_$zero.ifc$j\_$zero.ps_m$i);  // Invalid connection : sg---ifc.ifc.p (PC)\n";
    }
#connect_by_name : Invalid connection : sg---reg (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    sg$j\_$zero.connect_by_name(b$k\_$zero.a$k\_$zero.reg$k\_$zero);  // Invalid connection : sg---reg (PC)\n";
    }
#connect_by_name : Invalid connection : sg---concat expr (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    b$k\_$zero.sg$j\_$zero.connect_by_name({s_x$i,s_y$i});  // Invalid connection : sg---concat expr (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    print FH "  c$k c$k\_$zero;\n";
    if($i > 50 && $i <= 100) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_m$i(br2);\n";
	print FH "  csl_signal s_n$i(br1);\n";
	print FH "  csl_signal s_o$i($val2);\n";
    }
    print FH "  d$k () {\n";
#connect_by_name : Invalid connection : sg---sig (CP), Invalid connection : sg---sg (PC)
    if($i <= 50) {
	print FH "    c$k\_$zero.b$k\_$zero.sg$j\_$one.connect_by_name(c$k\_$zero.s_m$i);  // Invalid connection : sg---sig (CP)\n";
	print FH "    c$k\_$zero.sg$j\_$zero.connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$one);  // Invalid connection : sg---sg (PC)\n";
    }
#connect_by_name : Invalid connection : sg---p.ps (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$j\_$one.connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.p_a$i\[".$val3."\:".($val3-5)."\]);  // Invalid connection : sg---p.ps (PC)\n";
    }
#connect_by_name : Invalid connection : sg---sg.sg.sig (CP), Invalid connection : sg---sg.sg (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.b$k\_$zero.sg$j\_$one.connect_by_name(sg$m\_$one.sg$j\_$one.s_b$i);  // Invalid connection : sg---sg.sg.sig (CP)\n";
	print FH "    sg$m\_$one.sg$j\_$zero.connect_by_name(c$k\_$zero.sg$m\_$two.sg$j\_$one);  // Invalid connection : sg---sg.sg (PC)\n";
    }
#connect_by_name : Invalid connection : sg---rf (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    sg$j\_$one.connect_by_name(c$k\_$zero.b$k\_$zero.rf$k\_$zero);  // Invalid connection : sg---rf (PC)\n";
    }
#connect_by_name : Invalid connection : sg---repl expr (CP), Invalid connection : sg---op expr (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.b$k\_$zero.sg$j\_$zero.connect_by_name({2{s_m$i,s_n$i}});  // Invalid connection : sg---repl expr (CP)\n";
	print FH "    c$k\_$zero.sg$j\_$one.connect_by_name(s_m$i | s_o$i);  // Invalid connection : sg---op expr (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";









}
