#!/usr/bin/perl

#oanab
#connect_by_name() with param : const obj, par obj, par obj with const ps, const obj with par ps, par obj with par ps and par obj

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_param_invalid2/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 400; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_param".$i."_illegal.csl";
    if($j != $m && $j != $n && $m != $n) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+2;
    my $val2 = int(rand(100))+1;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_param_valid1");
        open(FH,">$path/ar_conn_name_param_valid1/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_param_invalid2"); 
        open(FH,">$path/ar_conn_name_param_invalid2/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#ifcj
    print FH "csl_interface ifc$j {\n";
    if($i <= 50) {
	print FH "  csl_port p_m$i(output,br3);\n";
	print FH "  csl_port p_n$i(input,".($val1+$val3).");\n";
	print FH "  csl_port p_o$i(input,br1);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par_m$i(".($val3+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_parameter par1(".($val3+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_port p_n$i(input,par_m$i);\n";
	print FH "  csl_port p_o$i(input,".($val1+$val2).");\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par_m$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_port p_n$i(input,".($val3+$val1).");\n";
	print FH "  csl_port p_o$i(input,".($val1+$val2).");\n";
    }
    elsif($i > 150 && $i <= 250) {
	print FH "  csl_parameter par_o$i(".(2*$val1+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_o$i);\n";
	print FH "  csl_parameter par1(".($val3+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_port p_n$i(input,".($val1+$val3+$val2).");\n";
	print FH "  csl_port p_o$i(input,par_o$i);\n";
    }
    elsif($i > 250 && $i <= 350) {
	print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_port p_n$i(input,".($val1+$val2).");\n";
	print FH "  csl_port p_o$i(input,".($val1+$val2+$val3).");\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_port p_n$i(input,par_m$i);\n";
	print FH "  csl_parameter par_o$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_o$i(input,par_o$i);\n";
    }
    print FH "  ifc$j () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#sgj
    print FH "csl_signal_group sg$j {\n";
    if($i <= 50) {
	print FH "  csl_signal p_m$i(".($val1+$val3).");\n";
	print FH "  csl_signal p_n$i(br2);\n";
	print FH "  csl_signal p_o$i(br3);\n";
    }
    elsif($i > 50 && $i <= 150) {
	print FH "  csl_parameter par_m$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal p_m$i(par_m$i);\n";
	print FH "  csl_parameter par_n$i(".($val1+$val2).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
	print FH "  csl_signal p_o$i(br3);\n";
    }
    elsif($i > 150 && $i <= 250) {
	print FH "  csl_signal p_m$i(".($val1+$val2).");\n";
	print FH "  csl_parameter par_n$i(".(3*$val2+$val1).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
	print FH "  csl_signal p_o$i(par_n$i);\n";
    }
    elsif($i > 250 && $i <= 350) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_n$i(".($val2+2*$val1).");\n";
	print FH "  csl_signal p_m$i(par_n$i);\n";
	print FH "  csl_signal p_n$i(".($val1+$val2+$val3).");\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  csl_parameter par_m$i(".($val3+$val2).");\n";
	print FH "  csl_signal p_m$i(par_m$i);\n";
	print FH "  csl_parameter par1(".($val3+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_signal p_n$i(par_m$i);\n";
	print FH "  csl_parameter par_o$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal p_o$i(par_o$i);\n";
    }
    print FH "  sg$j () {\n";
    print FH "  }\n";
    print FH "};\n\n";


#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  ifc$j ifc$j\_$zero;\n";	
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par_a$i(".($val2).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par_x$i(".($val2+$val3).");\n";
	print FH "  csl_signal s_x$i(par_x$i);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_parameter par_a$i(".($val2).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_parameter par_a$i(".($val2+$val1).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par_b$i(".($val1).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par_x$i(".($val3+$val2+$val1).");\n";
	print FH "  csl_port p_x$i(input,par_x$i);\n";
	print FH "  csl_parameter par1(".($val3+$val2+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par_a$i(".($val3).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_parameter par_a$i(".($val2).");\n";	
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  csl_port p_a$i(input,par_a$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par_b$i(".($val1).");\n";
	print FH "  csl_port p_b$i(input,par_b$i);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par_c$i(".($val2).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  csl_parameter par_m$i(".($val3+$val2).");\n";
	print FH "  csl_port p_m$i(input,par_m$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  a$k a$k\_$one;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  csl_port p_b$i(input,".($val1+$val2).");\n";
	print FH "  csl_parameter par3(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par4(".($val1).");\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par1(".($val2).");\n";
	print FH "  csl_signal s_y$i(par1);\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  csl_parameter par_a$i(".($val1+$val2).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    print FH "  b$k () {\n";
#Invalid connection : ifc---spar (PC)
    if($i > 50 && $i <= 100) {
	print FH "    ifc$j\_$zero.connect_by_name(a$k\_$zero.s_a$i);  // Invalid connection : ifc---spar (PC)\n";
    }
#Invalid connection : spar.ps---spar (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    a$k\_$zero.s_x$i\[".($val2+$val3-1)."\:".($val3)."\].connect_by_name(s_c$i);  // Invalid connection : spar.ps---spar (CP)\n";
    }
#Invalid connection : sg.spar.ps---ifc (CP)
    elsif($i > 150 && $i <= 200) {
	print FH "    a$k\_$zero.sg$j\_$zero.p_n$i\[".($val2+$val1+1)."\].connect_by_name(ifc$j\_$zero);  // Invalid connection : sg.spar.ps---ifc (CP)\n";
    }
#Invalid connection : s.pspar---spar (SS) and p.pspar---sg (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    a$k\_$zero.s_a$i\[par1\:par2\].connect_by_name(a$k\_$one.s_b$i);  // Invalid connection : s.pspar---spar (SS)\n";
	print FH "    p_b$i\[par3\:par4\].connect_by_name(a$k\_$zero.sg$j\_$zero);  // Invalid connection : p.pspar---sg (PC)\n";
    }
#Invalid connection : sg.s.pspar---spar (CP)
    elsif($i > 250 && $i <= 300) {
	print FH "    a$k\_$zero.sg$j\_$one.p_n$i\[par1\:par2\].connect_by_name(s_y$i);  // Invalid connection : sg.s.pspar---spar (CP)\n";
    }
#Invalid connection : ppar.pspar---sg (CP)
    elsif($i > 300 && $i <= 350) {
	print FH "    a$k\_$zero.p_x$i\[par1\:par2\].connect_by_name(sg$j\_$zero);  // Invalid connection : ppar.pspar---sg (CP)\n";
    }
#Invalid connection : sg.spar.pspar---spar (PC)
    elsif($i > 350 && $i <= 400) {
	print FH "    sg$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(a$k\_$zero.s_a$i);  // Invalid connection : sg.spar.pspar---spar (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_parameter par_c$i(".($val2).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  csl_parameter par_b$i(".($val3).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  csl_port p_c$i(output,par_b$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par_x$i(".($val1).");\n";
	print FH "  csl_port p_x$i(input,par_x$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";	
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par_c$i(".($val1+$val2).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  csl_port p_c$i(output,par_c$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_c$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  csl_parameter par_c$i(".($val1).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  b$k b$k\_$one;\n";
	print FH "  csl_parameter par_m$i(".($val3+$val2).");\n";
	print FH "  csl_signal s_m$i(par_m$i);\n";
	print FH "  csl_port p_m$i(input,par_m$i);\n";
	print FH "  csl_parameter par1(".($val3+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    print FH "  c$k () {\n";
#Invalid connection : spar---spar (CP) and ppar---ifc (PC)
    if($i <= 50) {
	print FH "    b$k\_$zero.s_a$i.connect_by_name(s_c$i);  // Invalid connection : spar---spar (CP)\n";
	print FH "    b$k\_$zero.p_a$i.connect_by_name(b$k\_$zero.a$k\_$zero.ifc$j\_$zero);  // Invalid connection : ppar---ifc (PC)\n";
    }
#Invalid connection : ifcpar---ppar (CP) and sgpar---sg (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.ifc$j\_$zero.connect_by_name(p_x$i);  //  Invalid connection : ifcpar---ppar (CP)\n";
	print FH "    sg$j\_$zero.connect_by_name(b$k\_$zero.a$k\_$zero.sg$j\_$zero);  // Invalid connection : sgpar---sg (PC)\n";
    }
#Invalid connection : ppar.ps---ifc (PC) and ppar---sg (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    p_c$i\[".($val1+$val2-1)."\:".($val1)."\].connect_by_name(b$k\_$zero.a$k\_$zero.ifc$j\_$zero);  // Invalid connection : ppar.ps---ifc (PC)\n";
	print FH "    b$k\_$zero.p_m$i\[".($val2+$val3-1)."\-\:".($val3)."\].connect_by_name(sg$j\_$zero);  // Invalid connection : ppar---sg (CP)\n";
    }
#Invalid connection : ifc.ppar.ps---ifc (CP) and sg.spar.ps---sg (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.ifc$j\_$zero.p_m$i\[".($val1+$val2-1)."\:".($val1)."\].connect_by_name(ifc$j\_$one);  // Invalid connection : ifc.ppar.ps---ifc (CP)\n";
	print FH "    sg$j\_$one.p_o$i\[".(2*$val2+$val1-1)."\:".($val1)."\].connect_by_name(b$k\_$zero.a$k\_$zero.sg$j\_$zero);  // Invalid connection : sg.spar.ps---sg (PC)\n";
    }
#Invalid connection : s.pspar---ifc (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    b$k\_$zero.a$k\_$zero.s_a$i\[par1\:par2\].connect_by_name(b$k\_$zero.ifc$j\_$one);  // Invalid connection : s.pspar---ifc (CP)\n";
    }
#Invalid connection : ifc.p.pspar---ifc (CP) and sg.s.pspar---sg (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    b$k\_$zero.ifc$j\_$zero.p_n$i\[par1\:par2\].connect_by_name(ifc$j\_$one);  // Invalid connection : ifc.p.pspar---ifc (CP)\n";
	print FH "    sg$j\_$one.p_n$i\[par1\-\:par2\].connect_by_name(b$k\_$zero.a$k\_$zero.sg$j\_$one);  // Invalid connection : sg.s.pspar---sg (PC)\n";
    }
#Invalid connection : spar.pspar---ifc (SS) and ppar.pspar---ifc (PC)
    elsif($i > 300 && $i <= 350) {
	print FH "    b$k\_$one.s_a$i\[par1\:par2\].connect_by_name(b$k\_$zero.ifc$j\_$zero);  // Invalid connection : spar.pspar---ifc (SS)\n";
	print FH "    p_m$i\[par1\:par2\].connect_by_name(b$k\_$zero.a$k\_$zero.ifc$j\_$zero);  // Invalid connection : ppar.pspar---ifc (PC)\n";
    }
#Invalid connection : ifc.ppar.pspar---ifc (CP) and sg.spar.pspar---ifc (CP)
    elsif($i > 350 && $i <= 400) {
	print FH "    b$k\_$zero.a$k\_$zero.ifc$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(ifc$j\_$one);  // Invalid connection : ifc.ppar.pspar---ifc (CP)\n";
	print FH "    b$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par1\].connect_by_name(ifc$j\_$one);  // Invalid connection : sg.spar.pspar---ifc (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    print FH "  c$k c$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_parameter par_d$i(".($val3+$val2).");\n";
	print FH "  csl_signal s_d$i(par_d$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par_m$i(".($val3).");\n";
	print FH "  csl_signal s_m$i(par_m$i);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par_y$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_y$i(par_y$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_d$i(output,".($val1+$val3).");\n";
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    print FH "  d$k () {\n";
#Invalid connection : spar---ifc (PC) and spar---sg (PC) and ppar---sg (CP)
    if($i <= 50) {
	print FH "    c$k\_$zero.s_b$i.connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.ifc$j\_$zero);  // Invalid connection : spar---ifc (PC)\n";
	print FH "    s_d$i.connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$zero);  // Invalid connection : spar---sg (PC)\n";
	print FH "    c$k\_$zero.p_c$i.connect_by_name(sg$j\_$zero);  // Invalid connection : ppar---sg (CP)\n";
    }
#Invalid connection : sg---spar (CP) and sg---ppar (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    c$k\_$zero.sg$j\_$zero.connect_by_name(s_m$i);  // Invalid connection : sg---spar (CP)\n";
	print FH "    sg$j\_$one.connect_by_name(c$k\_$zero.b$k\_$zero.p_b$i);  // Invalid connection : sg---ppar (PC)\n";
    }
#Invalid connection : spar.ps---ifc (PC) and spar.ps---sg (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    s_y$i\[".($val1+$val3-1)."\:".($val1)."\].connect_by_name(c$k\_$zero.ifc$j\_$zero.);  // Invalid connection : spar.ps---ifc (PC)\n";
	print FH "    c$k\_$zero.s_c$i\[".($val1+$val2-1)."\-\:".($val2)."\].connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$zero);  // Invalid connection : spar.ps---sg (PC)\n";
    }
#Invalid connection : ifc.ppar.ps---sg (CP) and sg.spar.ps---spar (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    c$k\_$zero.ifc$j\_$one.p_o$i\[".(2*$val1)."\-\:".($val1)."\].connect_by_name(sg$j\_$one);  // Invalid connection : ifc.ppar.ps---sg (CP)\n";
	print FH "    sg$j\_$one.p_o$i\[".($val2+$val1-1)."\:".($val1)."\].connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.s_a$i);  // Invalid connection : sg.spar.ps---spar (PC)\n";
    }
#Invalid connection : s.pspar---sg (PC) and p.pspar---ifc (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.s_c$i\[par1\:par2\].connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$zero);  // Invalid connection : s.pspar---sg (PC)\n";
	print FH "    p_d$i\[par1\-\:par2\].connect_by_name(c$k\_$zero.ifc$j\_$one);  // Invalid connection : p.pspar---ifc (PC)\n";
    }
#Invalid connection : ifc.p.pspar---sg (CP) and sg.s.pspar---ifc (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    c$k\_$zero.ifc$j\_$one.p_o$i\[par1\:par2\].connect_by_name(sg$j\_$one);  // Invalid connection : ifc.p.pspar---sg (CP)\n";
	print FH "    sg$j\_$one.p_n$i\[par1\].connect_by_name(c$k\_$zero.ifc$j\_$one);  // Invalid connection : sg.s.pspar---ifc (PC)\n";
    }
#Invalid connection : spar.pspar---spar (CP) and spar.pspar---sg (CP)
    elsif($i > 300 && $i <= 350) {
	print FH "    c$k\_$zero.b$k\_$zero.s_a$i\[par1\:par2\].connect_by_name(c$k\_$zero.s_c$i);  // Invalid connection : spar.pspar---spar (CP)\n";
	print FH "    c$k\_$zero.s_m$i\[par1\-\:par2\].connect_by_name(sg$j\_$one);  // Invalid connection : spar.pspar---sg (CP)\n";
    }
#Invalid connection : ifc.ppar.pspar---sg (CP) and sg.spar.pspar---sg (PC)
    elsif($i > 350 && $i <= 400) {
	print FH "    c$k\_$zero.ifc$j\_$one.p_o$i\[par1\-\:par2\].connect_by_name(sg$j\_$zero);  // Invalid connection : ifc.ppar.pspar---sg (CP)\n";
	print FH "    sg$j\_$zero.p_n$i\[par1\:par2\].connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$zero);  // Invalid connection : sg.spar.pspar---sg (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
