#!/usr/bin/perl

#oanab
#connect_by_name() with param : par obj with const ps, const obj with par ps, par obj with par ps and par obj with par ps

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_param_valid7/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 300; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_param".$i."_legal.csl";
    if($j != $m) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100)) + 3;
    my $val2 = int(rand(100)) + 4;
    my $val3 = int(rand(100)) + 8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_param_valid7");
        open(FH,">$path/ar_conn_name_param_valid7/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_param_invalid1"); 
        open(FH,">$path/ar_conn_name_param_invalid1/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#ifcj
    print FH "csl_interface ifc$j {\n";
    if($i <= 100) {
	print FH "  csl_parameter par_m$i(".($val3+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_parameter par1(".($val3+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_port p_n$i(input,par_m$i);\n";
	print FH "  csl_port p_o$i(input,".($val1+$val2).");\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par_m$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_port p_n$i(input,".($val3+$val1).");\n";
	print FH "  csl_port p_o$i(input,".($val1+$val2).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_parameter par_o$i(".(2*$val1+$val2+$val3).");\n";
	print FH "  csl_port p_m$i(output,".($val3+$val2).");\n";
	print FH "  csl_parameter par1(".($val3+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_port p_n$i(input,".($val1+$val3+$val2).");\n";
	print FH "  csl_port p_o$i(input,par_o$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_port p_n$i(input,par_m$i);\n";
	print FH "  csl_port p_o$i(output,".($val2+$val1).");\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_parameter par_m$i(".($val1+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_m$i);\n";
	print FH "  csl_parameter par_n$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_port p_n$i(input,par_n$i);\n";
	print FH "  csl_parameter par3(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par4(".($val2).");\n";
	print FH "  csl_parameter par_o$i(".(2*$val1+$val2+$val3).");\n";
	print FH "  csl_port p_o$i(input,par_o$i);\n";
	
    }
    print FH "  ifc$j () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#sgj
    print FH "csl_signal_group sg$j {\n";
    if($i <= 100) {
	print FH "  csl_parameter par_m$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal p_m$i(par_m$i);\n";
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_parameter par3(".($val2+$val3-1).");\n";
	print FH "  csl_signal p_n$i(par_m$i);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal p_m$i(".($val1+$val3).");\n";
	print FH "  csl_parameter par_n$i(".($val1+$val2+$val2).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
	print FH "  csl_signal p_o$i(par_n$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal p_m$i(".($val1+$val2).");\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par3(".($val3).");\n";
	print FH "  csl_parameter par_n$i(".($val2+2*$val1).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
	print FH "  csl_signal p_o$i(".($val2+$val3).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_parameter par1(".($val3+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_signal p_m$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_parameter par_n$i(".($val3+$val2).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_n$i(".($val2+2*$val1).");\n";
	print FH "  csl_signal p_m$i(par_n$i);\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
    }
    print FH "  sg$j () {\n";
    print FH "  }\n";
    print FH "};\n\n";


#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  csl_parameter par_a$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  csl_signal s_b$i(par_a$i);\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par1(".($val3+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_c$i(".($val3+$val1+3).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par1(".($val3+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_parameter par_c$i(".($val3+$val1+3).");\n";
	print FH "  csl_port p_c$i(input,par_c$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_parameter par1(".($val2+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_c$i(".($val2+$val1+3).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
	print FH "  csl_port p_a$i(output,par_c$i);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_parameter par1(".($val2+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par_m$i(".($val2+$val1+$val3).");\n";
	print FH "  csl_signal s_m$i(par_m$i);\n";
	print FH "  csl_port p_c$i(input,par_m$i);\n";
	print FH "  csl_port p_d$i(input,par_m$i);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  ifc$j ifc$j\_$two;\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par_c$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_c$i(input,par_c$i);\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    if($i <= 50) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$one.p_n$i(ifc$j\_$zero.p_n$i),.ifc$j\_$one.p_o$i(ifc$j\_$zero.p_o$i));\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par_b$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_b$i(input,par_b$i);\n";
	print FH "  csl_port p_m$i(output,par_b$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$one.p_m$i(ifc$j\_$zero.p_m$i),.ifc$j\_$one.p_n$i(ifc$j\_$zero.p_n$i),.ifc$j\_$one.p_o$i(ifc$j\_$zero.p_o$i));\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$two ;\n";
	print FH "  a$k a$k\_$one(.ifc$j\_$one.p_m$i(ifc$j\_$two.p_m$i),.ifc$j\_$one.p_n$i(ifc$j\_$two.p_n$i),.ifc$j\_$one.p_o$i(ifc$j\_$two.p_o$i));\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  a$k a$k\_$zero(.p_c$i(s_n$i\[".($val2+$val3+$val1-1)."\-\:".($val1+$val3+3)."\]));\n";
	print FH "  csl_signal s_m$i(".($val1+2*$val2).");\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_signal s_n$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_d$i(input,".($val2+$val3+$val1-1).");\n";
	print FH "  csl_port p_x$i(output,".($val2+$val1).");\n";
	print FH "  csl_port p_y$i(input,".($val3+$val2).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$zero.p_m$i(ifc$j\_$zero.p_m$i),.ifc$j\_$zero.p_n$i(ifc$j\_$zero.p_n$i),.ifc$j\_$zero.p_o$i(ifc$j\_$zero.p_o$i),.ifc$j\_$one.p_m$i(ifc$j\_$one.p_m$i),.ifc$j\_$one.p_n$i(ifc$j\_$one.p_n$i),.ifc$j\_$one.p_o$i(ifc$j\_$one.p_o$i));\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  csl_parameter par3(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par4(".($val2).");\n";
	print FH "  csl_parameter par_n$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_n$i(input,par_n$i);\n";
	print FH "  csl_port p_m$i(output,par_n$i);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_parameter par3(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par4(".($val1).");\n";
	print FH "  csl_parameter par_n$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal s_n$i(par_n$i);\n";
	print FH "  csl_port p_a$i(output,par_n$i);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    print FH "  b$k () {\n";
#connect_by_name : spar.ps---ifc.ppar.pspar (CP)
    if($i <= 50) {
	print FH "    a$k\_$zero.s_b$i\[".($val1+$val3-1)."\:".($val1)."\].connect_by_name(ifc$j\_$zero.p_m$i\[par1\:par2\]);  // spar.ps---ifc.ppar.pspar (CP)\n";
    }
#connect_by_name : ifc.ppar.ps---spar.pspar (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    ifc$j\_$zero.p_n$i\[".($val2+$val3-1)."\:".($val2)."\].connect_by_name(a$k\_$zero.s_c$i\[par1\:par2\]);  // ifc.ppar.ps---spar.pspar (PC)\n";
    }
#connect_by_name : p.pspar---sg.spar.pspar (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    p_y$i\[par2\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_m$i\[par1\:par1\]);  // p.pspar---sg.spar.pspar (PC)\n";
    }
#connect_by_name : ifc.p.pspar---ppar.pspar (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    ifc$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(a$k\_$zero.p_a$i\[par1\:par2\]);  // ifc.p.pspar---ppar.pspar (PC)\n";
    }
#connect_by_name : ppar.pspar---ppar.pspar (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    a$k\_$zero.p_c$i\[par1\:par2\].connect_by_name(p_n$i\[par3\:par4\]);  // ppar.pspar---ppar.pspar (CP)\n";
    }
#connect_by_name : ifc.ppar.pspar---spar.pspar (CP) and sg.spar.pspar---ifc.ppar.pspar (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    a$k\_$zero.ifc$j\_$one.p_m$i\[par1\:par2\].connect_by_name(s_n$i\[par3\:par4\]);  // ifc.ppar.pspar---spar.pspar (CP)\n";
	print FH "    sg$j\_$one.p_n$i\[par2\:par2\].connect_by_name(a$k\_$zero.ifc$j\_$two.p_o$i\[par4\]);  // sg.spar.pspar---ifc.ppar.pspar (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    if($i <= 50) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero.p_n$i(p_a$i\[".($val1+$val2+$val3-1)."\:".($val1)."\]),.ifc$j\_$zero.p_o$i(s_c$i\[".($val1+$val2+$val3-1)."\:".($val3)."\]));\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par3(".($val1).");\n";
	print FH "  csl_parameter par_a$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_a$i(input,par_a$i);\n";
	print FH "  csl_signal s_c$i(par_a$i);\n";
	print FH "  csl_port p_c$i(output,par_a$i);\n";
	print FH "  csl_port p_d$i(input,par_a$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero.p_m$i(ifc$j\_$one.p_m$i),.ifc$j\_$zero.p_n$i(ifc$j\_$one.p_n$i),.ifc$j\_$zero.p_o$i(ifc$j\_$one.p_o$i),.ifc$j\_$two.p_m$i(ifc$j\_$one.p_m$i),.ifc$j\_$two.p_n$i(ifc$j\_$one.p_n$i),.ifc$j\_$two.p_o$i(ifc$j\_$one.p_o$i));\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_a$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_a$i(output,par_a$i);\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  b$k b$k\_$zero(.p_y$i(s_a$i\[".($val1+$val2+$val3-1)."\:".($val1)."\]));\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par3(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par_a$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_a$i(input,par_a$i);\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  b$k b$k\_$zero(.ifc$j\_$zero.p_m$i(ifc$j\_$zero.p_m$i),.ifc$j\_$zero.p_n$i(ifc$j\_$zero.p_n$i),.ifc$j\_$zero.p_o$i(ifc$j\_$zero.p_o$i),.ifc$j\_$one.p_m$i(ifc$j\_$zero.p_m$i),.ifc$j\_$one.p_n$i(ifc$j\_$zero.p_n$i),.ifc$j\_$one.p_o$i(ifc$j\_$zero.p_o$i));\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  b$k b$k\_$one(.ifc$j\_$zero.p_m$i(sg$j\_$one.p_o$i),.ifc$j\_$zero.p_n$i(ifc$j\_$zero.p_n$i),.ifc$j\_$zero.p_o$i(ifc$j\_$zero.p_o$i),.ifc$j\_$one.p_m$i(ifc$j\_$zero.p_m$i),.ifc$j\_$one.p_n$i(ifc$j\_$zero.p_n$i),.ifc$j\_$one.p_o$i(ifc$j\_$zero.p_o$i));\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_parameter par3(".($val1+$val3+$val2-1).");\n";
	print FH "  csl_parameter par4(".($val2).");\n";
	print FH "  csl_parameter par_a$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_a$i(input,par_a$i);\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  csl_signal s_b$i(par_a$i);\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    print FH "  c$k () {\n";
#connect_by_name : ppar.ps---spar.pspar (CP) and ppar.ps---ifc.ppar.pspar (PC)
    if($i <= 50) {
	print FH "    b$k\_$zero.p_b$i\[".($val1+$val2+$val3-1)."\:".($val3+$val1)."\].connect_by_name(s_c$i\[\par1\:par3]);  // ppar.ps---spar.pspar (CP)\n";
	print FH "    b$k\_$zero.p_m$i\[".($val1+$val3-1)."\:".($val1)."\].connect_by_name(b$k\_$zero.a$k\_$zero.ifc$j\_$one.p_m$i\[par1\:par2\]);  // ppar.ps---ifc.ppar.pspar (PC)\n";
    }
#connect_by_name : ifc.ppar.ps---ppar.pspar (CP) and ifc.ppar.ps---sg.spar.pspar (SS) and sg.spar.ps---ifc.ppar.pspar (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.ifc$j\_$zero.p_m$i\[".($val2+$val3-1)."\:".($val3)."\].connect_by_name(p_a$i\[par1\:par2\]);  // ifc.ppar.ps---ppar.pspar (CP)\n";
	print FH "    b$k\_$zero.a$k\_$one.ifc$j\_$one.p_n$i\[".($val2+$val3-1)."\:".($val3)."\].connect_by_name(b$k\_$zero.a$k\_$zero.sg$j\_$zero.p_m$i\[par3\:par2\]);  // ifc.ppar.ps---sg.spar.pspar (SS)\n";
	print FH "    sg$j\_$one.p_m$i\[".($val1+$val3)."\].connect_by_name(b$k\_$zero.ifc$j\_$two.p_n$i\[par2\:par2\]);  // sg.spar.ps---ifc.ppar.pspar (PC)\n";
    }
#connect_by_name : s.pspar---ppar.pspar (CP) and p.pspar---ppar.pspar (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    b$k\_$zero.s_m$i\[par1\:par2\].connect_by_name(p_a$i\[par1\:par2\]);  // s.pspar---ppar.pspar (CP)\n";
	print FH "    b$k\_$zero.p_d$i\[par1\:par2\].connect_by_name(b$k\_$zero.a$k\_$zero.p_c$i\[par1\:par2\]);  // p.pspar---ppar.pspar (PC)\n";
    }
#connect_by_name : ifc.p.pspar---spar.pspar (PC) and ifc.p.pspar---ifc.ppar.pspar (CP) and sg.s.pspar---ifc.ppar.pspar (SS)
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.ifc$j\_$zero.p_n$i\[par1\:par2\].connect_by_name(b$k\_$zero.a$k\_$zero.s_c$i\[par1\:par2\]);  // ifc.p.pspar---spar.pspar (PC)\n";
	print FH "    b$k\_$zero.a$k\_$zero.ifc$j\_$one.p_n$i\[par1\:par2\].connect_by_name(ifc$j\_$zero.p_o$i\[par1\:par2\]);  // ifc.p.pspar---ifc.ppar.pspar (CP)\n";
	print FH "    b$k\_$zero.sg$j\_$zero.p_o$i\[".($val2+$val3-1)."\:par3\].connect_by_name(b$k\_$one.ifc$j\_$one.p_o$i\[par1\:par2\]);  // sg.s.pspar---ifc.ppar.pspar (SS)\n";
    }
#connect_by_name : spar.pspar---ppar.pspar (CP) and ifc.ppar.pspar---ppar.pspar (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    b$k\_$zero.a$k\_$zero.s_m$i\[par1\:par2\].connect_by_name(p_a$i\[par1\:par2\]);  // spar.pspar---ppar.pspar (CP)\n";
	print FH "    ifc$j\_$one.p_n$i\[par1\].connect_by_name(b$k\_$zero.a$k\_$zero.p_d$i\[par2\]);  // ifc.ppar.pspar---ppar.pspar (PC)\n";
    }
#connect_by_name : ifc.ppar.pspar---ppar.pspar (PC) and ifc.ppar.pspar---ifc.ppar.pspar (CP)
    elsif($i > 250 && $i <= 300) {
	print FH "    ifc$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(b$k\_$zero.p_a$i\[par3\:par4\]);  // ifc.ppar.pspar---ppar.pspar (PC)\n";
	print FH "    b$k\_$zero.a$k\_$zero.ifc$j\_$one.p_n$i\[par1\:par2\].connect_by_name(ifc$j\_$zero.p_o$i\[par3\-\:par4\]);  // ifc.ppar.pspar---ifc.ppar.pspar (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    if($i <= 50) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  csl_parameter par_c$i(".($val1+$val2).");\n";
	print FH "  csl_port p_c$i(output,par_c$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  c$k c$k\_$zero(.p_a$i(p_a$i),.ifc$j\_$one.p_m$i(ifc$j\_$two.p_m$i),.ifc$j\_$one.p_n$i(ifc$j\_$two.p_n$i),.ifc$j\_$one.p_o$i(ifc$j\_$two.p_o$i));\n";
	print FH "  ifc$j ifc$j\_$two;\n";
	print FH "  csl_parameter par_a$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_port p_a$i(output,par_a$i);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  c$k c$k\_$zero(.p_a$i(s_a$i));\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  csl_signal s_a$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_port p_c$i(output,".($val1+$val2+$val3).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par_a$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_a$i(output,par_a$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  csl_parameter par3(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par4(".($val2).");\n";
	print FH "  csl_parameter par_b$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_port p_b$i(output,par_b$i);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    print FH "  d$k () {\n";
#connect_by_name : spar.ps---spar.pspar (CP) and ppar.ps---ppar.pspar (PC)
    if($i <= 50) {
	print FH "    p_c$i = sg$j\_$zero.p_n$i\[".($val1+$val2+$val3-1)."\-\:".($val1+$val2)."\];\n";
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.s_a$i\[".($val1+$val3-1)."\:".($val3)."\].connect_by_name(c$k\_$zero.p_a$i\[par1\:par2\]);  // spar.ps---spar.pspar (CP)\n";
	print FH "    p_c$i\[".($val1+$val2-1)."\:".($val1)."\].connect_by_name(c$k\_$zero.p_c$i\[par1\-\:par2\]);  // ppar.ps---ppar.pspar (PC)\n";
	print FH "    c$k\_$zero.p_d$i\[".($val1+$val2+$val3-1)."\-\:".($val1+$val2)."\].connect_by_name(sg$j\_$zero.p_m$i\[par1\:par2\]);\n";
    }
#connect_by_name : ifc.ppar.ps---ifc.ppar.pspar (CP) and sg.spar.ps---ppar.pspar (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "    c$k\_$zero.ifc$j\_$one.p_m$i\[".($val3+$val2-1)."\-\:".($val3)."\].connect_by_name(ifc$j\_$two.p_m$i\[par1\:par2\]);  // ifc.ppar.ps---ifc.ppar.pspar (CP)\n";
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.sg$j\_$zero.p_n$i\[".($val1+$val2+$val3-1)."\:".($val2)."\].connect_by_name(p_a$i\[par1\:par2\]);  // sg.spar.ps---ppar.pspar (CP)\n";
    }
#connect_by_name : s.pspar---ifc.ppar.pspar (CP) and p.pspar---spar.pspar (PC) and p.pspar---ifc.ppar.pspar (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    s_a$i = {ifc$j\_$one.p_n$i\[".($val3+$val1-1)."\:".(0)."\],ifc$j\_$one.p_o$i\[".($val1+$val2-1)."\-\:".($val2)."\]};\n";
	print FH "    s_a$i = {ifc$j\_$zero.p_n$i\[".($val3+$val1-1)."\-\:".($val3)."\],ifc$j\_$zero.p_o$i\[".($val1+$val2-1)."\:".(0)."\]};\n";
	print FH "    c$k\_$zero.b$k\_$zero.s_n$i\[par1\:par2\].connect_by_name(ifc$j\_$zero.p_m$i\[par1\:par2\]);  // s.pspar---ifc.ppar.pspar (CP)\n";
	print FH "    p_c$i\[par1\:par2\].connect_by_name(c$k\_$zero.s_a$i\[par3\:par2\]);  // p.pspar---spar.pspar (PC)\n";
	print FH "    c$k\_$zero.b$k\_$zero.p_x$i\[par1\:par1\].connect_by_name(ifc$j\_$one.p_m$i\[par2\-\:1\]);  // p.pspar---ifc.ppar.pspar (CP)\n";
    }
#connect_by_name : ifc.p.pspar---sg.spar.pspar (CP) and sg.s.pspar---ppar.pspar (CP)
    elsif($i > 150 && $i <= 200) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.ifc$j\_$zero.p_n$i\[par1\:par2\].connect_by_name(sg$j\_$zero.p_n$i\[par1\:par2\]);  // ifc.p.pspar---sg.spar.pspar (CP)\n";
	print FH "    c$k\_$zero.sg$j\_$one.p_m$i\[par1\:par2\].connect_by_name(p_a$i\[par1\-\:par2\]);  // sg.s.pspar---ppar.pspar (CP)\n";
    }
#connect_by_name : spar.pspar---ifc.ppar.pspar (PC) and ppar.pspar---spar.pspar (PC) and ppar.pspar---sg.spar.pspar (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.s_a$i\[par1\:par2\].connect_by_name(c$k\_$zero.b$k\_$zero.ifc$j\_$zero.p_m$i\[par1\:par2\]);  // spar.pspar---ifc.ppar.pspar (PC)\n";
	print FH "    p_b$i\[par3\:par4\].connect_by_name(c$k\_$zero.s_b$i\[par3\:par4\]);  // ppar.pspar---spar.pspar (PC)\n";
	print FH "    c$k\_$zero.b$k\_$zero.p_m$i\[par3\-\:par4\].connect_by_name(c$k\_$zero.sg$j\_$one.p_n$i\[par1\-\:par2\]);  // ppar.pspar---sg.spar.pspar (CP)\n";
    }
#connect_by_name : ifc.ppar.pspar---sg.spar.pspar (CP) and sg.spar.pspar---ppar.pspar (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    c$k\_$zero.ifc$j\_$zero.p_n$i\[par1\:par2\].connect_by_name(sg$j\_$zero.p_n$i\[par1\:par2\]);  // ifc.ppar.pspar---sg.spar.pspar (CP)\n";
	print FH "    sg$j\_$zero.p_m$i\[par1\-\:par2\].connect_by_name(c$k\_$zero.b$k\_$zero.a$k\_$zero.p_c$i\[par1\:par2\]);  // sg.spar.pspar---ppar.pspar (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
