#!/usr/bin/perl

#oanab
#connect_by_name() & f2a; with part select also

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_f2a_valid/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 300; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_f2a".$i."_legal.csl";
    if($j != $m && $j != $n && $m != $n) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+2;
    my $val2 = int(rand(100))+3;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_f2a_valid");
        open(FH,">$path/ar_conn_name_f2a_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_f2a_invalid"); 
        open(FH,">$path/ar_conn_name_f2a_invalid/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#ifcj
    if($i > 200 && $i <= 300) {
	print FH "csl_interface ifc$j {\n";
	print FH "  csl_port p_m$i($dir{$l},br1);\n";
	print FH "  csl_port p_n$i(input,br3);\n";
	print FH "  ifc$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#ifcm
    if($i > 350 && $i <= 300) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_x$i($dir{$l},br2);\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  ifc$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgj
    if($i > 250) {
	print FH "csl_signal_group sg$j {\n";
	print FH "  csl_signal p_m$i($val1);\n";
	print FH "  csl_signal p_n$i(br3);\n";
	print FH "  sg$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#unit a
    print FH "csl_unit a$k {\n";
    if($i > 50 && $i <= 100) {
	print FH "  csl_port p_b$i(input,1);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_port p_x$i(input,br3);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal s_m$i($val1);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_x$i(input,$val3);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    
    if($i <= 100) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_port p_a$i(input,br2);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_signal s_a$i(br3);\n";
	print FH "  a$k a$k\_$zero(.p_x$i($val3));\n";
	print FH "  a$k a$k\_$two(.p_x$i(s_a$i));\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_port p_n$i(output,".(2*$val3+2*$val2).");\n";
    }
#f2a : port---ifc.p
    elsif($i > 200 && $i <= 250) {
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  a$k a$k\_$one(.p_x$i(ifc$j\_$zero.p_n$i));  // f2a : port---ifc.p\n";
    }
#f2a : ifc---ifc
    elsif($i > 250 && $i <= 300) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  ifc$j ifc$j\_$two;\n";
#	print FH "  a$k a$k(.ifc$j\_$zero(ifc$j\_$one));  // f2a : ifc---ifc\n";
    }
    print FH "  b$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
#f2a : port---port
    if($i <= 50) {
	print FH "  csl_port p_b$i(input,br2);\n";
	print FH "  b$k b$k\_$one;\n";
	print FH "  b$k b$k\_$zero(.p_a$i(p_b$i));  // f2a : port---port\n";
    }
#f2a : port---concat expr
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_a$i(".($val2-2).");\n";
	print FH "  csl_signal s_b$i(2);\n";
	print FH "  b$k b$k\_$zero(.p_a$i({s_a$i,s_b$i}));  // f2a : port---concat expr\n";
	print FH "  b$k b$k\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  csl_port p_x$i(input,$val3);\n";
	print FH "  csl_port p_y$i(output,br3);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_signal s_m$i(".(2*$val3+2*$val2).");\n";
	print FH "  b$k b$k\_$zero(.p_n$i(s_m$i));\n";
	print FH "  csl_port p_m$i(input,".($val1+$val2).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  b$k b$k\_$zero;\n";
    }
#f2a : ifc---sg
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$j sg$j\_$zero;\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  b$k b$k\_$one(.ifc$j\_$one(sg$j\_$zero),.ifc$j\_$two(sg$j\_$zero));  // f2a : ifc---sg\n";
    }
    print FH "  c$k () {\n";
#connect_by_name : port---port (PC)
    if($i <= 50) {
	print FH "    p_b$i.connect_by_name(b$k\_$one.p_a$i);  // port---port (PC)\n";
    }
#connect_by_name : sig---p.ps (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    s_a$i.connect_by_name(b$k\_$one.p_a$i\[".($val2-3)."\:0\]);  // sig---p.ps (PC)\n";
	print FH "    b$k\_$zero.a$k\_$zero.p_b$i.connect_by_name(s_b$i\[1\]);  // port---sig.ps (CP)\n"
    }
#connect_by_name : sig---p.ps (CP)
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.a$k\_$zero.s_m$i.connect_by_name(p_m$i\[".($val1)."\-\:".$val1."\]);  // sig---p.ps (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    if($i <= 50) {
	print FH "  csl_port p_d$i(input,$val2);\n";
	print FH "  c$k c$k\_$zero(.p_b$i(p_d$i));\n";
    }
#f2a : port---p.ps
    if($i > 50 && $i <= 100) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  csl_port p_c$i(input,".($val2+$val1).");\n";
	print FH "  csl_signal s_b$i($val2);\n";
	print FH "  a$k a$k(.p_b$i(p_c$i\[".($val1-1)."\:".($val1-1)."\]));  // f2a : port---p.ps\n";
    }
#f2a : port---op expr, port---sig
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_signal s_x$i(br3);\n";
	print FH "  csl_signal s_y$i($val3);\n";
	print FH "  c$k c$k\_$zero(.p_x$i(s_x$i & s_y$i),.p_y$i(s_x$i));  // f2a : port---op expr, port---sig\n";
    }
#f2a : port---repl expr
    elsif($i > 150 && $i <= 200) {
#	print FH "  csl_signal s_p$i(".($val1+$val2).");\n";
	print FH "  c$k c$k\_$zero;\n";   #(.p_m$i(s_p$i));\n";
	print FH "  csl_signal s_m$i($val1);\n";
	print FH "  csl_signal s_n$i(br2);\n";
	print FH "  c$k c$k\_$one(.p_m$i({1{s_m$i,s_n$i}}));  // f2a : port---repl expr\n";
    }
#f2a : ifc---ifc
    elsif($i > 200 && $i <= 250) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  b$k b$k\_$one(.ifc$j\_$zero(ifc$j\_$one));  // f2a : ifc---ifc\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  c$k c$k\_$zero(.ifc$j\_$zero(ifc$j\_$one));\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    print FH "  d$k () {\n";
#connect_by_name : port---sig.ps (CP)
    if($i > 50 && $i <= 100) {
	print FH "    c$k\_$zero.b$k\_$one.a$k\_$zero.p_b$i.connect_by_name(s_b$i\[1\]);  // port---sig.ps (CP)\n";
    }
#connect_by_name : port---sig (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.p_x$i.connect_by_name(c$k\_$zero.b$k\_$zero.s_a$i);  // port---sig (PC)\n";
    }
#connect_by_name : ifc---ifc (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    ifc$j\_$one.connect_by_name(c$k\_$zero.b$k\_$zero.ifc$j\_$zero,pa$i);  // ifc---ifc (PC)\n";
    }
#connect_by_name : ifc---ifc (CP)
    elsif($i > 250 && $i <= 300) {
	print FH "    c$k\_$zero.b$k\_$one.a$k\_$zero.ifc$j\_$zero.connect_by_name(c$k\_$zero.b$k\_$one.ifc$j\_$two);  // ifc---ifc (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
