#!/usr/bin/perl

#oanab
#assign with part select

use strict;

print "Generated tests path : test/csl_test_gen/assign_part_sel_invalid1/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 300; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "assign_part_sel".$i."_illegal.csl";
   	&createCslFile($test_name, $i, %dir);
}

sub createCslFile {
    my ($test_name, $i, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(20)) + 2;
    my $val2 = int(rand(100)) + 3;
    my $val3 = int(rand(100)) + 4;
    my $l = int(rand(3))+1;
    my $m = $k + int(rand(10)) + 1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/assign_part_sel_valid");
        open(FH,">$path/assign_part_sel_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/assign_part_sel_invalid1"); 
        open(FH,">$path/assign_part_sel_invalid1/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges and fields
    print FH "csl_bitrange br1($val1);\n";
    print FH "csl_bitrange br2($val2);\n";
    print FH "csl_field f3($val3);\n";
    print FH "csl_bitrange br4(".($val2+$val3).");\n";
    print FH "csl_bitrange br5(".(2*$val1+$val2+$val3).");\n\n";

#ifck
    if($i <= 150) {
	print FH "csl_interface ifc$k {\n";
	print FH "  csl_port p_a$i(input,f3);\n";
	print FH "  csl_port p_b$i(output,$val2);\n";
	print FH "  csl_port p_c$i(output,br4);\n";
	print FH "  csl_port p_d$i(input,br1);\n";
	print FH "  ifc$k () {}\n";
	print FH "};\n\n";
    }

#ifcm
    if($i <= 150) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_x$i(input,f3);\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  ifc$k ifc$k\_$one;\n";
	print FH "  ifc$k ifc$k\_$two;\n";
	print FH "  ifc$m () {}\n";
	print FH "};\n\n";
    }

#sgk
    if($i <= 150 || $i > 200 && $i <= 300) {
	print FH "csl_signal_group sg$k {\n";
	print FH "  csl_signal s_a$i(br2);\n";
	print FH "  csl_signal s_b$i($val3);\n";
	print FH "  csl_signal s_c$i(br2);\n";
	print FH "  csl_signal s_d$i(br4);\n";
	print FH "  sg$k () {}\n";
	print FH "};\n\n";
    }

#sgm
    if($i <= 150 || $i > 250 && $i <= 300) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  csl_signal s_x$i(br2);\n";
	print FH "  csl_signal s_y$i(f3);\n";
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
	print FH "  sg$m () {}\n";
	print FH "};\n\n";
    }

#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  csl_signal s_x$i(".(1+$val3).");\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
	print FH "  ifc$m ifc$m\_$one;\n";
    }
    elsif($i > 150 && $i <= 250) {
	print FH "  csl_port p_x$i(input,br2);\n";
	print FH "  csl_port p_y$i(inout,br1);\n";
	print FH "  csl_port p_z$i(output,$val3);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_x$i(input,br2);\n";
	print FH "  csl_port p_y$i(inout,".($val1+1).");\n";
	print FH "  csl_port p_z$i(output,$val3);\n";
	print FH "  sg$k sg$k\_$zero;\n";
    }
    elsif($i > 250 && $i <= 300) { 
	print FH "  csl_port p_a$i(output,$val2);\n";
	print FH "  sg$m sg$m\_$zero;\n";
    }
    print FH "  a$k () {\n";
#Invalid assign between sig.ps and ifc.ifc
    if($i <= 50) {
	print FH "    s_x$i\[".$val3."\:".($val3-2)."\] = ifc$m\_$zero.ifc$k\_$one;   // Invalid assign between sig.ps and ifc.ifc\n";
    }
#Invalid assign between sg.sig.ps and sg
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$k\_$zero.s_c$i\[".$val2."\:".($val2-2)."\] = sg$k\_$one;   // Invalid assign between sg.sig.ps and sg\n";
    }
#Invalid assign between sg.sg.sig.ps and sg, sg.sg.sig.ps and ifc.ifc
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$m\_$zero.sg$k\_$one.s_d$i\[".($val2+$val3)."\:".$val2."\] = sg$k\_$one;   // Invalid assign between sg.sg.sig.ps and sg\n";
	print FH "    sg$m\_$zero.sg$k\_$zero.s_a$i\[".$val2."\-\:".(2)."\] = ifc$m\_$one.ifc$k\_$two;    // Invalid assign between sg.sg.sig.ps and ifc.ifc\n";
    }
#Invalid assign between sg.sig.ps and p-p
    elsif($i > 200 && $i <= 250) {
	print FH "    sg$k\_$zero.s_c$i\[3\] = p_z$i;   // Invalid assign between sg.sig.ps and p-p\n";
    }
#Invalid assign between sg.sg.sig.ps and p-p
    elsif($i > 250 && $i <= 300) { 
	print FH "    sg$m\_$zero.sg$k\_$zero.s_b$i\[".$val3."\:".($val3-2)."\] = p_a$i;   // Invalid assign between sg.sg.sig.ps and p-p\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit b
    print FH "csl_unit b$k {\n";
    print FH "  csl_signal s_a$i(br4);\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 50) {
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  ifc$m ifc$m\_$one;\n";
	print FH "  sg$k sg$k\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$one;\n";
	print FH "  sg$m sg$m\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$k sg$k\_$zero;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_port p_a$i(input,br2);\n";
	print FH "  csl_port p_b$i(inout,$val1);\n";
    }
    print FH "  b$k () {\n";
#Invalid assign between sig.ps and sg, sig.ps and ifc
    if($i <= 50) {
	print FH "    s_a$i\[".($val2+$val3)."\:".$val2."\] = sg$k\_$zero;    // Invalid assign between sig.ps and sg\n"; 
	print FH "    s_a$i\[".($val3)."\:".($val3-1)."\] = ifc$k\_$zero;    // Invalid assign between sig.ps and ifc\n";
    }
#Invalid assign between sg.sig.ps and ifc.ifc
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$k\_$zero.s_b$i\[".$val3."\:".($val3-3)."\] = ifc$m\_$one.ifc$k\_$two;    // Invalid assign between sg.sig.ps and ifc.ifc\n";
    }
#Invalid assign between sg.sg.sig.ps and sg.sg
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$m\_$one.sg$k\_$zero.s_c$i\[".$val2."\:".($val2-2)."\] = sg$m\_$zero.sg$k\_$zero;    // Invalid assign between sg.sg.sig.ps and sg.sg\n";
    }
#Invalid assign between sig.ps and p-c
    elsif($i > 150 && $i <= 200) {
	print FH "    s_a$i\[5\] = a$k\_$zero.p_x$i;    // assign between sig.ps and p-c\n";
	print FH "    s_a$i\[".($val2+$val3)."\-\:".$val2."\] = a$k\_$zero.p_y$i;    // assign between sig.ps and p-c\n";
    }
#Invalid assign between sg.sig.ps and p-c
    elsif($i > 200 && $i <= 250) {
	print FH "    sg$k\_$zero.s_b$i\[2\] = a$k\_$zero.p_x$i;   // assign between sg.sig.ps and p-c\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  sg$m sg$m\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  sg$m sg$m\_$one;\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$two;\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_port p_a$i(output,".($val3-1).");\n";
	print FH "  csl_signal s_a$i(br4);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$k sg$k\_$one;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$m sg$m\_$one;\n";
    }
    print FH "  c$k () {\n";
#Invalid assign between sig.ps and sg.sg
    if($i <= 50) {
	print FH "    b$k\_$zero.s_a$i\[".($val2+$val3)."\:".$val3."\] = sg$m\_$zero.sg$k\_$one;   // Invalid assign between sig.ps and sg.sg\n";
    }
#Invalid assign between sg.sig.ps and sg.sg, sg.sig.ps and ifc
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$k\_$zero.s_d$i\[".($val2+$val3)."\:".$val2."\] = sg$m\_$one.sg$k\_$one;   // Invalid assign between sg.sig.ps and sg.sg\n";
	print FH "    sg$k\_$zero.s_d$i\[".($val2+$val3)."\:".$val2."\] = ifc$k\_$zero;   // Invalid assign between sg.sig.ps and ifc\n";
    }
#Invalid assign between sg.sg.sig.ps and ifc
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$m\_$two.sg$k\_$one.s_d$i\[".($val2+$val3-5)."\:".$val2."\] = ifc$k\_$zero;    // Invalid assign between sg.sg.sig.ps and ifc\n";
    }
#Invalid assign between sig.ps and p-p
    elsif($i > 150 && $i <= 200) {
	print FH "    s_a$i\[".($val2+$val3)."\:".$val2."\] = p_a$i;    // Invalid assign between sig.ps and p-p\n";
    }
#Invalid assign between sg.sig.ps and p-c
    elsif($i > 200 && $i <= 250) {
	print FH "    sg$k\_$one.s_d$i\[".($val2+$val3-2)."\:".$val2."\] = b$k\_$zero.a$k\_$zero.p_y$i;   // Invalid assign between sg.sig.ps and p-c\n";
    }
#Invalid assign between sg.sg.sig.ps and p-c
    elsif($i > 250 && $i <= 300) {
	print FH "    sg$m\_$one.sg$k\_$zero.s_a$i\[1\] = b$k\_$zero.p_a$i;    // Invalid assign between sg.sg.sig.ps and p-c\n";
	print FH "    sg$m\_$one.sg$k\_$one.s_d$i\[".($val3)."\-\:".(3)."\] = b$k\_$zero.p_b$i;    // Invalid assign between sg.sg.sig.ps and p-c\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
