#!/usr/bin/perl

#Author Petronela
#modified by oanab
use strict;

my $path = "$ENV{WORK}/test/csl_test_gen/";
print "the path for the generated tests is : $path"."assign_part_select_sps_pps_valid/ \n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

my @lower = (0,3,10,23);
my @upper = (32,51,64,80);
for(my $i=1;$i <=3;++$i){
    foreach my $l(@lower) {
        foreach my $u(@upper) { 
            &main($i,$l,$u);
        }
    }
}

sub main {
    my ($i,$l,$u) = @_;
    my $test_name;
    $test_name = "assign_part_select_sps_pps".$i."_".$l."_".$u."_legal.csl";
    my $val1 = $u + int(rand(100)) + 1;
    my $w = $u - $l + 1;
    my $w1 = $w -1;
    my $val2 = $val1 + int(rand(100)) + 1;
    my $val3 = $val1 + int(rand(30)) + 1;
    my $val4 = $val1 + int(rand(30)) + 1;
    my $val5 = $val1 + int(rand(30)) + 1;
    &mkDir("$path/assign_part_select_sps_pps_valid");
    open(FH,">$path/assign_part_select_sps_pps_valid/$test_name");
    
    print FH "//Generated by Petronela\n";
    print FH "//part select used in assign sig[ps], sg[.+sg].sig[ps] with port[ps] parent input,child output,parent inout \n";
    print FH "//and port[ps] parent output,child input,parent inout with  sig[ps], sg[.+sg].sig[ps]\n\n";
    #print FH "csl_bitrange br($val1);\n";
    #print FH "csl_bitrange brt($val2);\n";
    #print FH "csl_filed f1($val1),f2($val5);\n";

    print FH "csl_signal_group sga {\n";
    print FH "  csl_signal s_sga$i($val1);\n";
    print FH "  csl_signal s_sgga($val2);\n";
    print FH "  csl_signal s_sa($w);\n";
    print FH "  csl_signal s_sgaa$i($w);\n";
    print FH "  sga() {\n";
    print FH "  }\n";
    print FH "};\n\n";

    print FH "csl_signal_group sgb {\n";
    print FH "  sga sga0;\n";
#    print FH "  sga sga1;\n";
    print FH "  csl_signal s_sgb$i($val1);\n";
    print FH "  csl_signal s_sggb($val2);\n";
    print FH "  csl_signal s_sb($w);\n";
    print FH "  csl_signal s_sgbb$i($w);\n";
    print FH "  sgb() {\n";
    print FH "  }\n";
    print FH "};\n\n";

    
    print FH "csl_unit a {\n";
    print FH "  csl_signal s_data($val1);\n"; 
    print FH "  csl_signal s_addr($val4);\n";
    print FH "  csl_port p_data1(input,$val1);\n";
    print FH "  csl_port p_addr1(output,$val2);\n"; 
    print FH "  csl_signal s_addr2($w);\n";
    print FH "  csl_signal s_data2($w);\n"; 
    print FH "  csl_port p_addr3(input,$val2);\n";
    print FH "  csl_port p_data3(output,$w);\n";
    
    print FH "  a() {\n";
    print FH "    s_data2 = p_data1[$u:$l];\n";
    print FH "    p_addr1[$u:$l] = s_data[$u:$l];\n";
    print FH "    s_addr[$u:$l] = p_addr3[$u:$l];\n";
    print FH "    p_data3 = s_addr2;\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";

    if($i >= 2 ){
        print FH "csl_unit f {\n";
        print FH "  csl_signal s_data($val1);\n"; 
        print FH "  csl_port p_addr(input,$val1);\n";
        print FH "  csl_signal s_data1($val1);\n";
        print FH "  csl_port p_d(output,$val1);\n";
        print FH "  f() {\n";  
        print FH "    s_data[$u:$l] = p_addr[$u:$l];\n";
        print FH "    p_d = s_data1;\n";
        print FH "  }\n";        
        print FH "};\n";        
        print FH "\n";
    }

    print FH "csl_unit b {\n"; 
    if($i < 2){
        print FH "  a a0(.p_data1(sga2.s_sga$i),.p_addr1(p_addr11),.p_addr3(p_data31),.p_data3(s_data21));\n";
	print FH "  csl_signal s_data21($w);\n";
	print FH "  csl_port p_addr11(output,$val2);\n";
	print FH "  csl_port p_data31(input,$val2);\n";
#        print FH "  sgb sgb1;\n";
	print FH "  sga sga2;\n";
    }
    else {
	print FH "  sgb sgb1;\n";
#        print FH "  sga sga2;\n";
        print FH "  f f0(.p_addr(sgb1.sga0.s_sga$i),.p_d(sgb1.s_sgb$i));\n";
        print FH "  a a0(.p_data1(sgb1.sga0.s_sga$i),.p_addr1(sgb1.sga0.s_sgga),.p_addr3(sgb1.s_sggb),.p_data3(sgb1.s_sb));\n";
        print FH "  a a1(.p_data1(sgb1.s_sgb$i),.p_addr1(sgb1.s_sggb),.p_addr3(sgb1.sga0.s_sgga),.p_data3(sgb1.sga0.s_sa));\n";
    }
    
    print FH "  b() {\n";
    if($i < 2){
	print FH "    s_data21 = p_addr11[$u:$l];\n";
	print FH "    sga2.s_sgaa$i = p_data31[$u:$l];\n";
	print FH "    sga2.s_sga$i\[".($val1-1)."\] = sga2.s_sgga\[".($val2-1)."\];\n";
	print FH "    sga2.s_sgaa$i = sga2.s_sa;\n";
    }
    else {
	print FH "    sgb1.sga0.s_sga$i = sgb1.s_sgb$i;\n";
	print FH "    sgb1.sga0.s_sgaa$i = sgb1.s_sgbb$i;\n";
	print FH "    sgb1.sga0.s_sa = sgb1.s_sb;\n";
    }
    
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";
    if($i < 2){
        print FH "  b b0(.p_addr11(sgb2.sga0.s_sgga),.p_data31(sgb2.s_sggb));\n";
#        print FH "  b b1;\n";
        print FH "  sgb sgb2;\n";
    }
    else {
        print FH "  b b0;\n";
        print FH "  a a2(.p_data1(sgb3.sga0.s_sga$i),.p_addr1(sgb3.sga0.s_sgga),.p_addr3(sgb3.s_sggb),.p_data3(sgb3.sga0.s_sa));\n";
	print FH "  csl_port p_data32(input,$val1);\n";
	print FH "  csl_port p_addr12(output,$val2);\n";
#        print FH "  sgb sgb2;\n";
        print FH "  sgb sgb3;\n";
    }
 
    print FH "  c() {\n";
    if($i < 2){
	print FH "    sgb2.sga0.s_sga$i = sgb2.s_sgb$i;\n";
	print FH "    sgb2.sga0.s_sgga = sgb2.s_sggb;\n";
	print FH "    sgb2.sga0.s_sgaa$i = sgb2.s_sgbb$i;\n";
	print FH "    sgb2.sga0.s_sa = sgb2.s_sb;\n";
    }
    else {
	print FH "    p_data32[$u:$l] = sgb3.s_sgb$i"."[$u:$l] ;\n"; 
	print FH "    p_addr12[$u:$l] = sgb3.s_sb;\n";
	print FH "    sgb3.sga0.s_sgaa$i = sgb3.s_sgbb$i;\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    if($i < 2){
        print FH "  c c0;\n";
        print FH "  c c1;\n";
	print FH "  csl_port p_addr13(output,$val1);\n";
	print FH "  csl_port p_data13(input,$val1);\n";
	print FH "  csl_signal s_data6($val2);\n"; 
	print FH "  sgb sgb4;\n";
    }
    else {
        print FH "  c c0(.p_data32(p_data13),.p_addr12(sgb5.sga0.s_sgga));\n";
#        print FH "  c c1;\n";
	print FH "  csl_port p_data13(input,$val1);\n";
	print FH "  csl_port p_addr13(output,$val1);\n";
	print FH "  sgb sgb5;\n";
    }
    
    print FH "  d() {\n";
    if($i < 2) {
        print FH "    sgb4.s_sggb[$u:$l] = p_addr13[$u:$l];\n";
        print FH "    p_data13[$u] = s_data6[$u];\n";
	print FH "    sgb4.sga0.s_sga$i = sgb4.s_sgb$i;\n";
	print FH "    sgb4.sga0.s_sgga = sgb4.s_sggb;\n";
	print FH "    sgb4.sga0.s_sgaa$i = sgb4.s_sgbb$i;\n";
	print FH "    sgb4.sga0.s_sa = sgb4.s_sb;\n";
       
    }
    else {
        print FH "    p_data13[$u:$l] = sgb5.sga0.s_sa;\n";
        print FH "    p_addr13[$u:$l] = sgb5.s_sgb$i"."[$u:$l];\n";
	print FH "    sgb5.sga0.s_sga$i = sgb5.s_sgb$i;\n";
	print FH "    sgb5.sga0.s_sgga = sgb5.s_sggb;\n";
	print FH "    sgb5.sga0.s_sgaa$i = sgb5.s_sgbb$i;\n";
	print FH "    sgb5.sga0.s_sa = sgb5.s_sb;\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";

    print FH "csl_unit e {\n";  
    if($i < 2){
        print FH "  d d0(.p_addr13(sgb3.sga0.s_sga$i),.p_data13(sgb3.s_sgb$i));\n";
        print FH "  d d1(.p_addr13(sgb3.sga0.s_sga$i),.p_data13(p_data34));\n";
	print FH "  csl_port p_data14(input,$val2);\n"; 
	print FH "  csl_signal s_data24($w);\n"; 
	print FH "  csl_port p_data34(input,$val1);\n";
	print FH "  sgb sgb3;\n";
    }
    else {
        print FH "  d d0(.p_addr13(s_data7),.p_data13(s_data7));\n";
#        print FH "  d d1;\n";
	print FH "  csl_port p_addr14(output,$val2);\n";
	print FH "  csl_signal s_data7($val1);\n"; 
	print FH "  csl_signal s_addr24($w);\n";   
    }
  
    print FH "  e() {\n";
    if($i < 2) {
        print FH "    p_data14[$u:$l] = sgb3.s_sggb[$u:$l];\n";
	print FH "    sgb3.sga0.s_sgaa$i = sgb3.s_sgbb$i;\n";
	print FH "    sgb3.sga0.s_sa = sgb3.s_sb;\n";
        print FH "    s_data24 = p_data34[$u:$l];\n";
	print FH "    sgb3.sga0.s_sgga = sgb3.s_sggb;\n";
    }
    else {
        print FH "    p_addr14[$l] = s_data7[$u];\n";
        print FH "    p_addr14[$u:$l] = s_addr24;\n";
    }
  
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    if($i < 2){
#        print FH "  d d0;\n";
        print FH "  e e0(.p_data14(s_data10),.p_data34(s_data8));\n"; 
        print FH "  e e1(.p_data14(s_data10),.p_data34(s_addr8));\n";
	print FH "  csl_signal s_data8($val1);\n"; 
	print FH "  csl_signal s_data10($val2);\n";
	print FH "  csl_signal s_addr25($w);\n";
	print FH "  csl_port p_addr15(output,$w);\n";  
	print FH "  csl_signal s_data25($w);\n"; 
	print FH "  csl_signal s_addr8($val1);\n"; 
	print FH "  csl_port p_data15(input,$w);\n";  
    }
    else {
	print FH "  e e0(.p_addr14(s_data10));\n"; 
#        print FH "  e e1;\n"; 
	print FH "  csl_signal s_data10($val2);\n";
	print FH "  csl_signal s_data8($val1);\n";
	print FH "  csl_port p_data35(input,$w);\n";
	print FH "  sga sga3;\n";
    }
   
    print FH "  top(){\n";
    if($i < 2) {
        print FH "    s_data8[$u:$l] = s_addr25;\n";
        print FH "    s_data8[$u:$l] = p_addr15;\n";
        print FH "    s_data25 = s_addr8[$u:$l];\n"; 
        print FH "   {s_data25,s_addr25}={p_data15,p_data25};\n";
    }
    else {
        print FH "    s_data8[$u:$l] = s_data8[$u:$l];\n";
        print FH "    p_data35[$w1] = sga3.s_sgga[$u];\n";
	print FH "    sga3.s_sga$i\[".($val1-1)."\] = sga3.s_sgga\[".($val2-1)."\];\n";
	print FH "    sga3.s_sgaa$i = sga3.s_sa;\n";
        
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}

