#!/usr/bin/perl

#Author Monica
use strict;

my $path = "$ENV{WORK}/test/csl_test_gen/";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}
for(my $i = 1;$i <= 40; $i++){
    &main($i);
}

sub main {
    my ($i) = @_;
    my $test_name;
   
    $test_name = "conn_unit_u_u".$i."_param_llegal.csl";
   
    &createCslFile($test_name, $i);
}
sub createCslFile {
    my($test_name, $i) = @_;
    
    my $val1 = int(rand(30)) + 1;
    my $val2 = int(rand(30)) + 1;
    my $val3 = int(rand(30)) + 1;
    my $val4 = int(rand(30)) + 1;
    my $val5 = int(rand(30)) + 1;
  
    &mkDir("$path/conn_units_u_u_param_valid");
    open(FH,">$path/conn_units_u_u_param_valid/$test_name");
    if($i == 1){ print "Generated path: $path/conn_units_u_u_param_valid/\n"; }


    print FH "//Generated by Monica\n";
    print FH "//testing the command connect_units for connections unit to unit with parameter --legal \n\n";

# parameter in interface without override  
    if($i > 0 && $i<=5){
        print FH "csl_interface ifca {\n";
        print FH "  csl_parameter w1($val1);\n";
        print FH "  csl_parameter w2($val2);\n";
        print FH "  csl_parameter w3($val3);\n";
        print FH "  csl_parameter w4($val4);\n";
        print FH "  csl_parameter w5($val5);\n";
        print FH "  csl_port p_ifc1(input,w1);\n";
        print FH "  csl_port p_ifc2(input,w2);\n";
        print FH "  csl_port p_ifc3(input,w3);\n";
        print FH "  csl_port p_ifc4(output,w4);\n";
        print FH "  csl_port p_ifc5(output,w5);\n";
        print FH "  ifca() {\n";
        print FH "  }\n";
        print FH "};\n\n";
        print FH "csl_interface ifcb {\n";
        print FH "  csl_port p_ifc1(output,$val1);\n";
        print FH "  csl_port p_ifc2(output,$val2);\n";
        print FH "  csl_port p_ifc3(output,$val3);\n";
        print FH "  csl_port p_ifc4(input,$val4);\n";
        print FH "  csl_port p_ifc5(input,$val5);\n";
        print FH "  ifcb() {\n";
        print FH "  }\n";
        print FH "};\n\n";
#connect c-p
        if($i <3){
        print FH " csl_unit unit_a {\n";
        print FH "   ifca ifcai;\n";
        print FH "   unit_a(){\n";
        print FH "  }\n";
        print FH "   };\n";
        print FH " csl_unit unit_b {\n";
        print FH "   ifca ifcai;\n";
        print FH "   unit_a a0;\n";
        print FH "   unit_b(){}\n";
        print FH "   };\n";
        print FH " csl_unit unit_top{\n";
        print FH "   unit_a a;\n";
        print FH "   unit_b b;\n";
        print FH "   unit_top(){\n";
        print FH "   b.connect_units(b.a0);\n";
        print FH "   }\n";
        print FH "};\n";
        }
#connect s-s
         if($i >=3 ){
        print FH " csl_unit unit_a {\n";
        print FH "   ifcb ifcai;\n";
        print FH "   unit_a(){\n";
        print FH " }\n";
        print FH "   };\n";
        print FH " csl_unit unit_b {\n";
        print FH "   ifca ifcai;\n";
        print FH "   unit_b(){\n";
        print FH "   }\n";
        print FH "   };\n";
        print FH " csl_unit unit_top{\n";
        print FH "   unit_a a;\n";
        print FH "   unit_b b;\n";
        print FH "   unit_top(){\n";
        print FH "   a.connect_units(b);\n";
        print FH "   }\n";
        print FH "};\n";
        }
    }
#parameter in signal_group without override

    if($i>5 && $i<=10){
        print FH "csl_signal_group sga {\n";
        print FH "  csl_signal s_sg1($val1);\n";
        print FH "  csl_signal s_sg2($val2);\n";
        print FH "  csl_signal s_sg3($val3);\n";
        print FH "  csl_signal s_sg4($val4);\n";
        print FH "  csl_signal s_sg5($val5);\n";
        print FH "  sga() {\n";
        print FH "  }\n";
        print FH "};\n\n";
        print FH "csl_signal_group sgb {\n";
        print FH "  csl_parameter w1($val1);\n";
        print FH "  csl_parameter w2($val2);\n";
        print FH "  csl_parameter w3($val3);\n";
        print FH "  csl_parameter w4($val4);\n";
        print FH "  csl_parameter w5($val5);\n";       
        print FH "  csl_signal s_sg1(w1);\n";
        print FH "  csl_signal s_sg2(w2);\n";
        print FH "  csl_signal s_sg3(w3);\n";
        print FH "  csl_signal s_sg4(w4);\n";
        print FH "  csl_signal s_sg5(w5);\n";
        print FH "  sgb() {\n";
        print FH "  }\n";
        print FH "};\n\n";
#connect p-c, c-p

        if($i<= 8){
    print FH "csl_unit unit_a {\n";
    print FH "  csl_parameter pa1($val2);\n";
    print FH "  csl_parameter pa2($val1);\n";
    print FH "  csl_parameter pa3(pa2);\n";
    print FH "  csl_port p_data(output,pa1);\n"; 
    print FH "  csl_port p_addr(output,pa2);\n";
    print FH "  csl_port p_data1(output,pa3);\n";
    print FH "  sga sgai;\n";
    print FH "  unit_a(){};\n";
    print FH "  };\n";
    print FH "csl_unit unit_b {\n";
    print FH "  csl_parameter pb1($val2);\n";
    print FH "  csl_parameter pb2($val1);\n";
    print FH "  csl_parameter pb3(pb2);\n";
    print FH "  csl_port p_data(output,pb1);\n"; 
    print FH "  csl_port p_addr(output,pb2);\n";
    print FH "  csl_port p_data1(output,pb3);\n";
    print FH "  sgb sgbi;\n";
    print FH "  unit_a a;\n";
    print FH "  unit_b(){};\n";
    print FH "  };\n";
    print FH "csl_unit unit_c {\n";
    print FH "  unit_b b1;\n";
    print FH "  unit_b b2;\n";
    print FH "  unit_c(){;\n";
    print FH "  b1.connect_units(b1.a);\n";
    print FH "  b2.a.connect_units(b2);\n";
    print FH "  }\n";
    print FH "  };\n";
    }
#connect p-c
    if($i>8){
    print FH "csl_unit unit_a {\n";
    print FH "  csl_parameter pa1($val2);\n";
    print FH "  csl_parameter pa2($val1);\n";
    print FH "  csl_parameter pa3(pa2);\n";
    print FH "  csl_port p_data(output,pa1);\n"; 
    print FH "  csl_port p_addr(output,pa2);\n";
    print FH "  csl_port p_data1(output,pa3);\n";
    print FH "  sga sgai;\n";
    print FH "  unit_a(){};\n";
    print FH "  };\n";
    print FH "csl_unit unit_b {\n";
    print FH "  csl_parameter pb1($val2);\n";
    print FH "  csl_parameter pb2($val1);\n";
    print FH "  csl_parameter pb3(pb2);\n";
    print FH "  csl_port p_data(output,pb1);\n"; 
    print FH "  csl_port p_addr(output,pb2);\n";
    print FH "  csl_port p_data1(output,pb3);\n";
    print FH "  sgb sgbi;\n";
    print FH " unit_a a0;\n";
    print FH "  unit_b(){};\n";
    print FH "  };\n";
    print FH " csl_unit unit_c{\n";
    print FH " unit_b b0;\n";
    print FH " unit_c (){}\n";
    print FH "};\n"; 
    print FH "csl_unit unit_d {\n";
    print FH "  unit_c c1;\n";
    print FH "  unit_d(){;\n";
    print FH "  c1.b0.connect_units(c1.b0.a0);\n";
    print FH "  }\n";
    print FH "  };\n";
    }
    }
#parameter with sg and ifc with override

    if($i>10 && $i<=15) {
       print FH "csl_interface ifca {\n";
        print FH "  csl_parameter w1(4'b0001);\n";
        print FH "  csl_parameter w2(2'b11);\n";
        print FH "  csl_parameter w3(4'hF);\n";
        print FH "  csl_parameter w4(8'hAA);\n";
        print FH "  csl_parameter w5(8'd30);\n";
        print FH "  csl_port p_ifc1(input,w1);\n";
        print FH "  csl_port p_ifc2(input,w2);\n";
        print FH "  csl_port p_ifc3(input,w3);\n";
        print FH "  csl_port p_ifc4(output,w4);\n";
        print FH "  csl_port p_ifc5(output,w5);\n";
        print FH "  ifca() {\n";
        print FH "  }\n";
        print FH "};\n\n";
        print FH "csl_signal_group sgb {\n";
        print FH "  csl_parameter w1($val5);\n";
        print FH "  csl_parameter w2($val4);\n";
        print FH "  csl_parameter w3($val3);\n";
        print FH "  csl_parameter w4($val2);\n";
        print FH "  csl_parameter w5($val1);\n";       
        print FH "  csl_signal s_sg1(w1);\n";
        print FH "  csl_signal s_sg2(w2);\n";
        print FH "  csl_signal s_sg3(w3);\n";
        print FH "  csl_signal s_sg4(w4);\n";
        print FH "  csl_signal s_sg5(w5);\n";
        print FH "  sgb() {\n";
        print FH "  }\n";
        print FH "};\n\n";
#connect c-p,p-c
    if($i <=13){
        print FH " csl_unit unit_a{\n";
        print FH "  ifca ifcai;\n";
        print FH "  sgb sgbi;\n";
        print FH "  unit_a(){}\n";
        print FH "};\n";
        print FH " csl_unit unit_b{\n";
        print FH "  csl_port p_ifc1(input,$val1);\n";
        print FH "  csl_port p_ifc2(input,$val2);\n";
        print FH "  csl_port p_ifc3(input,$val3);\n";
        print FH "  csl_port p_ifc4(output,$val4);\n";
        print FH "  csl_port p_ifc5(output,$val5);\n";
        print FH "  sgb sgbi;\n";
        print FH "  unit_a #($val1,$val2,$val3,$val4,$val5,$val1) a0;\n";
        print FH "  unit_b(){}\n";
        print FH "};\n";
        print FH " csl_unit unit_c{\n";
        print FH "  unit_b b0;\n";
        print FH "  unit_b b1;\n";
        print FH "  unit_c(){\n";
        print FH "  b0.connect_units(b0.a0);\n";
        print FH "  b1.a0.connect_units(b1);\n";
        print FH "  }\n";
        print FH "};\n";
    }
#connect sib-sib
       if($i >13){
        print FH " csl_unit unit_a{\n";
        print FH "  ifca ifcai;\n";
        print FH "  sgb sgbi;\n";
        print FH "  unit_a(){}\n";
        print FH "};\n";
        print FH " csl_unit unit_b{\n";
        print FH "  ifca ifcai;\n";
        print FH "  sgb sgbi;\n";
        print FH "  unit_b(){\n";
        print FH "  ifcai.reverse();\n";
        print FH "  }\n";
        print FH "};\n";
        print FH " csl_unit unit_c{\n";
        print FH "  unit_a ($val1,$val2) a;\n";
        print FH "  unit_b ($val1,$val2) b;\n";
        print FH "  unit_c(){\n";
        print FH "  a.connect_units(b);\n";
        print FH "  }\n";
        print FH "};\n";
    }
   }
# parameter used in csl_unit 
    if($i >15 && $i<=20){
        print FH "csl_unit unit_a {\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
        print FH "  csl_port p_data(output,p1);\n"; 
        print FH "  csl_port p_addr(output,p1);\n";
        print FH "  csl_port p_data1(output,p2);\n";
        print FH "  csl_signal s_data(p3);\n"; 
        print FH "  csl_signal s_addr(p3);\n";
        print FH "  csl_signal s_data1(p4);\n";
        print FH "  csl_signal s_addr1(p4);\n";
        print FH "  unit_a(){}\n";
        print FH "};\n";
        print FH "csl_unit unit_b {\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
        print FH "  csl_port p_data(output,p1);\n"; 
        print FH "  csl_port p_addr(output,p1);\n";
        print FH "  csl_port p_data1(output,p2);\n";
        print FH "  csl_signal s_data(p3);\n"; 
        print FH "  csl_signal s_addr(p3);\n";
        print FH "  csl_signal s_data1(p4);\n";
        print FH "  csl_signal s_addr1(p4);\n";
my $j;     
  foreach ($j =16; $j <= $i; $j++){
         print FH " unit_a #(.p4($val2)) a_$j;\n";
         }
        print FH "  unit_b(){}\n";
        print FH "};\n";
        
     
         print FH " csl_unit unit_top{\n";
          foreach ($j =16; $j <=$i; $j++){
         print FH " unit_a #(.p4($val2)) a_$j;\n";
         print FH " unit_b #(,,,$val2)  b_$j;\n";
            }       
        print FH " unit_top(){\n";
         foreach ( $j=16; $j <=$i; $j++){
             print FH " b_$j.connect_units(b_$j.a_$j);\n";
         }
        print FH "}\n";
        print FH "};\n";
    }
#parameter used in csl_unit s-s connection
   if($i >20 && $i<=30){
        print FH "csl_unit unit_a1 {\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
        print FH "  csl_port p_data(output,p1);\n"; 
        print FH "  csl_port p_addr(output,p1);\n";
        print FH "  csl_port p_data1(output,p2);\n";
        print FH "  csl_signal s_data(p3);\n"; 
        print FH "  csl_signal s_addr(p3);\n";
        print FH "  csl_signal s_data1(p4);\n";
        print FH "  csl_signal s_addr1(p4);\n";
        print FH "  unit_a1(){}\n";
        print FH "};\n";
        print FH "csl_unit unit_a2 {\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
        print FH "  csl_port p_data(input,p1);\n"; 
        print FH "  csl_port p_addr(input,p1);\n";
        print FH "  csl_port p_data1(input,p2);\n";
        print FH "  csl_signal s_data(p3);\n"; 
        print FH "  csl_signal s_addr(p3);\n";
        print FH "  csl_signal s_data1(p4);\n";
        print FH "  csl_signal s_addr1(p4);\n";
        print FH "  unit_a2(){}\n";
        print FH "};\n";
        print FH "csl_unit unit_b1 {\n";
        print FH " csl_parameter pb($val2);\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n"; 
my $j;     
  foreach ($j =21; $j <= $i; $j++){
         print FH " unit_a1 #(.p4($j)) a1_$j;\n";
         }
        print FH "  unit_b1(){}\n";
        print FH "};\n";
          print FH "csl_unit unit_b2 {\n";
        print FH " csl_parameter pb($val2);\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
     
  foreach ($j =21; $j <= $i; $j++){
         print FH " unit_a2 #(.p4($j)) a2_$j;\n";
         }
        print FH "  unit_b2(){}\n";
        print FH "};\n";
        
     
         print FH " csl_unit unit_top{\n";
          foreach ($j =21; $j <=$i; $j++){
         print FH " unit_b1 #(.p4($j)) b10_$j;\n";
         print FH " unit_b2 #(,,,$j)  b20_$j;\n";
            }       
        print FH " unit_top(){\n";
         foreach ( $j=21; $j <=$i; $j++){
             print FH " b10_$j.a1_$j.connect_units(b20_$j.a2_$j);\n";
         }
        print FH "}\n";
        print FH "};\n";
    } 
#parameter used in csl_unit s-s connection
   if($i >30 && $i<=40){
        print FH "csl_unit unit_a1 {\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
        print FH "  csl_port p_data(output,p1);\n"; 
        print FH "  csl_port p_addr(output,p1);\n";
        print FH "  csl_port p_data1(output,p2);\n";
        print FH "  csl_signal s_data(p3);\n"; 
        print FH "  csl_signal s_addr(p3);\n";
        print FH "  csl_signal s_data1(p4);\n";
        print FH "  csl_signal s_addr1(p4);\n";
        print FH "  unit_a1(){}\n";
        print FH "};\n";
        print FH "csl_unit unit_a2 {\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
        print FH "  csl_port p_data(input,p1);\n"; 
        print FH "  csl_port p_addr(input,p1);\n";
        print FH "  csl_port p_data1(input,p2);\n";
        print FH "  csl_signal s_addr(p3);\n";
        print FH "  csl_signal s_data1(p4);\n";
        print FH "  csl_signal s_addr1(p4);\n";
        print FH "  unit_a2(){}\n";
        print FH "};\n";
        print FH "csl_unit unit_b1 {\n";
        print FH " csl_parameter pb($val2);\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n"; 
my $j;     
  foreach ($j =31; $j <= $i; $j++){
         print FH " unit_a1  a1_$j;\n";
         }
        print FH "  unit_b1(){\n";
   foreach ($j =31; $j <= $i; $j++){
     print FH " a1_$j.override_parameter(p2,$j);\n";
   }
        print FH "  }\n";
        print FH "};\n";
        print FH "csl_unit unit_b2 {\n";
        print FH " csl_parameter pb($val2);\n";
        print FH "  csl_parameter p1($val1);\n"; 
        print FH "  csl_parameter p2(4'd5);\n";
        print FH "  csl_parameter p3($val2);\n";
        print FH "  csl_parameter p4(23);\n";
     
  foreach ($j =31; $j <= $i; $j++){
         print FH " unit_a2 a2_$j;\n";
         }
        print FH "  unit_b2(){\n";
  foreach ($j =31; $j <= $i; $j++){
     print FH " a2_$j.override_parameter(p2,$j);\n";
 }
        print FH "  }\n";
        print FH "};\n";
        
     
         print FH " csl_unit unit_top{\n";
          foreach ($j =31; $j <=$i; $j++){
         print FH " unit_b1  b10_$j;\n";
         print FH " unit_b2  b20_$j;\n";
            }       
        print FH " unit_top(){\n";
      foreach ($j =31; $j <= $i; $j++){
     print FH " b10_$j.override_parameter(p2,$j);\n";
     print FH " b20_$j.override_parameter(p2,$j);\n";
 }
         foreach ( $j=31; $j <=$i; $j++){
             print FH " b10_$j.a1_$j.connect_units(b20_$j.a2_$j);\n";
         }
        print FH "}\n";
        print FH "};\n";
    } 
    close(FH);
}

