#!/usr/bin/perl

#Author Petronela
use strict;

my $path = "$ENV{WORK}/test/csl_test_gen/";
print "the path for generated tests is: $path"."ifc_sgr_parameter_valid/ \n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

for(my $i = 1;$i <= 40; $i++){
    &main($i);
}

sub main {
    my $i = $_[0];
    my $test_name = "ifc_sgr_parameter_".$i."_legal.csl";
    &createCslFile($test_name, $i);
}

sub binar {
    my $val1 = int(rand(7)) + 2;
    my $val2 = 1;
    for(my $v = 1; $v < $val1; $v++){
        $val2 = $val2 * 10;
    }
    my $val3 = int(rand($val1)) - 1;
    my $val4 = 1;
    for(my $s = 2; $s < $val3; $s++){
        $val4 = $val4 * 10;
    }
    $val2 = $val2 + $val4;
    my @array=($val1,$val2);
    return @array;
}

sub deci{
    my $val1 = int(rand(70)) + 2;
    my $val2 = $val1;
    my $i = 0;
    while($val2 != 0){
        $val2 =int($val2 / 2);
        $i = $i + 1;
    }
    $i=$i+1;
    my @array=($val1,$i);
    return @array;
}

sub createCslFile {
    my($test_name, $i) = @_;
    my $val1 = int(rand(20)) + 1;
    my $val2 = $val1 + int(rand(20)) + 1;
    my $val3 = int(rand(30)) + 1;
    my $val4 = int(rand(50)) + 1;
    my $val5 = int(rand(80)) + 1;
    my $val27 = int(rand(100)) +1;
    my $val10 = int(rand(200)) + 1;
    my ($val6,$val7) = &binar; 
    my ($val8,$val9) = &binar;
    my ($val11,$val12) = &binar; 
    my ($val13,$val14) = &binar;
    my ($val15,$val16) = &binar;
    my ($val17,$val18) = &binar;
    my ($val19,$val20) = &binar;
    my ($val41,$val42) = &deci;
    my ($val43,$val44) = &deci;
    my ($val45,$val46) = &deci;
    my ($val47,$val48) = &deci;
    my ($val49,$val50) = &deci;
    my $val22 = int(rand(3)) + 2;
    my $val21 = sprintf("%.".$val22."o",$val5);
    $val22 = $val22 * 3;
    my $val23 = int(rand(3)) + 2;
    my $val24 = sprintf("%.".$val23."o",$val10);
    $val23 = $val23 * 3;
    my $val25 = int(rand(2)) + 2;
    my $val26 = sprintf("%.".$val25."o",$val27);
    $val25 = $val25 * 3;
    my $val32 = int(rand(3)) + 2;
    my $val31 = sprintf("%.".$val32."x",$val5);
    $val32 = $val32 * 4;
    my $val33 = int(rand(3)) + 2;
    my $val34 = sprintf("%.".$val33."x",$val10);
    $val33 = $val33 * 4;
    &mkDir("$path/ifc_sgr_parameter_valid/");
    open(FH,">$path/ifc_sgr_parameter_valid/$test_name");
    

    print FH "//Generated by Petronela\n";
    if($i <= 30) {
        print FH "//testing parameter in interfaces \n\n";
    }
    else {
        print FH "//testing parameter in interfaces and signal_group \n\n";
    }
    print FH "csl_interface ifca {\n";
    print FH "  csl_parameter ifa_x($val1);\n";
    print FH "  csl_parameter ifa_y($val3);\n";
    print FH "  csl_port p_ifca(input,ifa_x);\n";
    print FH "  csl_port p_ifa(input,ifa_y);\n";
    if($i > 5) {
        print FH "  csl_parameter ifa_z($val4);\n";
        print FH "  csl_parameter ifa_t($val5);\n";
        print FH "  csl_parameter ifa_s($val3);\n";
        print FH "  csl_port p_ifta(input,ifa_z);\n";
        print FH "  csl_port p_iftca(output,ifa_t);\n";
        print FH "  csl_port pt_ifa(output,ifa_s);\n";
    }
    print FH "  ifca() {\n";
    print FH "  }\n";        
    print FH "};\n\n";
    if($i > 15 && $i <= 30 || $i > 35) {
        print FH "csl_interface ifcd {\n";
        print FH "  csl_parameter ifcd_x($val6 \'b$val7);\n";
        print FH "  csl_parameter ifcd_y($val8 \'b$val9);\n";
        print FH "  csl_parameter ifcd_z($val11 \'b$val12);\n";
        print FH "  csl_parameter ifcd_t($val13 \'b$val14);\n";
        print FH "  csl_port p_ifcd(input,ifcd_x);\n";
        print FH "  csl_port p_ifd(output,ifcd_y);\n";
        print FH "  csl_port p_iftcd(output,ifcd_z);\n";
        print FH "  csl_port p_id(output,ifcd_t);\n";
        print FH "  ifcd() {\n";
        print FH "  }\n";        
        print FH "};\n\n"
    }
    print FH "csl_interface ifcb {\n";
    print FH "  csl_parameter ifb_x($val2);\n";
    print FH "  csl_parameter ifb_y($val5);\n";
    print FH "  csl_parameter ifb_z($val3);\n";
    print FH "  csl_port p_ifcb(input,ifb_x);\n";
    print FH "  csl_port p_ifb(input,ifb_y);\n";
    print FH "  csl_port pt_itb(output,ifb_z);\n";
    if($i > 10 ) {
        print FH "  csl_parameter ifcb_t($val4,$val2);\n";
        print FH "  csl_port p_icb(output,ifcb_t);\n";
    }
    if($i > 15 && $i <= 30) {
        print FH "  csl_parameter ifcb_v($val15 \'b$val16);\n";
        print FH "  csl_parameter ifcb_s($val17 \'b$val18);\n";
        print FH "  csl_port p_iftcb(input,ifcb_v);\n";
        print FH "  csl_port p_itcb(output,ifcb_s);\n";
        print FH "  csl_port p_ictb(input,ifcb_v);\n";
        print FH "  ifcd #($val15 'b$val16) ifcd0;\n";
        print FH "  ifcd #(,$val4,$val17 'b$val18,) ifcd1;\n";    
    }
    print FH "  ifca #(,$val5) ifca0;\n";
    print FH "  ifcb() {\n";
    print FH "  }\n";        
    print FH "};\n\n";
    
    if($i > 20 && $i <= 30 || $i > 35) {
        print FH "csl_interface ifce {\n";
        print FH "  csl_parameter ifce_x($val22 \'o$val21);\n";
        print FH "  csl_parameter ifce_y($val23 \'o$val24);\n";
        print FH "  csl_parameter ifce_z($val25 \'o$val26);\n";
        print FH "  csl_port p_ifce(input,ifce_x);\n";
        print FH "  csl_port p_ife(input,ifce_z);\n";
        print FH "  csl_port p_iftce(output,ifce_y);\n";
        if($i > 20 && $i <= 30){
            print FH "  ifcb #(,,,,$val25 \'o$val26) ifcb1;\n";
        }    
        if($i > 35){
            print FH "  ifcd #($val22 \'o$val21) ifcd0;\n";
        }
        print FH "  ifce() {}\n";        
        print FH "};\n\n"
    }
    if($i > 25 && $i <= 30){
        print FH "csl_interface ifcf {\n";
        print FH "  csl_parameter ifcf_x($val32 \'h$val31);\n";
        print FH "  csl_parameter ifcf_y($val33 \'h$val34);\n";
        print FH "  csl_parameter ifcf_z($val22 \'o$val21);\n";
        print FH "  csl_parameter ifcf_t($val5,$val1);\n";
        print FH "  csl_port p_ifcf(output,ifcf_z);\n";
        print FH "  csl_port p_iff(output,ifcf_y);\n";
        print FH "  csl_port p_ifc(output,ifcf_t);\n";
        print FH "  csl_port p_if(input,ifc_x);\n";
        print FH "  ifca #(.ifa_x($val32 \'h$val31),.ifa_t($val33 \'h$val34),.ifa_s($val22 \'o$val21)) ifca3;\n";
        print FH "  ifcf() {\n";
        print FH "  }\n";        
        print FH "};\n\n" ;   
    }
    if($i > 10 && $i <= 15){
        print FH "csl_interface ifcd {\n";
        print FH "  csl_parameter ifcd_x($val41,$val42);\n";
        print FH "  csl_parameter ifcd_y($val43,$val44);\n";
        print FH "  csl_parameter ifcd_z($val45,$val46);\n";
        print FH "  csl_parameter ifcd_t($val47,$val48);\n";
        print FH "  csl_port p_ifcd(input,ifcd_x);\n";
        print FH "  csl_port p_ifd(input,ifcd_y);\n";
        print FH "  csl_port p_iftcd(output,ifcd_z);\n";
        print FH "  csl_port p_id(output,ifcd_t);\n";
        print FH "  ifcd() {\n";
        print FH "  }\n";        
        print FH "};\n\n";
        print FH "csl_interface ifce {\n";
        print FH "  csl_parameter ifce_x($val49,$val50);\n";
        print FH "  csl_parameter ifce_y($val45,$val46);\n";
        print FH "  csl_parameter ifce_z($val41,$val42);\n";
        print FH "  csl_parameter ifce_t($val47,$val48);\n";
        print FH "  csl_parameter ifce_v($val43,$val44);\n";
        print FH "  csl_port p_ifce(input,ifce_x);\n";
        print FH "  csl_port p_ife(input,ifce_z);\n";
        print FH "  csl_port p_iftce(output,ifce_y);\n";
        print FH "  csl_port p_ie(output,ifce_t);\n";
        print FH "  csl_port p_itfe(output,ifce_v);\n";
        print FH "  ifcd #(.ifcd_x($val1)) ifcd1;\n";
        print FH "  ifcb #(,,,$val5) ifcb2;\n";
        print FH "  ifce() {\n";
        print FH "  }\n";        
        print FH "};\n\n";
    }
    if($i > 30) {     
        print FH "csl_unit b{\n";
        print FH "  csl_parameter b_x($val2);\n";
        print FH "  csl_parameter b_z($val1);\n";
        print FH "  csl_port p_b(input,b_x);\n";
        print FH "  csl_port pb(output,b_z);\n";
       
        print FH "  b(){}\n";
        print FH "};\n\n";          
        print FH "csl_signal_group sga{\n";
        print FH "  csl_parameter sga_x($val2);\n";
        print FH "  csl_parameter sga_y($val5);\n";
        print FH "  csl_parameter sga_z($val1);\n"; 
        print FH "  csl_signal s_sga(sga_z);\n";
        print FH "  csl_signal s_sg(sga_x);\n";
        print FH "  csl_signal s_sa(sga_y);\n";
        print FH "  sga(){}\n";
        print FH "};\n\n";
        
        print FH "csl_signal_group sgb{\n";
        print FH "  sga sga0;\n";
        print FH "  csl_parameter sgb_x($val43,$val44);\n";
        print FH "  csl_parameter sgb_y($val41,$val42);\n";
        print FH "  csl_parameter sgb_z($val49,$val50);\n"; 
        print FH "  csl_parameter sgb_t($val45,$val46);\n";
        print FH "  csl_signal s_sgb(sgb_z);\n";
        print FH "  csl_signal s_sg(sgb_x);\n";
        print FH "  csl_signal s_sb(sgb_y);\n";
        print FH "  csl_signal s_b(sgb_t);\n";    
        print FH "  sgb(){}\n";
        print FH "};\n\n";
    }
    if($i > 35) { 
       
        print FH "csl_signal_group sgc{\n";
        print FH "  csl_parameter sgc_x($val15 \'b$val16);\n";
        print FH "  csl_parameter sgc_y($val33 \'h$val34);\n";
        print FH "  csl_parameter sgc_z($val23 \'o$val24);\n"; 
        print FH "  csl_parameter sgc_t($val17 \'b$val18);\n";
        print FH "  csl_parameter sgc_s($val25 \'o$val26);\n";
        print FH "  csl_signal s_sgc(sgc_z);\n";
        print FH "  csl_signal s_c(sgc_y);\n";
        print FH "  csl_signal s_sc(sgc_x);\n";
        print FH "  csl_signal s_sgrc(sgc_t);\n";
        print FH "  csl_signal s_src(sgc_s);\n";
        print FH "  sgb sgb0;\n";
        print FH "  sgc(){}\n";
        print FH "};\n\n";
    }
    if($i > 5 && $i <= 15) {
        print FH "csl_unit a {\n";
        print FH "  csl_parameter a_x($val1);\n";
        print FH "  csl_parameter a_y($val3);\n";
        print FH "  csl_parameter a_z($val5);\n";
        print FH "  csl_port pa(input,a_x);\n";
        print FH "  csl_port p_a(input,a_y);\n";
        print FH "  csl_port pta(input,a_z);\n";
        print FH "  ifca #(.ifa_x($val5)) ifca4;\n";
        print FH "  a(){\n";
        print FH "  }\n";
        print FH "};\n\n";
    }
    if($i > 10 && $i <= 15){
        print FH "csl_unit b{\n";
        print FH "  csl_parameter b_x($val2);\n";
        print FH "  csl_parameter b_z($val1);\n";
        print FH "  csl_port p_b(input,b_x);\n";
        print FH "  csl_port pb(output,b_z);\n";
        print FH "  ifce #(.ifce_v($val2)) ifce2;\n";
        print FH "  b(){}\n";
        print FH "};\n\n";
    }
   
    print FH "csl_unit top {\n";
    print FH "  csl_parameter top_x($val2);\n";
    print FH "  csl_parameter top_y($val3);\n";
    print FH "  csl_port p_top(input,top_x);\n";
    print FH "  csl_signal s_top(top_y);\n";
    print FH "  ifca #(,$val2) ifca5;\n";
    print FH "  ifcb #(.ifb_x($val2),.ifb_y($val3)) ifcb0;\n";
    if($i > 5 && $i <= 15) {
        print FH "  a a0;\n";        
        print FH "  ifca #(,,$val1,$val3) ifca1;\n";
    }
    if($i > 10 && $i <= 15){
        print FH "  csl_parameter top_z($val2,$val3);\n";
        print FH "  csl_port pt_top(output,top_z);\n";
        print FH "  ifce ifce1;\n";    
        print FH "  b b0;\n";
        print FH "  ifcd #(.ifcd_z($val2)) ifcd2;\n";
    }
    if($i > 15 && $i <= 30) {
        print FH "  csl_signal st_top(top_y);\n";
        print FH "  ifcd #(.ifcd_z($val3)) ifcd2;\n";
    }
    if($i > 20 && $i <= 30) {
        print FH "  csl_parameter top_t($val23 \'o$val24);\n";
        print FH "  csl_parameter top_v($val2);\n";
        print FH "  csl_port ptop(input,top_t);\n";
        print FH "  csl_port pt_t(output,top_v);\n";
        print FH "  ifce #($val23 \'o$val24,,$val2) ifce0;\n";
    }
    if($i > 25 && $i <= 30) {
        print FH "  ifcf #(.ifcf_t($val4)) ifcf0;\n";
    }
    if($i > 30){
       
        print FH "  sgb #(,$val2,,$val5) sgb1;\n";
        print FH "  ifca #(.ifa_t($val2)) ifca2;\n";
        print FH "  ifcb #(,,,$val1) ifcb3;\n"; 
        print FH "  ifca #(.ifa_z($val5),.ifa_s($val4)) ifca3;\n";
        print FH " b b1;\n";
    }
    if($i > 35) {
        print FH "  sgc sgc0;\n";
        print FH "  ifcd #(.ifcd_x($val33 \'h$val34)) ifcd2;\n";
        print FH "  ifce #(,$val15 \'b$val16,$val17 \'b$val18) ifce1;\n";
        print FH "  ifcd #(,$val23 \'o$val24,,$val25 \'o$val26) ifcd3;\n";
    }
    print FH "  top(){\n";
    if($i > 10 && $i <= 15){
        print FH "    b0.override_parameter(b_x,$val2);\n";
        
    }
    if($i > 30){
        print FH "    b1.override_parameter(b_z,$val2);\n";
    }
    print FH "  }\n";
    print FH "};\n";
    close(FH);
}
