`ifndef INC_GUARD_ISA
`define INC_GUARD_ISA

`define IF_B1_UPPER_INDEX  (25)
`define IF_B1_LOWER_INDEX (27)
`define IF_B1_RANGE `IF_B1_UPPER_INDEX:`IF_B1_LOWER_INDEX

`define IF_C1_UPPER_INDEX  (25)
`define IF_C1_LOWER_INDEX (27)
`define IF_C1_RANGE `IF_C1_UPPER_INDEX:`IF_C1_LOWER_INDEX

`define IF_C10_UPPER_INDEX  (20)
`define IF_C10_LOWER_INDEX (21)
`define IF_C10_RANGE `IF_C10_UPPER_INDEX:`IF_C10_LOWER_INDEX

`define IF_C11_UPPER_INDEX  (0)
`define IF_C11_LOWER_INDEX (19)
`define IF_C11_RANGE `IF_C11_UPPER_INDEX:`IF_C11_LOWER_INDEX

`define IF_C12_UPPER_INDEX  (20)
`define IF_C12_LOWER_INDEX (21)
`define IF_C12_RANGE `IF_C12_UPPER_INDEX:`IF_C12_LOWER_INDEX

`define IF_C13_UPPER_INDEX  (25)
`define IF_C13_LOWER_INDEX (27)
`define IF_C13_RANGE `IF_C13_UPPER_INDEX:`IF_C13_LOWER_INDEX

`define IF_C14_UPPER_INDEX  (25)
`define IF_C14_LOWER_INDEX (27)
`define IF_C14_RANGE `IF_C14_UPPER_INDEX:`IF_C14_LOWER_INDEX

`define IF_C15_UPPER_INDEX  (5)
`define IF_C15_LOWER_INDEX (24)
`define IF_C15_RANGE `IF_C15_UPPER_INDEX:`IF_C15_LOWER_INDEX

`define IF_C16_UPPER_INDEX  (28)
`define IF_C16_LOWER_INDEX (31)
`define IF_C16_RANGE `IF_C16_UPPER_INDEX:`IF_C16_LOWER_INDEX

`define IF_C17_UPPER_INDEX  (27)
`define IF_C17_LOWER_INDEX (27)
`define IF_C17_RANGE `IF_C17_UPPER_INDEX:`IF_C17_LOWER_INDEX

`define IF_C18_UPPER_INDEX  (0)
`define IF_C18_LOWER_INDEX (26)
`define IF_C18_RANGE `IF_C18_UPPER_INDEX:`IF_C18_LOWER_INDEX

`define IF_C19_UPPER_INDEX  (25)
`define IF_C19_LOWER_INDEX (27)
`define IF_C19_RANGE `IF_C19_UPPER_INDEX:`IF_C19_LOWER_INDEX

`define IF_C2_UPPER_INDEX  (21)
`define IF_C2_LOWER_INDEX (24)
`define IF_C2_RANGE `IF_C2_UPPER_INDEX:`IF_C2_LOWER_INDEX

`define IF_C20_UPPER_INDEX  (0)
`define IF_C20_LOWER_INDEX (24)
`define IF_C20_RANGE `IF_C20_UPPER_INDEX:`IF_C20_LOWER_INDEX

`define IF_C21_UPPER_INDEX  (25)
`define IF_C21_LOWER_INDEX (27)
`define IF_C21_RANGE `IF_C21_UPPER_INDEX:`IF_C21_LOWER_INDEX

`define IF_C22_UPPER_INDEX  (25)
`define IF_C22_LOWER_INDEX (27)
`define IF_C22_RANGE `IF_C22_UPPER_INDEX:`IF_C22_LOWER_INDEX

`define IF_C23_UPPER_INDEX  (24)
`define IF_C23_LOWER_INDEX (27)
`define IF_C23_RANGE `IF_C23_UPPER_INDEX:`IF_C23_LOWER_INDEX

`define IF_C24_UPPER_INDEX  (24)
`define IF_C24_LOWER_INDEX (27)
`define IF_C24_RANGE `IF_C24_UPPER_INDEX:`IF_C24_LOWER_INDEX

`define IF_C25_UPPER_INDEX  (0)
`define IF_C25_LOWER_INDEX (23)
`define IF_C25_RANGE `IF_C25_UPPER_INDEX:`IF_C25_LOWER_INDEX

`define IF_C26_UPPER_INDEX  (5)
`define IF_C26_LOWER_INDEX (6)
`define IF_C26_RANGE `IF_C26_UPPER_INDEX:`IF_C26_LOWER_INDEX

`define IF_C3_UPPER_INDEX  (5)
`define IF_C3_LOWER_INDEX (19)
`define IF_C3_RANGE `IF_C3_UPPER_INDEX:`IF_C3_LOWER_INDEX

`define IF_C4_UPPER_INDEX  (0)
`define IF_C4_LOWER_INDEX (3)
`define IF_C4_RANGE `IF_C4_UPPER_INDEX:`IF_C4_LOWER_INDEX

`define IF_C5_UPPER_INDEX  (8)
`define IF_C5_LOWER_INDEX (19)
`define IF_C5_RANGE `IF_C5_UPPER_INDEX:`IF_C5_LOWER_INDEX

`define IF_C6_UPPER_INDEX  (8)
`define IF_C6_LOWER_INDEX (24)
`define IF_C6_RANGE `IF_C6_UPPER_INDEX:`IF_C6_LOWER_INDEX

`define IF_C7_UPPER_INDEX  (25)
`define IF_C7_LOWER_INDEX (27)
`define IF_C7_RANGE `IF_C7_UPPER_INDEX:`IF_C7_LOWER_INDEX

`define IF_C8_UPPER_INDEX  (23)
`define IF_C8_LOWER_INDEX (24)
`define IF_C8_RANGE `IF_C8_UPPER_INDEX:`IF_C8_LOWER_INDEX

`define IF_C9_UPPER_INDEX  (22)
`define IF_C9_LOWER_INDEX (22)
`define IF_C9_RANGE `IF_C9_UPPER_INDEX:`IF_C9_LOWER_INDEX

`define IF_COND_UPPER_INDEX  (28)
`define IF_COND_LOWER_INDEX (31)
`define IF_COND_RANGE `IF_COND_UPPER_INDEX:`IF_COND_LOWER_INDEX

`define IF_CPNUM_UPPER_INDEX  (8)
`define IF_CPNUM_LOWER_INDEX (11)
`define IF_CPNUM_RANGE `IF_CPNUM_UPPER_INDEX:`IF_CPNUM_LOWER_INDEX

`define IF_CRD_UPPER_INDEX  (12)
`define IF_CRD_LOWER_INDEX (15)
`define IF_CRD_RANGE `IF_CRD_UPPER_INDEX:`IF_CRD_LOWER_INDEX

`define IF_CRM_UPPER_INDEX  (0)
`define IF_CRM_LOWER_INDEX (3)
`define IF_CRM_RANGE `IF_CRM_UPPER_INDEX:`IF_CRM_LOWER_INDEX

`define IF_CRN_UPPER_INDEX  (16)
`define IF_CRN_LOWER_INDEX (19)
`define IF_CRN_RANGE `IF_CRN_UPPER_INDEX:`IF_CRN_LOWER_INDEX

`define IF_H_UPPER_INDEX  (24)
`define IF_H_LOWER_INDEX (24)
`define IF_H_RANGE `IF_H_UPPER_INDEX:`IF_H_LOWER_INDEX

`define IF_IMMEDIATE_UPPER_INDEX  (0)
`define IF_IMMEDIATE_LOWER_INDEX (7)
`define IF_IMMEDIATE_RANGE `IF_IMMEDIATE_UPPER_INDEX:`IF_IMMEDIATE_LOWER_INDEX

`define IF_IMMEDIATE2_UPPER_INDEX  (0)
`define IF_IMMEDIATE2_LOWER_INDEX (11)
`define IF_IMMEDIATE2_RANGE `IF_IMMEDIATE2_UPPER_INDEX:`IF_IMMEDIATE2_LOWER_INDEX

`define IF_L_UPPER_INDEX  (24)
`define IF_L_LOWER_INDEX (24)
`define IF_L_RANGE `IF_L_UPPER_INDEX:`IF_L_LOWER_INDEX

`define IF_LU_UPPER_INDEX  (20)
`define IF_LU_LOWER_INDEX (20)
`define IF_LU_RANGE `IF_LU_UPPER_INDEX:`IF_LU_LOWER_INDEX

`define IF_MASK_UPPER_INDEX  (16)
`define IF_MASK_LOWER_INDEX (19)
`define IF_MASK_RANGE `IF_MASK_UPPER_INDEX:`IF_MASK_LOWER_INDEX

`define IF_N_UPPER_INDEX  (22)
`define IF_N_LOWER_INDEX (22)
`define IF_N_RANGE `IF_N_UPPER_INDEX:`IF_N_LOWER_INDEX

`define IF_O_UPPER_INDEX  (4)
`define IF_O_LOWER_INDEX (4)
`define IF_O_RANGE `IF_O_UPPER_INDEX:`IF_O_LOWER_INDEX

`define IF_OFFS24_UPPER_INDEX  (0)
`define IF_OFFS24_LOWER_INDEX (23)
`define IF_OFFS24_RANGE `IF_OFFS24_UPPER_INDEX:`IF_OFFS24_LOWER_INDEX

`define IF_OFFS8_UPPER_INDEX  (0)
`define IF_OFFS8_LOWER_INDEX (7)
`define IF_OFFS8_RANGE `IF_OFFS8_UPPER_INDEX:`IF_OFFS8_LOWER_INDEX

`define IF_OPCODE_UPPER_INDEX  (21)
`define IF_OPCODE_LOWER_INDEX (24)
`define IF_OPCODE_RANGE `IF_OPCODE_UPPER_INDEX:`IF_OPCODE_LOWER_INDEX

`define IF_OPCODE1_UPPER_INDEX  (20)
`define IF_OPCODE1_LOWER_INDEX (23)
`define IF_OPCODE1_RANGE `IF_OPCODE1_UPPER_INDEX:`IF_OPCODE1_LOWER_INDEX

`define IF_OPCODE2_UPPER_INDEX  (5)
`define IF_OPCODE2_LOWER_INDEX (7)
`define IF_OPCODE2_RANGE `IF_OPCODE2_UPPER_INDEX:`IF_OPCODE2_LOWER_INDEX

`define IF_OPCODE12_UPPER_INDEX  (21)
`define IF_OPCODE12_LOWER_INDEX (23)
`define IF_OPCODE12_RANGE `IF_OPCODE12_UPPER_INDEX:`IF_OPCODE12_LOWER_INDEX

`define IF_OUP_UPPER_INDEX  (7)
`define IF_OUP_LOWER_INDEX (7)
`define IF_OUP_RANGE `IF_OUP_UPPER_INDEX:`IF_OUP_LOWER_INDEX

`define IF_P_UPPER_INDEX  (24)
`define IF_P_LOWER_INDEX (24)
`define IF_P_RANGE `IF_P_UPPER_INDEX:`IF_P_LOWER_INDEX

`define IF_R_UPPER_INDEX  (22)
`define IF_R_LOWER_INDEX (22)
`define IF_R_RANGE `IF_R_UPPER_INDEX:`IF_R_LOWER_INDEX

`define IF_RD1_UPPER_INDEX  (12)
`define IF_RD1_LOWER_INDEX (15)
`define IF_RD1_RANGE `IF_RD1_UPPER_INDEX:`IF_RD1_LOWER_INDEX

`define IF_RLIST_UPPER_INDEX  (0)
`define IF_RLIST_LOWER_INDEX (15)
`define IF_RLIST_RANGE `IF_RLIST_UPPER_INDEX:`IF_RLIST_LOWER_INDEX

`define IF_RM_UPPER_INDEX  (0)
`define IF_RM_LOWER_INDEX (3)
`define IF_RM_RANGE `IF_RM_UPPER_INDEX:`IF_RM_LOWER_INDEX

`define IF_RN_UPPER_INDEX  (16)
`define IF_RN_LOWER_INDEX (19)
`define IF_RN_RANGE `IF_RN_UPPER_INDEX:`IF_RN_LOWER_INDEX

`define IF_ROTATE_UPPER_INDEX  (8)
`define IF_ROTATE_LOWER_INDEX (11)
`define IF_ROTATE_RANGE `IF_ROTATE_UPPER_INDEX:`IF_ROTATE_LOWER_INDEX

`define IF_RS_UPPER_INDEX  (8)
`define IF_RS_LOWER_INDEX (11)
`define IF_RS_RANGE `IF_RS_UPPER_INDEX:`IF_RS_LOWER_INDEX

`define IF_S1_UPPER_INDEX  (20)
`define IF_S1_LOWER_INDEX (20)
`define IF_S1_RANGE `IF_S1_UPPER_INDEX:`IF_S1_LOWER_INDEX

`define IF_SBO_UPPER_INDEX  (12)
`define IF_SBO_LOWER_INDEX (15)
`define IF_SBO_RANGE `IF_SBO_UPPER_INDEX:`IF_SBO_LOWER_INDEX

`define IF_SH_UPPER_INDEX  (5)
`define IF_SH_LOWER_INDEX (6)
`define IF_SH_RANGE `IF_SH_UPPER_INDEX:`IF_SH_LOWER_INDEX

`define IF_SHAM_UPPER_INDEX  (7)
`define IF_SHAM_LOWER_INDEX (11)
`define IF_SHAM_RANGE `IF_SHAM_UPPER_INDEX:`IF_SHAM_LOWER_INDEX

`define IF_SUP_UPPER_INDEX  (22)
`define IF_SUP_LOWER_INDEX (22)
`define IF_SUP_RANGE `IF_SUP_UPPER_INDEX:`IF_SUP_LOWER_INDEX

`define IF_SWIN_UPPER_INDEX  (0)
`define IF_SWIN_LOWER_INDEX (23)
`define IF_SWIN_RANGE `IF_SWIN_UPPER_INDEX:`IF_SWIN_LOWER_INDEX

`define IF_U_UPPER_INDEX  (23)
`define IF_U_LOWER_INDEX (23)
`define IF_U_RANGE `IF_U_UPPER_INDEX:`IF_U_LOWER_INDEX

`define IF_W_UPPER_INDEX  (21)
`define IF_W_LOWER_INDEX (21)
`define IF_W_RANGE `IF_W_UPPER_INDEX:`IF_W_LOWER_INDEX

`define IF_Z_UPPER_INDEX  (4)
`define IF_Z_LOWER_INDEX (4)
`define IF_Z_RANGE `IF_Z_UPPER_INDEX:`IF_Z_LOWER_INDEX

`define IF_ZM_UPPER_INDEX  (7)
`define IF_ZM_LOWER_INDEX (7)
`define IF_ZM_RANGE `IF_ZM_UPPER_INDEX:`IF_ZM_LOWER_INDEX

`define IF_ZUP_UPPER_INDEX  (20)
`define IF_ZUP_LOWER_INDEX (20)
`define IF_ZUP_RANGE `IF_ZUP_UPPER_INDEX:`IF_ZUP_LOWER_INDEX

`define IE_ROOT_UPPER_INDEX (32-1)
`define IE_ROOT_LOWER_INDEX (0)
`define IE_ROOT_WIDTH (32)
`define IE_ROOT_RANGE `IE_ROOT_UPPER_INDEX:`IE_ROOT_LOWER_INDEX
`define IE_BASEFORMAT_UPPER_INDEX (32-1)
`define IE_BASEFORMAT_LOWER_INDEX (0)
`define IE_BASEFORMAT_WIDTH (32)
`define IE_BASEFORMAT_RANGE `IE_BASEFORMAT_UPPER_INDEX:`IE_BASEFORMAT_LOWER_INDEX
`define IE_FORMAT1_UPPER_INDEX (32-1)
`define IE_FORMAT1_LOWER_INDEX (0)
`define IE_FORMAT1_WIDTH (32)
`define IE_FORMAT1_RANGE `IE_FORMAT1_UPPER_INDEX:`IE_FORMAT1_LOWER_INDEX
`define IE_FORMAT1_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT1_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT1_IF_COND0_RANGE `IE_FORMAT1_IF_COND0_UPPER_INDEX:`IE_FORMAT1_IF_COND0_LOWER_INDEX

`define IE_FORMAT1_IF_C10_UPPER_INDEX  (25)
`define IE_FORMAT1_IF_C10_LOWER_INDEX (27)
`define IE_FORMAT1_IF_C10_RANGE `IE_FORMAT1_IF_C10_UPPER_INDEX:`IE_FORMAT1_IF_C10_LOWER_INDEX

`define IE_FORMAT1_IF_OPCODE0_UPPER_INDEX  (21)
`define IE_FORMAT1_IF_OPCODE0_LOWER_INDEX (24)
`define IE_FORMAT1_IF_OPCODE0_RANGE `IE_FORMAT1_IF_OPCODE0_UPPER_INDEX:`IE_FORMAT1_IF_OPCODE0_LOWER_INDEX

`define IE_FORMAT1_IF_S10_UPPER_INDEX  (20)
`define IE_FORMAT1_IF_S10_LOWER_INDEX (20)
`define IE_FORMAT1_IF_S10_RANGE `IE_FORMAT1_IF_S10_UPPER_INDEX:`IE_FORMAT1_IF_S10_LOWER_INDEX

`define IE_FORMAT1_IF_RN0_UPPER_INDEX  (16)
`define IE_FORMAT1_IF_RN0_LOWER_INDEX (19)
`define IE_FORMAT1_IF_RN0_RANGE `IE_FORMAT1_IF_RN0_UPPER_INDEX:`IE_FORMAT1_IF_RN0_LOWER_INDEX

`define IE_FORMAT1_IF_RD10_UPPER_INDEX  (12)
`define IE_FORMAT1_IF_RD10_LOWER_INDEX (15)
`define IE_FORMAT1_IF_RD10_RANGE `IE_FORMAT1_IF_RD10_UPPER_INDEX:`IE_FORMAT1_IF_RD10_LOWER_INDEX

`define IE_FORMAT1_IF_SHAM0_UPPER_INDEX  (7)
`define IE_FORMAT1_IF_SHAM0_LOWER_INDEX (11)
`define IE_FORMAT1_IF_SHAM0_RANGE `IE_FORMAT1_IF_SHAM0_UPPER_INDEX:`IE_FORMAT1_IF_SHAM0_LOWER_INDEX

`define IE_FORMAT1_IF_SH0_UPPER_INDEX  (5)
`define IE_FORMAT1_IF_SH0_LOWER_INDEX (6)
`define IE_FORMAT1_IF_SH0_RANGE `IE_FORMAT1_IF_SH0_UPPER_INDEX:`IE_FORMAT1_IF_SH0_LOWER_INDEX

`define IE_FORMAT1_IF_Z0_UPPER_INDEX  (4)
`define IE_FORMAT1_IF_Z0_LOWER_INDEX (4)
`define IE_FORMAT1_IF_Z0_RANGE `IE_FORMAT1_IF_Z0_UPPER_INDEX:`IE_FORMAT1_IF_Z0_LOWER_INDEX

`define IE_FORMAT1_IF_RM0_UPPER_INDEX  (0)
`define IE_FORMAT1_IF_RM0_LOWER_INDEX (3)
`define IE_FORMAT1_IF_RM0_RANGE `IE_FORMAT1_IF_RM0_UPPER_INDEX:`IE_FORMAT1_IF_RM0_LOWER_INDEX

`define IE_FORMAT10_UPPER_INDEX (32-1)
`define IE_FORMAT10_LOWER_INDEX (0)
`define IE_FORMAT10_WIDTH (32)
`define IE_FORMAT10_RANGE `IE_FORMAT10_UPPER_INDEX:`IE_FORMAT10_LOWER_INDEX
`define IE_FORMAT10_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT10_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT10_IF_COND0_RANGE `IE_FORMAT10_IF_COND0_UPPER_INDEX:`IE_FORMAT10_IF_COND0_LOWER_INDEX

`define IE_FORMAT10_IF_C140_UPPER_INDEX  (25)
`define IE_FORMAT10_IF_C140_LOWER_INDEX (27)
`define IE_FORMAT10_IF_C140_RANGE `IE_FORMAT10_IF_C140_UPPER_INDEX:`IE_FORMAT10_IF_C140_LOWER_INDEX

`define IE_FORMAT10_IF_P0_UPPER_INDEX  (24)
`define IE_FORMAT10_IF_P0_LOWER_INDEX (24)
`define IE_FORMAT10_IF_P0_RANGE `IE_FORMAT10_IF_P0_UPPER_INDEX:`IE_FORMAT10_IF_P0_LOWER_INDEX

`define IE_FORMAT10_IF_U0_UPPER_INDEX  (23)
`define IE_FORMAT10_IF_U0_LOWER_INDEX (23)
`define IE_FORMAT10_IF_U0_RANGE `IE_FORMAT10_IF_U0_UPPER_INDEX:`IE_FORMAT10_IF_U0_LOWER_INDEX

`define IE_FORMAT10_IF_B10_UPPER_INDEX  (25)
`define IE_FORMAT10_IF_B10_LOWER_INDEX (27)
`define IE_FORMAT10_IF_B10_RANGE `IE_FORMAT10_IF_B10_UPPER_INDEX:`IE_FORMAT10_IF_B10_LOWER_INDEX

`define IE_FORMAT10_IF_W0_UPPER_INDEX  (21)
`define IE_FORMAT10_IF_W0_LOWER_INDEX (21)
`define IE_FORMAT10_IF_W0_RANGE `IE_FORMAT10_IF_W0_UPPER_INDEX:`IE_FORMAT10_IF_W0_LOWER_INDEX

`define IE_FORMAT10_IF_LU0_UPPER_INDEX  (20)
`define IE_FORMAT10_IF_LU0_LOWER_INDEX (20)
`define IE_FORMAT10_IF_LU0_RANGE `IE_FORMAT10_IF_LU0_UPPER_INDEX:`IE_FORMAT10_IF_LU0_LOWER_INDEX

`define IE_FORMAT10_IF_RN0_UPPER_INDEX  (16)
`define IE_FORMAT10_IF_RN0_LOWER_INDEX (19)
`define IE_FORMAT10_IF_RN0_RANGE `IE_FORMAT10_IF_RN0_UPPER_INDEX:`IE_FORMAT10_IF_RN0_LOWER_INDEX

`define IE_FORMAT10_IF_RD10_UPPER_INDEX  (12)
`define IE_FORMAT10_IF_RD10_LOWER_INDEX (15)
`define IE_FORMAT10_IF_RD10_RANGE `IE_FORMAT10_IF_RD10_UPPER_INDEX:`IE_FORMAT10_IF_RD10_LOWER_INDEX

`define IE_FORMAT10_IF_SHAM0_UPPER_INDEX  (7)
`define IE_FORMAT10_IF_SHAM0_LOWER_INDEX (11)
`define IE_FORMAT10_IF_SHAM0_RANGE `IE_FORMAT10_IF_SHAM0_UPPER_INDEX:`IE_FORMAT10_IF_SHAM0_LOWER_INDEX

`define IE_FORMAT10_IF_SH0_UPPER_INDEX  (5)
`define IE_FORMAT10_IF_SH0_LOWER_INDEX (6)
`define IE_FORMAT10_IF_SH0_RANGE `IE_FORMAT10_IF_SH0_UPPER_INDEX:`IE_FORMAT10_IF_SH0_LOWER_INDEX

`define IE_FORMAT10_IF_Z0_UPPER_INDEX  (4)
`define IE_FORMAT10_IF_Z0_LOWER_INDEX (4)
`define IE_FORMAT10_IF_Z0_RANGE `IE_FORMAT10_IF_Z0_UPPER_INDEX:`IE_FORMAT10_IF_Z0_LOWER_INDEX

`define IE_FORMAT10_IF_RM0_UPPER_INDEX  (0)
`define IE_FORMAT10_IF_RM0_LOWER_INDEX (3)
`define IE_FORMAT10_IF_RM0_RANGE `IE_FORMAT10_IF_RM0_UPPER_INDEX:`IE_FORMAT10_IF_RM0_LOWER_INDEX

`define IE_FORMAT11_UPPER_INDEX (32-1)
`define IE_FORMAT11_LOWER_INDEX (0)
`define IE_FORMAT11_WIDTH (32)
`define IE_FORMAT11_RANGE `IE_FORMAT11_UPPER_INDEX:`IE_FORMAT11_LOWER_INDEX
`define IE_FORMAT11_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT11_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT11_IF_COND0_RANGE `IE_FORMAT11_IF_COND0_UPPER_INDEX:`IE_FORMAT11_IF_COND0_LOWER_INDEX

`define IE_FORMAT11_IF_C140_UPPER_INDEX  (25)
`define IE_FORMAT11_IF_C140_LOWER_INDEX (27)
`define IE_FORMAT11_IF_C140_RANGE `IE_FORMAT11_IF_C140_UPPER_INDEX:`IE_FORMAT11_IF_C140_LOWER_INDEX

`define IE_FORMAT11_IF_C150_UPPER_INDEX  (5)
`define IE_FORMAT11_IF_C150_LOWER_INDEX (24)
`define IE_FORMAT11_IF_C150_RANGE `IE_FORMAT11_IF_C150_UPPER_INDEX:`IE_FORMAT11_IF_C150_LOWER_INDEX

`define IE_FORMAT11_IF_O0_UPPER_INDEX  (4)
`define IE_FORMAT11_IF_O0_LOWER_INDEX (4)
`define IE_FORMAT11_IF_O0_RANGE `IE_FORMAT11_IF_O0_UPPER_INDEX:`IE_FORMAT11_IF_O0_LOWER_INDEX

`define IE_FORMAT11_IF_C40_UPPER_INDEX  (0)
`define IE_FORMAT11_IF_C40_LOWER_INDEX (3)
`define IE_FORMAT11_IF_C40_RANGE `IE_FORMAT11_IF_C40_UPPER_INDEX:`IE_FORMAT11_IF_C40_LOWER_INDEX

`define IE_FORMAT12_UPPER_INDEX (32-1)
`define IE_FORMAT12_LOWER_INDEX (0)
`define IE_FORMAT12_WIDTH (32)
`define IE_FORMAT12_RANGE `IE_FORMAT12_UPPER_INDEX:`IE_FORMAT12_LOWER_INDEX
`define IE_FORMAT12_IF_C160_UPPER_INDEX  (28)
`define IE_FORMAT12_IF_C160_LOWER_INDEX (31)
`define IE_FORMAT12_IF_C160_RANGE `IE_FORMAT12_IF_C160_UPPER_INDEX:`IE_FORMAT12_IF_C160_LOWER_INDEX

`define IE_FORMAT12_IF_C170_UPPER_INDEX  (27)
`define IE_FORMAT12_IF_C170_LOWER_INDEX (27)
`define IE_FORMAT12_IF_C170_RANGE `IE_FORMAT12_IF_C170_UPPER_INDEX:`IE_FORMAT12_IF_C170_LOWER_INDEX

`define IE_FORMAT12_IF_C180_UPPER_INDEX  (0)
`define IE_FORMAT12_IF_C180_LOWER_INDEX (26)
`define IE_FORMAT12_IF_C180_RANGE `IE_FORMAT12_IF_C180_UPPER_INDEX:`IE_FORMAT12_IF_C180_LOWER_INDEX

`define IE_FORMAT13_UPPER_INDEX (32-1)
`define IE_FORMAT13_LOWER_INDEX (0)
`define IE_FORMAT13_WIDTH (32)
`define IE_FORMAT13_RANGE `IE_FORMAT13_UPPER_INDEX:`IE_FORMAT13_LOWER_INDEX
`define IE_FORMAT13_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT13_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT13_IF_COND0_RANGE `IE_FORMAT13_IF_COND0_UPPER_INDEX:`IE_FORMAT13_IF_COND0_LOWER_INDEX

`define IE_FORMAT13_IF_C190_UPPER_INDEX  (25)
`define IE_FORMAT13_IF_C190_LOWER_INDEX (27)
`define IE_FORMAT13_IF_C190_RANGE `IE_FORMAT13_IF_C190_UPPER_INDEX:`IE_FORMAT13_IF_C190_LOWER_INDEX

`define IE_FORMAT13_IF_P0_UPPER_INDEX  (24)
`define IE_FORMAT13_IF_P0_LOWER_INDEX (24)
`define IE_FORMAT13_IF_P0_RANGE `IE_FORMAT13_IF_P0_UPPER_INDEX:`IE_FORMAT13_IF_P0_LOWER_INDEX

`define IE_FORMAT13_IF_U0_UPPER_INDEX  (23)
`define IE_FORMAT13_IF_U0_LOWER_INDEX (23)
`define IE_FORMAT13_IF_U0_RANGE `IE_FORMAT13_IF_U0_UPPER_INDEX:`IE_FORMAT13_IF_U0_LOWER_INDEX

`define IE_FORMAT13_IF_SUP0_UPPER_INDEX  (22)
`define IE_FORMAT13_IF_SUP0_LOWER_INDEX (22)
`define IE_FORMAT13_IF_SUP0_RANGE `IE_FORMAT13_IF_SUP0_UPPER_INDEX:`IE_FORMAT13_IF_SUP0_LOWER_INDEX

`define IE_FORMAT13_IF_W0_UPPER_INDEX  (21)
`define IE_FORMAT13_IF_W0_LOWER_INDEX (21)
`define IE_FORMAT13_IF_W0_RANGE `IE_FORMAT13_IF_W0_UPPER_INDEX:`IE_FORMAT13_IF_W0_LOWER_INDEX

`define IE_FORMAT13_IF_LU0_UPPER_INDEX  (20)
`define IE_FORMAT13_IF_LU0_LOWER_INDEX (20)
`define IE_FORMAT13_IF_LU0_RANGE `IE_FORMAT13_IF_LU0_UPPER_INDEX:`IE_FORMAT13_IF_LU0_LOWER_INDEX

`define IE_FORMAT13_IF_RN0_UPPER_INDEX  (16)
`define IE_FORMAT13_IF_RN0_LOWER_INDEX (19)
`define IE_FORMAT13_IF_RN0_RANGE `IE_FORMAT13_IF_RN0_UPPER_INDEX:`IE_FORMAT13_IF_RN0_LOWER_INDEX

`define IE_FORMAT13_IF_RLIST0_UPPER_INDEX  (0)
`define IE_FORMAT13_IF_RLIST0_LOWER_INDEX (15)
`define IE_FORMAT13_IF_RLIST0_RANGE `IE_FORMAT13_IF_RLIST0_UPPER_INDEX:`IE_FORMAT13_IF_RLIST0_LOWER_INDEX

`define IE_FORMAT14_UPPER_INDEX (32-1)
`define IE_FORMAT14_LOWER_INDEX (0)
`define IE_FORMAT14_WIDTH (32)
`define IE_FORMAT14_RANGE `IE_FORMAT14_UPPER_INDEX:`IE_FORMAT14_LOWER_INDEX
`define IE_FORMAT14_IF_C160_UPPER_INDEX  (28)
`define IE_FORMAT14_IF_C160_LOWER_INDEX (31)
`define IE_FORMAT14_IF_C160_RANGE `IE_FORMAT14_IF_C160_UPPER_INDEX:`IE_FORMAT14_IF_C160_LOWER_INDEX

`define IE_FORMAT14_IF_C190_UPPER_INDEX  (25)
`define IE_FORMAT14_IF_C190_LOWER_INDEX (27)
`define IE_FORMAT14_IF_C190_RANGE `IE_FORMAT14_IF_C190_UPPER_INDEX:`IE_FORMAT14_IF_C190_LOWER_INDEX

`define IE_FORMAT14_IF_C200_UPPER_INDEX  (0)
`define IE_FORMAT14_IF_C200_LOWER_INDEX (24)
`define IE_FORMAT14_IF_C200_RANGE `IE_FORMAT14_IF_C200_UPPER_INDEX:`IE_FORMAT14_IF_C200_LOWER_INDEX

`define IE_FORMAT15_UPPER_INDEX (32-1)
`define IE_FORMAT15_LOWER_INDEX (0)
`define IE_FORMAT15_WIDTH (32)
`define IE_FORMAT15_RANGE `IE_FORMAT15_UPPER_INDEX:`IE_FORMAT15_LOWER_INDEX
`define IE_FORMAT15_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT15_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT15_IF_COND0_RANGE `IE_FORMAT15_IF_COND0_UPPER_INDEX:`IE_FORMAT15_IF_COND0_LOWER_INDEX

`define IE_FORMAT15_IF_C210_UPPER_INDEX  (25)
`define IE_FORMAT15_IF_C210_LOWER_INDEX (27)
`define IE_FORMAT15_IF_C210_RANGE `IE_FORMAT15_IF_C210_UPPER_INDEX:`IE_FORMAT15_IF_C210_LOWER_INDEX

`define IE_FORMAT15_IF_L0_UPPER_INDEX  (24)
`define IE_FORMAT15_IF_L0_LOWER_INDEX (24)
`define IE_FORMAT15_IF_L0_RANGE `IE_FORMAT15_IF_L0_UPPER_INDEX:`IE_FORMAT15_IF_L0_LOWER_INDEX

`define IE_FORMAT15_IF_OFFS240_UPPER_INDEX  (0)
`define IE_FORMAT15_IF_OFFS240_LOWER_INDEX (23)
`define IE_FORMAT15_IF_OFFS240_RANGE `IE_FORMAT15_IF_OFFS240_UPPER_INDEX:`IE_FORMAT15_IF_OFFS240_LOWER_INDEX

`define IE_FORMAT16_UPPER_INDEX (32-1)
`define IE_FORMAT16_LOWER_INDEX (0)
`define IE_FORMAT16_WIDTH (32)
`define IE_FORMAT16_RANGE `IE_FORMAT16_UPPER_INDEX:`IE_FORMAT16_LOWER_INDEX
`define IE_FORMAT16_IF_C160_UPPER_INDEX  (28)
`define IE_FORMAT16_IF_C160_LOWER_INDEX (31)
`define IE_FORMAT16_IF_C160_RANGE `IE_FORMAT16_IF_C160_UPPER_INDEX:`IE_FORMAT16_IF_C160_LOWER_INDEX

`define IE_FORMAT16_IF_C210_UPPER_INDEX  (25)
`define IE_FORMAT16_IF_C210_LOWER_INDEX (27)
`define IE_FORMAT16_IF_C210_RANGE `IE_FORMAT16_IF_C210_UPPER_INDEX:`IE_FORMAT16_IF_C210_LOWER_INDEX

`define IE_FORMAT16_IF_H0_UPPER_INDEX  (24)
`define IE_FORMAT16_IF_H0_LOWER_INDEX (24)
`define IE_FORMAT16_IF_H0_RANGE `IE_FORMAT16_IF_H0_UPPER_INDEX:`IE_FORMAT16_IF_H0_LOWER_INDEX

`define IE_FORMAT16_IF_OFFS240_UPPER_INDEX  (0)
`define IE_FORMAT16_IF_OFFS240_LOWER_INDEX (23)
`define IE_FORMAT16_IF_OFFS240_RANGE `IE_FORMAT16_IF_OFFS240_UPPER_INDEX:`IE_FORMAT16_IF_OFFS240_LOWER_INDEX

`define IE_FORMAT17_UPPER_INDEX (32-1)
`define IE_FORMAT17_LOWER_INDEX (0)
`define IE_FORMAT17_WIDTH (32)
`define IE_FORMAT17_RANGE `IE_FORMAT17_UPPER_INDEX:`IE_FORMAT17_LOWER_INDEX
`define IE_FORMAT17_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT17_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT17_IF_COND0_RANGE `IE_FORMAT17_IF_COND0_UPPER_INDEX:`IE_FORMAT17_IF_COND0_LOWER_INDEX

`define IE_FORMAT17_IF_C220_UPPER_INDEX  (25)
`define IE_FORMAT17_IF_C220_LOWER_INDEX (27)
`define IE_FORMAT17_IF_C220_RANGE `IE_FORMAT17_IF_C220_UPPER_INDEX:`IE_FORMAT17_IF_C220_LOWER_INDEX

`define IE_FORMAT17_IF_P0_UPPER_INDEX  (24)
`define IE_FORMAT17_IF_P0_LOWER_INDEX (24)
`define IE_FORMAT17_IF_P0_RANGE `IE_FORMAT17_IF_P0_UPPER_INDEX:`IE_FORMAT17_IF_P0_LOWER_INDEX

`define IE_FORMAT17_IF_U0_UPPER_INDEX  (23)
`define IE_FORMAT17_IF_U0_LOWER_INDEX (23)
`define IE_FORMAT17_IF_U0_RANGE `IE_FORMAT17_IF_U0_UPPER_INDEX:`IE_FORMAT17_IF_U0_LOWER_INDEX

`define IE_FORMAT17_IF_N0_UPPER_INDEX  (22)
`define IE_FORMAT17_IF_N0_LOWER_INDEX (22)
`define IE_FORMAT17_IF_N0_RANGE `IE_FORMAT17_IF_N0_UPPER_INDEX:`IE_FORMAT17_IF_N0_LOWER_INDEX

`define IE_FORMAT17_IF_W0_UPPER_INDEX  (21)
`define IE_FORMAT17_IF_W0_LOWER_INDEX (21)
`define IE_FORMAT17_IF_W0_RANGE `IE_FORMAT17_IF_W0_UPPER_INDEX:`IE_FORMAT17_IF_W0_LOWER_INDEX

`define IE_FORMAT17_IF_LU0_UPPER_INDEX  (20)
`define IE_FORMAT17_IF_LU0_LOWER_INDEX (20)
`define IE_FORMAT17_IF_LU0_RANGE `IE_FORMAT17_IF_LU0_UPPER_INDEX:`IE_FORMAT17_IF_LU0_LOWER_INDEX

`define IE_FORMAT17_IF_RN0_UPPER_INDEX  (16)
`define IE_FORMAT17_IF_RN0_LOWER_INDEX (19)
`define IE_FORMAT17_IF_RN0_RANGE `IE_FORMAT17_IF_RN0_UPPER_INDEX:`IE_FORMAT17_IF_RN0_LOWER_INDEX

`define IE_FORMAT17_IF_CRD0_UPPER_INDEX  (12)
`define IE_FORMAT17_IF_CRD0_LOWER_INDEX (15)
`define IE_FORMAT17_IF_CRD0_RANGE `IE_FORMAT17_IF_CRD0_UPPER_INDEX:`IE_FORMAT17_IF_CRD0_LOWER_INDEX

`define IE_FORMAT17_IF_CPNUM0_UPPER_INDEX  (8)
`define IE_FORMAT17_IF_CPNUM0_LOWER_INDEX (11)
`define IE_FORMAT17_IF_CPNUM0_RANGE `IE_FORMAT17_IF_CPNUM0_UPPER_INDEX:`IE_FORMAT17_IF_CPNUM0_LOWER_INDEX

`define IE_FORMAT17_IF_OFFS80_UPPER_INDEX  (0)
`define IE_FORMAT17_IF_OFFS80_LOWER_INDEX (7)
`define IE_FORMAT17_IF_OFFS80_RANGE `IE_FORMAT17_IF_OFFS80_UPPER_INDEX:`IE_FORMAT17_IF_OFFS80_LOWER_INDEX

`define IE_FORMAT18_UPPER_INDEX (32-1)
`define IE_FORMAT18_LOWER_INDEX (0)
`define IE_FORMAT18_WIDTH (32)
`define IE_FORMAT18_RANGE `IE_FORMAT18_UPPER_INDEX:`IE_FORMAT18_LOWER_INDEX
`define IE_FORMAT18_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT18_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT18_IF_COND0_RANGE `IE_FORMAT18_IF_COND0_UPPER_INDEX:`IE_FORMAT18_IF_COND0_LOWER_INDEX

`define IE_FORMAT18_IF_C230_UPPER_INDEX  (24)
`define IE_FORMAT18_IF_C230_LOWER_INDEX (27)
`define IE_FORMAT18_IF_C230_RANGE `IE_FORMAT18_IF_C230_UPPER_INDEX:`IE_FORMAT18_IF_C230_LOWER_INDEX

`define IE_FORMAT18_IF_OPCODE10_UPPER_INDEX  (20)
`define IE_FORMAT18_IF_OPCODE10_LOWER_INDEX (23)
`define IE_FORMAT18_IF_OPCODE10_RANGE `IE_FORMAT18_IF_OPCODE10_UPPER_INDEX:`IE_FORMAT18_IF_OPCODE10_LOWER_INDEX

`define IE_FORMAT18_IF_CRN0_UPPER_INDEX  (16)
`define IE_FORMAT18_IF_CRN0_LOWER_INDEX (19)
`define IE_FORMAT18_IF_CRN0_RANGE `IE_FORMAT18_IF_CRN0_UPPER_INDEX:`IE_FORMAT18_IF_CRN0_LOWER_INDEX

`define IE_FORMAT18_IF_CRD0_UPPER_INDEX  (12)
`define IE_FORMAT18_IF_CRD0_LOWER_INDEX (15)
`define IE_FORMAT18_IF_CRD0_RANGE `IE_FORMAT18_IF_CRD0_UPPER_INDEX:`IE_FORMAT18_IF_CRD0_LOWER_INDEX

`define IE_FORMAT18_IF_CPNUM0_UPPER_INDEX  (8)
`define IE_FORMAT18_IF_CPNUM0_LOWER_INDEX (11)
`define IE_FORMAT18_IF_CPNUM0_RANGE `IE_FORMAT18_IF_CPNUM0_UPPER_INDEX:`IE_FORMAT18_IF_CPNUM0_LOWER_INDEX

`define IE_FORMAT18_IF_OPCODE20_UPPER_INDEX  (5)
`define IE_FORMAT18_IF_OPCODE20_LOWER_INDEX (7)
`define IE_FORMAT18_IF_OPCODE20_RANGE `IE_FORMAT18_IF_OPCODE20_UPPER_INDEX:`IE_FORMAT18_IF_OPCODE20_LOWER_INDEX

`define IE_FORMAT18_IF_Z0_UPPER_INDEX  (4)
`define IE_FORMAT18_IF_Z0_LOWER_INDEX (4)
`define IE_FORMAT18_IF_Z0_RANGE `IE_FORMAT18_IF_Z0_UPPER_INDEX:`IE_FORMAT18_IF_Z0_LOWER_INDEX

`define IE_FORMAT18_IF_CRM0_UPPER_INDEX  (0)
`define IE_FORMAT18_IF_CRM0_LOWER_INDEX (3)
`define IE_FORMAT18_IF_CRM0_RANGE `IE_FORMAT18_IF_CRM0_UPPER_INDEX:`IE_FORMAT18_IF_CRM0_LOWER_INDEX

`define IE_FORMAT19_UPPER_INDEX (32-1)
`define IE_FORMAT19_LOWER_INDEX (0)
`define IE_FORMAT19_WIDTH (32)
`define IE_FORMAT19_RANGE `IE_FORMAT19_UPPER_INDEX:`IE_FORMAT19_LOWER_INDEX
`define IE_FORMAT19_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT19_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT19_IF_COND0_RANGE `IE_FORMAT19_IF_COND0_UPPER_INDEX:`IE_FORMAT19_IF_COND0_LOWER_INDEX

`define IE_FORMAT19_IF_C230_UPPER_INDEX  (24)
`define IE_FORMAT19_IF_C230_LOWER_INDEX (27)
`define IE_FORMAT19_IF_C230_RANGE `IE_FORMAT19_IF_C230_UPPER_INDEX:`IE_FORMAT19_IF_C230_LOWER_INDEX

`define IE_FORMAT19_IF_OPCODE120_UPPER_INDEX  (21)
`define IE_FORMAT19_IF_OPCODE120_LOWER_INDEX (23)
`define IE_FORMAT19_IF_OPCODE120_RANGE `IE_FORMAT19_IF_OPCODE120_UPPER_INDEX:`IE_FORMAT19_IF_OPCODE120_LOWER_INDEX

`define IE_FORMAT19_IF_LU0_UPPER_INDEX  (20)
`define IE_FORMAT19_IF_LU0_LOWER_INDEX (20)
`define IE_FORMAT19_IF_LU0_RANGE `IE_FORMAT19_IF_LU0_UPPER_INDEX:`IE_FORMAT19_IF_LU0_LOWER_INDEX

`define IE_FORMAT19_IF_CRN0_UPPER_INDEX  (16)
`define IE_FORMAT19_IF_CRN0_LOWER_INDEX (19)
`define IE_FORMAT19_IF_CRN0_RANGE `IE_FORMAT19_IF_CRN0_UPPER_INDEX:`IE_FORMAT19_IF_CRN0_LOWER_INDEX

`define IE_FORMAT19_IF_RD10_UPPER_INDEX  (12)
`define IE_FORMAT19_IF_RD10_LOWER_INDEX (15)
`define IE_FORMAT19_IF_RD10_RANGE `IE_FORMAT19_IF_RD10_UPPER_INDEX:`IE_FORMAT19_IF_RD10_LOWER_INDEX

`define IE_FORMAT19_IF_CPNUM0_UPPER_INDEX  (8)
`define IE_FORMAT19_IF_CPNUM0_LOWER_INDEX (11)
`define IE_FORMAT19_IF_CPNUM0_RANGE `IE_FORMAT19_IF_CPNUM0_UPPER_INDEX:`IE_FORMAT19_IF_CPNUM0_LOWER_INDEX

`define IE_FORMAT19_IF_OPCODE20_UPPER_INDEX  (5)
`define IE_FORMAT19_IF_OPCODE20_LOWER_INDEX (7)
`define IE_FORMAT19_IF_OPCODE20_RANGE `IE_FORMAT19_IF_OPCODE20_UPPER_INDEX:`IE_FORMAT19_IF_OPCODE20_LOWER_INDEX

`define IE_FORMAT19_IF_O0_UPPER_INDEX  (4)
`define IE_FORMAT19_IF_O0_LOWER_INDEX (4)
`define IE_FORMAT19_IF_O0_RANGE `IE_FORMAT19_IF_O0_UPPER_INDEX:`IE_FORMAT19_IF_O0_LOWER_INDEX

`define IE_FORMAT19_IF_CRM0_UPPER_INDEX  (0)
`define IE_FORMAT19_IF_CRM0_LOWER_INDEX (3)
`define IE_FORMAT19_IF_CRM0_RANGE `IE_FORMAT19_IF_CRM0_UPPER_INDEX:`IE_FORMAT19_IF_CRM0_LOWER_INDEX

`define IE_FORMAT2_UPPER_INDEX (32-1)
`define IE_FORMAT2_LOWER_INDEX (0)
`define IE_FORMAT2_WIDTH (32)
`define IE_FORMAT2_RANGE `IE_FORMAT2_UPPER_INDEX:`IE_FORMAT2_LOWER_INDEX
`define IE_FORMAT2_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT2_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT2_IF_COND0_RANGE `IE_FORMAT2_IF_COND0_UPPER_INDEX:`IE_FORMAT2_IF_COND0_LOWER_INDEX

`define IE_FORMAT2_IF_C10_UPPER_INDEX  (25)
`define IE_FORMAT2_IF_C10_LOWER_INDEX (27)
`define IE_FORMAT2_IF_C10_RANGE `IE_FORMAT2_IF_C10_UPPER_INDEX:`IE_FORMAT2_IF_C10_LOWER_INDEX

`define IE_FORMAT2_IF_C20_UPPER_INDEX  (21)
`define IE_FORMAT2_IF_C20_LOWER_INDEX (24)
`define IE_FORMAT2_IF_C20_RANGE `IE_FORMAT2_IF_C20_UPPER_INDEX:`IE_FORMAT2_IF_C20_LOWER_INDEX

`define IE_FORMAT2_IF_ZUP0_UPPER_INDEX  (20)
`define IE_FORMAT2_IF_ZUP0_LOWER_INDEX (20)
`define IE_FORMAT2_IF_ZUP0_RANGE `IE_FORMAT2_IF_ZUP0_UPPER_INDEX:`IE_FORMAT2_IF_ZUP0_LOWER_INDEX

`define IE_FORMAT2_IF_C30_UPPER_INDEX  (5)
`define IE_FORMAT2_IF_C30_LOWER_INDEX (19)
`define IE_FORMAT2_IF_C30_RANGE `IE_FORMAT2_IF_C30_UPPER_INDEX:`IE_FORMAT2_IF_C30_LOWER_INDEX

`define IE_FORMAT2_IF_Z0_UPPER_INDEX  (4)
`define IE_FORMAT2_IF_Z0_LOWER_INDEX (4)
`define IE_FORMAT2_IF_Z0_RANGE `IE_FORMAT2_IF_Z0_UPPER_INDEX:`IE_FORMAT2_IF_Z0_LOWER_INDEX

`define IE_FORMAT2_IF_C40_UPPER_INDEX  (0)
`define IE_FORMAT2_IF_C40_LOWER_INDEX (3)
`define IE_FORMAT2_IF_C40_RANGE `IE_FORMAT2_IF_C40_UPPER_INDEX:`IE_FORMAT2_IF_C40_LOWER_INDEX

`define IE_FORMAT20_UPPER_INDEX (32-1)
`define IE_FORMAT20_LOWER_INDEX (0)
`define IE_FORMAT20_WIDTH (32)
`define IE_FORMAT20_RANGE `IE_FORMAT20_UPPER_INDEX:`IE_FORMAT20_LOWER_INDEX
`define IE_FORMAT20_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT20_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT20_IF_COND0_RANGE `IE_FORMAT20_IF_COND0_UPPER_INDEX:`IE_FORMAT20_IF_COND0_LOWER_INDEX

`define IE_FORMAT20_IF_C240_UPPER_INDEX  (24)
`define IE_FORMAT20_IF_C240_LOWER_INDEX (27)
`define IE_FORMAT20_IF_C240_RANGE `IE_FORMAT20_IF_C240_UPPER_INDEX:`IE_FORMAT20_IF_C240_LOWER_INDEX

`define IE_FORMAT20_IF_SWIN0_UPPER_INDEX  (0)
`define IE_FORMAT20_IF_SWIN0_LOWER_INDEX (23)
`define IE_FORMAT20_IF_SWIN0_RANGE `IE_FORMAT20_IF_SWIN0_UPPER_INDEX:`IE_FORMAT20_IF_SWIN0_LOWER_INDEX

`define IE_FORMAT21_UPPER_INDEX (32-1)
`define IE_FORMAT21_LOWER_INDEX (0)
`define IE_FORMAT21_WIDTH (32)
`define IE_FORMAT21_RANGE `IE_FORMAT21_UPPER_INDEX:`IE_FORMAT21_LOWER_INDEX
`define IE_FORMAT21_IF_C160_UPPER_INDEX  (28)
`define IE_FORMAT21_IF_C160_LOWER_INDEX (31)
`define IE_FORMAT21_IF_C160_RANGE `IE_FORMAT21_IF_C160_UPPER_INDEX:`IE_FORMAT21_IF_C160_LOWER_INDEX

`define IE_FORMAT21_IF_C240_UPPER_INDEX  (24)
`define IE_FORMAT21_IF_C240_LOWER_INDEX (27)
`define IE_FORMAT21_IF_C240_RANGE `IE_FORMAT21_IF_C240_UPPER_INDEX:`IE_FORMAT21_IF_C240_LOWER_INDEX

`define IE_FORMAT21_IF_C250_UPPER_INDEX  (0)
`define IE_FORMAT21_IF_C250_LOWER_INDEX (23)
`define IE_FORMAT21_IF_C250_RANGE `IE_FORMAT21_IF_C250_UPPER_INDEX:`IE_FORMAT21_IF_C250_LOWER_INDEX

`define IE_FORMAT3_UPPER_INDEX (32-1)
`define IE_FORMAT3_LOWER_INDEX (0)
`define IE_FORMAT3_WIDTH (32)
`define IE_FORMAT3_RANGE `IE_FORMAT3_UPPER_INDEX:`IE_FORMAT3_LOWER_INDEX
`define IE_FORMAT3_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT3_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT3_IF_COND0_RANGE `IE_FORMAT3_IF_COND0_UPPER_INDEX:`IE_FORMAT3_IF_COND0_LOWER_INDEX

`define IE_FORMAT3_IF_C10_UPPER_INDEX  (25)
`define IE_FORMAT3_IF_C10_LOWER_INDEX (27)
`define IE_FORMAT3_IF_C10_RANGE `IE_FORMAT3_IF_C10_UPPER_INDEX:`IE_FORMAT3_IF_C10_LOWER_INDEX

`define IE_FORMAT3_IF_OPCODE0_UPPER_INDEX  (21)
`define IE_FORMAT3_IF_OPCODE0_LOWER_INDEX (24)
`define IE_FORMAT3_IF_OPCODE0_RANGE `IE_FORMAT3_IF_OPCODE0_UPPER_INDEX:`IE_FORMAT3_IF_OPCODE0_LOWER_INDEX

`define IE_FORMAT3_IF_S10_UPPER_INDEX  (20)
`define IE_FORMAT3_IF_S10_LOWER_INDEX (20)
`define IE_FORMAT3_IF_S10_RANGE `IE_FORMAT3_IF_S10_UPPER_INDEX:`IE_FORMAT3_IF_S10_LOWER_INDEX

`define IE_FORMAT3_IF_RN0_UPPER_INDEX  (16)
`define IE_FORMAT3_IF_RN0_LOWER_INDEX (19)
`define IE_FORMAT3_IF_RN0_RANGE `IE_FORMAT3_IF_RN0_UPPER_INDEX:`IE_FORMAT3_IF_RN0_LOWER_INDEX

`define IE_FORMAT3_IF_RD10_UPPER_INDEX  (12)
`define IE_FORMAT3_IF_RD10_LOWER_INDEX (15)
`define IE_FORMAT3_IF_RD10_RANGE `IE_FORMAT3_IF_RD10_UPPER_INDEX:`IE_FORMAT3_IF_RD10_LOWER_INDEX

`define IE_FORMAT3_IF_RS0_UPPER_INDEX  (8)
`define IE_FORMAT3_IF_RS0_LOWER_INDEX (11)
`define IE_FORMAT3_IF_RS0_RANGE `IE_FORMAT3_IF_RS0_UPPER_INDEX:`IE_FORMAT3_IF_RS0_LOWER_INDEX

`define IE_FORMAT3_IF_ZM0_UPPER_INDEX  (7)
`define IE_FORMAT3_IF_ZM0_LOWER_INDEX (7)
`define IE_FORMAT3_IF_ZM0_RANGE `IE_FORMAT3_IF_ZM0_UPPER_INDEX:`IE_FORMAT3_IF_ZM0_LOWER_INDEX

`define IE_FORMAT3_IF_SH0_UPPER_INDEX  (5)
`define IE_FORMAT3_IF_SH0_LOWER_INDEX (6)
`define IE_FORMAT3_IF_SH0_RANGE `IE_FORMAT3_IF_SH0_UPPER_INDEX:`IE_FORMAT3_IF_SH0_LOWER_INDEX

`define IE_FORMAT3_IF_O0_UPPER_INDEX  (4)
`define IE_FORMAT3_IF_O0_LOWER_INDEX (4)
`define IE_FORMAT3_IF_O0_RANGE `IE_FORMAT3_IF_O0_UPPER_INDEX:`IE_FORMAT3_IF_O0_LOWER_INDEX

`define IE_FORMAT3_IF_RM0_UPPER_INDEX  (0)
`define IE_FORMAT3_IF_RM0_LOWER_INDEX (3)
`define IE_FORMAT3_IF_RM0_RANGE `IE_FORMAT3_IF_RM0_UPPER_INDEX:`IE_FORMAT3_IF_RM0_LOWER_INDEX

`define IE_FORMAT4_UPPER_INDEX (32-1)
`define IE_FORMAT4_LOWER_INDEX (0)
`define IE_FORMAT4_WIDTH (32)
`define IE_FORMAT4_RANGE `IE_FORMAT4_UPPER_INDEX:`IE_FORMAT4_LOWER_INDEX
`define IE_FORMAT4_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT4_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT4_IF_COND0_RANGE `IE_FORMAT4_IF_COND0_UPPER_INDEX:`IE_FORMAT4_IF_COND0_LOWER_INDEX

`define IE_FORMAT4_IF_C10_UPPER_INDEX  (25)
`define IE_FORMAT4_IF_C10_LOWER_INDEX (27)
`define IE_FORMAT4_IF_C10_RANGE `IE_FORMAT4_IF_C10_UPPER_INDEX:`IE_FORMAT4_IF_C10_LOWER_INDEX

`define IE_FORMAT4_IF_C20_UPPER_INDEX  (21)
`define IE_FORMAT4_IF_C20_LOWER_INDEX (24)
`define IE_FORMAT4_IF_C20_RANGE `IE_FORMAT4_IF_C20_UPPER_INDEX:`IE_FORMAT4_IF_C20_LOWER_INDEX

`define IE_FORMAT4_IF_ZUP0_UPPER_INDEX  (20)
`define IE_FORMAT4_IF_ZUP0_LOWER_INDEX (20)
`define IE_FORMAT4_IF_ZUP0_RANGE `IE_FORMAT4_IF_ZUP0_UPPER_INDEX:`IE_FORMAT4_IF_ZUP0_LOWER_INDEX

`define IE_FORMAT4_IF_C50_UPPER_INDEX  (8)
`define IE_FORMAT4_IF_C50_LOWER_INDEX (19)
`define IE_FORMAT4_IF_C50_RANGE `IE_FORMAT4_IF_C50_UPPER_INDEX:`IE_FORMAT4_IF_C50_LOWER_INDEX

`define IE_FORMAT4_IF_ZM0_UPPER_INDEX  (7)
`define IE_FORMAT4_IF_ZM0_LOWER_INDEX (7)
`define IE_FORMAT4_IF_ZM0_RANGE `IE_FORMAT4_IF_ZM0_UPPER_INDEX:`IE_FORMAT4_IF_ZM0_LOWER_INDEX

`define IE_FORMAT4_IF_C260_UPPER_INDEX  (5)
`define IE_FORMAT4_IF_C260_LOWER_INDEX (6)
`define IE_FORMAT4_IF_C260_RANGE `IE_FORMAT4_IF_C260_UPPER_INDEX:`IE_FORMAT4_IF_C260_LOWER_INDEX

`define IE_FORMAT4_IF_O0_UPPER_INDEX  (4)
`define IE_FORMAT4_IF_O0_LOWER_INDEX (4)
`define IE_FORMAT4_IF_O0_RANGE `IE_FORMAT4_IF_O0_UPPER_INDEX:`IE_FORMAT4_IF_O0_LOWER_INDEX

`define IE_FORMAT4_IF_C40_UPPER_INDEX  (0)
`define IE_FORMAT4_IF_C40_LOWER_INDEX (3)
`define IE_FORMAT4_IF_C40_RANGE `IE_FORMAT4_IF_C40_UPPER_INDEX:`IE_FORMAT4_IF_C40_LOWER_INDEX

`define IE_FORMAT5_UPPER_INDEX (32-1)
`define IE_FORMAT5_LOWER_INDEX (0)
`define IE_FORMAT5_WIDTH (32)
`define IE_FORMAT5_RANGE `IE_FORMAT5_UPPER_INDEX:`IE_FORMAT5_LOWER_INDEX
`define IE_FORMAT5_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT5_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT5_IF_COND0_RANGE `IE_FORMAT5_IF_COND0_UPPER_INDEX:`IE_FORMAT5_IF_COND0_LOWER_INDEX

`define IE_FORMAT5_IF_C10_UPPER_INDEX  (25)
`define IE_FORMAT5_IF_C10_LOWER_INDEX (27)
`define IE_FORMAT5_IF_C10_RANGE `IE_FORMAT5_IF_C10_UPPER_INDEX:`IE_FORMAT5_IF_C10_LOWER_INDEX

`define IE_FORMAT5_IF_C60_UPPER_INDEX  (8)
`define IE_FORMAT5_IF_C60_LOWER_INDEX (24)
`define IE_FORMAT5_IF_C60_RANGE `IE_FORMAT5_IF_C60_UPPER_INDEX:`IE_FORMAT5_IF_C60_LOWER_INDEX

`define IE_FORMAT5_IF_OUP0_UPPER_INDEX  (7)
`define IE_FORMAT5_IF_OUP0_LOWER_INDEX (7)
`define IE_FORMAT5_IF_OUP0_RANGE `IE_FORMAT5_IF_OUP0_UPPER_INDEX:`IE_FORMAT5_IF_OUP0_LOWER_INDEX

`define IE_FORMAT5_IF_C260_UPPER_INDEX  (5)
`define IE_FORMAT5_IF_C260_LOWER_INDEX (6)
`define IE_FORMAT5_IF_C260_RANGE `IE_FORMAT5_IF_C260_UPPER_INDEX:`IE_FORMAT5_IF_C260_LOWER_INDEX

`define IE_FORMAT5_IF_O0_UPPER_INDEX  (4)
`define IE_FORMAT5_IF_O0_LOWER_INDEX (4)
`define IE_FORMAT5_IF_O0_RANGE `IE_FORMAT5_IF_O0_UPPER_INDEX:`IE_FORMAT5_IF_O0_LOWER_INDEX

`define IE_FORMAT5_IF_C40_UPPER_INDEX  (0)
`define IE_FORMAT5_IF_C40_LOWER_INDEX (3)
`define IE_FORMAT5_IF_C40_RANGE `IE_FORMAT5_IF_C40_UPPER_INDEX:`IE_FORMAT5_IF_C40_LOWER_INDEX

`define IE_FORMAT6_UPPER_INDEX (32-1)
`define IE_FORMAT6_LOWER_INDEX (0)
`define IE_FORMAT6_WIDTH (32)
`define IE_FORMAT6_RANGE `IE_FORMAT6_UPPER_INDEX:`IE_FORMAT6_LOWER_INDEX
`define IE_FORMAT6_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT6_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT6_IF_COND0_RANGE `IE_FORMAT6_IF_COND0_UPPER_INDEX:`IE_FORMAT6_IF_COND0_LOWER_INDEX

`define IE_FORMAT6_IF_C70_UPPER_INDEX  (25)
`define IE_FORMAT6_IF_C70_LOWER_INDEX (27)
`define IE_FORMAT6_IF_C70_RANGE `IE_FORMAT6_IF_C70_UPPER_INDEX:`IE_FORMAT6_IF_C70_LOWER_INDEX

`define IE_FORMAT6_IF_OPCODE0_UPPER_INDEX  (21)
`define IE_FORMAT6_IF_OPCODE0_LOWER_INDEX (24)
`define IE_FORMAT6_IF_OPCODE0_RANGE `IE_FORMAT6_IF_OPCODE0_UPPER_INDEX:`IE_FORMAT6_IF_OPCODE0_LOWER_INDEX

`define IE_FORMAT6_IF_S10_UPPER_INDEX  (20)
`define IE_FORMAT6_IF_S10_LOWER_INDEX (20)
`define IE_FORMAT6_IF_S10_RANGE `IE_FORMAT6_IF_S10_UPPER_INDEX:`IE_FORMAT6_IF_S10_LOWER_INDEX

`define IE_FORMAT6_IF_RN0_UPPER_INDEX  (16)
`define IE_FORMAT6_IF_RN0_LOWER_INDEX (19)
`define IE_FORMAT6_IF_RN0_RANGE `IE_FORMAT6_IF_RN0_UPPER_INDEX:`IE_FORMAT6_IF_RN0_LOWER_INDEX

`define IE_FORMAT6_IF_RD10_UPPER_INDEX  (12)
`define IE_FORMAT6_IF_RD10_LOWER_INDEX (15)
`define IE_FORMAT6_IF_RD10_RANGE `IE_FORMAT6_IF_RD10_UPPER_INDEX:`IE_FORMAT6_IF_RD10_LOWER_INDEX

`define IE_FORMAT6_IF_ROTATE0_UPPER_INDEX  (8)
`define IE_FORMAT6_IF_ROTATE0_LOWER_INDEX (11)
`define IE_FORMAT6_IF_ROTATE0_RANGE `IE_FORMAT6_IF_ROTATE0_UPPER_INDEX:`IE_FORMAT6_IF_ROTATE0_LOWER_INDEX

`define IE_FORMAT6_IF_IMMEDIATE0_UPPER_INDEX  (0)
`define IE_FORMAT6_IF_IMMEDIATE0_LOWER_INDEX (7)
`define IE_FORMAT6_IF_IMMEDIATE0_RANGE `IE_FORMAT6_IF_IMMEDIATE0_UPPER_INDEX:`IE_FORMAT6_IF_IMMEDIATE0_LOWER_INDEX

`define IE_FORMAT7_UPPER_INDEX (32-1)
`define IE_FORMAT7_LOWER_INDEX (0)
`define IE_FORMAT7_WIDTH (32)
`define IE_FORMAT7_RANGE `IE_FORMAT7_UPPER_INDEX:`IE_FORMAT7_LOWER_INDEX
`define IE_FORMAT7_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT7_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT7_IF_COND0_RANGE `IE_FORMAT7_IF_COND0_UPPER_INDEX:`IE_FORMAT7_IF_COND0_LOWER_INDEX

`define IE_FORMAT7_IF_C70_UPPER_INDEX  (25)
`define IE_FORMAT7_IF_C70_LOWER_INDEX (27)
`define IE_FORMAT7_IF_C70_RANGE `IE_FORMAT7_IF_C70_UPPER_INDEX:`IE_FORMAT7_IF_C70_LOWER_INDEX

`define IE_FORMAT7_IF_C80_UPPER_INDEX  (23)
`define IE_FORMAT7_IF_C80_LOWER_INDEX (24)
`define IE_FORMAT7_IF_C80_RANGE `IE_FORMAT7_IF_C80_UPPER_INDEX:`IE_FORMAT7_IF_C80_LOWER_INDEX

`define IE_FORMAT7_IF_C90_UPPER_INDEX  (22)
`define IE_FORMAT7_IF_C90_LOWER_INDEX (22)
`define IE_FORMAT7_IF_C90_RANGE `IE_FORMAT7_IF_C90_UPPER_INDEX:`IE_FORMAT7_IF_C90_LOWER_INDEX

`define IE_FORMAT7_IF_C100_UPPER_INDEX  (20)
`define IE_FORMAT7_IF_C100_LOWER_INDEX (21)
`define IE_FORMAT7_IF_C100_RANGE `IE_FORMAT7_IF_C100_UPPER_INDEX:`IE_FORMAT7_IF_C100_LOWER_INDEX

`define IE_FORMAT7_IF_C110_UPPER_INDEX  (0)
`define IE_FORMAT7_IF_C110_LOWER_INDEX (19)
`define IE_FORMAT7_IF_C110_RANGE `IE_FORMAT7_IF_C110_UPPER_INDEX:`IE_FORMAT7_IF_C110_LOWER_INDEX

`define IE_FORMAT8_UPPER_INDEX (32-1)
`define IE_FORMAT8_LOWER_INDEX (0)
`define IE_FORMAT8_WIDTH (32)
`define IE_FORMAT8_RANGE `IE_FORMAT8_UPPER_INDEX:`IE_FORMAT8_LOWER_INDEX
`define IE_FORMAT8_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT8_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT8_IF_COND0_RANGE `IE_FORMAT8_IF_COND0_UPPER_INDEX:`IE_FORMAT8_IF_COND0_LOWER_INDEX

`define IE_FORMAT8_IF_C70_UPPER_INDEX  (25)
`define IE_FORMAT8_IF_C70_LOWER_INDEX (27)
`define IE_FORMAT8_IF_C70_RANGE `IE_FORMAT8_IF_C70_UPPER_INDEX:`IE_FORMAT8_IF_C70_LOWER_INDEX

`define IE_FORMAT8_IF_C80_UPPER_INDEX  (23)
`define IE_FORMAT8_IF_C80_LOWER_INDEX (24)
`define IE_FORMAT8_IF_C80_RANGE `IE_FORMAT8_IF_C80_UPPER_INDEX:`IE_FORMAT8_IF_C80_LOWER_INDEX

`define IE_FORMAT8_IF_R0_UPPER_INDEX  (22)
`define IE_FORMAT8_IF_R0_LOWER_INDEX (22)
`define IE_FORMAT8_IF_R0_RANGE `IE_FORMAT8_IF_R0_UPPER_INDEX:`IE_FORMAT8_IF_R0_LOWER_INDEX

`define IE_FORMAT8_IF_C120_UPPER_INDEX  (20)
`define IE_FORMAT8_IF_C120_LOWER_INDEX (21)
`define IE_FORMAT8_IF_C120_RANGE `IE_FORMAT8_IF_C120_UPPER_INDEX:`IE_FORMAT8_IF_C120_LOWER_INDEX

`define IE_FORMAT8_IF_MASK0_UPPER_INDEX  (16)
`define IE_FORMAT8_IF_MASK0_LOWER_INDEX (19)
`define IE_FORMAT8_IF_MASK0_RANGE `IE_FORMAT8_IF_MASK0_UPPER_INDEX:`IE_FORMAT8_IF_MASK0_LOWER_INDEX

`define IE_FORMAT8_IF_SBO0_UPPER_INDEX  (12)
`define IE_FORMAT8_IF_SBO0_LOWER_INDEX (15)
`define IE_FORMAT8_IF_SBO0_RANGE `IE_FORMAT8_IF_SBO0_UPPER_INDEX:`IE_FORMAT8_IF_SBO0_LOWER_INDEX

`define IE_FORMAT8_IF_ROTATE0_UPPER_INDEX  (8)
`define IE_FORMAT8_IF_ROTATE0_LOWER_INDEX (11)
`define IE_FORMAT8_IF_ROTATE0_RANGE `IE_FORMAT8_IF_ROTATE0_UPPER_INDEX:`IE_FORMAT8_IF_ROTATE0_LOWER_INDEX

`define IE_FORMAT8_IF_IMMEDIATE0_UPPER_INDEX  (0)
`define IE_FORMAT8_IF_IMMEDIATE0_LOWER_INDEX (7)
`define IE_FORMAT8_IF_IMMEDIATE0_RANGE `IE_FORMAT8_IF_IMMEDIATE0_UPPER_INDEX:`IE_FORMAT8_IF_IMMEDIATE0_LOWER_INDEX

`define IE_FORMAT9_UPPER_INDEX (32-1)
`define IE_FORMAT9_LOWER_INDEX (0)
`define IE_FORMAT9_WIDTH (32)
`define IE_FORMAT9_RANGE `IE_FORMAT9_UPPER_INDEX:`IE_FORMAT9_LOWER_INDEX
`define IE_FORMAT9_IF_COND0_UPPER_INDEX  (28)
`define IE_FORMAT9_IF_COND0_LOWER_INDEX (31)
`define IE_FORMAT9_IF_COND0_RANGE `IE_FORMAT9_IF_COND0_UPPER_INDEX:`IE_FORMAT9_IF_COND0_LOWER_INDEX

`define IE_FORMAT9_IF_C130_UPPER_INDEX  (25)
`define IE_FORMAT9_IF_C130_LOWER_INDEX (27)
`define IE_FORMAT9_IF_C130_RANGE `IE_FORMAT9_IF_C130_UPPER_INDEX:`IE_FORMAT9_IF_C130_LOWER_INDEX

`define IE_FORMAT9_IF_P0_UPPER_INDEX  (24)
`define IE_FORMAT9_IF_P0_LOWER_INDEX (24)
`define IE_FORMAT9_IF_P0_RANGE `IE_FORMAT9_IF_P0_UPPER_INDEX:`IE_FORMAT9_IF_P0_LOWER_INDEX

`define IE_FORMAT9_IF_U0_UPPER_INDEX  (23)
`define IE_FORMAT9_IF_U0_LOWER_INDEX (23)
`define IE_FORMAT9_IF_U0_RANGE `IE_FORMAT9_IF_U0_UPPER_INDEX:`IE_FORMAT9_IF_U0_LOWER_INDEX

`define IE_FORMAT9_IF_B0_UPPER_INDEX  (25)
`define IE_FORMAT9_IF_B0_LOWER_INDEX (27)
`define IE_FORMAT9_IF_B0_RANGE `IE_FORMAT9_IF_B0_UPPER_INDEX:`IE_FORMAT9_IF_B0_LOWER_INDEX

`define IE_FORMAT9_IF_W0_UPPER_INDEX  (21)
`define IE_FORMAT9_IF_W0_LOWER_INDEX (21)
`define IE_FORMAT9_IF_W0_RANGE `IE_FORMAT9_IF_W0_UPPER_INDEX:`IE_FORMAT9_IF_W0_LOWER_INDEX

`define IE_FORMAT9_IF_LU0_UPPER_INDEX  (20)
`define IE_FORMAT9_IF_LU0_LOWER_INDEX (20)
`define IE_FORMAT9_IF_LU0_RANGE `IE_FORMAT9_IF_LU0_UPPER_INDEX:`IE_FORMAT9_IF_LU0_LOWER_INDEX

`define IE_FORMAT9_IF_RN0_UPPER_INDEX  (16)
`define IE_FORMAT9_IF_RN0_LOWER_INDEX (19)
`define IE_FORMAT9_IF_RN0_RANGE `IE_FORMAT9_IF_RN0_UPPER_INDEX:`IE_FORMAT9_IF_RN0_LOWER_INDEX

`define IE_FORMAT9_IF_RD10_UPPER_INDEX  (12)
`define IE_FORMAT9_IF_RD10_LOWER_INDEX (15)
`define IE_FORMAT9_IF_RD10_RANGE `IE_FORMAT9_IF_RD10_UPPER_INDEX:`IE_FORMAT9_IF_RD10_LOWER_INDEX

`define IE_FORMAT9_IF_IMMEDIATE20_UPPER_INDEX  (0)
`define IE_FORMAT9_IF_IMMEDIATE20_LOWER_INDEX (11)
`define IE_FORMAT9_IF_IMMEDIATE20_RANGE `IE_FORMAT9_IF_IMMEDIATE20_UPPER_INDEX:`IE_FORMAT9_IF_IMMEDIATE20_LOWER_INDEX


`endif
