#!/usr/bin/perl

#Author Monica
#modified by oanab
use strict;

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 40; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $test_name = "ar_conn_name_op_".$i."_legal.csl";
    &createCslFile($test_name, $i);
}
sub createCslFile {
    my($test_name, $i) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen";
   if($i==1){
        print (" Generated path: $path/ar_conn_name_op_valid1/\n");}
    my $val1 = int(rand(500));
    if($val1 == 0) { $val1 = 1; }
    my $val2= int(rand(200));
    if($val2== 0) { $val2= 1; }
    my $val3 = int(rand(100));
    if($val3==0) {$val3=1;}

         

    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_op_valid1");
        open(FH,">$path/ar_conn_name_op_valid1/$test_name");
    }

if($i>0 && $i<=40){
#***********************************************
# sg.sig.connect_by_name (op_expr);

if($i>0 && $i<=10){
    print FH "//Generated by Monica\n";
    print FH "//Connect SG.signal--operation_expression\n\n";
    print FH "// TEST $i;\n";        

      print FH " csl_bitrange br1($val1);\n";
      print FH " csl_bitrange br2($val2);\n"; 
 foreach( my $j=1; $j<=$i; $j++){
       
         print FH " csl_signal_group sg1_$j {\n";
         print FH "   csl_signal  s11_$j($j);\n";
         print FH "   csl_signal  s12_$j(br1);\n";
         print FH "   csl_signal  s13_$j(br2);\n";
         print FH "   csl_signal  s14_$j(5);\n";
     
         print FH " sg1_$j(){}\n";
         print FH " };\n";
     }
    print FH " csl_unit u1_$i {\n";
    foreach( my $j=1; $j<=$i; $j++){
	print FH "   csl_port p11_$j(output,$j);\n";
	print FH "   csl_port p12_$j(input,br1);\n";
	print FH "   csl_port p13_$j(input,br2);\n";
	print FH "   csl_port p14_$j(input,5);\n";
    }     
    foreach( my $j=1; $j<=$i; $j++){    
	print FH " sg1_$j sg1_i$j;\n";    
    }
    print FH " u1_$i() {\n";
    foreach( my $j=1; $j<=$i; $j++){
	print FH "    sg1_i$j.s13_$j = p13_$j;\n";
	print FH "    sg1_i$j.s14_$j = p14_$j;\n";
    }
    print FH "  }\n";
    print FH " };\n";
    
    print FH " csl_unit u2_$i {\n";
    foreach( my $j=1; $j<=$i; $j++){
	print FH "   csl_port p21_$j(output,$j);\n";
	print FH "   csl_port p22_$j(input,br1);\n";
	print FH "   csl_port p23_$j(input,br2);\n";
	print FH "   csl_port p24_$j(input,5);\n";
    }
    print FH " u1_$i u1_i$i(";
    foreach( my $j=1; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p13_$j(p23_$j),.p14_$j(p24_$j),";
	}
	else {
	    print FH ".p13_$j(p23_$j),.p14_$j(p24_$j)";
	}
    }
    print FH ");\n";
    foreach( my $j=1; $j<=$i; $j++){    
	print FH " sg1_$j sg2_i$j;\n";    
    }
    print FH " u2_$i() {\n";
    foreach( my $j=1; $j<=$i; $j++){ 
	print FH "    sg2_i$j.s11_$j.connect_by_name(u1_i$i.p11_$j);\n";
	print FH "    sg2_i$j.s12_$j.connect_by_name(u1_i$i.p12_$j);\n"; 
	print FH "    sg2_i$j.s13_$j = p23_$j;\n";
    }
    print FH "  }\n";
    print FH " };\n";

    print FH " csl_unit u3_$i {\n";
    foreach( my $j=1; $j<=$i; $j++){
	print FH "   csl_port p31_$j(output,$j);\n";
	print FH "   csl_port p32_$j(input,br1);\n";
	print FH "   csl_port p33_$j(input,br2);\n";
	print FH "   csl_port p34_$j(output,$j);\n";
	print FH "   csl_port p35_$j(input,5);\n";
	print FH "   csl_port p36_$j(input,br1);\n";
    }     
    print FH " u2_$i u2_i$i(";
    foreach( my $j=1; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p21_$j(p31_$j),.p22_$j(p32_$j),.p23_$j(p33_$j),.p24_$j(p35_$j),";
	}
	else {
	    print FH ".p21_$j(p31_$j),.p22_$j(p32_$j),.p23_$j(p33_$j),.p24_$j(p35_$j)";
	}
    }
    print FH ");\n";
    print FH " u3_$i() {\n";
    foreach( my $j=1; $j<=$i; $j++){ 
	print FH "    u2_i$i.sg2_i$j.s12_$j.connect_by_name(p36_$j + p32_$j);\n";
	print FH "    u2_i$i.sg2_i$j.s11_$j.connect_by_name(p34_$j & p31_$j);\n";
	print FH "    u2_i$i.sg2_i$j.s14_$j.connect_by_name(p35_$j - 5'b11110);\n";
	print FH "    u2_i$i.u1_i$i.sg1_i$j.s12_$j.connect_by_name(p32_$j & p36_$j);\n";
	print FH "    u2_i$i.u1_i$i.sg1_i$j.s11_$j.connect_by_name(~(p31_$j ^ p34_$j));\n";
	
    }
     print FH " }\n";
     print FH " };\n";
}
#******************************************************************
#sg.sig[ps].connect_by_name (op_expr);

if($i>10 && $i<=20){
    print FH "//Generated by Monica\n";
    print FH "//Connect SG.signal[part_select]--operation_expr\n\n";
    print FH "// TEST $i;\n";
my $o=0;
      print FH " csl_bitrange br1($val1);\n";
      print FH " csl_bitrange br2($val2);\n"; 
 foreach( my $j=11; $j<=$i; $j++){
     print FH " csl_signal_group sg1_$j {\n";
     print FH "   csl_signal  s11_$j($j);\n";
     print FH "   csl_signal  s12_$j(br1);\n";
     print FH "   csl_signal  s13_$j(br2);\n";
     print FH "   csl_signal  s14_$j(3);\n";
     print FH " sg1_$j(){}\n";
     print FH " };\n";
 }
    print FH " csl_unit u1_$i {\n";
    foreach( my $j=11; $j<=$i; $j++){
	print FH "   csl_port p11_$j(output,$j);\n";
	print FH "   csl_port p12_$j(input,br1);\n";
	print FH "   csl_port p13_$j(input,br2);\n";
	print FH "   csl_port p14_$j(input,3);\n";
    }     
    foreach( my $j=11; $j<=$i; $j++){    
	print FH " sg1_$j sg1_i$j;\n";    
    }
    print FH " u1_$i() {\n";
    foreach( my $j=11; $j<=$i; $j++){ 
	print FH "    sg1_i$j.s13_$j = p13_$j;\n";
	print FH "    sg1_i$j.s14_$j = p14_$j;\n";
    }
    print FH " }\n";
    print FH " };\n";
    
    print FH " csl_unit u2_$i {\n";
    foreach( my $j=11; $j<=$i; $j++){
	print FH "   csl_port p21_$j(output,$j);\n";
	print FH "   csl_port p22_$j(input,br1);\n";
	print FH "   csl_port p23_$j(input,br2);\n";
	print FH "   csl_port p24_$j(input,3);\n";
    }  
    foreach( my $j=11; $j<=$i; $j++){    
	print FH " sg1_$j sg2_i$j;\n";    
    }
    print FH " u1_$i u1_i$i(";
    foreach( my $j=11; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p11_$j(sg2_i$j.s11_$j),.p12_$j(sg2_i$j.s12_$j),.p13_$j(sg2_i$j.s13_$j),.p14_$j(sg2_i$j.s14_$j),";
	}
	else {
	    print FH ".p11_$j(sg2_i$j.s11_$j),.p12_$j(sg2_i$j.s12_$j),.p13_$j(sg2_i$j.s13_$j),.p14_$j(sg2_i$j.s14_$j)";
	}
    }
    print FH ");\n";
    print FH " u2_$i() {}\n";
    print FH " };\n";
    
    print FH " csl_unit u3_$i {\n";
    foreach( my $j=11; $j<=$i; $j++){
	print FH "   csl_port p31_$j(output,$j);\n";
	print FH "   csl_port p32_$j(input,br1);\n";
	print FH "   csl_port p33_$j(input,br2);\n";
	print FH "   csl_port p34_$j(output,$j);\n";
	print FH "   csl_port p35_$j(input,3);\n";
	print FH "   csl_port p36_$j(input,br1);\n";
	print FH "   csl_port p37_$j(input,3);\n";
    }     
    print FH " u2_$i u2_i$i(";
    foreach( my $j=11; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p21_$j(p31_$j),.p22_$j(p32_$j),.p23_$j(p33_$j),.p24_$j(p35_$j),";
	}
	else {
	    print FH ".p21_$j(p31_$j),.p22_$j(p32_$j),.p23_$j(p33_$j),.p24_$j(p35_$j)";
	}
    }
    print FH ");\n";
    print FH " u3_$i() {\n";
    foreach( my $j=11; $j<=$i; $j++){ 
     my $ui1=$j-1;
     my $ui2=2;
     my $ui3=$val1-1;
     print FH "    u2_i$i.u1_i$i.sg1_i$j.s14_$j [$ui2:$o].connect_by_name(3'b111 | p37_$j);\n";
     print FH "    u2_i$i.sg2_i$j.s11_$j [$ui1:$o].connect_by_name(p31_$j & p34_$j);\n";
     print FH "    u2_i$i.sg2_i$j.s14_$j [$ui2:$o].connect_by_name(p35_$j - 3'b110);\n";
     print FH "    u2_i$i.u1_i$i.sg1_i$j.s12_$j [$ui3:$o].connect_by_name(p32_$j & p36_$j);\n";
     print FH "    u2_i$i.u1_i$i.sg1_i$j.s11_$j  [$ui1:$o].connect_by_name(~(p34_$j ^ p31_$j));\n";
    
 }
     print FH " }\n";
     print FH " };\n";
}

#*************************************************************
# sg.sg1.sig.connect_by_name(op_expr);

if( $i>20 && $i<=30){

    print FH "//Generated by Monica\n";
    print FH "//Connect SG.sg1.signal--operation_expr\n\n";
    print FH "// TEST $i;\n";
    print FH " csl_bitrange br1($val1);\n";
    print FH " csl_bitrange br2($val2);\n"; 
    
    foreach( my $j=21; $j<=$i; $j++){
	print FH " csl_signal_group sg1_$j {\n";
	print FH "   csl_signal  s11_$j($j);\n";
	print FH "   csl_signal  s12_$j(br1);\n";
	print FH "   csl_signal  s13_$j(br2);\n";
	print FH "   csl_signal  s14_$j(3);\n";
	print FH " sg1_$j(){}\n";
	print FH " };\n";
    }
    print FH " csl_signal_group sg2_$i {\n";
    print FH "    csl_signal s21(br2);\n";
    foreach( my $j=21; $j<=$i; $j++){
	print FH " sg1_$j  sg1_i$j;\n";
    }
    print FH " sg2_$i () {}\n";
    print FH " };\n";
    
    print FH " csl_unit u1_$i {\n";
    foreach( my $j=21; $j<=$i; $j++){
	print FH "   csl_port p11_$j(output,$j);\n";
	print FH "   csl_port p12_$j(input,br1);\n";
	print FH "   csl_port p13_$j(input,br2);\n";
	print FH "   csl_port p14_$j(input,3);\n";
    }     
    print FH " sg2_$i sg_1i$i;\n";    
    
    print FH " u1_$i() {\n";
    foreach( my $j=21; $j<=$i; $j++){ 
	print FH "    sg_1i$i.sg1_i$j.s13_$j = sg_1i$i.s21;\n";
	print FH "    sg_1i$i.sg1_i$j.s14_$j = p14_$j;\n";
    }
    print FH " }\n";
    print FH "};\n";
    
    print FH " csl_unit u2_$i {\n";
    foreach( my $j=21; $j<=$i; $j++){
	print FH "   csl_port p21_$j(output,$j);\n";
	print FH "   csl_port p22_$j(input,br1);\n";
	print FH "   csl_port p23_$j(input,br2);\n";
	print FH "   csl_port p24_$j(input,3);\n";
    }     
    print FH " sg2_$i sg_2i$i;\n";    
    print FH " u1_$i u1_i$i(";
    foreach( my $j=21; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p11_$j(p21_$j),.p12_$j(p22_$j),.p13_$j(p23_$j),.p14_$j(p24_$j),";
	}
	else {
	    print FH ".p11_$j(p21_$j),.p12_$j(p22_$j),.p13_$j(p23_$j),.p14_$j(p24_$j)";
	}
    }
    print FH ");\n";
    
    print FH " u2_$i() {\n";
    foreach( my $j=21; $j<=$i; $j++){ 
	print FH "    sg_2i$i.sg1_i$j.s13_$j = sg_2i$i.s21;\n";
	print FH "    sg_2i$i.sg1_i$j.s12_$j = p22_$j;\n";
    }
    print FH " }\n";
    print FH " };\n";
    
    print FH " csl_unit u3_$i {\n";
    foreach( my $j=21; $j<=$i; $j++){
     print FH "   csl_port p31_$j(output,$j);\n";
     print FH "   csl_port p32_$j(input,br1);\n";
     print FH "   csl_port p33_$j(input,br2);\n";
     print FH "   csl_port p34_$j(output,$j);\n";
     print FH "   csl_port p35_$j(output,3);\n";
     print FH "   csl_port p36_$j(input,br1);\n";
 }     
    print FH " sg2_$i sg_3i$i;\n";    
    print FH " u2_$i u2_i$i(";
    foreach( my $j=21; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p21_$j(sg_3i$i.sg1_i$j.s11_$j),.p22_$j(sg_3i$i.sg1_i$j.s12_$j),.p23_$j(sg_3i$i.sg1_i$j.s13_$j),.p24_$j(sg_3i$i.sg1_i$j.s14_$j),";
	}
	else {
	    print FH ".p21_$j(sg_3i$i.sg1_i$j.s11_$j),.p22_$j(sg_3i$i.sg1_i$j.s12_$j),.p23_$j(sg_3i$i.sg1_i$j.s13_$j),.p24_$j(sg_3i$i.sg1_i$j.s14_$j)";
	}
    }
    print FH ");\n";
    print FH " u3_$i() {\n";
    foreach( my $j=21; $j<=$i; $j++){ 
	print FH "    u2_i$i.sg_2i$i.sg1_i$j.s11_$j.connect_by_name(p34_$j & p31_$j);\n";
	print FH "    u2_i$i.sg_2i$i.sg1_i$j.s14_$j.connect_by_name(p35_$j - 3'b110);\n";
	print FH "    u2_i$i.u1_i$i.sg_1i$i.sg1_i$j.s12_$j.connect_by_name(p32_$j & p36_$j);\n";
	print FH "    u2_i$i.u1_i$i.sg_1i$i.sg1_i$j.s11_$j.connect_by_name(~(p31_$j ^ p34_$j));\n";
	print FH "    sg_3i$i.s21 = p33_$j;\n";
	
    }
    print FH " }\n";
    print FH " };\n";
}

#*************************************************************
# sg.sg1.sig[part_select].connect_by_name(op_expr);
if( $i>30 && $i<=40){
    my $o=0;
    print FH "//Generated by Monica\n";
    print FH "//Connect SG.sg1[part_select].signal--operation_expr\n\n";
    print FH "// TEST $i;\n";
    print FH " csl_bitrange br1($val1);\n";
    print FH " csl_bitrange br2($val2);\n"; 
    
    foreach( my $j=31; $j<=$i; $j++){
	print FH " csl_signal_group sg1_$j {\n";
	print FH "   csl_signal  s11_$j($j);\n";
	print FH "   csl_signal  s12_$j(br1);\n";
	print FH "   csl_signal  s13_$j(br2);\n";
	print FH "   csl_signal  s14_$j(3);\n";
	print FH " sg1_$j(){}\n";
	print FH " };\n";
    }
    print FH " csl_signal_group sg2_$i {\n";
    print FH "    csl_signal s21(br2);\n";
    foreach( my $j=31; $j<=$i; $j++){
	print FH " sg1_$j  sg1_i$j;\n";
    }
    print FH " sg2_$i () {}\n";
    print FH " };\n";

    print FH " csl_unit u1_$i {\n";
    foreach( my $j=31; $j<=$i; $j++){
	print FH "   csl_port p11_$j(output,$j);\n";
	print FH "   csl_port p12_$j(input,br1);\n";
	print FH "   csl_port p13_$j(input,br2);\n";
	print FH "   csl_port p14_$j(input,3);\n";
    }     
    print FH " sg2_$i sg_1i$i;\n";    
    
    print FH " u1_$i() {\n";
    foreach( my $j=31; $j<=$i; $j++){ 
	print FH "    sg_1i$i.sg1_i$j.s13_$j = sg_1i$i.s21;\n";
	print FH "    sg_1i$i.sg1_i$j.s14_$j = p14_$j;\n";
    }
    print FH " }\n";
    print FH " };\n";
    
    print FH " csl_unit u2_$i {\n";
    foreach( my $j=31; $j<=$i; $j++){
	print FH "   csl_port p21_$j(output,$j);\n";
	print FH "   csl_port p22_$j(input,br1);\n";
	print FH "   csl_port p23_$j(input,br2);\n";
	print FH "   csl_port p24_$j(input,3);\n";
    }     
    print FH " sg2_$i sg_2i$i;\n";    
    print FH " u1_$i u1_i$i(";
    foreach( my $j=31; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p11_$j(sg_2i$i.sg1_i$j.s11_$j),.p12_$j(sg_2i$i.sg1_i$j.s12_$j),.p13_$j(sg_2i$i.sg1_i$j.s13_$j),.p14_$j(sg_2i$i.sg1_i$j.s14_$j),";
	}
	else {
	    print FH ".p11_$j(sg_2i$i.sg1_i$j.s11_$j),.p12_$j(sg_2i$i.sg1_i$j.s12_$j),.p13_$j(sg_2i$i.sg1_i$j.s13_$j),.p14_$j(sg_2i$i.sg1_i$j.s14_$j)";
	}
    }
    print FH ");\n";
  
    print FH " u2_$i() {\n";
    foreach( my $j=31; $j<=$i; $j++){
	print FH "    sg_2i$i.s21 = p23_$j;\n";
    }
    print FH " }\n";
    print FH " };\n";
    
    print FH " csl_unit u3_$i {\n";
    foreach( my $j=31; $j<=$i; $j++){
	print FH "   csl_port p31_$j(output,$j);\n";
	print FH "   csl_port p32_$j(input,br1);\n";
	print FH "   csl_port p33_$j(input,br2);\n";
	print FH "   csl_port p34_$j(output,$j);\n";
	print FH "   csl_port p35_$j(input,3);\n";
	print FH "   csl_port p36_$j(input,br1);\n";
    }     
    print FH " u2_$i u2_i$i(";
    foreach( my $j=31; $j<=$i; $j++){
	if($j < $i) {
	    print FH ".p21_$j(p31_$j),.p22_$j(p32_$j),.p23_$j(p33_$j),.p24_$j(p35_$j),";
	}
	else {
	    print FH ".p21_$j(p31_$j),.p22_$j(p32_$j),.p23_$j(p33_$j),.p24_$j(p35_$j)";
	}
    }
    print FH ");\n";
   
    print FH " u3_$i() {\n";
    foreach( my $j=31; $j<=$i; $j++){ 
	my $ui1=$j-1;
	my $ui2=2;
	my $ui3=$val1-1;
	print FH " u2_i$i.sg_2i$i.sg1_i$j.s11_$j [$ui1:$o].connect_by_name(p31_$j & p34_$j);\n";
	print FH " u2_i$i.sg_2i$i.sg1_i$j.s14_$j [$ui2:$o].connect_by_name(p35_$j - 3'b110);\n";
	print FH " u2_i$i.u1_i$i.sg_1i$i.sg1_i$j.s12_$j [$ui3:$o].connect_by_name(p32_$j & p36_$j);\n";
	print FH " u2_i$i.u1_i$i.sg_1i$i.sg1_i$j.s11_$j [$ui1:$o].connect_by_name(~(p34_$j ^ p31_$j));\n";
	
    }
    print FH " }\n";
     print FH " };\n";
}


}
    close(FH);
}
