#!/usr/bin/perl

#oanab
#connect_by_name() with param : par obj with const ps and par obj with const ps, const obj with par ps, par obj with par ps; const obj with par ps and par obj with const ps, const obj with par ps, par oj with par ps; par obj with par ps and par obj with const ps, const obj with par ps, par obj with par ps

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_param_invalid5/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 450; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_param".$i."_illegal.csl";
    if($j != $m && $j != $n && $m != $n) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+2;
    my $val2 = int(rand(100))+1;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_param_valid1");
        open(FH,">$path/ar_conn_name_param_valid1/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_param_invalid5"); 
        open(FH,">$path/ar_conn_name_param_invalid5/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#sgj
    print FH "csl_signal_group sg$j {\n";
    if($i <= 50) {
	print FH "  csl_parameter par_m$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal p_m$i(par_m$i);\n";
	print FH "  csl_parameter par_n$i(".($val1+$val2).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
	print FH "  csl_signal p_o$i(br3);\n";
    }
    elsif($i > 50 && $i <= 300) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par3(".($val1).");\n";
	print FH "  csl_signal p_m$i(".($val1+$val2).");\n";
	print FH "  csl_parameter par_n$i(".(3*$val2+$val1).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
	print FH "  csl_signal p_o$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal p_p$i(par_n$i);\n";
    }
    elsif($i > 300 && $i <= 450) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par3(".($val1).");\n";
	print FH "  csl_parameter par_m$i(".($val2+$val1+$val3).");\n";
	print FH "  csl_signal p_m$i(par_m$i);\n";
	print FH "  csl_parameter par_n$i(".(3*$val2+$val1).");\n";
	print FH "  csl_signal p_n$i(par_n$i);\n";
	print FH "  csl_signal p_o$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal p_p$i(par_n$i);\n";
    }
    print FH "  sg$j () {\n";
    print FH "  }\n";
    print FH "};\n\n";


#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par_b$i(".($val1+$val2).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_b$i(".($val1+$val2+2).");\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_a$i(".($val1+2*$val2).");\n";
	print FH "  csl_signal s_a$i(par_a$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 400 && $i <= 450) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    print FH "  a$k () {\n";
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_parameter par_b$i(".($val1+$val2).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par_z$i(".($val3+$val2).");\n";
	print FH "  csl_signal s_z$i(par_z$i);\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_m$i(".($val1+$val2).");\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par_b$i(".($val3+$val2+$val1).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_b$i(".($val1+$val2+$val3).");\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_p$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par3(".($val2).");\n";
	print FH "  csl_signal s_m$i(".($val1+$val2).");\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_parameter par1(".($val3+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_b$i(".($val3+$val1).");\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_x$i(".($val1+$val2).");\n";
	print FH "  csl_signal s_x$i(par_x$i);\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  csl_parameter par_b$i(".($val3+$val1+$val2).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par3(".($val2).");\n";
	print FH "  csl_signal s_m$i(".($val1+$val2).");\n";
    }
    elsif($i > 400 && $i <= 450) {
	print FH "  csl_parameter par_b$i(".($val3+2*$val1).");\n";
	print FH "  csl_parameter par1(".($val3+$val1-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_b$i(par_b$i);\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    print FH "  b$k () {\n";
#Invalid connection : spar.ps---sg.spar.ps (PC)
    if($i <= 50) {
	print FH "    s_b$i\[".($val1+$val2-1)."\:".($val1)."\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_m$i\[".($val2+$val1+$val3-1)."\-\:".($val2)."\]);  // Invalid connection : spar.ps---sg.spar.ps (PC)\n";
    }
#Invalid connection : spar.ps---sg.s.pspar (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    s_z$i\[".($val3+$val2-1)."\-\:".($val2)."\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par2\]);  // Invalid connection : spar.ps---sg.s.pspar (PC)\n";
    }
#Invalid connection : sg.spar.ps---sg.spar.pspar (PC)
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$j\_$one.p_p$i\[".(2*$val2+$val1-1)."\:".(2*$val2)."\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_n$i\[par1\:par2\]);  // Invalid connection : sg.spar.ps---sg.spar.pspar (PC)\n";
    }
#Invalid connection : s.pspar---sg.spar.ps (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    s_b$i\[par1\:par2\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_m$i\[".($val2+$val1+$val3-1)."\-\:".($val2)."\]);  // Invalid connection : s.pspar---sg.spar.ps (PC)\n";
    }
#Invalid connection : s.pspar---sg.s.pspar (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    s_p$i\[par1\-\:par3\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par2\]);  // Invalid connection : s.pspar---sg.s.pspar (PC)\n";
    }
#Invalid connection : sg.s.pspar---sg.spar.pspar (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    sg$j\_$zero.p_n$i\[par1\:par2\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par2\]);  // Invalid connection : sg.s.pspar---sg.spar.pspar (PC)\n";
    }
#Invalid connection : spar.pspar---sg.spar.ps (PC)
    elsif($i > 300 && $i <= 350) {
	print FH "    s_x$i\[par1\:par2\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_m$i\[".($val2+$val1+$val3-1)."\-\:".($val2)."\]);  // Invalid connection : spar.pspar---sg.spar.ps (PC)\n";
    }
#Invalid connection : spar.pspar---sg.s.pspar (PC)
    elsif($i > 350 && $i <= 400) {
	print FH "    s_b$i\[par1\-\:par3\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par2\]);  // Invalid connection : spar.pspar---sg.s.pspar (PC)\n";
    }
#sg.spar.pspar---sg.spar.pspar (PC)
    elsif($i > 400 && $i <= 450) {
	print FH "    sg$j\_$one.p_n$i\[par1\:par2\].connect_by_name(a$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par2\]);  // Invalid connection : sg.spar.pspar---sg.spar.pspar (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_c$i(".($val1+$val2+$val3).");\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_parameter par_c$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_c$i(".($val1+$val2+$val3).");\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_parameter par_m$i(".(2*$val1+$val2+$val3).");\n";
	print FH "  csl_signal s_m$i(par_m$i);\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  csl_signal s_c$i(".($val1+$val2).");\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_signal s_c$i(".($val1+$val2+$val3).");\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 400 && $i <= 450) {
	print FH "  csl_parameter par1(".($val1+$val2+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val3).");\n";
	print FH "  csl_parameter par_c$i(".(2*$val1+$val2+$val3).");\n";
	print FH "  csl_signal s_c$i(par_c$i);\n";
    }
    print FH "  c$k () {\n";
#Invalid connection : sg.spar.ps---sg.spar.ps (CP)
    if($i <= 50) {
	print FH "    b$k\_$zero.sg$j\_$one.p_m$i\[".($val2+$val1+$val3-1)."\:".($val2+$val3)."\].connect_by_name(sg$j\_$zero.p_n$i\[".($val2+$val1-1)."\:".($val2)."\]);  // Invalid connection : sg.spar.ps---sg.spar.ps (CP)\n";
    }
#Invalid connection : spar.ps---s.pspar (CP) and sg.spar.ps---s.pspar (PC)
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.a$k\_$zero.s_b$i\[".($val1+$val2-1)."\:".($val1)."\].connect_by_name(s_c$i\[par1\:par2\]);  // Invalid connection : spar.ps---s.pspar (CP)\n";
	print FH "    sg$j\_$zero.p_n$i\[".($val1+$val2-1)."\:".($val1)."\].connect_by_name(b$k\_$zero.s_m$i\[par1\:par2\]);  // Invalid connection : sg.spar.ps---s.pspar (PC)\n";
    }
#Invalid connection : sg.spar.ps---spar.pspar (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    b$k\_$zero.sg$j\_$one.p_p$i\[".(3*$val2+$val1-1)."\:".(2*$val2)."\].connect_by_name(s_c$i\[par1\:par2\]);  // Invalid connection : sg.spar.ps---spar.pspar (CP)\n";
    }
#Invalid connection : sg.s.pspar---sg.spar.ps (CP)
    elsif($i > 150 && $i <= 200) {
	print FH "    b$k\_$zero.sg$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(sg$j\_$zero.p_n$i\[".($val2+$val1-1)."\:".($val2)."\]);  // Invalid connection : sg.s.pspar---sg.spar.ps (CP)\n";
    }
#Invalid connection : s.pspar---s.pspar (CP) and sg.s.pspar---s.pspar (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    b$k\_$zero.a$k\_$zero.s_b$i\[par1\:par2\].connect_by_name(s_c$i\[par1\:par2\]);  // Invalid connection : s.pspar---s.pspar (CP)\n";
	print FH "    sg$j\_$one.p_m$i\[par1\:par3\].connect_by_name(b$k\_$zero.s_m$i\[par1\:par2\]);  // Invalid connection : sg.s.pspar---s.pspar (PC)\n";
    }
#Invalid connection : sg.s.pspar---spar.pspar (CP)
    elsif($i > 250 && $i <= 300) {
	print FH "    b$k\_$zero.sg$j\_$zero.p_o$i\[par1\:par2\].connect_by_name(s_m$i\[par1\:par2\]);  // Invalid connection : sg.s.pspar---spar.pspar (CP)\n";
    }
#Invalid connection : sg.spar.pspar---sg.spar.ps (CP)
    elsif($i > 300 && $i <= 350) {
	print FH "    b$k\_$zero.sg$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(sg$j\_$one.p_n$i\[".($val2+$val1-1)."\:".($val2)."\]);  // Invalid connection : sg.spar.pspar---sg.spar.ps (CP)\n";
    }
#Invalid connection : spar.pspar---s.pspar (CP) and sg.spar.pspar---s.pspar (PC)
    elsif($i > 350 && $i <= 400) {
	print FH "    b$k\_$zero.a$k\_$zero.s_a$i\[par1\:par2\].connect_by_name(s_c$i\[par1\:par2\]);  // Invalid connection : spar.pspar---s.pspar (CP)\n";
	print FH "    sg$j\_$zero.p_n$i\[par1\:par3\].connect_by_name(b$k\_$zero.s_m$i\[par1\:par2\]);  // Invalid connection : sg.spar.pspar---s.pspar (PC)\n";
    }
#Invalid connection : sg.spar.pspar---spar.pspar (CP)
    elsif($i > 400 && $i <= 450) {
	print FH "    b$k\_$zero.sg$j\_$one.p_m$i\[par1\:par2\].connect_by_name(s_c$i\[par1\:par2\]);  // Invalid connection : sg.spar.pspar---spar.pspar (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    print FH "  c$k c$k\_$zero;\n";
    if($i <= 50) {
	print FH "  csl_parameter par_d$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_d$i(par_d$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_d$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_d$i(par_d$i);\n";
	print FH "  b$k b$k\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_signal s_d$i(".($val1+$val2).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_d$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_d$i(par_d$i);\n";
	print FH "  csl_signal s_e$i(".($val1+$val2+$val3).");\n";
	print FH "  b$k b$k\_$one;\n";
    }
    elsif($i > 300 && $i <= 350) {
	print FH "  csl_parameter par1(".($val1+$val2-1).");\n";
	print FH "  csl_parameter par2(".($val2).");\n";
	print FH "  csl_parameter par_y$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal s_y$i(par_y$i);\n";
    }
    elsif($i > 350 && $i <= 400) {
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 400 && $i <= 450) {
	print FH "  csl_parameter par1(".($val1+$val3-1).");\n";
	print FH "  csl_parameter par2(".($val1).");\n";
	print FH "  csl_parameter par_z$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_z$i(par_z$i);\n";
	print FH "  b$k b$k\_$two;\n";
    }
    print FH "  d$k () {\n";
#Invalid connection : spar.ps---spar.ps (PC) and  sg.spar.ps---spar.ps (CP)
    if($i <= 50) {
	print FH "    s_d$i\[".($val1+$val3-1)."\:".($val3)."\].connect_by_name(c$k\_$zero.b$k\_$zero.s_b$i\[".($val1+$val2-1)."\:".($val2)."\]);  // Invalid connection : spar.ps---spar.ps (PC)\n";
	print FH "    c$k\_$zero.sg$j\_$zero.p_m$i\[".($val2+$val1+$val3-1)."\:".($val2+$val1)."\].connect_by_name(s_d$i\[".($val1+$val3-1)."\:".($val1)."\]);  // Invalid connection : sg.spar.ps---spar.ps (CP)\n";
    }
#Invalid connection : sg.spar.ps---sg.s.pspar (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "    c$k\_$zero.sg$j\_$zero.p_n$i\[".($val1+$val2-1)."\:".($val2)."\].connect_by_name(sg$j\_$zero.p_m$i\[par1\:par2\]);  // Invalid connection : sg.spar.ps---sg.s.pspar (CP)\n";
    }
#Invalid connection : spar.ps---spar.pspar (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.b$k\_$zero.s_b$i\[".($val2+$val3-1)."\:".($val2)."\].connect_by_name(s_d$i\[par1\:par2\]);  // Invalid connection : spar.ps---spar.pspar (CP)\n";
	print FH "    s_d$i\[".($val1+$val3-1)."\:".($val1)."\].connect_by_name(b$k\_$one.sg$j\_$one.p_n$i\[par1\:par2\]);\n";
    }
#Invalid connection : s.pspar---spar.ps (PC) and sg.s.pspar---spar.ps (CP)
    elsif($i > 150 && $i <= 200) {
	print FH "    s_d$i\[par1\:par2\].connect_by_name(c$k\_$zero.b$k\_$zero.s_b$i\[".($val1+$val2-1)."\:".($val2)."\]);  // Invalid connection : s.pspar---spar.ps (PC)\n";
	print FH "    c$k\_$zero.sg$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(s_d$i\[".($val1+$val3-1)."\:".($val1)."\]);  // Invalid connection : sg.s.pspar---spar.ps (CP)\n";
    }
#Invalid connection : sg.s.pspar---sg.s.pspar (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.sg$j\_$one.p_m$i\[par1\:par2\].connect_by_name(sg$j\_$zero.p_m$i\[par1\:par2\]);  // Invalid connection : sg.s.pspar---sg.s.pspar (CP)\n";
    }
#Invalid connection : s.pspar---spar.pspar (CP) and s.pspar---sg.spar.pspar (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    c$k\_$zero.b$k\_$zero.s_b$i\[par1\:par2\].connect_by_name(s_d$i\[par1\:par2\]);  // Invalid connection : s.pspar---spar.pspar (CP)\n";
	print FH "    s_e$i\[par1\:par2\].connect_by_name(b$k\_$one.sg$j\_$zero.p_n$i\[par1\:par2\]);  // s.pspar---sg.spar.pspar (PC)\n";
    }
#Invalid connection : spar.pspar---spar.ps (PC) and sg.spar.pspar---spar.ps (CP)
    elsif($i > 300 && $i <= 350) {
	print FH "    s_y$i\[par1\:par2\].connect_by_name(c$k\_$zero.b$k\_$zero.s_x$i\[".($val1+$val2-1)."\:".($val2)."\]);  // Invalid connection : spar.pspar---spar.ps (PC)\n";
	print FH "    c$k\_$zero.sg$j\_$one.p_m$i\[par1\:par2\].connect_by_name(s_y$i\[".($val1+$val3-1)."\:".($val1)."\]);  // Invalid connection : sg.spar.pspar---spar.ps (CP)\n";
    }
#Invalid connection : sg.spar.pspar---sg.s.pspar (CP)
    elsif($i > 350 && $i <= 400) {
	print FH "    c$k\_$zero.sg$j\_$zero.p_m$i\[par1\:par2\].connect_by_name(sg$j\_$zero.p_m$i\[par1\:par2\]);  // Invalid connection : sg.spar.pspar---sg.s.pspar (CP)\n";
    }
#Invalid connection : spar.pspar---spar.pspar (CP) and spar.pspar---sg.spar.pspar (PC)
    elsif($i > 400 && $i <= 450) {
	print FH "    c$k\_$zero.b$k\_$zero.s_b$i\[par1\:par2\].connect_by_name(s_z$i\[par1\:par2\]);  // Invalid connection : spar.pspar---spar.pspar (CP)\n";
	print FH "    s_z$i\[par1\:par2\].connect_by_name(b$k\_$two.sg$j\_$one.p_n$i\[par1\:par2\]);  // Invalid connection : spar.pspar---sg.spar.pspar (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
