#!/usr/bin/perl

#oanab
#connect_by_name() with param

use strict;

print "Generated tests path : test/csl_test_gen/ar_conn_name_param_valid2/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 300; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my $j = $_[1];
    my $m = $_[2];
    my $n = $_[3];
    $j = int(rand(20))+1; 
    $m = int(rand(20))+2; 
    $n = int(rand(20))+3; 
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "ar_conn_name_param".$i."_legal.csl";
    if($j != $m) {
	&createCslFile($test_name, $i, $j, $m, $n, %dir);
    }
    else {
	&createCslFile($test_name, $i, $j+1, $m+2, $n+3, %dir);
    }
}
sub createCslFile {
    my($test_name, $i, $j, $m, $n, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(100))+3;
    my $val2 = int(rand(100))+1;
    my $val3 = int(rand(100))+8;
    my $l = int(rand(3))+1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/ar_conn_name_param_valid2");
        open(FH,">$path/ar_conn_name_param_valid2/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/ar_conn_name_param_invalid1"); 
        open(FH,">$path/ar_conn_name_param_invalid1/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges
    print FH "csl_bitrange br1($val1);\n\n";

    print FH "csl_bitrange br2($val2);\n\n";
    
    print FH "csl_bitrange br3($val3);\n\n";

#ifcj
    if($i > 50 && $i <= 150 || $i > 250 && $i <= 300) {
	print FH "csl_interface ifc$j {\n";
	print FH "  csl_parameter par_pm$i(".($val1+$val2).");\n";
	print FH "  csl_port p_m$i(output,par_pm$i);\n";
	print FH "  csl_parameter par_pn$i(".($val3+$val2).");\n";
	print FH "  csl_port p_n$i(input,par_pn$i);\n";
	print FH "  ifc$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#ifcm
    if($i > 50 && $i <= 100 || $i > 250 && $i <= 300) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_m$i(output,".($val2+$val3).");\n";
	print FH "  csl_port p_n$i(input,".($val1+$val2+$val3).");\n";
	print FH "  ifc$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgj
    if($i > 50 && $i <= 150 || $i > 250 && $i <= 300) {
	print FH "csl_signal_group sg$j {\n";
	print FH "  csl_parameter par_sm$i(".($val2+$val3).");\n";
	print FH "  csl_signal p_m$i(par_sm$i);\n";
	print FH "  csl_parameter par_sn$i(".($val1+$val2+$val3).");\n";
	print FH "  csl_signal p_n$i(par_sn$i);\n";
	print FH "  sg$j () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }

#sgm
    if($i > 100 && $i <= 150 || $i > 250 && $i <= 300) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  csl_signal p_m$i($val1);\n";
	print FH "  csl_signal p_n$i(br3);\n";
	print FH "  sg$m () {\n";
	print FH "  }\n";
	print FH "};\n\n";
    }


#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  csl_parameter par$i(".($val2+$val1).");\n";
	print FH "  csl_port p_x$i(input,par$i);\n";
    }
    elsif($i > 50 && $i <= 150) {
	print FH "  ifc$j ifc$j\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  csl_parameter par$i(".($val3+$val2).");\n";
	print FH "  csl_signal s_x$i(par$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_signal s_a$i(br2);\n";
	print FH "  csl_parameter par$i(".($val1+$val3).");\n";
	print FH "  csl_signal s_x$i(par$i);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
    }
    print FH "  a$k () {\n";
    if($i > 250 && $i <= 300) {
	print FH "    ifc$j\_$one.p_m$i\[".($val1+$val2-1)."\:".($val2)."\] = sg$m\_$zero.p_m$i;  // assign : ifc.ppar.ps---sg.sig\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit b
    print FH "csl_unit b$k {\n";
    if($i <= 50) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_port p_y$i(output,".($val1+$val2).");\n";
	print FH "  csl_parameter par_s$i(".($val3+3).");\n";
	print FH "  csl_signal s_m$i(par_s$i);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$zero.p_n$i(ifc$j\_$one.p_n$i));\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  csl_signal s_x$i(br3);\n";
	print FH "  csl_signal s_y$i(".($val1+$val2).");\n";
	print FH "  a$k a$k\_$zero(.ifc$j\_$zero.p_m$i(s_y$i));\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_parameter par_s$i($val3);\n";
	print FH "  csl_signal s_m$i(par_s$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  a$k a$k\_$zero;\n";
	print FH "  csl_parameter par$i(".($val2+$val3).");\n";
	print FH "  csl_port p_x$i(input,par$i);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  a$k a$k\_$zero(.ifc$j\_$one.p_m$i(s_m$i));\n";
	print FH "  csl_signal s_m$i(".($val1+$val2).");\n";
    }
    print FH "  b$k () {\n";
    if($i > 50 && $i <= 100) {
	print FH "    ifc$j\_$one.p_m$i = sg$j\_$zero.p_n$i\[".($val1+$val2+$val3-1)."\:".($val3)."\];\n";
	print FH "    sg$j\_$zero.p_m$i = ifc$j\_$one.p_n$i;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "    sg$j\_$one.p_n$i\[".($val1+$val2+$val3-1)."\:".($val1+$val2)."\] = s_x$i;\n";
    }
#connect_by_name : sig---ppar.ps (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    a$k\_$zero.s_a$i.connect_by_name(p_x$i\[".($val2+$val3-1)."\:".($val3)."\]); // sig---ppar.ps (CP)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit c
    print FH "csl_unit c$k {\n";
    if($i <= 50) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  a$k a$k\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_n$i(".($val2+$val3).");\n";
	print FH "  b$k b$k\_$zero(.ifc$j\_$one.p_n$i(s_n$i));\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  ifc$j ifc$j\_$one;\n";
	print FH "  sg$j sg$j\_$one;\n";
	print FH "  csl_signal s_m$i(".($val2+$val3+$val1).");\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  csl_parameter par_x$i(".($val3+3).");\n";
	print FH "  csl_port p_x$i(input,par_x$i);\n";
	print FH "  csl_port p_y$i(input,par_x$i);\n";
	print FH "  csl_parameter par_z$i(".($val3).");\n";
	print FH "  csl_port p_z$i(input,par_z$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  csl_port p_a$i(input,br1);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  b$k b$k\_$zero;\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    print FH "  c$k () {\n";
#connect_by_name : ppar---p.ps (SS)
    if($i <= 50) {
	print FH "    a$k\_$one.p_x$i.connect_by_name(b$k\_$zero.p_y$i\[".($val1+$val2-1)."\:".(0)."\]);  // ppar---p.ps (SS)\n";
    }
#connect_by_name : ifc.ppar.ps---ifc.ppar.ps (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "    b$k\_$zero.a$k\_$zero.ifc$j\_$zero.p_m$i\[".($val1+$val2-1)."\:".($val2)."\].connect_by_name(b$k\_$zero.ifc$j\_$one.p_m$i\[".($val1+$val2-2)."\-\:".($val1)."\]);  // ifc.ppar.ps---ifc.ppar.ps (CP)\n";
#connect_by_name : sg.spar.ps---ifc.p.ps (CP)
	print FH "    b$k\_$zero.sg$j\_$zero.p_m$i\[".($val2+$val3-1)."\:".($val2)."\].connect_by_name(ifc$m\_$zero.p_m$i\[".($val2+$val3-2)."\:".($val2-1)."\]);  // sg.spar.ps---ifc.p.ps (CP)\n";
    }
#connect_by_name : ifc.ppar.ps---sg.s.ps (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    b$k\_$zero.a$k\_$zero.ifc$j\_$zero.p_n$i\[".($val2+$val3-2)."\:".($val2+$val3-2)."\].connect_by_name(sg$m\_$zero.p_n$i\[".($val3-1)."\]);  // ifc.ppar.ps---sg.s.ps (CP)\n";
	print FH "    sg$m\_$zero.p_m$i = s_m$i\[".($val1+$val3-1)."\:".($val3)."\];\n";
	print FH "    sg$j\_$one.p_m$i = s_m$i\[".($val1+$val2+$val3-1)."\-\:".($val2+$val3)."\];\n";
    }
#connect_by_name : ppar.ps---sigpar.ps (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    p_z$i\[".($val3-1)."\:".(0)."\].connect_by_name(b$k\_$zero.a$k\_$zero.s_x$i\[".($val3+$val2-1 )."\:".($val2)."\]);  // ppar.ps---sigpar.ps (PC)\n";
    }
#connect_by_name : port---sigpar.ps (PC)
    elsif($i > 200 && $i <= 250) {
	print FH "    p_a$i.connect_by_name(b$k\_$zero.a$k\_$zero.s_x$i\[".($val1+$val3-1)."\:".($val3)."\]);  // port---sigpar.ps (PC)\n";
    }
#connect_by_name : ifc.p---ifc.ppar.ps (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    ifc$m\_$zero.p_n$i\[".($val1+$val2+$val3-1)."\-\:".($val3)."\].connect_by_name(b$k\_$zero.a$k\_$zero.ifc$j\_$one.p_n$i\[".($val2+$val3-1)."\:".($val2)."\]);  // ifc.p---ifc.ppar.ps (PC)\n";
    }
    print FH "  }\n";
    print FH "};\n\n";

#unit d
    print FH "csl_unit d$k {\n";
    if($i <= 50) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  csl_signal s_a$i(br2);\n";
	print FH "  csl_port p_n$i($dir{$l},br3);\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  csl_signal s_d$i(".($val1+$val2+$val3).");\n";
	print FH "  c$k c$k\_$zero(.ifc$m\_$zero.p_m$i(s_d$i\[".($val1+$val2+$val3-1)."\:".($val1)."\]),.ifc$m\_$zero.p_n$i(s_d$i));\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  c$k c$k\_$zero(.ifc$j\_$one.p_n$i(ifc$j\_$two.p_n$i));\n";
	print FH "  csl_signal s_m$i(".($val1+$val2).");\n";
	print FH "  ifc$j ifc$j\_$two;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  c$k c$k\_$zero(.p_z$i(p_y$i));\n";
	print FH "  csl_parameter par_y$i($val3);\n";
	print FH "  csl_port p_y$i(input,par_y$i);\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  c$k c$k\_$zero;\n";
	print FH "  csl_parameter par_s$i(".($val1+$val3).");\n";
	print FH "  csl_port p_b$i(input,par_s$i);\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  c$k c$k\_$zero(.ifc$m\_$zero.p_n$i(sg$j\_$one.p_n$i));\n";
	print FH "  ifc$j ifc$j\_$zero;\n";
	print FH "  sg$j sg$j\_$one;\n";
    }
    print FH "  d$k () {\n";
#connect_by_name : ppar.ps---sig (CP) and sigpar.ps---port (CP)
    if($i <= 50) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.p_x$i\[".($val2+$val1-1)."\-\:".($val2)."\].connect_by_name(s_a$i);  // ppar.ps---sig (CP)\n";
	print FH "    c$k\_$zero.b$k\_$zero.s_m$i\[".($val3+2)."\:".(3)."\].connect_by_name(p_n$i);  // sigpar.ps---port (CP)\n";
    }
#connect_by_name : ifc.ppar.ps---ifc.p (CP)
    elsif($i > 50 && $i <= 100) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.ifc$j\_$zero.p_n$i\[".($val2+$val3-1)."\:".($val2)."\].connect_by_name(c$k\_$zero.ifc$m\_$zero.p_n$i\[".($val2+$val3-1)."\-\:".($val3)."\]);  // ifc.ppar.ps---ifc.p (CP)\n";
    }
#connect_by_name : ifc.ppar.ps---sg.spar.ps (SS) and sg.spar.pa---ifc.ppar.ps (CP)
    elsif($i > 100 && $i <= 150) {
	print FH "    c$k\_$zero.ifc$j\_$one.p_m$i\[".($val1+$val2-1)."\:".($val1)."\].connect_by_name(c$k\_$zero.b$k\_$zero.sg$j\_$one.p_m$i\[".($val2+$val3-1)."\-\:".($val2)."\]);  // ifc.ppar.ps---sg.spar.ps (SS)\n";
	print FH "    c$k\_$zero.sg$j\_$one.p_n$i\[".($val3-1)."\:".(1)."\].connect_by_name(ifc$j\_$two.p_n$i\[".($val2+$val3-1)."\:".($val2+1)."\]);  // sg.spar.ps---ifc.ppar.ps (CP)\n";
	print FH "    ifc$j\_$two.p_m$i = s_m$i;  // assign : ifc.p---sig\n";
    }
#connect_by_name : sigpar.ps---ppar.ps (CP) and ppar.ps---ppar.ps (PC)
    elsif($i > 150 && $i <= 200) {
	print FH "    c$k\_$zero.b$k\_$zero.s_m$i\[".($val3-1)."\].connect_by_name(c$k\_$zero.p_x$i\[".($val3+1)."\]);  // sigpar.ps---ppar.ps (CP)\n";
	print FH "    p_y$i\[".($val3-1)."\:".(0)."\].connect_by_name(c$k\_$zero.p_y$i\[".($val3+2)."\:".(3)."\]);  // ppar.ps---ppar.ps (PC)\n";
    }
#connect_by_name : port---ppar.ps (CP)
    elsif($i > 200 && $i <= 250) {
	print FH "    c$k\_$zero.p_a$i.connect_by_name(p_b$i\[".($val1+$val3-1)."\:".($val3)."\]);  // port---ppar.ps (CP)\n";
    }
#connect_by_name : sg.s---ifc.ppar.ps (CP) and ifc.p---sg.spar.ps (PC)
    elsif($i > 250 && $i <= 300) {
	print FH "    c$k\_$zero.b$k\_$zero.a$k\_$zero.sg$m\_$zero.p_n$i.connect_by_name(ifc$j\_$zero.p_n$i\[".($val2+$val3-1)."\:".($val2)."\]);  // sg.s---ifc.ppar.ps (CP)\n";
	print FH "    c$k\_$zero.ifc$m\_$zero.p_m$i.connect_by_name(sg$j\_$one.p_m$i\[".($val2+$val3-1)."\-\:".($val2+$val3)."\]);  // ifc---sgpar (PC)\n";
	print FH "    ifc$j\_$zero.p_m$i\[".($val2+$val1-1)."\:".($val1+$val2-1)."\] = sg$j\_$one.p_n$i\[".($val3)."\];  // ifc.ppar.ps---sg.spar\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
