#!/usr/bin/perl

#oanab
#assign with part select

use strict;

print "Generated tests path : test/csl_test_gen/assign_part_sel_invalid3/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 200; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "assign_part_sel".$i."_illegal.csl";
   	&createCslFile($test_name, $i, %dir);
}

sub createCslFile {
    my ($test_name, $i, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(20)) + 2;
    my $val2 = int(rand(100)) + 3;
    my $val3 = int(rand(100)) + 4;
    my $l = int(rand(3))+1;
    my $m = $k + int(rand(10)) + 1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/assign_part_sel_valid");
        open(FH,">$path/assign_part_sel_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/assign_part_sel_invalid3"); 
        open(FH,">$path/assign_part_sel_invalid3/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges and fields
    print FH "csl_bitrange br1($val1);\n";
    print FH "csl_bitrange br2($val2);\n";
    print FH "csl_bitrange br3($val3);\n";
    print FH "csl_bitrange f4(".($val2+$val3).");\n";
    print FH "csl_bitrange br5(".($val1+$val2+$val3).");\n";

#ifck
    if($i > 100 && $i <= 200) {
	print FH "csl_interface ifc$k {\n";
	print FH "  csl_port p_a$i(input,br3);\n";
	print FH "  csl_port p_b$i(output,$val2);\n";
	print FH "  csl_port p_c$i(input,br2);\n";
	print FH "  csl_port p_d$i(output,f4);\n";
	print FH "  ifc$k () {}\n";
	print FH "};\n\n";
    }

#ifcm
    if($i > 150 && $i <= 200) {
	print FH "csl_interface ifc$m {\n";
	print FH "  csl_port p_x$i(input,".($val3+2).");\n";
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  ifc$k ifc$k\_$one;\n";
	print FH "  ifc$k ifc$k\_$two;\n";
	print FH "  ifc$m () {}\n";
	print FH "};\n\n";
    }

#sgk
    if($i <= 200) {
	print FH "csl_signal_group sg$k {\n";
	print FH "  csl_signal s_a$i(br2);\n";
	print FH "  csl_signal s_b$i(br3);\n";
	print FH "  csl_signal s_c$i($val2);\n";
	print FH "  csl_signal s_d$i(f4);\n";
	if($i > 100 && $i <= 125) {
	    print FH "  csl_signal s_e$i(".(2*$val1+2*$val2+1).");\n";
	}
	print FH "  sg$k () {}\n";
	print FH "};\n\n";
    }

#sgm
    if($i <= 200) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  csl_signal s_x$i(br2);\n";
	print FH "  csl_signal s_y$i(br3);\n";
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
	print FH "  sg$m () {}\n";
	print FH "};\n\n";
    }

#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  sg$k sg$k\_$two;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$m sg$m\_$one;\n";
	print FH "  csl_signal s_x$i(br5);\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$k ifc$k\_$one;\n";
	print FH "  sg$m sg$m\_$one;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$m ifc$m\_$zero;\n";
	print FH "  csl_signal s_x$i(br5);\n";
    }
    print FH "  a$k () {\n";
#Invalid assign between sg and sg.sg.sig.ps
    if($i <= 50) {
	print FH "    sg$k\_$two = sg$m\_$zero.sg$k\_$one.s_c$i\[".($val2-1)."\-\:".(2)."\];    // Invalid assign between sg and sg.sg.sig.ps\n";
    }
#Invalid assign between sg.sg and sig.ps
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$m\_$two.sg$k\_$zero = s_x$i\[".($val2+$val1+$val3)."\:".($val2+$val3)."\];   // Invalid assign between sg.sg and sig.ps\n";
    }
#Invalid assign between ifc and sg.sg.sig.ps
    elsif($i > 100 && $i <= 150) {
	print FH "    ifc$k\_$one = sg$m\_$one.sg$k\_$one.s_a$i\[1\];   // Invalid assign between ifc and sg.sg.sig.ps\n";
    }
#Invalid assign between ifc.ifc and sig.ps
    elsif($i > 150 && $i <= 200) {
	print FH "    ifc$m\_$zero.ifc$k\_$zero = s_x$i\[".($val2+$val1)."\-\:".($val2)."\];   // Invalid assign between ifc.ifc and sig.ps\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit b
    print FH "csl_unit b$k {\n";
    print FH "  csl_signal s_a$i(f4);\n";
    print FH "  a$k a$k\_$zero;\n";
    if($i <= 50) {
	print FH "  sg$k sg$k\_$zero;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  sg$k sg$k\_$two;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$m ifc$m\_$one;\n";
	print FH "  sg$k sg$k\_$one;\n";
    }
    print FH "  b$k () {\n";
#Invalid assign between sg and sig.ps
    if($i <= 50) {
	print FH "    sg$k\_$zero = s_a$i\[3\];    // Invalid assign between sg and sig.ps\n";
    }
#Invalid assign between sg.sg and sg.sig.ps
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$m\_$zero.sg$k\_$zero = sg$k\_$two.s_d$i\[".($val3+$val2)."\:".($val3)."];    // Invalid assign between sg.sg and sg.sig.ps\n";
    }
#Invalid assign between ifc and sig.ps
    elsif($i > 100 && $i <= 150) {
	print FH "    ifc$k\_$zero = s_a$i\[".($val2+$val3)."\:".$val2."\];    // Invalid assign between ifc and sig.ps\n";
    }
#Invalid assign between ifc.ifc and sg.sig.ps
    elsif($i > 150 && $i <= 200) {
	print FH "    ifc$m\_$one.ifc$k\_$one = sg$k\_$one.s_c$i\[".(3)."\];    // Invalid assign between ifc.ifc and sg.sig.ps\n";
    }
    print FH "  }\n";
    print FH "};\n\n";


#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
    if($i <= 50) {
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
    }
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  sg$m sg$m\_$one;\n";
    }
    elsif($i > 100 && $i <= 150) {
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  sg$k sg$k\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$m ifc$m\_$two;\n";
	print FH "  sg$m sg$m\_$one;\n";
    }
    print FH "  c$k () {\n";
#Invalid assign between sg and sg.sig.ps
    if($i <= 50) {
	print FH "    sg$k\_$one = sg$k\_$zero.s_d$i\[".($val2+$val3)."\:".(2)."\];   // Invalid assign between sg and sg.sig.ps\n";
    }
#Invalid assign between sg.sg and sg.sg.sig.ps
    elsif($i > 50 && $i <= 100) {
	print FH "    sg$m\_$zero.sg$k\_$zero = sg$m\_$one.sg$k\_$zero.s_a$i\[2\];   // Invalid assign between sg.sg and sg.sg.sig.ps\n";
    }
#Invalid assign between ifc and sg.sig.ps
    elsif($i > 100 && $i <= 150) {
	print FH "    ifc$k\_$zero = sg$k\_$zero.s_d$i\[".($val2+$val3)."\-\:".($val2-2)."\];    // Invalid assign between ifc and sg.sig.ps\n";
    }
#Invalid assign between ifc.ifc and sg.sg.sig.ps
    elsif($i > 150 && $i <= 200) {
	print FH "    ifc$m\_$two = sg$m\_$one.sg$k\_$one.s_d$i\[".($val2+$val3)."\:".($val2)."\];    // Invalid assign between ifc.ifc and sg.sg.sig.ps\n";
    }
    print FH "  }\n";
    print FH "};\n\n";











}
