#!/usr/bin/perl

#Author Petronela
use strict;

my $path = "$ENV{WORK}/test/csl_test_gen/";
print "the path for generated tests is : $path"."conn_pattern_p_p_valid/ \n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

sub word {
    my $val = $_[0];
    my @alpha = ('a'..'z','A'..'Z');
    my @alphanumeric = ('a'..'z','A'..'Z','0'..'9');
    my $ret = $alpha[rand @alpha]."zz";
    for(my $i=1;$i < $val; ++$i){
        $ret = $ret.$alphanumeric[rand @alphanumeric];
    }
    return $ret;
}

foreach(my $i = 1; $i <= 4; $i++) {
    my @map1 = ("b0","b1");
    my @map2 = ("c0","c1");
    my @map4 = ("d0","d1");
    my @map8 = ("a0","a1","a2");
    my @map9 = ("f0","f1");
    my @map10 = ("e0","e1","e2");
    my $it1;
    my $it2;
    my $it3 = "";
    my $it4 = "";
    if($i <= 2){
        foreach $it1 (@map1) {
            foreach $it2 (@map2){
                foreach $it3 (@map1){
                    foreach $it4 (@map4){
                        &main($i,$it1,$it2,$it3,$it4);
                    }
                }
            }
                    
        }
    }
    else {
        foreach $it1 (@map2) {
            foreach $it2 (@map8){
                if($it1 ne $it2){
                    foreach $it3 (@map8){
                        foreach $it4 (@map9){
                            &main($i,$it1,$it2,$it3,$it4);
                        }
                    }   
                }
            }
        }
    }
}
    



sub main {
    my ($i,$it1,$it2,$it3,$it4) = @_;
    my $test_name;
   
    $test_name = "conn_pattern_p_p".$i."_".$it1."_".$it2."_".$it3."_".$it4."_legal.csl";
   
    &createCslFile($test_name, $i,$it1,$it2,$it3,$it4);
}

sub createCslFile {
    my($test_name, $i,$it1,$it2,$it3,$it4) = @_;
    
    my $val1 = int(rand(30)) + 1;
    my $val2 = int(rand(30)) + 1;
    my $val3 = int(rand(30)) + 1;
    my $val4 = int(rand(30)) + 1;
    my $val5 = int(rand(30)) + 1;
    my $word = &word($val1);
    my $word1 = &word($val2);
    my $word2 = &word($val1);
    my $word3 = &word($val2);
    my $word4 = &word($val3);
    my $word5 = &word($val4);
    my $word6 = &word($val5);
    &mkDir("$path/conn_pattern_p_p_valid");
    open(FH,">$path/conn_pattern_p_p_valid/$test_name");
    
    print FH "//Generated by Petronela\n";
    print FH "//testing the command connect_by_pattern for connections port to port \n\n";
    print FH "csl_unit a {\n";
    if($i < 3) {
        print FH "  csl_port p_data(input,$val1);\n"; 
        print FH "  csl_port p_addr(input,$val1);\n";
        print FH "  csl_port p_data1(input,$val1);\n";
    }
    else{
        print FH "  csl_port p_data(output,$val1);\n"; 
        print FH "  csl_port p_addr(output,$val1);\n";
        print FH "  csl_port p_data1(output,$val1);\n";
    }
    print FH "  a() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    if($i > 2 ){
        print FH "csl_unit f {\n";
        print FH "  a $it3;\n";
        print FH "  csl_port p_data(output,$val1);\n"; 
        print FH "  csl_port p_addr(output,$val1);\n";
        print FH "  csl_port p_data1(output,$val1);\n";
        print FH "  f() {\n";  
        print FH "  }\n";        
        print FH "};\n";        
        print FH "\n";
    }
    print FH "csl_unit b {\n"; 
   
    if($i < 3) {
        print FH "  csl_port p_data(output,$val1);\n";
        print FH "  csl_port p_addr(output,$val1);\n";
        print FH "  csl_port p_data1(output,$val1);\n";
    }
    else {
        print FH "  csl_port p_data(input,$val1);\n";
        print FH "  csl_port p_addr(input,$val1);\n";
        print FH "  csl_port p_data1(input,$val1);\n";
    }
    print FH "  b() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";
    if($i <= 2){
        #print FH "  b b0;\n";
        #print FH "  b b1;\n";
    }
    else {
        #print FH "  b b0;\n";
        #print FH "  b b1;\n";
        #print FH "  b b2;\n";
    }
    if($i <= 2){
        print FH "  csl_port p_data(input,$val1);\n";
        print FH "  csl_port p_addr(input,$val1);\n";
        print FH "  csl_port p_data1(input,$val1);\n";
    }
    else {
        print FH "  csl_port p_data(output,$val1);\n";
        print FH "  csl_port p_addr(output,$val1);\n";
        print FH "  csl_port p_data1(output,$val1);\n";
    }

    print FH "  c() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    if($i <= 2){
        print FH "  b $it1;\n";
        print FH "  c $it2;\n";
    }
    else {
       
    }
    print FH "  csl_port p_data(input,$val1);\n"; 
    print FH "  csl_port p_addr(input,$val1);\n";
    print FH "  csl_port p_data1(input,$val1);\n";
    print FH "  d() {\n";
    if($i <= 2) {
        print FH "    $it1.p_data.connect_by_pattern($it2.p_data,$word);\n";
        print FH "    $it1.p_addr.connect_by_pattern($it2.p_addr,$word4);\n";
        print FH "    $it1.p_data1.connect_by_pattern($it2.p_data1,$word4);\n";
    }
    elsif($i > 2) {
        
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
     print FH "csl_unit e {\n";  
    if($i <= 2){
        print FH "  d $it4;\n";
        print FH "  b $it3;\n";
    }
    else {
        print FH "  d d0;\n";
        print FH "  f $it4;\n";
    }
    if($i <= 2){
        print FH "  csl_port p_data(output,$val1);\n"; 
        print FH "  csl_port p_addr(output,$val1);\n";   
        print FH "  csl_port p_data1(output,$val1);\n";
    }
    else {      
        print FH "  csl_port p_data(output,$val1);\n"; 
        print FH "  csl_port p_addr(output,$val1);\n";   
        print FH "  csl_port p_data1(output,$val1);\n";
    }
    print FH "  e() {\n";
    if($i <= 2) {
        print FH "    $it3.p_addr.connect_by_pattern($it4.p_data1,$word1);\n";
        print FH "    $it3.p_data.connect_by_pattern($it4.p_data,$word5);\n";
        print FH "    $it3.p_data1.connect_by_pattern($it4.p_addr,$word5);\n";
    }
    else {
        print FH "    d0.p_data.connect_by_pattern($it4.p_data,$word1);\n";
        print FH "    d0.p_addr.connect_by_pattern($it4.p_addr,$word5);\n";
        print FH "    d0.p_data1.connect_by_pattern($it4.p_data1,$word4);\n";
    }
  
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    if($i <=2){
        print FH "  e e0;\n"; 
        print FH "  a a0;\n"; 
    }
    elsif($i > 2) {
        print FH "  e e0;\n"; 
        print FH "  b b1;\n";
        print FH "  c $it1;\n";
    }
    if($i > 2) {
        print FH "  csl_port p_data(output,$val1);\n"; 
        print FH "  csl_port p_addr(output,$val1);\n";   
        print FH "  csl_port p_data1(output,$val1);\n";
    }
    print FH "  top(){\n";
   
    if($i <= 2) {
        print FH "    e0.p_data1.connect_by_pattern(a0.p_addr,$word6);\n";
        print FH "    e0.p_data.connect_by_pattern(a0.p_data,$word2);\n";
        print FH "    e0.p_addr.connect_by_pattern(a0.p_data1,$word3);\n"; 
    }
    elsif($i > 2) {
        print FH "    p_data1.connect_by_pattern(e0.p_addr,$word6);\n";
        print FH "    p_data.connect_by_pattern(e0.p_data,$word2);\n";
        print FH "    p_addr.connect_by_pattern(e0.p_data1,$word3);\n"; 
        print FH "    e0.$it4.$it3.p_addr.connect_by_pattern(e0.p_data1,$word2);\n";
        print FH "    e0.$it4.$it3.p_data.connect_by_pattern(e0.p_data,$word6);\n";
        print FH "    e0.$it4.$it3.p_data1.connect_by_pattern(e0.p_addr,$word3);\n";
        print FH "    b1.p_data.connect_by_pattern($it1.p_data,$word4);\n";
        print FH "    b1.p_addr.connect_by_pattern($it1.p_addr,$word);\n";
        print FH "    b1.p_data1.connect_by_pattern($it1.p_data1,$word);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}
