#!/usr/bin/perl

#Author Petronela
#modified by oanab
use strict;

my $path = "$ENV{WORK}/test/csl_test_gen/";
print "the path for generated tests is : $path"."conn_pattern_param_p_p_valid/ \n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

sub word {
    my $val = $_[0];
    my @alpha = ('a'..'z','A'..'Z');
    my @alphanumeric = ('a'..'z','A'..'Z','0'..'9');
    my $ret = $alpha[rand @alpha]."zz";
    for(my $i=1;$i < $val; ++$i){
        $ret = $ret.$alphanumeric[rand @alphanumeric];
    }
    return $ret;
}

foreach(my $i = 1; $i <= 5; $i++) {
    my @map1 = ("b0","b1");
    my @map2 = ("c0","c1");
    my @map3 = ("b0","b1");
    my @map4 = ("d0","d1");
    my @map5 = ("d1","d2");
    my @map6 = ("b0","b1","b2");
    my @map8 = ("f0","f1","a0","a1","a2");
    my @map7 = ("c0","c1");
    my @map9 = ("d0","d1");
    my @map10 = ("e0","e2");
    my $it1 = "";
    my $it2 = "";
    my $it3 = "";
    my $it4 = "";
    my $it5 = "";
    my $it6 = "";
    if($i <= 2){
        foreach $it1 (@map1) {
            foreach $it2 (@map2){
                if($it1 ne $it2){
                    if($i == 1){
                        foreach $it3 (@map3){
                            foreach $it4 (@map4){
                                if($it3 ne $it4){
                                    &main($i,$it1,$it2,$it3,$it4);
                                }
                            }
                        }
                    }
                    else{
                        foreach $it5 (@map5){
                            foreach $it6 (@map1){
                                if($it5 ne $it6){
                                    &main($i,$it1,$it2,$it5,$it6);
                                }       
                            }
                        }
                    }
                }
            }
        }
    }
    else {
	foreach $it1 (@map8) {
	    foreach $it2 (@map6) {
		if($it1 ne $it2) {
		    foreach $it3 (@map7){
			if($it2 ne $it3){
			    foreach $it4 (@map9){
				if($it3 ne $it4){
				    &main($i,$it1,$it2,$it3,$it4);
				}
			    }
			}
		    }
		}
	    }
	}
    }
}


sub main {
    my ($i,$it1,$it2,$it3,$it4) = @_;
    my $test_name;
   
    $test_name = "conn_pattern_param_p_p".$i."_".$it1."_".$it2."_".$it3."_".$it4."_legal.csl";
   
    &createCslFile($test_name, $i,$it1,$it2,$it3,$it4);
}

sub createCslFile {
    my($test_name, $i,$it1,$it2,$it3,$it4) = @_;
    
    my $val1 = int(rand(30)) + 1;
    my $val2 = int(rand(30)) + 1;
    my $val3 = int(rand(30)) + 1;
    my $val4 = int(rand(30)) + 1;
    my $val5 = int(rand(30)) + 1;
    my $word = &word($val1);
    my $word1 = &word($val2);
    my $word2 = &word($val1);
    my $word3 = &word($val2);
    my $word4 = &word($val3);
    my $word5 = &word($val4);
    my $word6 = &word($val5);
    &mkDir("$path/conn_pattern_param_p_p_valid");
    open(FH,">$path/conn_pattern_param_p_p_valid/$test_name");
    
    print FH "//Generated by Petronela\n";
    print FH "//testing the command connect_by_pattern with parameter for connections port to port \n\n";

    if($i <= 2){ 
	print FH "csl_unit a {\n";
	print FH "  csl_parameter a_x($val1);\n";
	print FH "  csl_parameter a_y($val1);\n";
	print FH "  csl_parameter a_z($val1);\n";
	print FH "  csl_port p_data(output,a_x);\n"; 
	print FH "  csl_port p_addr(input,$val1);\n";
	print FH "  a() {\n";
	print FH "  }\n";        
	print FH "};\n";        
	print FH "\n";
    }
    elsif($i > 2 && $it1 ne "f0" && $it1 ne "f1") {
	print FH "csl_unit a {\n";
	print FH "  csl_parameter a_x($val1);\n";
	print FH "  csl_parameter a_y($val1);\n";
	print FH "  csl_parameter a_z($val1);\n";
	print FH "  csl_port p_data(output,a_x);\n"; 
	print FH "  csl_port p_addr(input,$val1);\n";
        print FH "  csl_port p_data1(input,$val1);\n";
	print FH "  a() {\n";
	print FH "  }\n";        
	print FH "};\n";        
	print FH "\n";
    }


    if($i > 2 && ($it1 eq "f0" || $it1 eq "f1")) {
        print FH "csl_unit f {\n";
        print FH "  csl_parameter f_x($val1);\n";
        print FH "  csl_parameter f_y($val1);\n";
        print FH "  csl_parameter f_z($val1);\n";
        print FH "  csl_port p_data(output,f_y);\n"; 
        print FH "  csl_port p_addr(input,f_x);\n";
        print FH "  csl_port p_data1(input,$val1);\n";
        print FH "  f() {\n";  
        print FH "  }\n";        
        print FH "};\n";        
        print FH "\n";
    }

    print FH "csl_unit b {\n"; 
    if($i <= 2){
        print FH "  a a0;\n";
        print FH "  a a1(.p_data(p_data),.p_addr(p_addr));\n";
        print FH "  csl_parameter b_x($val1);\n";
        print FH "  csl_parameter b_y($val1);\n";
        print FH "  csl_parameter b_z($val1);\n";
        print FH "  csl_port p_data(output,$val1);\n";
        print FH "  csl_port p_addr(input,b_z);\n";
    }
    elsif($i > 2) {
	if($it1 eq "f0" || $it1 eq "f1") {
	    print FH "  f $it1;\n";
	}
#	print FH "  f f1;\n";
	else {
	    print FH "  a $it1;\n";
	}
#	print FH "  a a1;\n";
#	print FH "  a a2;\n";
	print FH "  csl_parameter b_x($val1);\n";
        print FH "  csl_parameter b_y($val1);\n";
        print FH "  csl_parameter b_z($val1);\n";
        print FH "  csl_port p_data(output,b_z);\n";
        print FH "  csl_port p_addr(input,$val1);\n";
        print FH "  csl_port p_data1(input,b_y);\n";
    }
    print FH "  b() {\n";
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit c {\n";
    if($i <= 2){
        print FH "  b b0(.p_data(p_data),.p_addr(p_addr));\n";
        print FH "  b b1;\n";
        print FH "  csl_parameter c_x($val1);\n";
        print FH "  csl_parameter c_y($val1);\n";
        print FH "  csl_parameter c_z($val1);\n";
        print FH "  csl_port p_data(output,c_y);\n";
        print FH "  csl_port p_addr(input,c_x);\n";
    }
    elsif($i > 2) {
        print FH "  b $it2;\n";
#	print FH "  b b1;\n";
#	print FH "  b b2;\n";
        print FH "  csl_parameter c_x($val1);\n";
        print FH "  csl_parameter c_y($val1);\n";
        print FH "  csl_parameter c_z($val1);\n";
        print FH "  csl_port p_data(output,c_x);\n";
        print FH "  csl_port p_addr(input,$val1);\n";
        print FH "  csl_port p_data1(input,c_z);\n";
    }
    print FH "  c() {\n";
    if($i <= 2){
	print FH "    p_data.connect_by_pattern(a0.p_data,$word);\n";
        print FH "    p_addr.connect_by_pattern(a0.p_addr,$word4);\n";
    }
    elsif($i > 2) {
	print FH "    p_data.connect_by_pattern($it1.p_data);\n";
	print FH "    p_addr.connect_by_pattern($it1.p_addr);\n";
	print FH "    p_data1.connect_by_pattern($it1.p_data1);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit d {\n";  
    if($i <= 2){
        print FH "  c c0;\n";
        print FH "  c c1(.p_data(p_data),.p_addr(p_addr));\n";
	print FH "  csl_parameter d_x($val1);\n";
	print FH "  csl_parameter d_y($val1);\n";
	print FH "  csl_parameter d_z($val1);\n";
	print FH "  csl_port p_data(output,$val1);\n"; 
	print FH "  csl_port p_addr(input,d_y);\n";
    }
    elsif($i > 2) {
        print FH "  c $it3;\n";
#	print FH "  c c1;\n";
	print FH "  csl_parameter d_x($val1);\n";
	print FH "  csl_parameter d_y($val1);\n";
	print FH "  csl_parameter d_z($val1);\n";
	print FH "  csl_port p_data(output,$val1);\n"; 
	print FH "  csl_port p_addr(input,d_y);\n";
	print FH "  csl_port p_data1(input,d_z);\n";
    }
    print FH "  d() {\n";
    if($i <= 2) {
	print FH "    p_data.connect_by_pattern(b1.p_data,$word);\n";
        print FH "    p_addr.connect_by_pattern(b1.p_addr,$word4);\n";
    }
    elsif($i > 2) {
#        print FH "    b1.$it2.p_data.connect_by_pattern($it1.p_data1,$word4);\n";
#        print FH "    b1.$it2.p_addr.connect_by_pattern($it1.p_data,$word);\n";
	print FH "    p_data.connect_by_pattern($it2.p_data,$word4);\n";
	print FH "    p_addr.connect_by_pattern($it2.p_addr,$word);\n";
	print FH "    p_data1.connect_by_pattern($it2.p_data1);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit e {\n";  
    if($i <= 2){
        print FH "  d d0(.p_data(p_data),.p_addr(p_addr));\n";
        print FH "  d d1(.p_data(p_data),.p_addr(p_addr));\n";
        print FH "  csl_parameter e_x($val1);\n";
        print FH "  csl_parameter e_y($val1);\n";
        print FH "  csl_parameter e_z($val1);\n";
        print FH "  csl_port p_data(output,$val1);\n"; 
        print FH "  csl_port p_addr(input,e_x);\n";   
    }
    elsif($i > 2) {
        print FH "  d $it4;\n";
#        print FH "  d d1;\n";
        print FH "  csl_parameter e_x($val1);\n";
        print FH "  csl_parameter e_y($val1);\n";
        print FH "  csl_parameter e_z($val1);\n";
        print FH "  csl_port p_data(output,e_y);\n"; 
        print FH "  csl_port p_addr(input,$val1);\n";   
        print FH "  csl_port p_data1(input,e_x);\n";
    }
    print FH "  e() {\n";
    if($i <= 2) {
        print FH "    p_addr.connect_by_pattern(c0.p_addr,$word1);\n";
        print FH "    p_data.connect_by_pattern(c0.p_data,$word5);\n";
    }
    elsif($i > 2) {
#        print FH "    d0.$it3.p_data.connect_by_pattern(d0.c1.$it4.p_data1,$word1);\n";
#        print FH "    d1.$it3.p_data1.connect_by_pattern(d1.c1.$it4.p_addr,$word5);\n";
	print FH "    p_data.connect_by_pattern($it3.p_data,$word1);\n";
	print FH "    p_addr.connect_by_pattern($it3.p_addr,$word5);\n";
	print FH "    p_data1.connect_by_pattern($it3.p_data1);\n";
    }
    
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
    
    print FH "csl_unit top {\n";
    if($i <= 2){
        print FH "  e e0(.p_data(p),.p_addr(ptop));\n"; 
	print FH "  csl_parameter top_x($val1);\n";
#	print FH "  csl_parameter top_y($val1);\n";
	print FH "  csl_port ptop(input,top_x);\n";
	print FH "  csl_port p(output,$val1);\n";
    }
    elsif($i > 2) {
        print FH "  e e0(.p_data(s));\n"; 
        print FH "  e e1(.p_data(s));\n"; 
        print FH "  e e2(.p_data(s));\n";
	print FH "  csl_parameter top_x($val1);\n";
	print FH "  csl_parameter top_y($val1);\n";
	print FH "  csl_port ptop(input,top_x);\n";
	print FH "  csl_port p(input,$val1);\n";
	print FH "  csl_signal s($val1);\n";
    }
    print FH "  top(){\n";
    if($i > 2) {
#        print FH "    e1.c0.b0.p_addr.connect_by_pattern($it3.p_data1,$word2);\n";
#        print FH "    a0.p_addr.connect_by_pattern($it3.p_data1,$word6);\n";
#        print FH "    e1.c1.p_data1.connect_by_pattern($it3.p_data1,$word3);\n";
	print FH "    ptop.connect_by_pattern($it4.p_addr,$word2);\n";
	print FH "    p.connect_by_pattern($it4.p_data1,$word6);\n";
    }
    print FH "  }\n";        
    print FH "};\n";        
    print FH "\n";
   
    close(FH);

}
