#!/usr/bin/perl

use strict;

use Switch;               # the switch/case command
use File::Find;           # traversing the directory tree
use File::Basename;       # retrieving the basename of a directory
use File::Path;           # mkpath command

my $ENUM         = "enum_";
my $cslEnum      = "csl_enum";
my $enumName     = "e";
my $enumItemName = "ei_";

my $ITEMS_NO     = 50;
my $BASE_BIN     = 2;
my $BASE_OCT     = 8;
my $BASE_DEC     = 10;
my $BASE_HEX     = 16;
#my $BASE_ANY     = 10;

my $testDate     = `date "+%d/%m/%G, %T"`;
my $start_time   = time();
my $testName     = "";
my $enumItemsNo;
my $noVerNo;
my $eiValue;

&gen_enum();

print "Generated tests path : csl_test_gen/enum_no_neg_values_valid\n";

sub printHeader{
    my $testName = $_[0];

    print FH "//Test generated by AncaO\n";
    print FH "//Test name: $testName\n";
    print FH "//Date: $testDate\n";
    print FH "//csl_enum with verilog numbers is created";
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
    #print "[INFO] Created directory $dirName\n";
}

sub createCSLfile{
    $testName = $_[0];
    &mkDir("$ENV{WORK}/test/csl_test_gen/enum_no_neg_values_valid");
    open( FH, ">$ENV{WORK}/test/csl_test_gen/enum_no_neg_values_valid/$testName");
    &printHeader($testName);
    print FH "\n";
    print FH "$cslEnum e {\n";
#    print FH "  $enumName() {\n";
}

sub closeCSLfile{
#    print FH "   }\n";
    print FH "};\n";       
}

sub generateRandomNumber{
    my ($_digits, $_base) = @_;
    $noVerNo = "";

    for( my $_noDigits = 0; $_noDigits < $_digits; $_noDigits++) {
        my $number = int( rand( $_base));
        $noVerNo .= $number; 
    }
#    print "\n";
}

sub gen_enum{
#valid
    my $_enumItemsNo;
    for( my $enumItemsNo = 0; $enumItemsNo < $ITEMS_NO; $enumItemsNo++) {
        $testName = $ENUM . "no_val" . "_" . $enumItemsNo . "_legal.csl";
        &createCSLfile($testName);
        for( $_enumItemsNo = 0; $_enumItemsNo < $enumItemsNo; $_enumItemsNo++) {
            print FH "     $enumItemName" . $_enumItemsNo . ",\n";
        }
        print FH "     $enumItemName" . $_enumItemsNo . "\n";
        closeCSLfile($testName);

        for( my $_digits = 1; $_digits < 5; $_digits++){
            
            $testName = $ENUM . "neg_val_" . $enumItemsNo . "_" . $_digits . "_legal.csl";
            &createCSLfile($testName);
            for( $_enumItemsNo = 0; $_enumItemsNo < $enumItemsNo-1; $_enumItemsNo++) {
                &generateRandomNumber($_digits, $BASE_DEC);
                print FH "     $enumItemName" . $_enumItemsNo . " = -" . $noVerNo . ",\n";
            }
            &generateRandomNumber($_digits, $BASE_DEC);
            print FH "     $enumItemName" . $_enumItemsNo . " = -" . $noVerNo . "\n";
            closeCSLfile($testName);
        }
    }

    my $finish_time  = time(); #statistics on the time elapsed from the start of the regression until it's end
    my $elapsed_time = $finish_time - $start_time;
    my $day          = int $elapsed_time/86400;
    my $hour         = int $elapsed_time%86400/3600;
    my $min          = int $elapsed_time%3600/60;
    my $sec          = $elapsed_time-$day*86400-$hour*3600-$min*60;
 #   print "min = $min\n";
 #   print "sec = $sec\n";
}
