#!/usr/bin/perl

#oanab
#f2a with part select

use strict;

print "Generated tests path : test/csl_test_gen/f2a_part_sel_invalid2/\n";

if(! defined $ENV{WORK}){
    die "[ERROR] The environment variable WORK is not set. Set it to point to TOT/se";
}

my $totDir     = $ENV{WORK};
&testDirExists($totDir);

sub testDirExists {
    my($execName) = @_;
    unless(-e "$execName") { die "[ERROR] The directory $execName does not exist!\n"; }
    
}

sub mkDir {
    my($dirName) = @_;
    unless(-e "$dirName")  { `mkdir $dirName`; }
}

foreach(my $i = 1; $i <= 300; $i++) {
    &main($i);
}

sub main {
    my $i = $_[0];
    my %dir = (1,"input",
	       2,"output",
	       3,"inout");
    my $dir = $_[4];
    my $test_name = "f2a_part_sel".$i."_illegal.csl";
   	&createCslFile($test_name, $i, %dir);
}

sub createCslFile {
    my ($test_name, $i, %dir) = @_;
    my $path = "$ENV{WORK}/test/csl_test_gen/";
    my $k = int(rand(20)) + int(rand(20));
    my $zero = 0;
    my $one = 1;
    my $two = 2;
    my $tre = 3;
    my $val1 = int(rand(20)) + 2;
    my $val2 = int(rand(100)) + 3;
    my $val3 = int(rand(100)) + 4;
    my $l = int(rand(3))+1;
    my $m = $k + int(rand(10)) + 1;
    if($test_name=~/(_legal)/){
        &mkDir("$path/f2a_part_sel_valid");
        open(FH,">$path/f2a_part_sel_valid/$test_name");
    }
    elsif($test_name=~/(_illegal)/) {
        &mkDir("$path/f2a_part_sel_invalid2"); 
        open(FH,">$path/f2a_part_sel_invalid2/$test_name");
    }
    print FH "//Generated by oanab\n\n";

#bitranges and fields
    print FH "csl_field f1($val1);\n";
    print FH "csl_bitrange br2($val2);\n";
    print FH "csl_bitrange br3($val3);\n";
    print FH "csl_bitrange br4(".($val2+$val3).");\n";
  
    
#ifc k
    print FH "csl_interface ifc$k {\n";
    print FH "  csl_port p_a$i(input,br3);\n";
    print FH "  csl_port p_b$i(output,$val2);\n";
    print FH "  csl_port p_c$i(output,br4);\n";
    print FH "  csl_port p_d$i(input,f1);\n";
    print FH "  ifc$k () {}\n";
    print FH "};\n\n";

#ifc m
    print FH "csl_interface ifc$m {\n";
    print FH "  ifc$k ifc$k\_$zero;\n";
    print FH "  ifc$k ifc$k\_$one;\n";
    print FH "  ifc$m () {}\n";
    print FH "};\n\n";
    
#sg k
    if($i > 50 && $i <= 150) {
	print FH "csl_signal_group sg$k {\n";
	print FH "  csl_signal s_a$i(br2);\n";
	print FH "  csl_signal s_b$i(br3);\n";
	print FH "  csl_signal s_c$i(f1);\n";
	print FH "  csl_signal s_d$i(br4);\n";
	print FH "  sg$k () {}\n";
	print FH "};\n\n";
    }

#sg m
    if($i > 100 && $i <= 150) {
	print FH "csl_signal_group sg$m {\n";
	print FH "  csl_signal s_x$i(br2);\n";
	print FH "  csl_signal s_y$i(br3);\n";
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  sg$k sg$k\_$one;\n";
	print FH "  sg$m () {}\n";
	print FH "};\n\n";
    }

#unit a
    print FH "csl_unit a$k {\n";
    if($i <= 50) {
	print FH "  ifc$k ifc$k\_$zero;\n";
    }
    elsif($i > 50 && $i <= 150) {
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  csl_port p_a$i($dir{$l},".($val2+3*$val1).");\n";
    }
    elsif($i > 200 && $i <= 250) {
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    elsif($i > 250 && $i <= 300) {
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
    }
    print FH "  a$k () {\n";
   
    print FH "  }\n";
    print FH "};\n\n";


#unit b
    print FH "csl_unit b$k {\n";
    print FH "  a$k a$k\_$zero;\n";
#f2a : Invalid connection : ifc---sig.ps
    if($i <= 50) {
	print FH "  ifc$k ifc$k\_$one;\n";
	print FH "  ifc$m ifc$m\_$zero;\n";
	print FH "  csl_signal s_a$i(".($val2+$val3+2).");\n";
	print FH "  a$k a$k\_$one(.ifc$k\_$zero(s_a$i\[".($val2+$val3)."\-\:".$val3."\]));  // Invalid connection : ifc---sig.ps\n";
    }
#f2a : Invalid connection : ifc.ifc---sg.sig.ps
    elsif($i > 50 && $i <= 100) {
	print FH "  ifc$k ifc$k\_$zero;\n";
	print FH "  sg$k sg$k\_$zero;\n";
	print FH "  a$k a$k\_$one(.ifc$m\_$zero.ifc$k\_$zero(sg$k\_$zero.s_c$i\[".($val2+$val1)."\-\:".$val1."\]));   // Invalid connection : ifc.ifc---sg.sig.ps\n";
    }
#f2a : Invalid connection : ifc.ifc---sg.sg.sig.ps, Invalid connection : ifc.ifc---sg.sg.sig.ps
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$zero;\n";
	print FH "  ifc$m ifc$m\_$one;\n";
	print FH "  a$k a$k\_$one(.ifc$m\_$zero.ifc$k\_$zero(sg$m\_$zero.sg$k\_$zero.s_d$i\[".($val2+$val3)."\:".$val3."\]));   // Invalid connection : ifc.ifc---sg.sg.sig.ps\n";
	print FH "  a$k a$k\_$two(.ifc$m\_$zero.ifc$k\_$one(sg$m\_$zero.sg$k\_$one.s_d$i\[".($val2+$val3)."\-\:".$val2."\]));   // Invalid connection : ifc.ifc---sg.sg.sig.ps\n";
    }
#f2a : Invalid connection : ifc---p.ps
    elsif($i > 150 && $i <= 200) {
	print FH "  ifc$m ifc$m\_$zero;\n";
	print FH "  csl_port p_b$i($dir{$l},".($val3+2*$val1).");\n";
	print FH "  a$k a$k\_$one(.ifc$k\_$zero(p_a$i\[".($val2+3*$val1)."\:".(2*$val1)."\]));   // Invalid connection : ifc---p.ps\n";
    }
#f2a : Invalid connection : ifc---p.ps
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_b$i($dir{$l},".($val3+2*$val1).");\n";
	print FH "  a$k a$k\_$one(.ifc$m\_$zero(p_b$i\[".($val3+2*$val1)."\:".($val2)."\]));   // Invalid connection : ifc---p.ps\n";
    }
#f2a : Invalid connection : ifc.ifc---op expr
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_signal s_a$i(br4);\n";
	print FH "  csl_signal s_b$i(".($val3+$val2+1).");\n";
	print FH "  a$k a$k\_$one(.ifc$m\_$zero.ifc$k\_$zero(s_a$i\[".($val2+$val3)."\:".($val2)."\] | s_b$i\[".($val2+$val3)."\-\:".($val3)."\]));   // Invalid connection : ifc.ifc---op expr\n";
    }
    print FH "  b$k () {\n";
   
    print FH "  }\n";
    print FH "};\n\n";


#unit c
    print FH "csl_unit c$k {\n";
    print FH "  b$k b$k\_$zero;\n";
#f2a : Invalid connection : ifc.ifc---sig.ps, Invalid connection : ifc.ifc---sig.ps
    if($i <= 50) {
	print FH "  csl_signal s_b$i(".($val2+2*$val1).");\n";
	print FH "  b$k b$k\_$one(.ifc$m\_$zero.ifc$k\_$zero(s_b$i\[".($val2+2*$val1)."\:".($val1)."\]));  // Invalid connection : ifc.ifc---sig.ps\n";
print FH "  b$k b$k\_$two(.ifc$m\_$zero.ifc$k\_$one(s_b$i\[".($val2+2*$val1)."\:".($val1+$val2-4)."\]));   // Invalid connection : ifc.ifc---sig.ps\n";
    }
#f2a : Invalid connection : ifc---sg.sig.ps
    elsif($i > 50 && $i <= 100) {
	print FH "  sg$k sg$k\_$one;\n";
	print FH "  b$k b$k\_$one(.ifc$k\_$zero(sg$k\_$one.s_a$i\[3\]));   // Invalid connection : ifc---sg.sig.ps\n";
    }
#f2a : Invalid connection : ifc---sg.sg.sig.ps
    elsif($i > 100 && $i <= 150) {
	print FH "  sg$m sg$m\_$one;\n";
	print FH "  b$k b$k\_$one(.ifc$m\_$one(sg$m\_$one.sg$k\_$one.s_b$i\[1\]));   // Invalid connection : ifc---sg.sg.sig.ps\n";
    }
#f2a : Invalid connection : ifc.ifc---p.ps
    elsif($i > 150 && $i <= 200) {
	print FH "  b$k b$k\_$one(.ifc$m\_$zero.ifc$k\_$one(p_b$i\[".($val3+2*$val1)."\-\:".($val1+$val3)."\]));   // Invalid connection : ifc.ifc---p.ps\n";
    }
#f2a : Invalid connection : ifc.ifc---p.ps
    elsif($i > 200 && $i <= 250) {
	print FH "  csl_port p_d$i($dir{$l},br4);\n";
	print FH "  a$k a$k\_$two(.ifc$m\_$zero.ifc$k\_$one(p_d$i\[".($val2+$val3)."\-\:".$val3."\]));   // Invalid connection : ifc.ifc---p.ps\n";
    }
#f2a : Invalid connection : ifc---concat expr, Invalid connection : ifc.ifc---repl expr
    elsif($i > 250 && $i <= 300) {
	print FH "  csl_signal s_x$i(br2);\n";
	print FH "  csl_signal s_y$i($val1);\n";
	print FH "  a$k a$k\_$one(.ifc$k\_$zero({s_x$i\[3\],s_y$i\[".($val1)."\-\:".(2)."\]}));   // Invalid connection : ifc---concat expr\n";
	print FH "  a$k a$k\_$two(.ifc$m\_$zero.ifc$k\_$zero({3{s_y$i\[1\]}}));   // Invalid connection : ifc.ifc---repl expr\n";
    }
    print FH "  c$k () {\n";
   
    print FH "  }\n";
    print FH "};\n\n";











}
